/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetPrayertimesMonthlyQueryResponse, GetPrayertimesMonthlyQueryParams, GetPrayertimesMonthly400, GetPrayertimesMonthly500 } from "../../types/GetPrayertimesMonthly.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getPrayertimesMonthlyQueryKey = (params: GetPrayertimesMonthlyQueryParams) => [{ url: '/prayertimes/monthly' }, ...(params ? [params] : [])] as const

export type GetPrayertimesMonthlyQueryKey = ReturnType<typeof getPrayertimesMonthlyQueryKey>

/**
 * @description Retrieve monthly prayer timings for a given location and month/year
 * @summary Get monthly prayer timings
 * {@link /prayertimes/monthly}
 */
export async function getPrayertimesMonthlyHook(params: GetPrayertimesMonthlyQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetPrayertimesMonthlyQueryResponse, ResponseErrorConfig<GetPrayertimesMonthly400 | GetPrayertimesMonthly500>, unknown>({ method : "GET", url : `/prayertimes/monthly`, params, ... requestConfig })  
  return res.data
}

export function getPrayertimesMonthlyQueryOptionsHook(params: GetPrayertimesMonthlyQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getPrayertimesMonthlyQueryKey(params)
  return queryOptions<GetPrayertimesMonthlyQueryResponse, ResponseErrorConfig<GetPrayertimesMonthly400 | GetPrayertimesMonthly500>, GetPrayertimesMonthlyQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getPrayertimesMonthlyHook(params, config)
   },
  })
}

/**
 * @description Retrieve monthly prayer timings for a given location and month/year
 * @summary Get monthly prayer timings
 * {@link /prayertimes/monthly}
 */
export function useGetPrayertimesMonthlyHook<TData = GetPrayertimesMonthlyQueryResponse, TQueryData = GetPrayertimesMonthlyQueryResponse, TQueryKey extends QueryKey = GetPrayertimesMonthlyQueryKey>(params: GetPrayertimesMonthlyQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetPrayertimesMonthlyQueryResponse, ResponseErrorConfig<GetPrayertimesMonthly400 | GetPrayertimesMonthly500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getPrayertimesMonthlyQueryKey(params)

  const query = useQuery({
   ...getPrayertimesMonthlyQueryOptionsHook(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetPrayertimesMonthly400 | GetPrayertimesMonthly500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}