/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetPrayertimesDailyQueryResponse, GetPrayertimesDailyQueryParams, GetPrayertimesDaily400, GetPrayertimesDaily500 } from "../../types/GetPrayertimesDaily.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getPrayertimesDailyQueryKey = (params: GetPrayertimesDailyQueryParams) => [{ url: '/prayertimes/daily' }, ...(params ? [params] : [])] as const

export type GetPrayertimesDailyQueryKey = ReturnType<typeof getPrayertimesDailyQueryKey>

/**
 * @description Retrieve daily prayer timings for a given location and date
 * @summary Get daily prayer timings
 * {@link /prayertimes/daily}
 */
export async function getPrayertimesDailyHook(params: GetPrayertimesDailyQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetPrayertimesDailyQueryResponse, ResponseErrorConfig<GetPrayertimesDaily400 | GetPrayertimesDaily500>, unknown>({ method : "GET", url : `/prayertimes/daily`, params, ... requestConfig })  
  return res.data
}

export function getPrayertimesDailyQueryOptionsHook(params: GetPrayertimesDailyQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getPrayertimesDailyQueryKey(params)
  return queryOptions<GetPrayertimesDailyQueryResponse, ResponseErrorConfig<GetPrayertimesDaily400 | GetPrayertimesDaily500>, GetPrayertimesDailyQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getPrayertimesDailyHook(params, config)
   },
  })
}

/**
 * @description Retrieve daily prayer timings for a given location and date
 * @summary Get daily prayer timings
 * {@link /prayertimes/daily}
 */
export function useGetPrayertimesDailyHook<TData = GetPrayertimesDailyQueryResponse, TQueryData = GetPrayertimesDailyQueryResponse, TQueryKey extends QueryKey = GetPrayertimesDailyQueryKey>(params: GetPrayertimesDailyQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetPrayertimesDailyQueryResponse, ResponseErrorConfig<GetPrayertimesDaily400 | GetPrayertimesDaily500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getPrayertimesDailyQueryKey(params)

  const query = useQuery({
   ...getPrayertimesDailyQueryOptionsHook(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetPrayertimesDaily400 | GetPrayertimesDaily500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}