/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetPrayertimesYearlyQueryResponse, GetPrayertimesYearlyQueryParams, GetPrayertimesYearly400, GetPrayertimesYearly500 } from "../../types/GetPrayertimesYearly.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getPrayertimesYearlyQueryKey = (params: GetPrayertimesYearlyQueryParams) => [{ url: '/prayertimes/yearly' }, ...(params ? [params] : [])] as const

export type GetPrayertimesYearlyQueryKey = ReturnType<typeof getPrayertimesYearlyQueryKey>

/**
 * @description Retrieve yearly prayer timings for a given location and year
 * @summary Get yearly prayer timings
 * {@link /prayertimes/yearly}
 */
export async function getPrayertimesYearlyHook(params: GetPrayertimesYearlyQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetPrayertimesYearlyQueryResponse, ResponseErrorConfig<GetPrayertimesYearly400 | GetPrayertimesYearly500>, unknown>({ method : "GET", url : `/prayertimes/yearly`, params, ... requestConfig })  
  return res.data
}

export function getPrayertimesYearlyQueryOptionsHook(params: GetPrayertimesYearlyQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getPrayertimesYearlyQueryKey(params)
  return queryOptions<GetPrayertimesYearlyQueryResponse, ResponseErrorConfig<GetPrayertimesYearly400 | GetPrayertimesYearly500>, GetPrayertimesYearlyQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getPrayertimesYearlyHook(params, config)
   },
  })
}

/**
 * @description Retrieve yearly prayer timings for a given location and year
 * @summary Get yearly prayer timings
 * {@link /prayertimes/yearly}
 */
export function useGetPrayertimesYearlyHook<TData = GetPrayertimesYearlyQueryResponse, TQueryData = GetPrayertimesYearlyQueryResponse, TQueryKey extends QueryKey = GetPrayertimesYearlyQueryKey>(params: GetPrayertimesYearlyQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetPrayertimesYearlyQueryResponse, ResponseErrorConfig<GetPrayertimesYearly400 | GetPrayertimesYearly500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getPrayertimesYearlyQueryKey(params)

  const query = useQuery({
   ...getPrayertimesYearlyQueryOptionsHook(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetPrayertimesYearly400 | GetPrayertimesYearly500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}