export type { DeleteQuranAyahsIdMutationKey } from "./useDeleteQuranAyahsIdHook.ts";
export type { GetQuranAyahsIdQueryKey } from "./useGetQuranAyahsIdHook.ts";
export type { GetQuranAyahsSurahSurahidQueryKey } from "./useGetQuranAyahsSurahSurahidHook.ts";
export type { GetQuranJuzJuznumberAyahsQueryKey } from "./useGetQuranJuzJuznumberAyahsHook.ts";
export type { PostQuranAyahsMutationKey } from "./usePostQuranAyahsHook.ts";
export type { PutQuranAyahsIdMutationKey } from "./usePutQuranAyahsIdHook.ts";
export { deleteQuranAyahsIdMutationKey, deleteQuranAyahsIdHook, deleteQuranAyahsIdMutationOptionsHook, useDeleteQuranAyahsIdHook } from "./useDeleteQuranAyahsIdHook.ts";
export { getQuranAyahsIdQueryKey, getQuranAyahsIdHook, getQuranAyahsIdQueryOptionsHook, useGetQuranAyahsIdHook } from "./useGetQuranAyahsIdHook.ts";
export { getQuranAyahsSurahSurahidQueryKey, getQuranAyahsSurahSurahidHook, getQuranAyahsSurahSurahidQueryOptionsHook, useGetQuranAyahsSurahSurahidHook } from "./useGetQuranAyahsSurahSurahidHook.ts";
export { getQuranJuzJuznumberAyahsQueryKey, getQuranJuzJuznumberAyahsHook, getQuranJuzJuznumberAyahsQueryOptionsHook, useGetQuranJuzJuznumberAyahsHook } from "./useGetQuranJuzJuznumberAyahsHook.ts";
export { postQuranAyahsMutationKey, postQuranAyahsHook, postQuranAyahsMutationOptionsHook, usePostQuranAyahsHook } from "./usePostQuranAyahsHook.ts";
export { putQuranAyahsIdMutationKey, putQuranAyahsIdHook, putQuranAyahsIdMutationOptionsHook, usePutQuranAyahsIdHook } from "./usePutQuranAyahsIdHook.ts";