/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { DeleteQuranAyahsIdMutationResponse, DeleteQuranAyahsIdPathParams, DeleteQuranAyahsId400, DeleteQuranAyahsId404, DeleteQuranAyahsId500 } from "../../types/DeleteQuranAyahsId.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteQuranAyahsIdMutationKey = () => [{ url: '/quran/ayahs/:id' }] as const

export type DeleteQuranAyahsIdMutationKey = ReturnType<typeof deleteQuranAyahsIdMutationKey>

/**
 * @description Delete an existing ayah from the Quran
 * @summary Delete an ayah
 * {@link /quran/ayahs/:id}
 */
export async function deleteQuranAyahsIdHook(id: DeleteQuranAyahsIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteQuranAyahsIdMutationResponse, ResponseErrorConfig<DeleteQuranAyahsId400 | DeleteQuranAyahsId404 | DeleteQuranAyahsId500>, unknown>({ method : "DELETE", url : `/quran/ayahs/${id}`, ... requestConfig })  
  return res.data
}

export function deleteQuranAyahsIdMutationOptionsHook(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = deleteQuranAyahsIdMutationKey()
  return mutationOptions<DeleteQuranAyahsIdMutationResponse, ResponseErrorConfig<DeleteQuranAyahsId400 | DeleteQuranAyahsId404 | DeleteQuranAyahsId500>, {id: DeleteQuranAyahsIdPathParams["id"]}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id }) => {
      return deleteQuranAyahsIdHook(id, config)
    },
  })
}

/**
 * @description Delete an existing ayah from the Quran
 * @summary Delete an ayah
 * {@link /quran/ayahs/:id}
 */
export function useDeleteQuranAyahsIdHook<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteQuranAyahsIdMutationResponse, ResponseErrorConfig<DeleteQuranAyahsId400 | DeleteQuranAyahsId404 | DeleteQuranAyahsId500>, {id: DeleteQuranAyahsIdPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteQuranAyahsIdMutationKey()

  const baseOptions = deleteQuranAyahsIdMutationOptionsHook(config) as UseMutationOptions<DeleteQuranAyahsIdMutationResponse, ResponseErrorConfig<DeleteQuranAyahsId400 | DeleteQuranAyahsId404 | DeleteQuranAyahsId500>, {id: DeleteQuranAyahsIdPathParams["id"]}, TContext>

  return useMutation<DeleteQuranAyahsIdMutationResponse, ResponseErrorConfig<DeleteQuranAyahsId400 | DeleteQuranAyahsId404 | DeleteQuranAyahsId500>, {id: DeleteQuranAyahsIdPathParams["id"]}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<DeleteQuranAyahsIdMutationResponse, ResponseErrorConfig<DeleteQuranAyahsId400 | DeleteQuranAyahsId404 | DeleteQuranAyahsId500>, {id: DeleteQuranAyahsIdPathParams["id"]}, TContext>
}