/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetQuranJuzJuznumberAyahsQueryResponse, GetQuranJuzJuznumberAyahsPathParams, GetQuranJuzJuznumberAyahsQueryParams, GetQuranJuzJuznumberAyahs400, GetQuranJuzJuznumberAyahs500 } from "../../types/GetQuranJuzJuznumberAyahs.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getQuranJuzJuznumberAyahsQueryKey = (juzNumber: GetQuranJuzJuznumberAyahsPathParams["juzNumber"], params?: GetQuranJuzJuznumberAyahsQueryParams) => [{ url: '/quran/juz/:juzNumber/ayahs', params: {juzNumber:juzNumber} }, ...(params ? [params] : [])] as const

export type GetQuranJuzJuznumberAyahsQueryKey = ReturnType<typeof getQuranJuzJuznumberAyahsQueryKey>

/**
 * @description Get all ayahs from a specific juz with pagination
 * @summary Get ayahs by juz
 * {@link /quran/juz/:juzNumber/ayahs}
 */
export async function getQuranJuzJuznumberAyahsHook(juzNumber: GetQuranJuzJuznumberAyahsPathParams["juzNumber"], params?: GetQuranJuzJuznumberAyahsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetQuranJuzJuznumberAyahsQueryResponse, ResponseErrorConfig<GetQuranJuzJuznumberAyahs400 | GetQuranJuzJuznumberAyahs500>, unknown>({ method : "GET", url : `/quran/juz/${juzNumber}/ayahs`, params, ... requestConfig })  
  return res.data
}

export function getQuranJuzJuznumberAyahsQueryOptionsHook(juzNumber: GetQuranJuzJuznumberAyahsPathParams["juzNumber"], params?: GetQuranJuzJuznumberAyahsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getQuranJuzJuznumberAyahsQueryKey(juzNumber, params)
  return queryOptions<GetQuranJuzJuznumberAyahsQueryResponse, ResponseErrorConfig<GetQuranJuzJuznumberAyahs400 | GetQuranJuzJuznumberAyahs500>, GetQuranJuzJuznumberAyahsQueryResponse, typeof queryKey>({
   enabled: !!(juzNumber),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getQuranJuzJuznumberAyahsHook(juzNumber, params, config)
   },
  })
}

/**
 * @description Get all ayahs from a specific juz with pagination
 * @summary Get ayahs by juz
 * {@link /quran/juz/:juzNumber/ayahs}
 */
export function useGetQuranJuzJuznumberAyahsHook<TData = GetQuranJuzJuznumberAyahsQueryResponse, TQueryData = GetQuranJuzJuznumberAyahsQueryResponse, TQueryKey extends QueryKey = GetQuranJuzJuznumberAyahsQueryKey>(juzNumber: GetQuranJuzJuznumberAyahsPathParams["juzNumber"], params?: GetQuranJuzJuznumberAyahsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetQuranJuzJuznumberAyahsQueryResponse, ResponseErrorConfig<GetQuranJuzJuznumberAyahs400 | GetQuranJuzJuznumberAyahs500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getQuranJuzJuznumberAyahsQueryKey(juzNumber, params)

  const query = useQuery({
   ...getQuranJuzJuznumberAyahsQueryOptionsHook(juzNumber, params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetQuranJuzJuznumberAyahs400 | GetQuranJuzJuznumberAyahs500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}