/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetQuranAyahsIdQueryResponse, GetQuranAyahsIdPathParams, GetQuranAyahsIdQueryParams, GetQuranAyahsId400, GetQuranAyahsId404, GetQuranAyahsId500 } from "../../types/GetQuranAyahsId.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getQuranAyahsIdQueryKey = (id: GetQuranAyahsIdPathParams["id"], params?: GetQuranAyahsIdQueryParams) => [{ url: '/quran/ayahs/:id', params: {id:id} }, ...(params ? [params] : [])] as const

export type GetQuranAyahsIdQueryKey = ReturnType<typeof getQuranAyahsIdQueryKey>

/**
 * @description Get an ayah by its ID from the Quran
 * @summary Get ayah by ID
 * {@link /quran/ayahs/:id}
 */
export async function getQuranAyahsIdHook(id: GetQuranAyahsIdPathParams["id"], params?: GetQuranAyahsIdQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetQuranAyahsIdQueryResponse, ResponseErrorConfig<GetQuranAyahsId400 | GetQuranAyahsId404 | GetQuranAyahsId500>, unknown>({ method : "GET", url : `/quran/ayahs/${id}`, params, ... requestConfig })  
  return res.data
}

export function getQuranAyahsIdQueryOptionsHook(id: GetQuranAyahsIdPathParams["id"], params?: GetQuranAyahsIdQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getQuranAyahsIdQueryKey(id, params)
  return queryOptions<GetQuranAyahsIdQueryResponse, ResponseErrorConfig<GetQuranAyahsId400 | GetQuranAyahsId404 | GetQuranAyahsId500>, GetQuranAyahsIdQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getQuranAyahsIdHook(id, params, config)
   },
  })
}

/**
 * @description Get an ayah by its ID from the Quran
 * @summary Get ayah by ID
 * {@link /quran/ayahs/:id}
 */
export function useGetQuranAyahsIdHook<TData = GetQuranAyahsIdQueryResponse, TQueryData = GetQuranAyahsIdQueryResponse, TQueryKey extends QueryKey = GetQuranAyahsIdQueryKey>(id: GetQuranAyahsIdPathParams["id"], params?: GetQuranAyahsIdQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetQuranAyahsIdQueryResponse, ResponseErrorConfig<GetQuranAyahsId400 | GetQuranAyahsId404 | GetQuranAyahsId500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getQuranAyahsIdQueryKey(id, params)

  const query = useQuery({
   ...getQuranAyahsIdQueryOptionsHook(id, params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetQuranAyahsId400 | GetQuranAyahsId404 | GetQuranAyahsId500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}