/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetQuranAyahsSurahSurahidQueryResponse, GetQuranAyahsSurahSurahidPathParams, GetQuranAyahsSurahSurahidQueryParams, GetQuranAyahsSurahSurahid400, GetQuranAyahsSurahSurahid500 } from "../../types/GetQuranAyahsSurahSurahid.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getQuranAyahsSurahSurahidQueryKey = (surahId: GetQuranAyahsSurahSurahidPathParams["surahId"], params?: GetQuranAyahsSurahSurahidQueryParams) => [{ url: '/quran/ayahs/surah/:surahId', params: {surahId:surahId} }, ...(params ? [params] : [])] as const

export type GetQuranAyahsSurahSurahidQueryKey = ReturnType<typeof getQuranAyahsSurahSurahidQueryKey>

/**
 * @description Get all ayahs from a specific surah with pagination
 * @summary Get ayahs by surah
 * {@link /quran/ayahs/surah/:surahId}
 */
export async function getQuranAyahsSurahSurahidHook(surahId: GetQuranAyahsSurahSurahidPathParams["surahId"], params?: GetQuranAyahsSurahSurahidQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetQuranAyahsSurahSurahidQueryResponse, ResponseErrorConfig<GetQuranAyahsSurahSurahid400 | GetQuranAyahsSurahSurahid500>, unknown>({ method : "GET", url : `/quran/ayahs/surah/${surahId}`, params, ... requestConfig })  
  return res.data
}

export function getQuranAyahsSurahSurahidQueryOptionsHook(surahId: GetQuranAyahsSurahSurahidPathParams["surahId"], params?: GetQuranAyahsSurahSurahidQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getQuranAyahsSurahSurahidQueryKey(surahId, params)
  return queryOptions<GetQuranAyahsSurahSurahidQueryResponse, ResponseErrorConfig<GetQuranAyahsSurahSurahid400 | GetQuranAyahsSurahSurahid500>, GetQuranAyahsSurahSurahidQueryResponse, typeof queryKey>({
   enabled: !!(surahId),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getQuranAyahsSurahSurahidHook(surahId, params, config)
   },
  })
}

/**
 * @description Get all ayahs from a specific surah with pagination
 * @summary Get ayahs by surah
 * {@link /quran/ayahs/surah/:surahId}
 */
export function useGetQuranAyahsSurahSurahidHook<TData = GetQuranAyahsSurahSurahidQueryResponse, TQueryData = GetQuranAyahsSurahSurahidQueryResponse, TQueryKey extends QueryKey = GetQuranAyahsSurahSurahidQueryKey>(surahId: GetQuranAyahsSurahSurahidPathParams["surahId"], params?: GetQuranAyahsSurahSurahidQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetQuranAyahsSurahSurahidQueryResponse, ResponseErrorConfig<GetQuranAyahsSurahSurahid400 | GetQuranAyahsSurahSurahid500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getQuranAyahsSurahSurahidQueryKey(surahId, params)

  const query = useQuery({
   ...getQuranAyahsSurahSurahidQueryOptionsHook(surahId, params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetQuranAyahsSurahSurahid400 | GetQuranAyahsSurahSurahid500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}