/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { PostQuranAyahsMutationRequest, PostQuranAyahsMutationResponse, PostQuranAyahs400, PostQuranAyahs500 } from "../../types/PostQuranAyahs.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postQuranAyahsMutationKey = () => [{ url: '/quran/ayahs' }] as const

export type PostQuranAyahsMutationKey = ReturnType<typeof postQuranAyahsMutationKey>

/**
 * @description Create a new ayah in the Quran
 * @summary Create a new ayah
 * {@link /quran/ayahs}
 */
export async function postQuranAyahsHook(data: PostQuranAyahsMutationRequest, config: Partial<RequestConfig<PostQuranAyahsMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostQuranAyahsMutationResponse, ResponseErrorConfig<PostQuranAyahs400 | PostQuranAyahs500>, PostQuranAyahsMutationRequest>({ method : "POST", url : `/quran/ayahs`, data : requestData, ... requestConfig })  
  return res.data
}

export function postQuranAyahsMutationOptionsHook(config: Partial<RequestConfig<PostQuranAyahsMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = postQuranAyahsMutationKey()
  return mutationOptions<PostQuranAyahsMutationResponse, ResponseErrorConfig<PostQuranAyahs400 | PostQuranAyahs500>, {data: PostQuranAyahsMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return postQuranAyahsHook(data, config)
    },
  })
}

/**
 * @description Create a new ayah in the Quran
 * @summary Create a new ayah
 * {@link /quran/ayahs}
 */
export function usePostQuranAyahsHook<TContext>(options: 
{
  mutation?: UseMutationOptions<PostQuranAyahsMutationResponse, ResponseErrorConfig<PostQuranAyahs400 | PostQuranAyahs500>, {data: PostQuranAyahsMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostQuranAyahsMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postQuranAyahsMutationKey()

  const baseOptions = postQuranAyahsMutationOptionsHook(config) as UseMutationOptions<PostQuranAyahsMutationResponse, ResponseErrorConfig<PostQuranAyahs400 | PostQuranAyahs500>, {data: PostQuranAyahsMutationRequest}, TContext>

  return useMutation<PostQuranAyahsMutationResponse, ResponseErrorConfig<PostQuranAyahs400 | PostQuranAyahs500>, {data: PostQuranAyahsMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<PostQuranAyahsMutationResponse, ResponseErrorConfig<PostQuranAyahs400 | PostQuranAyahs500>, {data: PostQuranAyahsMutationRequest}, TContext>
}