/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { PutQuranAyahsIdMutationRequest, PutQuranAyahsIdMutationResponse, PutQuranAyahsIdPathParams, PutQuranAyahsId400, PutQuranAyahsId404, PutQuranAyahsId500 } from "../../types/PutQuranAyahsId.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const putQuranAyahsIdMutationKey = () => [{ url: '/quran/ayahs/:id' }] as const

export type PutQuranAyahsIdMutationKey = ReturnType<typeof putQuranAyahsIdMutationKey>

/**
 * @description Update an existing ayah in the Quran
 * @summary Update an ayah
 * {@link /quran/ayahs/:id}
 */
export async function putQuranAyahsIdHook(id: PutQuranAyahsIdPathParams["id"], data: PutQuranAyahsIdMutationRequest, config: Partial<RequestConfig<PutQuranAyahsIdMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PutQuranAyahsIdMutationResponse, ResponseErrorConfig<PutQuranAyahsId400 | PutQuranAyahsId404 | PutQuranAyahsId500>, PutQuranAyahsIdMutationRequest>({ method : "PUT", url : `/quran/ayahs/${id}`, data : requestData, ... requestConfig })  
  return res.data
}

export function putQuranAyahsIdMutationOptionsHook(config: Partial<RequestConfig<PutQuranAyahsIdMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = putQuranAyahsIdMutationKey()
  return mutationOptions<PutQuranAyahsIdMutationResponse, ResponseErrorConfig<PutQuranAyahsId400 | PutQuranAyahsId404 | PutQuranAyahsId500>, {id: PutQuranAyahsIdPathParams["id"], data: PutQuranAyahsIdMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id, data }) => {
      return putQuranAyahsIdHook(id, data, config)
    },
  })
}

/**
 * @description Update an existing ayah in the Quran
 * @summary Update an ayah
 * {@link /quran/ayahs/:id}
 */
export function usePutQuranAyahsIdHook<TContext>(options: 
{
  mutation?: UseMutationOptions<PutQuranAyahsIdMutationResponse, ResponseErrorConfig<PutQuranAyahsId400 | PutQuranAyahsId404 | PutQuranAyahsId500>, {id: PutQuranAyahsIdPathParams["id"], data: PutQuranAyahsIdMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PutQuranAyahsIdMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? putQuranAyahsIdMutationKey()

  const baseOptions = putQuranAyahsIdMutationOptionsHook(config) as UseMutationOptions<PutQuranAyahsIdMutationResponse, ResponseErrorConfig<PutQuranAyahsId400 | PutQuranAyahsId404 | PutQuranAyahsId500>, {id: PutQuranAyahsIdPathParams["id"], data: PutQuranAyahsIdMutationRequest}, TContext>

  return useMutation<PutQuranAyahsIdMutationResponse, ResponseErrorConfig<PutQuranAyahsId400 | PutQuranAyahsId404 | PutQuranAyahsId500>, {id: PutQuranAyahsIdPathParams["id"], data: PutQuranAyahsIdMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<PutQuranAyahsIdMutationResponse, ResponseErrorConfig<PutQuranAyahsId400 | PutQuranAyahsId404 | PutQuranAyahsId500>, {id: PutQuranAyahsIdPathParams["id"], data: PutQuranAyahsIdMutationRequest}, TContext>
}