/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeleteQuranRecitersIdPathParams, DeleteQuranRecitersId200, DeleteQuranRecitersId400, DeleteQuranRecitersId500, DeleteQuranRecitersIdMutationResponse } from "../../types/DeleteQuranRecitersId.ts";
import { quranDeleteReciterSuccessResponseSchema } from "../quran/deleteReciterSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const deleteQuranRecitersIdPathParamsSchema = z.object({
    "id": z.string().describe("Reciter ID")
    }) as unknown as z.ZodType<DeleteQuranRecitersIdPathParams>

/**
 * @description Reciter deleted successfully
 */
export const deleteQuranRecitersId200Schema = quranDeleteReciterSuccessResponseSchema as unknown as z.ZodType<DeleteQuranRecitersId200>

/**
 * @description Bad request
 */
export const deleteQuranRecitersId400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<DeleteQuranRecitersId400>

/**
 * @description Internal server error
 */
export const deleteQuranRecitersId500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<DeleteQuranRecitersId500>

export const deleteQuranRecitersIdMutationResponseSchema = deleteQuranRecitersId200Schema as unknown as z.ZodType<DeleteQuranRecitersIdMutationResponse>