/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetQuranRecitersNamePathParams, GetQuranRecitersName200, GetQuranRecitersName400, GetQuranRecitersName500, GetQuranRecitersNameQueryResponse } from "../../types/GetQuranRecitersName.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { quranReciterSuccessResponseSchema } from "../quran/reciterSuccessResponseSchema.ts";
import { z } from "zod";

export const getQuranRecitersNamePathParamsSchema = z.object({
    "name": z.string().describe("Reciter name")
    }) as unknown as z.ZodType<GetQuranRecitersNamePathParams>

/**
 * @description Reciter retrieved successfully
 */
export const getQuranRecitersName200Schema = quranReciterSuccessResponseSchema as unknown as z.ZodType<GetQuranRecitersName200>

/**
 * @description Bad request
 */
export const getQuranRecitersName400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranRecitersName400>

/**
 * @description Internal server error
 */
export const getQuranRecitersName500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranRecitersName500>

export const getQuranRecitersNameQueryResponseSchema = getQuranRecitersName200Schema as unknown as z.ZodType<GetQuranRecitersNameQueryResponse>