/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetQuranRecitersQueryParams, GetQuranReciters200, GetQuranReciters400, GetQuranReciters500, GetQuranRecitersQueryResponse } from "../../types/GetQuranReciters.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { quranReciterListSuccessResponseSchema } from "../quran/reciterListSuccessResponseSchema.ts";
import { z } from "zod";

export const getQuranRecitersQueryParamsSchema = z.object({
    "limit": z.coerce.number().int().default(0).describe("Limit (0 for all)"),
"offset": z.coerce.number().int().default(0).describe("Offset")
    }) as unknown as z.ZodType<GetQuranRecitersQueryParams>

/**
 * @description Reciters retrieved successfully
 */
export const getQuranReciters200Schema = quranReciterListSuccessResponseSchema as unknown as z.ZodType<GetQuranReciters200>

/**
 * @description Bad request
 */
export const getQuranReciters400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranReciters400>

/**
 * @description Internal server error
 */
export const getQuranReciters500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranReciters500>

export const getQuranRecitersQueryResponseSchema = getQuranReciters200Schema as unknown as z.ZodType<GetQuranRecitersQueryResponse>