/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetQuranRecitersIdPathParams, GetQuranRecitersId200, GetQuranRecitersId400, GetQuranRecitersId500, GetQuranRecitersIdQueryResponse } from "../../types/GetQuranRecitersId.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { quranReciterSuccessResponseSchema } from "../quran/reciterSuccessResponseSchema.ts";
import { z } from "zod";

export const getQuranRecitersIdPathParamsSchema = z.object({
    "id": z.string().describe("Reciter ID")
    }) as unknown as z.ZodType<GetQuranRecitersIdPathParams>

/**
 * @description Reciter retrieved successfully
 */
export const getQuranRecitersId200Schema = quranReciterSuccessResponseSchema as unknown as z.ZodType<GetQuranRecitersId200>

/**
 * @description Bad request
 */
export const getQuranRecitersId400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranRecitersId400>

/**
 * @description Internal server error
 */
export const getQuranRecitersId500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranRecitersId500>

export const getQuranRecitersIdQueryResponseSchema = getQuranRecitersId200Schema as unknown as z.ZodType<GetQuranRecitersIdQueryResponse>