/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PostQuranReciters201, PostQuranReciters400, PostQuranReciters500, PostQuranRecitersMutationRequest, PostQuranRecitersMutationResponse } from "../../types/PostQuranReciters.ts";
import { dtoCreateReciterRequestSchema } from "../dto/createReciterRequestSchema.ts";
import { quranCreateReciterSuccessResponseSchema } from "../quran/createReciterSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

/**
 * @description Reciter created successfully
 */
export const postQuranReciters201Schema = quranCreateReciterSuccessResponseSchema as unknown as z.ZodType<PostQuranReciters201>

/**
 * @description Bad request
 */
export const postQuranReciters400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PostQuranReciters400>

/**
 * @description Internal server error
 */
export const postQuranReciters500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PostQuranReciters500>

/**
 * @description Create reciter request
 */
export const postQuranRecitersMutationRequestSchema = dtoCreateReciterRequestSchema as unknown as z.ZodType<PostQuranRecitersMutationRequest>

export const postQuranRecitersMutationResponseSchema = postQuranReciters201Schema as unknown as z.ZodType<PostQuranRecitersMutationResponse>