/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PutQuranRecitersIdPathParams, PutQuranRecitersId200, PutQuranRecitersId400, PutQuranRecitersId500, PutQuranRecitersIdMutationRequest, PutQuranRecitersIdMutationResponse } from "../../types/PutQuranRecitersId.ts";
import { dtoUpdateReciterRequestSchema } from "../dto/updateReciterRequestSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { quranUpdateReciterSuccessResponseSchema } from "../quran/updateReciterSuccessResponseSchema.ts";
import { z } from "zod";

export const putQuranRecitersIdPathParamsSchema = z.object({
    "id": z.string().describe("Reciter ID")
    }) as unknown as z.ZodType<PutQuranRecitersIdPathParams>

/**
 * @description Reciter updated successfully
 */
export const putQuranRecitersId200Schema = quranUpdateReciterSuccessResponseSchema as unknown as z.ZodType<PutQuranRecitersId200>

/**
 * @description Bad request
 */
export const putQuranRecitersId400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PutQuranRecitersId400>

/**
 * @description Internal server error
 */
export const putQuranRecitersId500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PutQuranRecitersId500>

/**
 * @description Update reciter request
 */
export const putQuranRecitersIdMutationRequestSchema = dtoUpdateReciterRequestSchema as unknown as z.ZodType<PutQuranRecitersIdMutationRequest>

export const putQuranRecitersIdMutationResponseSchema = putQuranRecitersId200Schema as unknown as z.ZodType<PutQuranRecitersIdMutationResponse>