/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeleteQuranSurahsIdPathParams, DeleteQuranSurahsId200, DeleteQuranSurahsId400, DeleteQuranSurahsId404, DeleteQuranSurahsId500, DeleteQuranSurahsIdMutationResponse } from "../../types/DeleteQuranSurahsId.ts";
import { quranDeleteSurahSuccessResponseSchema } from "../quran/deleteSurahSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const deleteQuranSurahsIdPathParamsSchema = z.object({
    "id": z.string().describe("Surah ID")
    }) as unknown as z.ZodType<DeleteQuranSurahsIdPathParams>

/**
 * @description Surah deleted successfully
 */
export const deleteQuranSurahsId200Schema = quranDeleteSurahSuccessResponseSchema as unknown as z.ZodType<DeleteQuranSurahsId200>

/**
 * @description Bad request
 */
export const deleteQuranSurahsId400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<DeleteQuranSurahsId400>

/**
 * @description Surah not found
 */
export const deleteQuranSurahsId404Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<DeleteQuranSurahsId404>

/**
 * @description Internal server error
 */
export const deleteQuranSurahsId500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<DeleteQuranSurahsId500>

export const deleteQuranSurahsIdMutationResponseSchema = deleteQuranSurahsId200Schema as unknown as z.ZodType<DeleteQuranSurahsIdMutationResponse>