/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetQuranSurahsIdPathParams, GetQuranSurahsIdQueryParams, GetQuranSurahsId200, GetQuranSurahsId400, GetQuranSurahsId404, GetQuranSurahsId500, GetQuranSurahsIdQueryResponse } from "../../types/GetQuranSurahsId.ts";
import { quranGetSurahByIdSuccessResponseSchema } from "../quran/getSurahByIdSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const getQuranSurahsIdPathParamsSchema = z.object({
    "id": z.string().describe("Surah ID")
    }) as unknown as z.ZodType<GetQuranSurahsIdPathParams>

export const getQuranSurahsIdQueryParamsSchema = z.object({
    "include": z.optional(z.enum(["ayahs"]).describe("Include related data"))
    }).optional() as unknown as z.ZodType<GetQuranSurahsIdQueryParams>

/**
 * @description Surah retrieved successfully
 */
export const getQuranSurahsId200Schema = quranGetSurahByIdSuccessResponseSchema as unknown as z.ZodType<GetQuranSurahsId200>

/**
 * @description Bad request
 */
export const getQuranSurahsId400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranSurahsId400>

/**
 * @description Surah not found
 */
export const getQuranSurahsId404Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranSurahsId404>

/**
 * @description Internal server error
 */
export const getQuranSurahsId500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranSurahsId500>

export const getQuranSurahsIdQueryResponseSchema = getQuranSurahsId200Schema as unknown as z.ZodType<GetQuranSurahsIdQueryResponse>