/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetQuranSurahsQueryParams, GetQuranSurahs200, GetQuranSurahs400, GetQuranSurahs500, GetQuranSurahsQueryResponse } from "../../types/GetQuranSurahs.ts";
import { quranGetAllSurahsSuccessResponseSchema } from "../quran/getAllSurahsSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const getQuranSurahsQueryParamsSchema = z.object({
    "limit": z.coerce.number().int().default(0).describe("Limit (0 for all)"),
"offset": z.coerce.number().int().default(0).describe("Offset"),
"include": z.optional(z.enum(["ayahs"]).describe("Include related data"))
    }) as unknown as z.ZodType<GetQuranSurahsQueryParams>

/**
 * @description Surahs retrieved successfully
 */
export const getQuranSurahs200Schema = quranGetAllSurahsSuccessResponseSchema as unknown as z.ZodType<GetQuranSurahs200>

/**
 * @description Bad request
 */
export const getQuranSurahs400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranSurahs400>

/**
 * @description Internal server error
 */
export const getQuranSurahs500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranSurahs500>

export const getQuranSurahsQueryResponseSchema = getQuranSurahs200Schema as unknown as z.ZodType<GetQuranSurahsQueryResponse>