/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetQuranSurahsNumberPathParams, GetQuranSurahsNumberQueryParams, GetQuranSurahsNumber200, GetQuranSurahsNumber400, GetQuranSurahsNumber404, GetQuranSurahsNumber500, GetQuranSurahsNumberQueryResponse } from "../../types/GetQuranSurahsNumber.ts";
import { quranGetSurahByNumberSuccessResponseSchema } from "../quran/getSurahByNumberSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const getQuranSurahsNumberPathParamsSchema = z.object({
    "number": z.coerce.number().int().describe("Surah Number")
    }) as unknown as z.ZodType<GetQuranSurahsNumberPathParams>

export const getQuranSurahsNumberQueryParamsSchema = z.object({
    "include": z.optional(z.enum(["ayahs"]).describe("Include related data"))
    }).optional() as unknown as z.ZodType<GetQuranSurahsNumberQueryParams>

/**
 * @description Surah retrieved successfully
 */
export const getQuranSurahsNumber200Schema = quranGetSurahByNumberSuccessResponseSchema as unknown as z.ZodType<GetQuranSurahsNumber200>

/**
 * @description Bad request
 */
export const getQuranSurahsNumber400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranSurahsNumber400>

/**
 * @description Surah not found
 */
export const getQuranSurahsNumber404Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranSurahsNumber404>

/**
 * @description Internal server error
 */
export const getQuranSurahsNumber500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranSurahsNumber500>

export const getQuranSurahsNumberQueryResponseSchema = getQuranSurahsNumber200Schema as unknown as z.ZodType<GetQuranSurahsNumberQueryResponse>