/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PostQuranSurahs201, PostQuranSurahs400, PostQuranSurahs500, PostQuranSurahsMutationRequest, PostQuranSurahsMutationResponse } from "../../types/PostQuranSurahs.ts";
import { dtoCreateSurahRequestSchema } from "../dto/createSurahRequestSchema.ts";
import { quranCreateSurahSuccessResponseSchema } from "../quran/createSurahSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

/**
 * @description Surah created successfully
 */
export const postQuranSurahs201Schema = quranCreateSurahSuccessResponseSchema as unknown as z.ZodType<PostQuranSurahs201>

/**
 * @description Bad request
 */
export const postQuranSurahs400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PostQuranSurahs400>

/**
 * @description Internal server error
 */
export const postQuranSurahs500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PostQuranSurahs500>

/**
 * @description Create surah request
 */
export const postQuranSurahsMutationRequestSchema = dtoCreateSurahRequestSchema as unknown as z.ZodType<PostQuranSurahsMutationRequest>

export const postQuranSurahsMutationResponseSchema = postQuranSurahs201Schema as unknown as z.ZodType<PostQuranSurahsMutationResponse>