/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PutQuranSurahsIdPathParams, PutQuranSurahsId200, PutQuranSurahsId400, PutQuranSurahsId404, PutQuranSurahsId500, PutQuranSurahsIdMutationRequest, PutQuranSurahsIdMutationResponse } from "../../types/PutQuranSurahsId.ts";
import { dtoUpdateSurahRequestSchema } from "../dto/updateSurahRequestSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { quranUpdateSurahSuccessResponseSchema } from "../quran/updateSurahSuccessResponseSchema.ts";
import { z } from "zod";

export const putQuranSurahsIdPathParamsSchema = z.object({
    "id": z.string().describe("Surah ID")
    }) as unknown as z.ZodType<PutQuranSurahsIdPathParams>

/**
 * @description Surah updated successfully
 */
export const putQuranSurahsId200Schema = quranUpdateSurahSuccessResponseSchema as unknown as z.ZodType<PutQuranSurahsId200>

/**
 * @description Bad request
 */
export const putQuranSurahsId400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PutQuranSurahsId400>

/**
 * @description Surah not found
 */
export const putQuranSurahsId404Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PutQuranSurahsId404>

/**
 * @description Internal server error
 */
export const putQuranSurahsId500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PutQuranSurahsId500>

/**
 * @description Update surah request
 */
export const putQuranSurahsIdMutationRequestSchema = dtoUpdateSurahRequestSchema as unknown as z.ZodType<PutQuranSurahsIdMutationRequest>

export const putQuranSurahsIdMutationResponseSchema = putQuranSurahsId200Schema as unknown as z.ZodType<PutQuranSurahsIdMutationResponse>