/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoAyahAudioFileResponse } from "./AyahAudioFileResponse.ts";
import type { DtoPaginationResponse } from "./PaginationResponse.ts";

export type DtoAyahAudioFileListResponse = {
    /**
     * @type array | undefined
    */
    data?: DtoAyahAudioFileResponse[];
    /**
     * @type object | undefined
    */
    pagination?: DtoPaginationResponse;
};