/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoAyahTranslationResponse } from "./AyahTranslationResponse.ts";
import type { DtoPaginationResponse } from "./PaginationResponse.ts";

export type DtoAyahTranslationListResponse = {
    /**
     * @type array | undefined
    */
    data?: DtoAyahTranslationResponse[];
    /**
     * @type object | undefined
    */
    pagination?: DtoPaginationResponse;
};