/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoAyahResponse } from "./AyahResponse.ts";
import type { DtoPaginationResponse } from "./PaginationResponse.ts";

export type DtoAyahListResponse = {
    /**
     * @type array | undefined
    */
    data?: DtoAyahResponse[];
    /**
     * @type object | undefined
    */
    pagination?: DtoPaginationResponse;
};