/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoAyahAudioFileResponse = {
    /**
     * @type string | undefined
    */
    ayahId?: string;
    /**
     * @type number | undefined
    */
    byteSize?: number;
    /**
     * @type string | undefined
    */
    createdAt?: string;
    /**
     * @type string | undefined
    */
    createdBy?: string;
    /**
     * @type number | undefined
    */
    duration?: number;
    /**
     * @type string | undefined
    */
    filePath?: string;
    /**
     * @type string | undefined
    */
    id?: string;
    /**
     * @type string | undefined
    */
    reciterId?: string;
    /**
     * @type string | undefined
    */
    surahId?: string;
    /**
     * @type string | undefined
    */
    updatedAt?: string;
    /**
     * @type string | undefined
    */
    updatedBy?: string;
};