/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoAyahTranslationResponse = {
    /**
     * @type string | undefined
    */
    ayahId?: string;
    /**
     * @type string | undefined
    */
    createdAt?: string;
    /**
     * @type string | undefined
    */
    createdBy?: string;
    /**
     * @type string | undefined
    */
    id?: string;
    /**
     * @type string | undefined
    */
    surahId?: string;
    /**
     * @type string | undefined
    */
    text?: string;
    /**
     * @type string | undefined
    */
    translationEditionId?: string;
    /**
     * @type string | undefined
    */
    updatedAt?: string;
    /**
     * @type string | undefined
    */
    updatedBy?: string;
};