/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoBookmarkAyahResponse } from "./BookmarkAyahResponse.ts";
import type { DtoPaginationResponse } from "./PaginationResponse.ts";

export type DtoBookmarkAyahListResponse = {
    /**
     * @type array | undefined
    */
    data?: DtoBookmarkAyahResponse[];
    /**
     * @type object | undefined
    */
    pagination?: DtoPaginationResponse;
};