/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoCreateAyahAudioFileRequest = {
    /**
     * @type string
    */
    ayahId: string;
    /**
     * @minLength 0
     * @type number
    */
    byteSize: number;
    /**
     * @minLength 1
     * @maxLength 255
     * @type string
    */
    createdBy: string;
    /**
     * @minLength 0
     * @type number
    */
    duration: number;
    /**
     * @minLength 1
     * @type string
    */
    filePath: string;
    /**
     * @type string
    */
    reciterId: string;
    /**
     * @type string
    */
    surahId: string;
};