/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoCreateLastReadRequest = {
    /**
     * @type string
    */
    ayahId: string;
    /**
     * @minLength 1
     * @type integer
    */
    ayahNumber: number;
    /**
     * @minLength 0
     * @maxLength 100
     * @type number
    */
    progressPct: number;
    /**
     * @type string
    */
    surahId: string;
};