/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoCreateSurahRequest = {
    /**
     * @minLength 1
     * @type integer
    */
    ayahCount: number;
    /**
     * @minLength 1
     * @maxLength 255
     * @type string
    */
    createdBy: string;
    /**
     * @minLength 1
     * @maxLength 255
     * @type string
    */
    nameArabic: string;
    /**
     * @minLength 1
     * @maxLength 255
     * @type string
    */
    nameEnglish: string;
    /**
     * @minLength 1
     * @maxLength 114
     * @type integer
    */
    revelationOrder: number;
    /**
     * @minLength 1
     * @maxLength 100
     * @type string
    */
    revelationPlace: string;
};