/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoCreateProgressHatamRequest = {
    /**
     * @type string
    */
    juzId: string;
    /**
     * @minLength 0
     * @maxLength 100
     * @type number
    */
    progressPct: number;
    /**
     * @type string
    */
    startAyahId: string;
};