/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoCreateJuzRequest = {
    /**
     * @minLength 1
     * @maxLength 255
     * @type string
    */
    createdBy: string;
    /**
     * @type string
    */
    endAyahId: string;
    /**
     * @type string
    */
    endSurahId: string;
    /**
     * @type string
    */
    startAyahId: string;
    /**
     * @type string
    */
    startSurahId: string;
};