/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoJuzResponse } from "./JuzResponse.ts";
import type { DtoPaginationResponse } from "./PaginationResponse.ts";

export type DtoJuzListResponse = {
    /**
     * @type array | undefined
    */
    data?: DtoJuzResponse[];
    /**
     * @type object | undefined
    */
    pagination?: DtoPaginationResponse;
};