/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoJuzResponse = {
    /**
     * @type string | undefined
    */
    createdAt?: string;
    /**
     * @type string | undefined
    */
    createdBy?: string;
    /**
     * @type string | undefined
    */
    endAyahId?: string;
    /**
     * @type string | undefined
    */
    endSurahId?: string;
    /**
     * @type string | undefined
    */
    id?: string;
    /**
     * @type string | undefined
    */
    startAyahId?: string;
    /**
     * @type string | undefined
    */
    startSurahId?: string;
    /**
     * @type string | undefined
    */
    updatedAt?: string;
    /**
     * @type string | undefined
    */
    updatedBy?: string;
};