/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoJuzWithProgressBasicResponse } from "./JuzWithProgressBasicResponse.ts";
import type { DtoPaginationResponse } from "./PaginationResponse.ts";

export type DtoJuzWithProgressBasicListResponse = {
    /**
     * @type array | undefined
    */
    data?: DtoJuzWithProgressBasicResponse[];
    /**
     * @type object | undefined
    */
    pagination?: DtoPaginationResponse;
};