/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoLastReadResponse } from "./LastReadResponse.ts";
import type { DtoPaginationResponse } from "./PaginationResponse.ts";

export type DtoLastReadListResponse = {
    /**
     * @type array | undefined
    */
    data?: DtoLastReadResponse[];
    /**
     * @type object | undefined
    */
    pagination?: DtoPaginationResponse;
};