/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoLastReadResponse = {
    /**
     * @type string | undefined
    */
    ayahId?: string;
    /**
     * @type integer | undefined
    */
    ayahNumber?: number;
    /**
     * @type string | undefined
    */
    createdAt?: string;
    /**
     * @type string | undefined
    */
    createdBy?: string;
    /**
     * @type string | undefined
    */
    id?: string;
    /**
     * @type string | undefined
    */
    lastReadAt?: string;
    /**
     * @type number | undefined
    */
    progressPct?: number;
    /**
     * @type string | undefined
    */
    surahId?: string;
    /**
     * @type string | undefined
    */
    updatedAt?: string;
    /**
     * @type string | undefined
    */
    updatedBy?: string;
    /**
     * @type string | undefined
    */
    userId?: string;
};