/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoPrayerTimesResponse } from "./PrayerTimesResponse.ts";

export type DtoPrayerTimesListResponse = {
    /**
     * @type array | undefined
    */
    items?: DtoPrayerTimesResponse[];
};