/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoPaginationResponse } from "./PaginationResponse.ts";
import type { DtoProgressHatamResponse } from "./ProgressHatamResponse.ts";

export type DtoProgressHatamListResponse = {
    /**
     * @type array | undefined
    */
    data?: DtoProgressHatamResponse[];
    /**
     * @type object | undefined
    */
    pagination?: DtoPaginationResponse;
};