/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoPaginationResponse } from "./PaginationResponse.ts";
import type { DtoReciterResponse } from "./ReciterResponse.ts";

export type DtoReciterListResponse = {
    /**
     * @type array | undefined
    */
    data?: DtoReciterResponse[];
    /**
     * @type object | undefined
    */
    pagination?: DtoPaginationResponse;
};