/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoReciterResponse = {
    /**
     * @type string | undefined
    */
    createdAt?: string;
    /**
     * @type string | undefined
    */
    createdBy?: string;
    /**
     * @type string | undefined
    */
    id?: string;
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string | undefined
    */
    picture?: string;
    /**
     * @type string | undefined
    */
    place?: string;
    /**
     * @type string | undefined
    */
    style?: string;
    /**
     * @type string | undefined
    */
    updatedAt?: string;
    /**
     * @type string | undefined
    */
    updatedBy?: string;
};