/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoAyahWithTranslationResponse } from "./AyahWithTranslationResponse.ts";
import type { DtoPaginationResponse } from "./PaginationResponse.ts";
import type { DtoReciterResponse } from "./ReciterResponse.ts";
import type { DtoSurahResponse } from "./SurahResponse.ts";

export type DtoSurahAyahsWithTranslationsResponse = {
    /**
     * @type array | undefined
    */
    ayahs?: DtoAyahWithTranslationResponse[];
    /**
     * @type object | undefined
    */
    pagination?: DtoPaginationResponse;
    /**
     * @type object | undefined
    */
    reciter?: DtoReciterResponse;
    /**
     * @type object | undefined
    */
    surah?: DtoSurahResponse;
};