/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoPaginationResponse } from "./PaginationResponse.ts";
import type { DtoSurahResponse } from "./SurahResponse.ts";

export type DtoSurahListResponse = {
    /**
     * @type array | undefined
    */
    data?: DtoSurahResponse[];
    /**
     * @type object | undefined
    */
    pagination?: DtoPaginationResponse;
};