/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoPaginationResponse } from "./PaginationResponse.ts";
import type { DtoTranslationEditionResponse } from "./TranslationEditionResponse.ts";

export type DtoTranslationEditionListResponse = {
    /**
     * @type array | undefined
    */
    data?: DtoTranslationEditionResponse[];
    /**
     * @type object | undefined
    */
    pagination?: DtoPaginationResponse;
};