/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoUpdateLastReadRequest = {
    /**
     * @type string
    */
    ayahId: string;
    /**
     * @minLength 1
     * @type integer
    */
    ayahNumber: number;
    /**
     * @type string
    */
    id: string;
    /**
     * @minLength 0
     * @maxLength 100
     * @type number
    */
    progressPct: number;
    /**
     * @minLength 1
     * @maxLength 255
     * @type string
    */
    updatedBy: string;
};