/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoUpdateAyahAudioFileRequest = {
    /**
     * @minLength 0
     * @type number
    */
    byteSize: number;
    /**
     * @minLength 0
     * @type number
    */
    duration: number;
    /**
     * @minLength 1
     * @type string
    */
    filePath: string;
    /**
     * @type string
    */
    id: string;
    /**
     * @minLength 1
     * @maxLength 255
     * @type string
    */
    updatedBy: string;
};