/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoUpdateProgressHatamRequest = {
    /**
     * @type string | undefined
    */
    completedAt?: string;
    /**
     * @type string
    */
    id: string;
    /**
     * @type boolean
    */
    isCompleted: boolean;
    /**
     * @type string
    */
    lastAyahId: string;
    /**
     * @minLength 0
     * @maxLength 100
     * @type number
    */
    progressPct: number;
    /**
     * @minLength 1
     * @maxLength 255
     * @type string
    */
    updatedBy: string;
};