/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoUpdateAyahRequest = {
    /**
     * @minLength 1
     * @maxLength 60
     * @type integer
    */
    hizbNumber: number;
    /**
     * @type string
    */
    id: string;
    /**
     * @minLength 1
     * @maxLength 30
     * @type integer
    */
    juzNumber: number;
    /**
     * @minLength 1
     * @maxLength 7
     * @type integer
    */
    manzilNumber: number;
    /**
     * @minLength 1
     * @maxLength 604
     * @type integer
    */
    pageNumber: number;
    /**
     * @minLength 1
     * @type string
    */
    text: string;
    /**
     * @minLength 1
     * @maxLength 255
     * @type string
    */
    updatedBy: string;
};