/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DtoUpdateReciterRequest = {
    /**
     * @type string
    */
    id: string;
    /**
     * @minLength 1
     * @maxLength 255
     * @type string
    */
    name: string;
    /**
     * @maxLength 255
     * @type string | undefined
    */
    picture?: string;
    /**
     * @maxLength 20
     * @type string | undefined
    */
    place?: string;
    /**
     * @minLength 1
     * @maxLength 255
     * @type string
    */
    style: string;
    /**
     * @minLength 1
     * @maxLength 255
     * @type string
    */
    updatedBy: string;
};