/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { DeleteQuranAudioAyahsIdMutationResponse, DeleteQuranAudioAyahsIdPathParams, DeleteQuranAudioAyahsId400, DeleteQuranAudioAyahsId500 } from "../../types/DeleteQuranAudioAyahsId.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteQuranAudioAyahsIdMutationKey = () => [{ url: '/quran/audio/ayahs/:id' }] as const

export type DeleteQuranAudioAyahsIdMutationKey = ReturnType<typeof deleteQuranAudioAyahsIdMutationKey>

/**
 * @description Delete an ayah audio file by ID
 * @summary Delete an ayah audio file
 * {@link /quran/audio/ayahs/:id}
 */
export async function deleteQuranAudioAyahsIdHook(id: DeleteQuranAudioAyahsIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteQuranAudioAyahsIdMutationResponse, ResponseErrorConfig<DeleteQuranAudioAyahsId400 | DeleteQuranAudioAyahsId500>, unknown>({ method : "DELETE", url : `/quran/audio/ayahs/${id}`, ... requestConfig })  
  return res.data
}

export function deleteQuranAudioAyahsIdMutationOptionsHook(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = deleteQuranAudioAyahsIdMutationKey()
  return mutationOptions<DeleteQuranAudioAyahsIdMutationResponse, ResponseErrorConfig<DeleteQuranAudioAyahsId400 | DeleteQuranAudioAyahsId500>, {id: DeleteQuranAudioAyahsIdPathParams["id"]}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id }) => {
      return deleteQuranAudioAyahsIdHook(id, config)
    },
  })
}

/**
 * @description Delete an ayah audio file by ID
 * @summary Delete an ayah audio file
 * {@link /quran/audio/ayahs/:id}
 */
export function useDeleteQuranAudioAyahsIdHook<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteQuranAudioAyahsIdMutationResponse, ResponseErrorConfig<DeleteQuranAudioAyahsId400 | DeleteQuranAudioAyahsId500>, {id: DeleteQuranAudioAyahsIdPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteQuranAudioAyahsIdMutationKey()

  const baseOptions = deleteQuranAudioAyahsIdMutationOptionsHook(config) as UseMutationOptions<DeleteQuranAudioAyahsIdMutationResponse, ResponseErrorConfig<DeleteQuranAudioAyahsId400 | DeleteQuranAudioAyahsId500>, {id: DeleteQuranAudioAyahsIdPathParams["id"]}, TContext>

  return useMutation<DeleteQuranAudioAyahsIdMutationResponse, ResponseErrorConfig<DeleteQuranAudioAyahsId400 | DeleteQuranAudioAyahsId500>, {id: DeleteQuranAudioAyahsIdPathParams["id"]}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<DeleteQuranAudioAyahsIdMutationResponse, ResponseErrorConfig<DeleteQuranAudioAyahsId400 | DeleteQuranAudioAyahsId500>, {id: DeleteQuranAudioAyahsIdPathParams["id"]}, TContext>
}