/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetQuranAudioAyahsIdQueryResponse, GetQuranAudioAyahsIdPathParams, GetQuranAudioAyahsId400, GetQuranAudioAyahsId500 } from "../../types/GetQuranAudioAyahsId.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getQuranAudioAyahsIdQueryKey = (id: GetQuranAudioAyahsIdPathParams["id"]) => [{ url: '/quran/audio/ayahs/:id', params: {id:id} }] as const

export type GetQuranAudioAyahsIdQueryKey = ReturnType<typeof getQuranAudioAyahsIdQueryKey>

/**
 * @description Get an ayah audio file by ID
 * @summary Get ayah audio file by ID
 * {@link /quran/audio/ayahs/:id}
 */
export async function getQuranAudioAyahsIdHook(id: GetQuranAudioAyahsIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetQuranAudioAyahsIdQueryResponse, ResponseErrorConfig<GetQuranAudioAyahsId400 | GetQuranAudioAyahsId500>, unknown>({ method : "GET", url : `/quran/audio/ayahs/${id}`, ... requestConfig })  
  return res.data
}

export function getQuranAudioAyahsIdQueryOptionsHook(id: GetQuranAudioAyahsIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getQuranAudioAyahsIdQueryKey(id)
  return queryOptions<GetQuranAudioAyahsIdQueryResponse, ResponseErrorConfig<GetQuranAudioAyahsId400 | GetQuranAudioAyahsId500>, GetQuranAudioAyahsIdQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getQuranAudioAyahsIdHook(id, config)
   },
  })
}

/**
 * @description Get an ayah audio file by ID
 * @summary Get ayah audio file by ID
 * {@link /quran/audio/ayahs/:id}
 */
export function useGetQuranAudioAyahsIdHook<TData = GetQuranAudioAyahsIdQueryResponse, TQueryData = GetQuranAudioAyahsIdQueryResponse, TQueryKey extends QueryKey = GetQuranAudioAyahsIdQueryKey>(id: GetQuranAudioAyahsIdPathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<GetQuranAudioAyahsIdQueryResponse, ResponseErrorConfig<GetQuranAudioAyahsId400 | GetQuranAudioAyahsId500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getQuranAudioAyahsIdQueryKey(id)

  const query = useQuery({
   ...getQuranAudioAyahsIdQueryOptionsHook(id, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetQuranAudioAyahsId400 | GetQuranAudioAyahsId500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}