/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetQuranAudioAyahsSurahSurahidReciterReciteridQueryResponse, GetQuranAudioAyahsSurahSurahidReciterReciteridPathParams, GetQuranAudioAyahsSurahSurahidReciterReciteridQueryParams, GetQuranAudioAyahsSurahSurahidReciterReciterid400, GetQuranAudioAyahsSurahSurahidReciterReciterid500 } from "../../types/GetQuranAudioAyahsSurahSurahidReciterReciterid.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getQuranAudioAyahsSurahSurahidReciterReciteridQueryKey = (surahId: GetQuranAudioAyahsSurahSurahidReciterReciteridPathParams["surahId"], reciterId: GetQuranAudioAyahsSurahSurahidReciterReciteridPathParams["reciterId"], params?: GetQuranAudioAyahsSurahSurahidReciterReciteridQueryParams) => [{ url: '/quran/audio/ayahs/surah/:surahId/reciter/:reciterId', params: {surahId:surahId,reciterId:reciterId} }, ...(params ? [params] : [])] as const

export type GetQuranAudioAyahsSurahSurahidReciterReciteridQueryKey = ReturnType<typeof getQuranAudioAyahsSurahSurahidReciterReciteridQueryKey>

/**
 * @description List ayah audio files by surah and reciter IDs with pagination
 * @summary List ayah audio files by surah and reciter
 * {@link /quran/audio/ayahs/surah/:surahId/reciter/:reciterId}
 */
export async function getQuranAudioAyahsSurahSurahidReciterReciteridHook(surahId: GetQuranAudioAyahsSurahSurahidReciterReciteridPathParams["surahId"], reciterId: GetQuranAudioAyahsSurahSurahidReciterReciteridPathParams["reciterId"], params?: GetQuranAudioAyahsSurahSurahidReciterReciteridQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetQuranAudioAyahsSurahSurahidReciterReciteridQueryResponse, ResponseErrorConfig<GetQuranAudioAyahsSurahSurahidReciterReciterid400 | GetQuranAudioAyahsSurahSurahidReciterReciterid500>, unknown>({ method : "GET", url : `/quran/audio/ayahs/surah/${surahId}/reciter/${reciterId}`, params, ... requestConfig })  
  return res.data
}

export function getQuranAudioAyahsSurahSurahidReciterReciteridQueryOptionsHook(surahId: GetQuranAudioAyahsSurahSurahidReciterReciteridPathParams["surahId"], reciterId: GetQuranAudioAyahsSurahSurahidReciterReciteridPathParams["reciterId"], params?: GetQuranAudioAyahsSurahSurahidReciterReciteridQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getQuranAudioAyahsSurahSurahidReciterReciteridQueryKey(surahId, reciterId, params)
  return queryOptions<GetQuranAudioAyahsSurahSurahidReciterReciteridQueryResponse, ResponseErrorConfig<GetQuranAudioAyahsSurahSurahidReciterReciterid400 | GetQuranAudioAyahsSurahSurahidReciterReciterid500>, GetQuranAudioAyahsSurahSurahidReciterReciteridQueryResponse, typeof queryKey>({
   enabled: !!(surahId&& reciterId),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getQuranAudioAyahsSurahSurahidReciterReciteridHook(surahId, reciterId, params, config)
   },
  })
}

/**
 * @description List ayah audio files by surah and reciter IDs with pagination
 * @summary List ayah audio files by surah and reciter
 * {@link /quran/audio/ayahs/surah/:surahId/reciter/:reciterId}
 */
export function useGetQuranAudioAyahsSurahSurahidReciterReciteridHook<TData = GetQuranAudioAyahsSurahSurahidReciterReciteridQueryResponse, TQueryData = GetQuranAudioAyahsSurahSurahidReciterReciteridQueryResponse, TQueryKey extends QueryKey = GetQuranAudioAyahsSurahSurahidReciterReciteridQueryKey>(surahId: GetQuranAudioAyahsSurahSurahidReciterReciteridPathParams["surahId"], reciterId: GetQuranAudioAyahsSurahSurahidReciterReciteridPathParams["reciterId"], params?: GetQuranAudioAyahsSurahSurahidReciterReciteridQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetQuranAudioAyahsSurahSurahidReciterReciteridQueryResponse, ResponseErrorConfig<GetQuranAudioAyahsSurahSurahidReciterReciterid400 | GetQuranAudioAyahsSurahSurahidReciterReciterid500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getQuranAudioAyahsSurahSurahidReciterReciteridQueryKey(surahId, reciterId, params)

  const query = useQuery({
   ...getQuranAudioAyahsSurahSurahidReciterReciteridQueryOptionsHook(surahId, reciterId, params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetQuranAudioAyahsSurahSurahidReciterReciterid400 | GetQuranAudioAyahsSurahSurahidReciterReciterid500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}