/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetQuranAudioAyahsAyahAyahidReciterReciteridQueryResponse, GetQuranAudioAyahsAyahAyahidReciterReciteridPathParams, GetQuranAudioAyahsAyahAyahidReciterReciterid400, GetQuranAudioAyahsAyahAyahidReciterReciterid500 } from "../../types/GetQuranAudioAyahsAyahAyahidReciterReciterid.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getQuranAudioAyahsAyahAyahidReciterReciteridQueryKey = (ayahId: GetQuranAudioAyahsAyahAyahidReciterReciteridPathParams["ayahId"], reciterId: GetQuranAudioAyahsAyahAyahidReciterReciteridPathParams["reciterId"]) => [{ url: '/quran/audio/ayahs/ayah/:ayahId/reciter/:reciterId', params: {ayahId:ayahId,reciterId:reciterId} }] as const

export type GetQuranAudioAyahsAyahAyahidReciterReciteridQueryKey = ReturnType<typeof getQuranAudioAyahsAyahAyahidReciterReciteridQueryKey>

/**
 * @description Get an ayah audio file by ayah and reciter IDs
 * @summary Get ayah audio file by ayah and reciter
 * {@link /quran/audio/ayahs/ayah/:ayahId/reciter/:reciterId}
 */
export async function getQuranAudioAyahsAyahAyahidReciterReciteridHook(ayahId: GetQuranAudioAyahsAyahAyahidReciterReciteridPathParams["ayahId"], reciterId: GetQuranAudioAyahsAyahAyahidReciterReciteridPathParams["reciterId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetQuranAudioAyahsAyahAyahidReciterReciteridQueryResponse, ResponseErrorConfig<GetQuranAudioAyahsAyahAyahidReciterReciterid400 | GetQuranAudioAyahsAyahAyahidReciterReciterid500>, unknown>({ method : "GET", url : `/quran/audio/ayahs/ayah/${ayahId}/reciter/${reciterId}`, ... requestConfig })  
  return res.data
}

export function getQuranAudioAyahsAyahAyahidReciterReciteridQueryOptionsHook(ayahId: GetQuranAudioAyahsAyahAyahidReciterReciteridPathParams["ayahId"], reciterId: GetQuranAudioAyahsAyahAyahidReciterReciteridPathParams["reciterId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getQuranAudioAyahsAyahAyahidReciterReciteridQueryKey(ayahId, reciterId)
  return queryOptions<GetQuranAudioAyahsAyahAyahidReciterReciteridQueryResponse, ResponseErrorConfig<GetQuranAudioAyahsAyahAyahidReciterReciterid400 | GetQuranAudioAyahsAyahAyahidReciterReciterid500>, GetQuranAudioAyahsAyahAyahidReciterReciteridQueryResponse, typeof queryKey>({
   enabled: !!(ayahId&& reciterId),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getQuranAudioAyahsAyahAyahidReciterReciteridHook(ayahId, reciterId, config)
   },
  })
}

/**
 * @description Get an ayah audio file by ayah and reciter IDs
 * @summary Get ayah audio file by ayah and reciter
 * {@link /quran/audio/ayahs/ayah/:ayahId/reciter/:reciterId}
 */
export function useGetQuranAudioAyahsAyahAyahidReciterReciteridHook<TData = GetQuranAudioAyahsAyahAyahidReciterReciteridQueryResponse, TQueryData = GetQuranAudioAyahsAyahAyahidReciterReciteridQueryResponse, TQueryKey extends QueryKey = GetQuranAudioAyahsAyahAyahidReciterReciteridQueryKey>(ayahId: GetQuranAudioAyahsAyahAyahidReciterReciteridPathParams["ayahId"], reciterId: GetQuranAudioAyahsAyahAyahidReciterReciteridPathParams["reciterId"], options: 
{
  query?: Partial<QueryObserverOptions<GetQuranAudioAyahsAyahAyahidReciterReciteridQueryResponse, ResponseErrorConfig<GetQuranAudioAyahsAyahAyahidReciterReciterid400 | GetQuranAudioAyahsAyahAyahidReciterReciterid500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getQuranAudioAyahsAyahAyahidReciterReciteridQueryKey(ayahId, reciterId)

  const query = useQuery({
   ...getQuranAudioAyahsAyahAyahidReciterReciteridQueryOptionsHook(ayahId, reciterId, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetQuranAudioAyahsAyahAyahidReciterReciterid400 | GetQuranAudioAyahsAyahAyahidReciterReciterid500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}