/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { PostQuranAudioAyahsMutationRequest, PostQuranAudioAyahsMutationResponse, PostQuranAudioAyahs400, PostQuranAudioAyahs500 } from "../../types/PostQuranAudioAyahs.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postQuranAudioAyahsMutationKey = () => [{ url: '/quran/audio/ayahs' }] as const

export type PostQuranAudioAyahsMutationKey = ReturnType<typeof postQuranAudioAyahsMutationKey>

/**
 * @description Create a new ayah audio file
 * @summary Create a new ayah audio file
 * {@link /quran/audio/ayahs}
 */
export async function postQuranAudioAyahsHook(data: PostQuranAudioAyahsMutationRequest, config: Partial<RequestConfig<PostQuranAudioAyahsMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostQuranAudioAyahsMutationResponse, ResponseErrorConfig<PostQuranAudioAyahs400 | PostQuranAudioAyahs500>, PostQuranAudioAyahsMutationRequest>({ method : "POST", url : `/quran/audio/ayahs`, data : requestData, ... requestConfig })  
  return res.data
}

export function postQuranAudioAyahsMutationOptionsHook(config: Partial<RequestConfig<PostQuranAudioAyahsMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = postQuranAudioAyahsMutationKey()
  return mutationOptions<PostQuranAudioAyahsMutationResponse, ResponseErrorConfig<PostQuranAudioAyahs400 | PostQuranAudioAyahs500>, {data: PostQuranAudioAyahsMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return postQuranAudioAyahsHook(data, config)
    },
  })
}

/**
 * @description Create a new ayah audio file
 * @summary Create a new ayah audio file
 * {@link /quran/audio/ayahs}
 */
export function usePostQuranAudioAyahsHook<TContext>(options: 
{
  mutation?: UseMutationOptions<PostQuranAudioAyahsMutationResponse, ResponseErrorConfig<PostQuranAudioAyahs400 | PostQuranAudioAyahs500>, {data: PostQuranAudioAyahsMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostQuranAudioAyahsMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postQuranAudioAyahsMutationKey()

  const baseOptions = postQuranAudioAyahsMutationOptionsHook(config) as UseMutationOptions<PostQuranAudioAyahsMutationResponse, ResponseErrorConfig<PostQuranAudioAyahs400 | PostQuranAudioAyahs500>, {data: PostQuranAudioAyahsMutationRequest}, TContext>

  return useMutation<PostQuranAudioAyahsMutationResponse, ResponseErrorConfig<PostQuranAudioAyahs400 | PostQuranAudioAyahs500>, {data: PostQuranAudioAyahsMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<PostQuranAudioAyahsMutationResponse, ResponseErrorConfig<PostQuranAudioAyahs400 | PostQuranAudioAyahs500>, {data: PostQuranAudioAyahsMutationRequest}, TContext>
}