/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { PutQuranAudioAyahsIdMutationRequest, PutQuranAudioAyahsIdMutationResponse, PutQuranAudioAyahsIdPathParams, PutQuranAudioAyahsId400, PutQuranAudioAyahsId500 } from "../../types/PutQuranAudioAyahsId.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const putQuranAudioAyahsIdMutationKey = () => [{ url: '/quran/audio/ayahs/:id' }] as const

export type PutQuranAudioAyahsIdMutationKey = ReturnType<typeof putQuranAudioAyahsIdMutationKey>

/**
 * @description Update an existing ayah audio file
 * @summary Update an ayah audio file
 * {@link /quran/audio/ayahs/:id}
 */
export async function putQuranAudioAyahsIdHook(id: PutQuranAudioAyahsIdPathParams["id"], data: PutQuranAudioAyahsIdMutationRequest, config: Partial<RequestConfig<PutQuranAudioAyahsIdMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PutQuranAudioAyahsIdMutationResponse, ResponseErrorConfig<PutQuranAudioAyahsId400 | PutQuranAudioAyahsId500>, PutQuranAudioAyahsIdMutationRequest>({ method : "PUT", url : `/quran/audio/ayahs/${id}`, data : requestData, ... requestConfig })  
  return res.data
}

export function putQuranAudioAyahsIdMutationOptionsHook(config: Partial<RequestConfig<PutQuranAudioAyahsIdMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = putQuranAudioAyahsIdMutationKey()
  return mutationOptions<PutQuranAudioAyahsIdMutationResponse, ResponseErrorConfig<PutQuranAudioAyahsId400 | PutQuranAudioAyahsId500>, {id: PutQuranAudioAyahsIdPathParams["id"], data: PutQuranAudioAyahsIdMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id, data }) => {
      return putQuranAudioAyahsIdHook(id, data, config)
    },
  })
}

/**
 * @description Update an existing ayah audio file
 * @summary Update an ayah audio file
 * {@link /quran/audio/ayahs/:id}
 */
export function usePutQuranAudioAyahsIdHook<TContext>(options: 
{
  mutation?: UseMutationOptions<PutQuranAudioAyahsIdMutationResponse, ResponseErrorConfig<PutQuranAudioAyahsId400 | PutQuranAudioAyahsId500>, {id: PutQuranAudioAyahsIdPathParams["id"], data: PutQuranAudioAyahsIdMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PutQuranAudioAyahsIdMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? putQuranAudioAyahsIdMutationKey()

  const baseOptions = putQuranAudioAyahsIdMutationOptionsHook(config) as UseMutationOptions<PutQuranAudioAyahsIdMutationResponse, ResponseErrorConfig<PutQuranAudioAyahsId400 | PutQuranAudioAyahsId500>, {id: PutQuranAudioAyahsIdPathParams["id"], data: PutQuranAudioAyahsIdMutationRequest}, TContext>

  return useMutation<PutQuranAudioAyahsIdMutationResponse, ResponseErrorConfig<PutQuranAudioAyahsId400 | PutQuranAudioAyahsId500>, {id: PutQuranAudioAyahsIdPathParams["id"], data: PutQuranAudioAyahsIdMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<PutQuranAudioAyahsIdMutationResponse, ResponseErrorConfig<PutQuranAudioAyahsId400 | PutQuranAudioAyahsId500>, {id: PutQuranAudioAyahsIdPathParams["id"], data: PutQuranAudioAyahsIdMutationRequest}, TContext>
}