/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeleteQuranLastReadsIdPathParams, DeleteQuranLastReadsId200, DeleteQuranLastReadsId400, DeleteQuranLastReadsId404, DeleteQuranLastReadsId500, DeleteQuranLastReadsIdMutationResponse } from "../../types/DeleteQuranLastReadsId.ts";
import { quranDeleteLastReadSuccessResponseSchema } from "../quran/deleteLastReadSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const deleteQuranLastReadsIdPathParamsSchema = z.object({
    "id": z.string().describe("LastRead ID")
    }) as unknown as z.ZodType<DeleteQuranLastReadsIdPathParams>

/**
 * @description Last read deleted successfully
 */
export const deleteQuranLastReadsId200Schema = quranDeleteLastReadSuccessResponseSchema as unknown as z.ZodType<DeleteQuranLastReadsId200>

/**
 * @description Bad request
 */
export const deleteQuranLastReadsId400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<DeleteQuranLastReadsId400>

/**
 * @description Last read not found
 */
export const deleteQuranLastReadsId404Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<DeleteQuranLastReadsId404>

/**
 * @description Internal server error
 */
export const deleteQuranLastReadsId500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<DeleteQuranLastReadsId500>

export const deleteQuranLastReadsIdMutationResponseSchema = deleteQuranLastReadsId200Schema as unknown as z.ZodType<DeleteQuranLastReadsIdMutationResponse>