/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetQuranLastReadsSurahSurahidPathParams, GetQuranLastReadsSurahSurahidQueryParams, GetQuranLastReadsSurahSurahid200, GetQuranLastReadsSurahSurahid400, GetQuranLastReadsSurahSurahid404, GetQuranLastReadsSurahSurahid500, GetQuranLastReadsSurahSurahidQueryResponse } from "../../types/GetQuranLastReadsSurahSurahid.ts";
import { quranLastReadSuccessResponseSchema } from "../quran/lastReadSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const getQuranLastReadsSurahSurahidPathParamsSchema = z.object({
    "surahId": z.string().describe("Surah ID")
    }) as unknown as z.ZodType<GetQuranLastReadsSurahSurahidPathParams>

export const getQuranLastReadsSurahSurahidQueryParamsSchema = z.object({
    "include": z.optional(z.enum(["relations"]).describe("Include related data"))
    }).optional() as unknown as z.ZodType<GetQuranLastReadsSurahSurahidQueryParams>

/**
 * @description Last read retrieved successfully
 */
export const getQuranLastReadsSurahSurahid200Schema = quranLastReadSuccessResponseSchema as unknown as z.ZodType<GetQuranLastReadsSurahSurahid200>

/**
 * @description Bad request
 */
export const getQuranLastReadsSurahSurahid400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranLastReadsSurahSurahid400>

/**
 * @description Last read not found
 */
export const getQuranLastReadsSurahSurahid404Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranLastReadsSurahSurahid404>

/**
 * @description Internal server error
 */
export const getQuranLastReadsSurahSurahid500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranLastReadsSurahSurahid500>

export const getQuranLastReadsSurahSurahidQueryResponseSchema = getQuranLastReadsSurahSurahid200Schema as unknown as z.ZodType<GetQuranLastReadsSurahSurahidQueryResponse>