/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetQuranLastReadsQueryParams, GetQuranLastReads200, GetQuranLastReads400, GetQuranLastReads500, GetQuranLastReadsQueryResponse } from "../../types/GetQuranLastReads.ts";
import { quranLastReadListSuccessResponseSchema } from "../quran/lastReadListSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const getQuranLastReadsQueryParamsSchema = z.object({
    "limit": z.optional(z.coerce.number().int().describe("Limit")),
"offset": z.optional(z.coerce.number().int().describe("Offset")),
"include": z.optional(z.enum(["relations"]).describe("Include related data"))
    }).optional() as unknown as z.ZodType<GetQuranLastReadsQueryParams>

/**
 * @description Last reads retrieved successfully
 */
export const getQuranLastReads200Schema = quranLastReadListSuccessResponseSchema as unknown as z.ZodType<GetQuranLastReads200>

/**
 * @description Bad request
 */
export const getQuranLastReads400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranLastReads400>

/**
 * @description Internal server error
 */
export const getQuranLastReads500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranLastReads500>

export const getQuranLastReadsQueryResponseSchema = getQuranLastReads200Schema as unknown as z.ZodType<GetQuranLastReadsQueryResponse>