/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetQuranLastReadsIdPathParams, GetQuranLastReadsIdQueryParams, GetQuranLastReadsId200, GetQuranLastReadsId400, GetQuranLastReadsId404, GetQuranLastReadsId500, GetQuranLastReadsIdQueryResponse } from "../../types/GetQuranLastReadsId.ts";
import { quranLastReadSuccessResponseSchema } from "../quran/lastReadSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const getQuranLastReadsIdPathParamsSchema = z.object({
    "id": z.string().describe("LastRead ID")
    }) as unknown as z.ZodType<GetQuranLastReadsIdPathParams>

export const getQuranLastReadsIdQueryParamsSchema = z.object({
    "include": z.optional(z.enum(["relations"]).describe("Include related data"))
    }).optional() as unknown as z.ZodType<GetQuranLastReadsIdQueryParams>

/**
 * @description Last read retrieved successfully
 */
export const getQuranLastReadsId200Schema = quranLastReadSuccessResponseSchema as unknown as z.ZodType<GetQuranLastReadsId200>

/**
 * @description Bad request
 */
export const getQuranLastReadsId400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranLastReadsId400>

/**
 * @description Last read not found
 */
export const getQuranLastReadsId404Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranLastReadsId404>

/**
 * @description Internal server error
 */
export const getQuranLastReadsId500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranLastReadsId500>

export const getQuranLastReadsIdQueryResponseSchema = getQuranLastReadsId200Schema as unknown as z.ZodType<GetQuranLastReadsIdQueryResponse>