/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PostQuranLastReads201, PostQuranLastReads400, PostQuranLastReads500, PostQuranLastReadsMutationRequest, PostQuranLastReadsMutationResponse } from "../../types/PostQuranLastReads.ts";
import { dtoCreateLastReadRequestSchema } from "../dto/createLastReadRequestSchema.ts";
import { quranLastReadSuccessResponseSchema } from "../quran/lastReadSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

/**
 * @description Last read created successfully
 */
export const postQuranLastReads201Schema = quranLastReadSuccessResponseSchema as unknown as z.ZodType<PostQuranLastReads201>

/**
 * @description Bad request
 */
export const postQuranLastReads400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PostQuranLastReads400>

/**
 * @description Internal server error
 */
export const postQuranLastReads500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PostQuranLastReads500>

/**
 * @description LastRead information
 */
export const postQuranLastReadsMutationRequestSchema = dtoCreateLastReadRequestSchema as unknown as z.ZodType<PostQuranLastReadsMutationRequest>

export const postQuranLastReadsMutationResponseSchema = postQuranLastReads201Schema as unknown as z.ZodType<PostQuranLastReadsMutationResponse>