/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PutQuranLastReadsIdPathParams, PutQuranLastReadsId200, PutQuranLastReadsId400, PutQuranLastReadsId404, PutQuranLastReadsId500, PutQuranLastReadsIdMutationRequest, PutQuranLastReadsIdMutationResponse } from "../../types/PutQuranLastReadsId.ts";
import { dtoUpdateLastReadRequestSchema } from "../dto/updateLastReadRequestSchema.ts";
import { quranLastReadSuccessResponseSchema } from "../quran/lastReadSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const putQuranLastReadsIdPathParamsSchema = z.object({
    "id": z.string().describe("LastRead ID")
    }) as unknown as z.ZodType<PutQuranLastReadsIdPathParams>

/**
 * @description Last read updated successfully
 */
export const putQuranLastReadsId200Schema = quranLastReadSuccessResponseSchema as unknown as z.ZodType<PutQuranLastReadsId200>

/**
 * @description Bad request
 */
export const putQuranLastReadsId400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PutQuranLastReadsId400>

/**
 * @description Last read not found
 */
export const putQuranLastReadsId404Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PutQuranLastReadsId404>

/**
 * @description Internal server error
 */
export const putQuranLastReadsId500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PutQuranLastReadsId500>

/**
 * @description LastRead update information
 */
export const putQuranLastReadsIdMutationRequestSchema = dtoUpdateLastReadRequestSchema as unknown as z.ZodType<PutQuranLastReadsIdMutationRequest>

export const putQuranLastReadsIdMutationResponseSchema = putQuranLastReadsId200Schema as unknown as z.ZodType<PutQuranLastReadsIdMutationResponse>