export type { DeleteQuranRecitersIdMutationKey } from "./useDeleteQuranRecitersIdHook.ts";
export type { GetQuranRecitersQueryKey } from "./useGetQuranRecitersHook.ts";
export type { GetQuranRecitersIdQueryKey } from "./useGetQuranRecitersIdHook.ts";
export type { GetQuranRecitersNameNameQueryKey } from "./useGetQuranRecitersNameNameHook.ts";
export type { PostQuranRecitersMutationKey } from "./usePostQuranRecitersHook.ts";
export type { PutQuranRecitersIdMutationKey } from "./usePutQuranRecitersIdHook.ts";
export { deleteQuranRecitersIdMutationKey, deleteQuranRecitersIdHook, deleteQuranRecitersIdMutationOptionsHook, useDeleteQuranRecitersIdHook } from "./useDeleteQuranRecitersIdHook.ts";
export { getQuranRecitersQueryKey, getQuranRecitersHook, getQuranRecitersQueryOptionsHook, useGetQuranRecitersHook } from "./useGetQuranRecitersHook.ts";
export { getQuranRecitersIdQueryKey, getQuranRecitersIdHook, getQuranRecitersIdQueryOptionsHook, useGetQuranRecitersIdHook } from "./useGetQuranRecitersIdHook.ts";
export { getQuranRecitersNameNameQueryKey, getQuranRecitersNameNameHook, getQuranRecitersNameNameQueryOptionsHook, useGetQuranRecitersNameNameHook } from "./useGetQuranRecitersNameNameHook.ts";
export { postQuranRecitersMutationKey, postQuranRecitersHook, postQuranRecitersMutationOptionsHook, usePostQuranRecitersHook } from "./usePostQuranRecitersHook.ts";
export { putQuranRecitersIdMutationKey, putQuranRecitersIdHook, putQuranRecitersIdMutationOptionsHook, usePutQuranRecitersIdHook } from "./usePutQuranRecitersIdHook.ts";