/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { DeleteQuranRecitersIdMutationResponse, DeleteQuranRecitersIdPathParams, DeleteQuranRecitersId400, DeleteQuranRecitersId500 } from "../../types/DeleteQuranRecitersId.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteQuranRecitersIdMutationKey = () => [{ url: '/quran/reciters/:id' }] as const

export type DeleteQuranRecitersIdMutationKey = ReturnType<typeof deleteQuranRecitersIdMutationKey>

/**
 * @description Delete a reciter by ID
 * @summary Delete a reciter
 * {@link /quran/reciters/:id}
 */
export async function deleteQuranRecitersIdHook(id: DeleteQuranRecitersIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteQuranRecitersIdMutationResponse, ResponseErrorConfig<DeleteQuranRecitersId400 | DeleteQuranRecitersId500>, unknown>({ method : "DELETE", url : `/quran/reciters/${id}`, ... requestConfig })  
  return res.data
}

export function deleteQuranRecitersIdMutationOptionsHook(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = deleteQuranRecitersIdMutationKey()
  return mutationOptions<DeleteQuranRecitersIdMutationResponse, ResponseErrorConfig<DeleteQuranRecitersId400 | DeleteQuranRecitersId500>, {id: DeleteQuranRecitersIdPathParams["id"]}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id }) => {
      return deleteQuranRecitersIdHook(id, config)
    },
  })
}

/**
 * @description Delete a reciter by ID
 * @summary Delete a reciter
 * {@link /quran/reciters/:id}
 */
export function useDeleteQuranRecitersIdHook<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteQuranRecitersIdMutationResponse, ResponseErrorConfig<DeleteQuranRecitersId400 | DeleteQuranRecitersId500>, {id: DeleteQuranRecitersIdPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteQuranRecitersIdMutationKey()

  const baseOptions = deleteQuranRecitersIdMutationOptionsHook(config) as UseMutationOptions<DeleteQuranRecitersIdMutationResponse, ResponseErrorConfig<DeleteQuranRecitersId400 | DeleteQuranRecitersId500>, {id: DeleteQuranRecitersIdPathParams["id"]}, TContext>

  return useMutation<DeleteQuranRecitersIdMutationResponse, ResponseErrorConfig<DeleteQuranRecitersId400 | DeleteQuranRecitersId500>, {id: DeleteQuranRecitersIdPathParams["id"]}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<DeleteQuranRecitersIdMutationResponse, ResponseErrorConfig<DeleteQuranRecitersId400 | DeleteQuranRecitersId500>, {id: DeleteQuranRecitersIdPathParams["id"]}, TContext>
}