/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetQuranRecitersIdQueryResponse, GetQuranRecitersIdPathParams, GetQuranRecitersId400, GetQuranRecitersId500 } from "../../types/GetQuranRecitersId.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getQuranRecitersIdQueryKey = (id: GetQuranRecitersIdPathParams["id"]) => [{ url: '/quran/reciters/:id', params: {id:id} }] as const

export type GetQuranRecitersIdQueryKey = ReturnType<typeof getQuranRecitersIdQueryKey>

/**
 * @description Get a reciter by ID
 * @summary Get reciter by ID
 * {@link /quran/reciters/:id}
 */
export async function getQuranRecitersIdHook(id: GetQuranRecitersIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetQuranRecitersIdQueryResponse, ResponseErrorConfig<GetQuranRecitersId400 | GetQuranRecitersId500>, unknown>({ method : "GET", url : `/quran/reciters/${id}`, ... requestConfig })  
  return res.data
}

export function getQuranRecitersIdQueryOptionsHook(id: GetQuranRecitersIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getQuranRecitersIdQueryKey(id)
  return queryOptions<GetQuranRecitersIdQueryResponse, ResponseErrorConfig<GetQuranRecitersId400 | GetQuranRecitersId500>, GetQuranRecitersIdQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getQuranRecitersIdHook(id, config)
   },
  })
}

/**
 * @description Get a reciter by ID
 * @summary Get reciter by ID
 * {@link /quran/reciters/:id}
 */
export function useGetQuranRecitersIdHook<TData = GetQuranRecitersIdQueryResponse, TQueryData = GetQuranRecitersIdQueryResponse, TQueryKey extends QueryKey = GetQuranRecitersIdQueryKey>(id: GetQuranRecitersIdPathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<GetQuranRecitersIdQueryResponse, ResponseErrorConfig<GetQuranRecitersId400 | GetQuranRecitersId500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getQuranRecitersIdQueryKey(id)

  const query = useQuery({
   ...getQuranRecitersIdQueryOptionsHook(id, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetQuranRecitersId400 | GetQuranRecitersId500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}