/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetQuranRecitersNameQueryResponse, GetQuranRecitersNamePathParams, GetQuranRecitersName400, GetQuranRecitersName500 } from "../../types/GetQuranRecitersNameName.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getQuranRecitersNameNameQueryKey = (name: GetQuranRecitersNamePathParams["name"]) => [{ url: '/quran/reciters/name/:name', params: {name:name} }] as const

export type GetQuranRecitersNameNameQueryKey = ReturnType<typeof getQuranRecitersNameNameQueryKey>

/**
 * @description Get a reciter by name
 * @summary Get reciter by name
 * {@link /quran/reciters/name/:name}
 */
export async function getQuranRecitersNameNameHook(name: GetQuranRecitersNamePathParams["name"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetQuranRecitersNameQueryResponse, ResponseErrorConfig<GetQuranRecitersName400 | GetQuranRecitersName500>, unknown>({ method : "GET", url : `/quran/reciters/name/${name}`, ... requestConfig })  
  return res.data
}

export function getQuranRecitersNameNameQueryOptionsHook(name: GetQuranRecitersNamePathParams["name"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getQuranRecitersNameNameQueryKey(name)
  return queryOptions<GetQuranRecitersNameQueryResponse, ResponseErrorConfig<GetQuranRecitersName400 | GetQuranRecitersName500>, GetQuranRecitersNameQueryResponse, typeof queryKey>({
   enabled: !!(name),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getQuranRecitersNameNameHook(name, config)
   },
  })
}

/**
 * @description Get a reciter by name
 * @summary Get reciter by name
 * {@link /quran/reciters/name/:name}
 */
export function useGetQuranRecitersNameNameHook<TData = GetQuranRecitersNameQueryResponse, TQueryData = GetQuranRecitersNameQueryResponse, TQueryKey extends QueryKey = GetQuranRecitersNameNameQueryKey>(name: GetQuranRecitersNamePathParams["name"], options: 
{
  query?: Partial<QueryObserverOptions<GetQuranRecitersNameQueryResponse, ResponseErrorConfig<GetQuranRecitersName400 | GetQuranRecitersName500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getQuranRecitersNameNameQueryKey(name)

  const query = useQuery({
   ...getQuranRecitersNameNameQueryOptionsHook(name, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetQuranRecitersName400 | GetQuranRecitersName500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}