/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetQuranRecitersQueryResponse, GetQuranRecitersQueryParams, GetQuranReciters400, GetQuranReciters500 } from "../../types/GetQuranReciters.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getQuranRecitersQueryKey = (params?: GetQuranRecitersQueryParams) => [{ url: '/quran/reciters' }, ...(params ? [params] : [])] as const

export type GetQuranRecitersQueryKey = ReturnType<typeof getQuranRecitersQueryKey>

/**
 * @description Get all reciters with pagination
 * @summary Get all reciters
 * {@link /quran/reciters}
 */
export async function getQuranRecitersHook(params?: GetQuranRecitersQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetQuranRecitersQueryResponse, ResponseErrorConfig<GetQuranReciters400 | GetQuranReciters500>, unknown>({ method : "GET", url : `/quran/reciters`, params, ... requestConfig })  
  return res.data
}

export function getQuranRecitersQueryOptionsHook(params?: GetQuranRecitersQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getQuranRecitersQueryKey(params)
  return queryOptions<GetQuranRecitersQueryResponse, ResponseErrorConfig<GetQuranReciters400 | GetQuranReciters500>, GetQuranRecitersQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getQuranRecitersHook(params, config)
   },
  })
}

/**
 * @description Get all reciters with pagination
 * @summary Get all reciters
 * {@link /quran/reciters}
 */
export function useGetQuranRecitersHook<TData = GetQuranRecitersQueryResponse, TQueryData = GetQuranRecitersQueryResponse, TQueryKey extends QueryKey = GetQuranRecitersQueryKey>(params?: GetQuranRecitersQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetQuranRecitersQueryResponse, ResponseErrorConfig<GetQuranReciters400 | GetQuranReciters500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getQuranRecitersQueryKey(params)

  const query = useQuery({
   ...getQuranRecitersQueryOptionsHook(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetQuranReciters400 | GetQuranReciters500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}