/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { PostQuranRecitersMutationRequest, PostQuranRecitersMutationResponse, PostQuranReciters400, PostQuranReciters500 } from "../../types/PostQuranReciters.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postQuranRecitersMutationKey = () => [{ url: '/quran/reciters' }] as const

export type PostQuranRecitersMutationKey = ReturnType<typeof postQuranRecitersMutationKey>

/**
 * @description Create a new reciter
 * @summary Create a new reciter
 * {@link /quran/reciters}
 */
export async function postQuranRecitersHook(data: PostQuranRecitersMutationRequest, config: Partial<RequestConfig<PostQuranRecitersMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostQuranRecitersMutationResponse, ResponseErrorConfig<PostQuranReciters400 | PostQuranReciters500>, PostQuranRecitersMutationRequest>({ method : "POST", url : `/quran/reciters`, data : requestData, ... requestConfig })  
  return res.data
}

export function postQuranRecitersMutationOptionsHook(config: Partial<RequestConfig<PostQuranRecitersMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = postQuranRecitersMutationKey()
  return mutationOptions<PostQuranRecitersMutationResponse, ResponseErrorConfig<PostQuranReciters400 | PostQuranReciters500>, {data: PostQuranRecitersMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return postQuranRecitersHook(data, config)
    },
  })
}

/**
 * @description Create a new reciter
 * @summary Create a new reciter
 * {@link /quran/reciters}
 */
export function usePostQuranRecitersHook<TContext>(options: 
{
  mutation?: UseMutationOptions<PostQuranRecitersMutationResponse, ResponseErrorConfig<PostQuranReciters400 | PostQuranReciters500>, {data: PostQuranRecitersMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostQuranRecitersMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postQuranRecitersMutationKey()

  const baseOptions = postQuranRecitersMutationOptionsHook(config) as UseMutationOptions<PostQuranRecitersMutationResponse, ResponseErrorConfig<PostQuranReciters400 | PostQuranReciters500>, {data: PostQuranRecitersMutationRequest}, TContext>

  return useMutation<PostQuranRecitersMutationResponse, ResponseErrorConfig<PostQuranReciters400 | PostQuranReciters500>, {data: PostQuranRecitersMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<PostQuranRecitersMutationResponse, ResponseErrorConfig<PostQuranReciters400 | PostQuranReciters500>, {data: PostQuranRecitersMutationRequest}, TContext>
}