/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { PutQuranRecitersIdMutationRequest, PutQuranRecitersIdMutationResponse, PutQuranRecitersIdPathParams, PutQuranRecitersId400, PutQuranRecitersId500 } from "../../types/PutQuranRecitersId.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const putQuranRecitersIdMutationKey = () => [{ url: '/quran/reciters/:id' }] as const

export type PutQuranRecitersIdMutationKey = ReturnType<typeof putQuranRecitersIdMutationKey>

/**
 * @description Update an existing reciter
 * @summary Update a reciter
 * {@link /quran/reciters/:id}
 */
export async function putQuranRecitersIdHook(id: PutQuranRecitersIdPathParams["id"], data: PutQuranRecitersIdMutationRequest, config: Partial<RequestConfig<PutQuranRecitersIdMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PutQuranRecitersIdMutationResponse, ResponseErrorConfig<PutQuranRecitersId400 | PutQuranRecitersId500>, PutQuranRecitersIdMutationRequest>({ method : "PUT", url : `/quran/reciters/${id}`, data : requestData, ... requestConfig })  
  return res.data
}

export function putQuranRecitersIdMutationOptionsHook(config: Partial<RequestConfig<PutQuranRecitersIdMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = putQuranRecitersIdMutationKey()
  return mutationOptions<PutQuranRecitersIdMutationResponse, ResponseErrorConfig<PutQuranRecitersId400 | PutQuranRecitersId500>, {id: PutQuranRecitersIdPathParams["id"], data: PutQuranRecitersIdMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id, data }) => {
      return putQuranRecitersIdHook(id, data, config)
    },
  })
}

/**
 * @description Update an existing reciter
 * @summary Update a reciter
 * {@link /quran/reciters/:id}
 */
export function usePutQuranRecitersIdHook<TContext>(options: 
{
  mutation?: UseMutationOptions<PutQuranRecitersIdMutationResponse, ResponseErrorConfig<PutQuranRecitersId400 | PutQuranRecitersId500>, {id: PutQuranRecitersIdPathParams["id"], data: PutQuranRecitersIdMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PutQuranRecitersIdMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? putQuranRecitersIdMutationKey()

  const baseOptions = putQuranRecitersIdMutationOptionsHook(config) as UseMutationOptions<PutQuranRecitersIdMutationResponse, ResponseErrorConfig<PutQuranRecitersId400 | PutQuranRecitersId500>, {id: PutQuranRecitersIdPathParams["id"], data: PutQuranRecitersIdMutationRequest}, TContext>

  return useMutation<PutQuranRecitersIdMutationResponse, ResponseErrorConfig<PutQuranRecitersId400 | PutQuranRecitersId500>, {id: PutQuranRecitersIdPathParams["id"], data: PutQuranRecitersIdMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<PutQuranRecitersIdMutationResponse, ResponseErrorConfig<PutQuranRecitersId400 | PutQuranRecitersId500>, {id: PutQuranRecitersIdPathParams["id"], data: PutQuranRecitersIdMutationRequest}, TContext>
}