/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PrayertimesPrayerTimesSuccessResponse } from "../../types/prayertimes/PrayerTimesSuccessResponse.ts";
import { dtoPrayerTimesResponseSchema } from "../dto/prayerTimesResponseSchema.ts";
import { z } from "zod";

export const prayertimesPrayerTimesSuccessResponseSchema = z.object({
    get "data"(){
                return dtoPrayerTimesResponseSchema.optional()
              },
"message": z.optional(z.string()),
"responseTime": z.optional(z.string()),
"status_code": z.optional(z.int()),
"success": z.optional(z.boolean()),
"timestamp": z.optional(z.string())
    }) as unknown as z.ZodType<PrayertimesPrayerTimesSuccessResponse>