/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PrayertimesPrayerTimesListSuccessResponse } from "../../types/prayertimes/PrayerTimesListSuccessResponse.ts";
import { dtoPrayerTimesListResponseSchema } from "../dto/prayerTimesListResponseSchema.ts";
import { z } from "zod";

export const prayertimesPrayerTimesListSuccessResponseSchema = z.object({
    get "data"(){
                return dtoPrayerTimesListResponseSchema.optional()
              },
"message": z.optional(z.string()),
"responseTime": z.optional(z.string()),
"status_code": z.optional(z.int()),
"success": z.optional(z.boolean()),
"timestamp": z.optional(z.string())
    }) as unknown as z.ZodType<PrayertimesPrayerTimesListSuccessResponse>