/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranDeleteLastReadSuccessResponse } from "./quran/DeleteLastReadSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type DeleteQuranLastReadsIdPathParams = {
    /**
     * @description LastRead ID
     * @type string
    */
    id: string;
};

/**
 * @description Last read deleted successfully
*/
export type DeleteQuranLastReadsId200 = QuranDeleteLastReadSuccessResponse;

/**
 * @description Bad request
*/
export type DeleteQuranLastReadsId400 = QuranQuranErrorResponse;

/**
 * @description Last read not found
*/
export type DeleteQuranLastReadsId404 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type DeleteQuranLastReadsId500 = QuranQuranErrorResponse;

export type DeleteQuranLastReadsIdMutationResponse = DeleteQuranLastReadsId200;

export type DeleteQuranLastReadsIdMutation = {
    Response: DeleteQuranLastReadsId200;
    PathParams: DeleteQuranLastReadsIdPathParams;
    Errors: DeleteQuranLastReadsId400 | DeleteQuranLastReadsId404 | DeleteQuranLastReadsId500;
};