/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranDeleteSurahSuccessResponse } from "./quran/DeleteSurahSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type DeleteQuranSurahsIdPathParams = {
    /**
     * @description Surah ID
     * @type string
    */
    id: string;
};

/**
 * @description Surah deleted successfully
*/
export type DeleteQuranSurahsId200 = QuranDeleteSurahSuccessResponse;

/**
 * @description Bad request
*/
export type DeleteQuranSurahsId400 = QuranQuranErrorResponse;

/**
 * @description Surah not found
*/
export type DeleteQuranSurahsId404 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type DeleteQuranSurahsId500 = QuranQuranErrorResponse;

export type DeleteQuranSurahsIdMutationResponse = DeleteQuranSurahsId200;

export type DeleteQuranSurahsIdMutation = {
    Response: DeleteQuranSurahsId200;
    PathParams: DeleteQuranSurahsIdPathParams;
    Errors: DeleteQuranSurahsId400 | DeleteQuranSurahsId404 | DeleteQuranSurahsId500;
};