/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranDeleteBookmarkAyahSuccessResponse } from "./quran/DeleteBookmarkAyahSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type DeleteQuranBookmarksAyahsIdPathParams = {
    /**
     * @description Bookmark ID
     * @type string
    */
    id: string;
};

/**
 * @description Bookmark deleted successfully
*/
export type DeleteQuranBookmarksAyahsId200 = QuranDeleteBookmarkAyahSuccessResponse;

/**
 * @description Bad request
*/
export type DeleteQuranBookmarksAyahsId400 = QuranQuranErrorResponse;

/**
 * @description Bookmark not found
*/
export type DeleteQuranBookmarksAyahsId404 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type DeleteQuranBookmarksAyahsId500 = QuranQuranErrorResponse;

export type DeleteQuranBookmarksAyahsIdMutationResponse = DeleteQuranBookmarksAyahsId200;

export type DeleteQuranBookmarksAyahsIdMutation = {
    Response: DeleteQuranBookmarksAyahsId200;
    PathParams: DeleteQuranBookmarksAyahsIdPathParams;
    Errors: DeleteQuranBookmarksAyahsId400 | DeleteQuranBookmarksAyahsId404 | DeleteQuranBookmarksAyahsId500;
};