/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranJuzSuccessResponse } from "./quran/JuzSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type DeleteQuranJuzIdPathParams = {
    /**
     * @description Juz ID
     * @type string
    */
    id: string;
};

/**
 * @description Juz deleted successfully
*/
export type DeleteQuranJuzId200 = QuranJuzSuccessResponse;

/**
 * @description Bad request
*/
export type DeleteQuranJuzId400 = QuranQuranErrorResponse;

/**
 * @description Juz not found
*/
export type DeleteQuranJuzId404 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type DeleteQuranJuzId500 = QuranQuranErrorResponse;

export type DeleteQuranJuzIdMutationResponse = DeleteQuranJuzId200;

export type DeleteQuranJuzIdMutation = {
    Response: DeleteQuranJuzId200;
    PathParams: DeleteQuranJuzIdPathParams;
    Errors: DeleteQuranJuzId400 | DeleteQuranJuzId404 | DeleteQuranJuzId500;
};