/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranDeleteReciterSuccessResponse } from "./quran/DeleteReciterSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type DeleteQuranRecitersIdPathParams = {
    /**
     * @description Reciter ID
     * @type string
    */
    id: string;
};

/**
 * @description Reciter deleted successfully
*/
export type DeleteQuranRecitersId200 = QuranDeleteReciterSuccessResponse;

/**
 * @description Bad request
*/
export type DeleteQuranRecitersId400 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type DeleteQuranRecitersId500 = QuranQuranErrorResponse;

export type DeleteQuranRecitersIdMutationResponse = DeleteQuranRecitersId200;

export type DeleteQuranRecitersIdMutation = {
    Response: DeleteQuranRecitersId200;
    PathParams: DeleteQuranRecitersIdPathParams;
    Errors: DeleteQuranRecitersId400 | DeleteQuranRecitersId500;
};