/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranDeleteProgressHatamSuccessResponse } from "./quran/DeleteProgressHatamSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type DeleteQuranProgressHatamIdPathParams = {
    /**
     * @description ProgressHatam ID
     * @type string
    */
    id: string;
};

/**
 * @description Progress hatam deleted successfully
*/
export type DeleteQuranProgressHatamId200 = QuranDeleteProgressHatamSuccessResponse;

/**
 * @description Bad request
*/
export type DeleteQuranProgressHatamId400 = QuranQuranErrorResponse;

/**
 * @description Progress hatam not found
*/
export type DeleteQuranProgressHatamId404 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type DeleteQuranProgressHatamId500 = QuranQuranErrorResponse;

export type DeleteQuranProgressHatamIdMutationResponse = DeleteQuranProgressHatamId200;

export type DeleteQuranProgressHatamIdMutation = {
    Response: DeleteQuranProgressHatamId200;
    PathParams: DeleteQuranProgressHatamIdPathParams;
    Errors: DeleteQuranProgressHatamId400 | DeleteQuranProgressHatamId404 | DeleteQuranProgressHatamId500;
};