/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranDeleteAyahSuccessResponse } from "./quran/DeleteAyahSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type DeleteQuranAyahsIdPathParams = {
    /**
     * @description Ayah ID
     * @type string
    */
    id: string;
};

/**
 * @description Ayah deleted successfully
*/
export type DeleteQuranAyahsId200 = QuranDeleteAyahSuccessResponse;

/**
 * @description Bad request
*/
export type DeleteQuranAyahsId400 = QuranQuranErrorResponse;

/**
 * @description Ayah not found
*/
export type DeleteQuranAyahsId404 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type DeleteQuranAyahsId500 = QuranQuranErrorResponse;

export type DeleteQuranAyahsIdMutationResponse = DeleteQuranAyahsId200;

export type DeleteQuranAyahsIdMutation = {
    Response: DeleteQuranAyahsId200;
    PathParams: DeleteQuranAyahsIdPathParams;
    Errors: DeleteQuranAyahsId400 | DeleteQuranAyahsId404 | DeleteQuranAyahsId500;
};