/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranDeleteAyahAudioFileSuccessResponse } from "./quran/DeleteAyahAudioFileSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type DeleteQuranAudioAyahsIdPathParams = {
    /**
     * @description Ayah audio file ID
     * @type string
    */
    id: string;
};

/**
 * @description Ayah audio file deleted successfully
*/
export type DeleteQuranAudioAyahsId200 = QuranDeleteAyahAudioFileSuccessResponse;

/**
 * @description Bad request
*/
export type DeleteQuranAudioAyahsId400 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type DeleteQuranAudioAyahsId500 = QuranQuranErrorResponse;

export type DeleteQuranAudioAyahsIdMutationResponse = DeleteQuranAudioAyahsId200;

export type DeleteQuranAudioAyahsIdMutation = {
    Response: DeleteQuranAudioAyahsId200;
    PathParams: DeleteQuranAudioAyahsIdPathParams;
    Errors: DeleteQuranAudioAyahsId400 | DeleteQuranAudioAyahsId500;
};