/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PrayertimesPrayerTimesErrorResponse } from "./prayertimes/PrayerTimesErrorResponse.ts";
import type { PrayertimesPrayerTimesListSuccessResponse } from "./prayertimes/PrayerTimesListSuccessResponse.ts";

export type GetPrayertimesMonthlyQueryParams = {
    /**
     * @description Latitude
     * @type number
    */
    latitude: number;
    /**
     * @description Longitude
     * @type number
    */
    longitude: number;
    /**
     * @description Timezone (IANA)
     * @type string
    */
    timezone: string;
    /**
     * @description Month (1-12)
     * @type integer
    */
    month: number;
    /**
     * @description Year
     * @type integer
    */
    year: number;
    /**
     * @description Calculation method (provider-specific)
     * @type integer | undefined
    */
    method?: number;
};

/**
 * @description Prayer times list retrieved successfully
*/
export type GetPrayertimesMonthly200 = PrayertimesPrayerTimesListSuccessResponse;

/**
 * @description Bad request
*/
export type GetPrayertimesMonthly400 = PrayertimesPrayerTimesErrorResponse;

/**
 * @description Internal server error
*/
export type GetPrayertimesMonthly500 = PrayertimesPrayerTimesErrorResponse;

export type GetPrayertimesMonthlyQueryResponse = GetPrayertimesMonthly200;

export type GetPrayertimesMonthlyQuery = {
    Response: GetPrayertimesMonthly200;
    QueryParams: GetPrayertimesMonthlyQueryParams;
    Errors: GetPrayertimesMonthly400 | GetPrayertimesMonthly500;
};