/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PrayertimesPrayerTimesErrorResponse } from "./prayertimes/PrayerTimesErrorResponse.ts";
import type { PrayertimesPrayerTimesSuccessResponse } from "./prayertimes/PrayerTimesSuccessResponse.ts";

export type GetPrayertimesDailyQueryParams = {
    /**
     * @description Latitude
     * @type number
    */
    latitude: number;
    /**
     * @description Longitude
     * @type number
    */
    longitude: number;
    /**
     * @description Timezone (IANA)
     * @type string
    */
    timezone: string;
    /**
     * @description Date (YYYY-MM-DD)
     * @type string | undefined
    */
    date?: string;
    /**
     * @description Calculation method (provider-specific)
     * @type integer | undefined
    */
    method?: number;
};

/**
 * @description Prayer times retrieved successfully
*/
export type GetPrayertimesDaily200 = PrayertimesPrayerTimesSuccessResponse;

/**
 * @description Bad request
*/
export type GetPrayertimesDaily400 = PrayertimesPrayerTimesErrorResponse;

/**
 * @description Internal server error
*/
export type GetPrayertimesDaily500 = PrayertimesPrayerTimesErrorResponse;

export type GetPrayertimesDailyQueryResponse = GetPrayertimesDaily200;

export type GetPrayertimesDailyQuery = {
    Response: GetPrayertimesDaily200;
    QueryParams: GetPrayertimesDailyQueryParams;
    Errors: GetPrayertimesDaily400 | GetPrayertimesDaily500;
};