/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PrayertimesPrayerTimesErrorResponse } from "./prayertimes/PrayerTimesErrorResponse.ts";
import type { PrayertimesPrayerTimesListSuccessResponse } from "./prayertimes/PrayerTimesListSuccessResponse.ts";

export type GetPrayertimesYearlyQueryParams = {
    /**
     * @description Latitude
     * @type number
    */
    latitude: number;
    /**
     * @description Longitude
     * @type number
    */
    longitude: number;
    /**
     * @description Timezone (IANA)
     * @type string
    */
    timezone: string;
    /**
     * @description Year
     * @type integer
    */
    year: number;
    /**
     * @description Calculation method (provider-specific)
     * @type integer | undefined
    */
    method?: number;
};

/**
 * @description Prayer times list retrieved successfully
*/
export type GetPrayertimesYearly200 = PrayertimesPrayerTimesListSuccessResponse;

/**
 * @description Bad request
*/
export type GetPrayertimesYearly400 = PrayertimesPrayerTimesErrorResponse;

/**
 * @description Internal server error
*/
export type GetPrayertimesYearly500 = PrayertimesPrayerTimesErrorResponse;

export type GetPrayertimesYearlyQueryResponse = GetPrayertimesYearly200;

export type GetPrayertimesYearlyQuery = {
    Response: GetPrayertimesYearly200;
    QueryParams: GetPrayertimesYearlyQueryParams;
    Errors: GetPrayertimesYearly400 | GetPrayertimesYearly500;
};