/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";
import type { QuranReciterSuccessResponse } from "./quran/ReciterSuccessResponse.ts";

export type GetQuranRecitersIdPathParams = {
    /**
     * @description Reciter ID
     * @type string
    */
    id: string;
};

/**
 * @description Reciter retrieved successfully
*/
export type GetQuranRecitersId200 = QuranReciterSuccessResponse;

/**
 * @description Bad request
*/
export type GetQuranRecitersId400 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type GetQuranRecitersId500 = QuranQuranErrorResponse;

export type GetQuranRecitersIdQueryResponse = GetQuranRecitersId200;

export type GetQuranRecitersIdQuery = {
    Response: GetQuranRecitersId200;
    PathParams: GetQuranRecitersIdPathParams;
    Errors: GetQuranRecitersId400 | GetQuranRecitersId500;
};