/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranJuzWithProgressListSuccessResponse } from "./quran/JuzWithProgressListSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export const getQuranJuzWithProgressQueryParamsIncludeEnum = {
    "relations": "relations"
} as const;

export type GetQuranJuzWithProgressQueryParamsIncludeEnumKey = (typeof getQuranJuzWithProgressQueryParamsIncludeEnum)[keyof typeof getQuranJuzWithProgressQueryParamsIncludeEnum];

export type GetQuranJuzWithProgressQueryParams = {
    /**
     * @description Limit
     * @type integer | undefined
    */
    limit?: number;
    /**
     * @description Offset
     * @type integer | undefined
    */
    offset?: number;
    /**
     * @description Include related data
     * @type string | undefined
    */
    include?: GetQuranJuzWithProgressQueryParamsIncludeEnumKey;
};

/**
 * @description OK
*/
export type GetQuranJuzWithProgress200 = QuranJuzWithProgressListSuccessResponse;

/**
 * @description Bad request
*/
export type GetQuranJuzWithProgress400 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type GetQuranJuzWithProgress500 = QuranQuranErrorResponse;

export type GetQuranJuzWithProgressQueryResponse = GetQuranJuzWithProgress200;

export type GetQuranJuzWithProgressQuery = {
    Response: GetQuranJuzWithProgress200;
    QueryParams: GetQuranJuzWithProgressQueryParams;
    Errors: GetQuranJuzWithProgress400 | GetQuranJuzWithProgress500;
};