/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranBookmarkAyahSuccessResponse } from "./quran/BookmarkAyahSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type GetQuranBookmarksAyahsIdPathParams = {
    /**
     * @description Bookmark ID
     * @type string
    */
    id: string;
};

export const getQuranBookmarksAyahsIdQueryParamsIncludeEnum = {
    "ayah": "ayah"
} as const;

export type GetQuranBookmarksAyahsIdQueryParamsIncludeEnumKey = (typeof getQuranBookmarksAyahsIdQueryParamsIncludeEnum)[keyof typeof getQuranBookmarksAyahsIdQueryParamsIncludeEnum];

export type GetQuranBookmarksAyahsIdQueryParams = {
    /**
     * @description Include related data
     * @type string | undefined
    */
    include?: GetQuranBookmarksAyahsIdQueryParamsIncludeEnumKey;
};

/**
 * @description Bookmark retrieved successfully
*/
export type GetQuranBookmarksAyahsId200 = QuranBookmarkAyahSuccessResponse;

/**
 * @description Bad request
*/
export type GetQuranBookmarksAyahsId400 = QuranQuranErrorResponse;

/**
 * @description Bookmark not found
*/
export type GetQuranBookmarksAyahsId404 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type GetQuranBookmarksAyahsId500 = QuranQuranErrorResponse;

export type GetQuranBookmarksAyahsIdQueryResponse = GetQuranBookmarksAyahsId200;

export type GetQuranBookmarksAyahsIdQuery = {
    Response: GetQuranBookmarksAyahsId200;
    PathParams: GetQuranBookmarksAyahsIdPathParams;
    QueryParams: GetQuranBookmarksAyahsIdQueryParams;
    Errors: GetQuranBookmarksAyahsId400 | GetQuranBookmarksAyahsId404 | GetQuranBookmarksAyahsId500;
};