/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranGetAyahByIdSuccessResponse } from "./quran/GetAyahByIdSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type GetQuranAyahsIdPathParams = {
    /**
     * @description Ayah ID
     * @type string
    */
    id: string;
};

export const getQuranAyahsIdQueryParamsIncludeEnum = {
    "surah": "surah"
} as const;

export type GetQuranAyahsIdQueryParamsIncludeEnumKey = (typeof getQuranAyahsIdQueryParamsIncludeEnum)[keyof typeof getQuranAyahsIdQueryParamsIncludeEnum];

export type GetQuranAyahsIdQueryParams = {
    /**
     * @description Include related data
     * @type string | undefined
    */
    include?: GetQuranAyahsIdQueryParamsIncludeEnumKey;
};

/**
 * @description Ayah retrieved successfully
*/
export type GetQuranAyahsId200 = QuranGetAyahByIdSuccessResponse;

/**
 * @description Bad request
*/
export type GetQuranAyahsId400 = QuranQuranErrorResponse;

/**
 * @description Ayah not found
*/
export type GetQuranAyahsId404 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type GetQuranAyahsId500 = QuranQuranErrorResponse;

export type GetQuranAyahsIdQueryResponse = GetQuranAyahsId200;

export type GetQuranAyahsIdQuery = {
    Response: GetQuranAyahsId200;
    PathParams: GetQuranAyahsIdPathParams;
    QueryParams: GetQuranAyahsIdQueryParams;
    Errors: GetQuranAyahsId400 | GetQuranAyahsId404 | GetQuranAyahsId500;
};