/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranGetAyahsBySurahWithTranslationsSuccessResponse } from "./quran/GetAyahsBySurahWithTranslationsSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type GetQuranAyahsSurahSurahidPathParams = {
    /**
     * @description Surah ID
     * @type string
    */
    surahId: string;
};

export const getQuranAyahsSurahSurahidQueryParamsIncludeEnum = {
    "surah": "surah"
} as const;

export type GetQuranAyahsSurahSurahidQueryParamsIncludeEnumKey = (typeof getQuranAyahsSurahSurahidQueryParamsIncludeEnum)[keyof typeof getQuranAyahsSurahSurahidQueryParamsIncludeEnum];

export type GetQuranAyahsSurahSurahidQueryParams = {
    /**
     * @description Limit (0 for all)
     * @default 0
     * @type integer | undefined
    */
    limit?: number;
    /**
     * @description Offset
     * @default 0
     * @type integer | undefined
    */
    offset?: number;
    /**
     * @description Include related data
     * @type string | undefined
    */
    include?: GetQuranAyahsSurahSurahidQueryParamsIncludeEnumKey;
    /**
     * @description Translation edition ID to include per-ayah translation
     * @type string | undefined
    */
    editionId?: string;
    /**
     * @description Reciter ID to include per-ayah audio
     * @type string | undefined
    */
    reciterId?: string;
};

/**
 * @description Ayahs with translations retrieved successfully
*/
export type GetQuranAyahsSurahSurahid200 = QuranGetAyahsBySurahWithTranslationsSuccessResponse;

/**
 * @description Bad request
*/
export type GetQuranAyahsSurahSurahid400 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type GetQuranAyahsSurahSurahid500 = QuranQuranErrorResponse;

export type GetQuranAyahsSurahSurahidQueryResponse = GetQuranAyahsSurahSurahid200;

export type GetQuranAyahsSurahSurahidQuery = {
    Response: GetQuranAyahsSurahSurahid200;
    PathParams: GetQuranAyahsSurahSurahidPathParams;
    QueryParams: GetQuranAyahsSurahSurahidQueryParams;
    Errors: GetQuranAyahsSurahSurahid400 | GetQuranAyahsSurahSurahid500;
};