/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranJuzSuccessResponse } from "./quran/JuzSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type GetQuranJuzNumberPathParams = {
    /**
     * @description Juz Number
     * @type integer
    */
    number: number;
};

export const getQuranJuzNumberQueryParamsIncludeEnum = {
    "relations": "relations"
} as const;

export type GetQuranJuzNumberQueryParamsIncludeEnumKey = (typeof getQuranJuzNumberQueryParamsIncludeEnum)[keyof typeof getQuranJuzNumberQueryParamsIncludeEnum];

export type GetQuranJuzNumberQueryParams = {
    /**
     * @description Include related data
     * @type string | undefined
    */
    include?: GetQuranJuzNumberQueryParamsIncludeEnumKey;
};

/**
 * @description Juz retrieved successfully
*/
export type GetQuranJuzNumber200 = QuranJuzSuccessResponse;

/**
 * @description Bad request
*/
export type GetQuranJuzNumber400 = QuranQuranErrorResponse;

/**
 * @description Juz not found
*/
export type GetQuranJuzNumber404 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type GetQuranJuzNumber500 = QuranQuranErrorResponse;

export type GetQuranJuzNumberQueryResponse = GetQuranJuzNumber200;

export type GetQuranJuzNumberNumberQuery = {
    Response: GetQuranJuzNumber200;
    PathParams: GetQuranJuzNumberPathParams;
    QueryParams: GetQuranJuzNumberQueryParams;
    Errors: GetQuranJuzNumber400 | GetQuranJuzNumber404 | GetQuranJuzNumber500;
};