/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranGetAyahsByJuzSuccessResponse } from "./quran/GetAyahsByJuzSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type GetQuranJuzJuznumberAyahsPathParams = {
    /**
     * @description Juz Number
     * @type integer
    */
    juzNumber: number;
};

export type GetQuranJuzJuznumberAyahsQueryParams = {
    /**
     * @description Limit (0 for all)
     * @default 0
     * @type integer | undefined
    */
    limit?: number;
    /**
     * @description Offset
     * @default 0
     * @type integer | undefined
    */
    offset?: number;
};

/**
 * @description Ayahs retrieved successfully
*/
export type GetQuranJuzJuznumberAyahs200 = QuranGetAyahsByJuzSuccessResponse;

/**
 * @description Bad request
*/
export type GetQuranJuzJuznumberAyahs400 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type GetQuranJuzJuznumberAyahs500 = QuranQuranErrorResponse;

export type GetQuranJuzJuznumberAyahsQueryResponse = GetQuranJuzJuznumberAyahs200;

export type GetQuranJuzJuznumberAyahsQuery = {
    Response: GetQuranJuzJuznumberAyahs200;
    PathParams: GetQuranJuzJuznumberAyahsPathParams;
    QueryParams: GetQuranJuzJuznumberAyahsQueryParams;
    Errors: GetQuranJuzJuznumberAyahs400 | GetQuranJuzJuznumberAyahs500;
};