/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranAyahAudioFileSuccessResponse } from "./quran/AyahAudioFileSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type GetQuranAudioAyahsAyahAyahidReciterReciteridPathParams = {
    /**
     * @description Ayah ID
     * @type string
    */
    ayahId: string;
    /**
     * @description Reciter ID
     * @type string
    */
    reciterId: string;
};

/**
 * @description Ayah audio file retrieved successfully
*/
export type GetQuranAudioAyahsAyahAyahidReciterReciterid200 = QuranAyahAudioFileSuccessResponse;

/**
 * @description Bad request
*/
export type GetQuranAudioAyahsAyahAyahidReciterReciterid400 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type GetQuranAudioAyahsAyahAyahidReciterReciterid500 = QuranQuranErrorResponse;

export type GetQuranAudioAyahsAyahAyahidReciterReciteridQueryResponse = GetQuranAudioAyahsAyahAyahidReciterReciterid200;

export type GetQuranAudioAyahsAyahAyahidReciterReciteridQuery = {
    Response: GetQuranAudioAyahsAyahAyahidReciterReciterid200;
    PathParams: GetQuranAudioAyahsAyahAyahidReciterReciteridPathParams;
    Errors: GetQuranAudioAyahsAyahAyahidReciterReciterid400 | GetQuranAudioAyahsAyahAyahidReciterReciterid500;
};