/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranLastReadListSuccessResponse } from "./quran/LastReadListSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export const getQuranLastReadsQueryParamsIncludeEnum = {
    "relations": "relations"
} as const;

export type GetQuranLastReadsQueryParamsIncludeEnumKey = (typeof getQuranLastReadsQueryParamsIncludeEnum)[keyof typeof getQuranLastReadsQueryParamsIncludeEnum];

export type GetQuranLastReadsQueryParams = {
    /**
     * @description Limit
     * @type integer | undefined
    */
    limit?: number;
    /**
     * @description Offset
     * @type integer | undefined
    */
    offset?: number;
    /**
     * @description Include related data
     * @type string | undefined
    */
    include?: GetQuranLastReadsQueryParamsIncludeEnumKey;
};

/**
 * @description Last reads retrieved successfully
*/
export type GetQuranLastReads200 = QuranLastReadListSuccessResponse;

/**
 * @description Bad request
*/
export type GetQuranLastReads400 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type GetQuranLastReads500 = QuranQuranErrorResponse;

export type GetQuranLastReadsQueryResponse = GetQuranLastReads200;

export type GetQuranLastReadsQuery = {
    Response: GetQuranLastReads200;
    QueryParams: GetQuranLastReadsQueryParams;
    Errors: GetQuranLastReads400 | GetQuranLastReads500;
};