/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranGetSurahByNumberSuccessResponse } from "./quran/GetSurahByNumberSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type GetQuranSurahsNumberPathParams = {
    /**
     * @description Surah Number
     * @type integer
    */
    number: number;
};

export const getQuranSurahsNumberQueryParamsIncludeEnum = {
    "ayahs": "ayahs"
} as const;

export type GetQuranSurahsNumberQueryParamsIncludeEnumKey = (typeof getQuranSurahsNumberQueryParamsIncludeEnum)[keyof typeof getQuranSurahsNumberQueryParamsIncludeEnum];

export type GetQuranSurahsNumberQueryParams = {
    /**
     * @description Include related data
     * @type string | undefined
    */
    include?: GetQuranSurahsNumberQueryParamsIncludeEnumKey;
};

/**
 * @description Surah retrieved successfully
*/
export type GetQuranSurahsNumber200 = QuranGetSurahByNumberSuccessResponse;

/**
 * @description Bad request
*/
export type GetQuranSurahsNumber400 = QuranQuranErrorResponse;

/**
 * @description Surah not found
*/
export type GetQuranSurahsNumber404 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type GetQuranSurahsNumber500 = QuranQuranErrorResponse;

export type GetQuranSurahsNumberQueryResponse = GetQuranSurahsNumber200;

export type GetQuranSurahsNumberNumberQuery = {
    Response: GetQuranSurahsNumber200;
    PathParams: GetQuranSurahsNumberPathParams;
    QueryParams: GetQuranSurahsNumberQueryParams;
    Errors: GetQuranSurahsNumber400 | GetQuranSurahsNumber404 | GetQuranSurahsNumber500;
};