/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranGetTranslationEditionListSuccessResponse } from "./quran/GetTranslationEditionListSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type GetQuranTranslationsEditionsQueryParams = {
    /**
     * @description Language code (e.g., en, id)
     * @type string | undefined
    */
    language?: string;
    /**
     * @description Limit (0 for all)
     * @default 0
     * @type integer | undefined
    */
    limit?: number;
    /**
     * @description Offset
     * @default 0
     * @type integer | undefined
    */
    offset?: number;
};

/**
 * @description Translation editions retrieved successfully
*/
export type GetQuranTranslationsEditions200 = QuranGetTranslationEditionListSuccessResponse;

/**
 * @description Bad request
*/
export type GetQuranTranslationsEditions400 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type GetQuranTranslationsEditions500 = QuranQuranErrorResponse;

export type GetQuranTranslationsEditionsQueryResponse = GetQuranTranslationsEditions200;

export type GetQuranTranslationsEditionsQuery = {
    Response: GetQuranTranslationsEditions200;
    QueryParams: GetQuranTranslationsEditionsQueryParams;
    Errors: GetQuranTranslationsEditions400 | GetQuranTranslationsEditions500;
};