/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranJuzSuccessResponse } from "./quran/JuzSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type GetQuranJuzIdPathParams = {
    /**
     * @description Juz ID
     * @type string
    */
    id: string;
};

export const getQuranJuzIdQueryParamsIncludeEnum = {
    "relations": "relations"
} as const;

export type GetQuranJuzIdQueryParamsIncludeEnumKey = (typeof getQuranJuzIdQueryParamsIncludeEnum)[keyof typeof getQuranJuzIdQueryParamsIncludeEnum];

export type GetQuranJuzIdQueryParams = {
    /**
     * @description Include related data
     * @type string | undefined
    */
    include?: GetQuranJuzIdQueryParamsIncludeEnumKey;
};

/**
 * @description Juz retrieved successfully
*/
export type GetQuranJuzId200 = QuranJuzSuccessResponse;

/**
 * @description Bad request
*/
export type GetQuranJuzId400 = QuranQuranErrorResponse;

/**
 * @description Juz not found
*/
export type GetQuranJuzId404 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type GetQuranJuzId500 = QuranQuranErrorResponse;

export type GetQuranJuzIdQueryResponse = GetQuranJuzId200;

export type GetQuranJuzIdQuery = {
    Response: GetQuranJuzId200;
    PathParams: GetQuranJuzIdPathParams;
    QueryParams: GetQuranJuzIdQueryParams;
    Errors: GetQuranJuzId400 | GetQuranJuzId404 | GetQuranJuzId500;
};