/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranGetAyahTranslationListSuccessResponse } from "./quran/GetAyahTranslationListSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type GetQuranTranslationsAyahsSurahSurahidEditionEditionidPathParams = {
    /**
     * @description Surah ID
     * @type string
    */
    surahId: string;
    /**
     * @description Translation Edition ID
     * @type string
    */
    editionId: string;
};

export type GetQuranTranslationsAyahsSurahSurahidEditionEditionidQueryParams = {
    /**
     * @description Limit (0 for all)
     * @default 0
     * @type integer | undefined
    */
    limit?: number;
    /**
     * @description Offset
     * @default 0
     * @type integer | undefined
    */
    offset?: number;
};

/**
 * @description Ayah translations retrieved successfully
*/
export type GetQuranTranslationsAyahsSurahSurahidEditionEditionid200 = QuranGetAyahTranslationListSuccessResponse;

/**
 * @description Bad request
*/
export type GetQuranTranslationsAyahsSurahSurahidEditionEditionid400 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type GetQuranTranslationsAyahsSurahSurahidEditionEditionid500 = QuranQuranErrorResponse;

export type GetQuranTranslationsAyahsSurahSurahidEditionEditionidQueryResponse = GetQuranTranslationsAyahsSurahSurahidEditionEditionid200;

export type GetQuranTranslationsAyahsSurahSurahidEditionEditionidQuery = {
    Response: GetQuranTranslationsAyahsSurahSurahidEditionEditionid200;
    PathParams: GetQuranTranslationsAyahsSurahSurahidEditionEditionidPathParams;
    QueryParams: GetQuranTranslationsAyahsSurahSurahidEditionEditionidQueryParams;
    Errors: GetQuranTranslationsAyahsSurahSurahidEditionEditionid400 | GetQuranTranslationsAyahsSurahSurahidEditionEditionid500;
};