/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranAyahAudioFileSuccessResponse } from "./quran/AyahAudioFileSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type GetQuranAudioAyahsIdPathParams = {
    /**
     * @description Ayah audio file ID
     * @type string
    */
    id: string;
};

/**
 * @description Ayah audio file retrieved successfully
*/
export type GetQuranAudioAyahsId200 = QuranAyahAudioFileSuccessResponse;

/**
 * @description Bad request
*/
export type GetQuranAudioAyahsId400 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type GetQuranAudioAyahsId500 = QuranQuranErrorResponse;

export type GetQuranAudioAyahsIdQueryResponse = GetQuranAudioAyahsId200;

export type GetQuranAudioAyahsIdQuery = {
    Response: GetQuranAudioAyahsId200;
    PathParams: GetQuranAudioAyahsIdPathParams;
    Errors: GetQuranAudioAyahsId400 | GetQuranAudioAyahsId500;
};