/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranAyahAudioFileListSuccessResponse } from "./quran/AyahAudioFileListSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type GetQuranAudioAyahsSurahSurahidReciterReciteridPathParams = {
    /**
     * @description Surah ID
     * @type string
    */
    surahId: string;
    /**
     * @description Reciter ID
     * @type string
    */
    reciterId: string;
};

export type GetQuranAudioAyahsSurahSurahidReciterReciteridQueryParams = {
    /**
     * @description Limit (0 for all)
     * @default 0
     * @type integer | undefined
    */
    limit?: number;
    /**
     * @description Offset
     * @default 0
     * @type integer | undefined
    */
    offset?: number;
};

/**
 * @description Ayah audio files retrieved successfully
*/
export type GetQuranAudioAyahsSurahSurahidReciterReciterid200 = QuranAyahAudioFileListSuccessResponse;

/**
 * @description Bad request
*/
export type GetQuranAudioAyahsSurahSurahidReciterReciterid400 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type GetQuranAudioAyahsSurahSurahidReciterReciterid500 = QuranQuranErrorResponse;

export type GetQuranAudioAyahsSurahSurahidReciterReciteridQueryResponse = GetQuranAudioAyahsSurahSurahidReciterReciterid200;

export type GetQuranAudioAyahsSurahSurahidReciterReciteridQuery = {
    Response: GetQuranAudioAyahsSurahSurahidReciterReciterid200;
    PathParams: GetQuranAudioAyahsSurahSurahidReciterReciteridPathParams;
    QueryParams: GetQuranAudioAyahsSurahSurahidReciterReciteridQueryParams;
    Errors: GetQuranAudioAyahsSurahSurahidReciterReciterid400 | GetQuranAudioAyahsSurahSurahidReciterReciterid500;
};