/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranBookmarkAyahListSuccessResponse } from "./quran/BookmarkAyahListSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type GetQuranBookmarksAyahsQueryParams = {
    /**
     * @description Limit
     * @type integer | undefined
    */
    limit?: number;
    /**
     * @description Offset
     * @type integer | undefined
    */
    offset?: number;
};

/**
 * @description Bookmarks retrieved successfully
*/
export type GetQuranBookmarksAyahs200 = QuranBookmarkAyahListSuccessResponse;

/**
 * @description Bad request
*/
export type GetQuranBookmarksAyahs400 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type GetQuranBookmarksAyahs500 = QuranQuranErrorResponse;

export type GetQuranBookmarksAyahsQueryResponse = GetQuranBookmarksAyahs200;

export type GetQuranBookmarksAyahsQuery = {
    Response: GetQuranBookmarksAyahs200;
    QueryParams: GetQuranBookmarksAyahsQueryParams;
    Errors: GetQuranBookmarksAyahs400 | GetQuranBookmarksAyahs500;
};