/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranProgressHatamSuccessResponse } from "./quran/ProgressHatamSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type GetQuranProgressHatamIdPathParams = {
    /**
     * @description ProgressHatam ID
     * @type string
    */
    id: string;
};

export const getQuranProgressHatamIdQueryParamsIncludeEnum = {
    "relations": "relations"
} as const;

export type GetQuranProgressHatamIdQueryParamsIncludeEnumKey = (typeof getQuranProgressHatamIdQueryParamsIncludeEnum)[keyof typeof getQuranProgressHatamIdQueryParamsIncludeEnum];

export type GetQuranProgressHatamIdQueryParams = {
    /**
     * @description Include related data
     * @type string | undefined
    */
    include?: GetQuranProgressHatamIdQueryParamsIncludeEnumKey;
};

/**
 * @description Progress hatam retrieved successfully
*/
export type GetQuranProgressHatamId200 = QuranProgressHatamSuccessResponse;

/**
 * @description Bad request
*/
export type GetQuranProgressHatamId400 = QuranQuranErrorResponse;

/**
 * @description Progress hatam not found
*/
export type GetQuranProgressHatamId404 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type GetQuranProgressHatamId500 = QuranQuranErrorResponse;

export type GetQuranProgressHatamIdQueryResponse = GetQuranProgressHatamId200;

export type GetQuranProgressHatamIdQuery = {
    Response: GetQuranProgressHatamId200;
    PathParams: GetQuranProgressHatamIdPathParams;
    QueryParams: GetQuranProgressHatamIdQueryParams;
    Errors: GetQuranProgressHatamId400 | GetQuranProgressHatamId404 | GetQuranProgressHatamId500;
};