/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranGetAyahTranslationSuccessResponse } from "./quran/GetAyahTranslationSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type GetQuranTranslationsAyahsAyahAyahidEditionEditionidPathParams = {
    /**
     * @description Ayah ID
     * @type string
    */
    ayahId: string;
    /**
     * @description Translation Edition ID
     * @type string
    */
    editionId: string;
};

/**
 * @description Ayah translation retrieved successfully
*/
export type GetQuranTranslationsAyahsAyahAyahidEditionEditionid200 = QuranGetAyahTranslationSuccessResponse;

/**
 * @description Bad request
*/
export type GetQuranTranslationsAyahsAyahAyahidEditionEditionid400 = QuranQuranErrorResponse;

/**
 * @description Not found
*/
export type GetQuranTranslationsAyahsAyahAyahidEditionEditionid404 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type GetQuranTranslationsAyahsAyahAyahidEditionEditionid500 = QuranQuranErrorResponse;

export type GetQuranTranslationsAyahsAyahAyahidEditionEditionidQueryResponse = GetQuranTranslationsAyahsAyahAyahidEditionEditionid200;

export type GetQuranTranslationsAyahsAyahAyahidEditionEditionidQuery = {
    Response: GetQuranTranslationsAyahsAyahAyahidEditionEditionid200;
    PathParams: GetQuranTranslationsAyahsAyahAyahidEditionEditionidPathParams;
    Errors: GetQuranTranslationsAyahsAyahAyahidEditionEditionid400 | GetQuranTranslationsAyahsAyahAyahidEditionEditionid404 | GetQuranTranslationsAyahsAyahAyahidEditionEditionid500;
};