/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranGetSurahByIdSuccessResponse } from "./quran/GetSurahByIdSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type GetQuranSurahsIdPathParams = {
    /**
     * @description Surah ID
     * @type string
    */
    id: string;
};

export const getQuranSurahsIdQueryParamsIncludeEnum = {
    "ayahs": "ayahs"
} as const;

export type GetQuranSurahsIdQueryParamsIncludeEnumKey = (typeof getQuranSurahsIdQueryParamsIncludeEnum)[keyof typeof getQuranSurahsIdQueryParamsIncludeEnum];

export type GetQuranSurahsIdQueryParams = {
    /**
     * @description Include related data
     * @type string | undefined
    */
    include?: GetQuranSurahsIdQueryParamsIncludeEnumKey;
};

/**
 * @description Surah retrieved successfully
*/
export type GetQuranSurahsId200 = QuranGetSurahByIdSuccessResponse;

/**
 * @description Bad request
*/
export type GetQuranSurahsId400 = QuranQuranErrorResponse;

/**
 * @description Surah not found
*/
export type GetQuranSurahsId404 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type GetQuranSurahsId500 = QuranQuranErrorResponse;

export type GetQuranSurahsIdQueryResponse = GetQuranSurahsId200;

export type GetQuranSurahsIdQuery = {
    Response: GetQuranSurahsId200;
    PathParams: GetQuranSurahsIdPathParams;
    QueryParams: GetQuranSurahsIdQueryParams;
    Errors: GetQuranSurahsId400 | GetQuranSurahsId404 | GetQuranSurahsId500;
};