/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";
import type { QuranReciterListSuccessResponse } from "./quran/ReciterListSuccessResponse.ts";

export type GetQuranRecitersQueryParams = {
    /**
     * @description Limit (0 for all)
     * @default 0
     * @type integer | undefined
    */
    limit?: number;
    /**
     * @description Offset
     * @default 0
     * @type integer | undefined
    */
    offset?: number;
};

/**
 * @description Reciters retrieved successfully
*/
export type GetQuranReciters200 = QuranReciterListSuccessResponse;

/**
 * @description Bad request
*/
export type GetQuranReciters400 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type GetQuranReciters500 = QuranQuranErrorResponse;

export type GetQuranRecitersQueryResponse = GetQuranReciters200;

export type GetQuranRecitersQuery = {
    Response: GetQuranReciters200;
    QueryParams: GetQuranRecitersQueryParams;
    Errors: GetQuranReciters400 | GetQuranReciters500;
};