/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranLastReadSuccessResponse } from "./quran/LastReadSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type GetQuranLastReadsSurahSurahidPathParams = {
    /**
     * @description Surah ID
     * @type string
    */
    surahId: string;
};

export const getQuranLastReadsSurahSurahidQueryParamsIncludeEnum = {
    "relations": "relations"
} as const;

export type GetQuranLastReadsSurahSurahidQueryParamsIncludeEnumKey = (typeof getQuranLastReadsSurahSurahidQueryParamsIncludeEnum)[keyof typeof getQuranLastReadsSurahSurahidQueryParamsIncludeEnum];

export type GetQuranLastReadsSurahSurahidQueryParams = {
    /**
     * @description Include related data
     * @type string | undefined
    */
    include?: GetQuranLastReadsSurahSurahidQueryParamsIncludeEnumKey;
};

/**
 * @description Last read retrieved successfully
*/
export type GetQuranLastReadsSurahSurahid200 = QuranLastReadSuccessResponse;

/**
 * @description Bad request
*/
export type GetQuranLastReadsSurahSurahid400 = QuranQuranErrorResponse;

/**
 * @description Last read not found
*/
export type GetQuranLastReadsSurahSurahid404 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type GetQuranLastReadsSurahSurahid500 = QuranQuranErrorResponse;

export type GetQuranLastReadsSurahSurahidQueryResponse = GetQuranLastReadsSurahSurahid200;

export type GetQuranLastReadsSurahSurahidQuery = {
    Response: GetQuranLastReadsSurahSurahid200;
    PathParams: GetQuranLastReadsSurahSurahidPathParams;
    QueryParams: GetQuranLastReadsSurahSurahidQueryParams;
    Errors: GetQuranLastReadsSurahSurahid400 | GetQuranLastReadsSurahSurahid404 | GetQuranLastReadsSurahSurahid500;
};