/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranProgressHatamListSuccessResponse } from "./quran/ProgressHatamListSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export const getQuranProgressHatamQueryParamsIncludeEnum = {
    "relations": "relations"
} as const;

export type GetQuranProgressHatamQueryParamsIncludeEnumKey = (typeof getQuranProgressHatamQueryParamsIncludeEnum)[keyof typeof getQuranProgressHatamQueryParamsIncludeEnum];

export type GetQuranProgressHatamQueryParams = {
    /**
     * @description Limit
     * @type integer | undefined
    */
    limit?: number;
    /**
     * @description Offset
     * @type integer | undefined
    */
    offset?: number;
    /**
     * @description Include related data
     * @type string | undefined
    */
    include?: GetQuranProgressHatamQueryParamsIncludeEnumKey;
};

/**
 * @description Progress hatam list retrieved successfully
*/
export type GetQuranProgressHatam200 = QuranProgressHatamListSuccessResponse;

/**
 * @description Bad request
*/
export type GetQuranProgressHatam400 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type GetQuranProgressHatam500 = QuranQuranErrorResponse;

export type GetQuranProgressHatamQueryResponse = GetQuranProgressHatam200;

export type GetQuranProgressHatamQuery = {
    Response: GetQuranProgressHatam200;
    QueryParams: GetQuranProgressHatamQueryParams;
    Errors: GetQuranProgressHatam400 | GetQuranProgressHatam500;
};