/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranBookmarkAyahSuccessResponse } from "./quran/BookmarkAyahSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type GetQuranBookmarksAyahsAyahAyahidPathParams = {
    /**
     * @description Ayah ID
     * @type string
    */
    ayahId: string;
};

export const getQuranBookmarksAyahsAyahAyahidQueryParamsIncludeEnum = {
    "ayah": "ayah"
} as const;

export type GetQuranBookmarksAyahsAyahAyahidQueryParamsIncludeEnumKey = (typeof getQuranBookmarksAyahsAyahAyahidQueryParamsIncludeEnum)[keyof typeof getQuranBookmarksAyahsAyahAyahidQueryParamsIncludeEnum];

export type GetQuranBookmarksAyahsAyahAyahidQueryParams = {
    /**
     * @description Include related data
     * @type string | undefined
    */
    include?: GetQuranBookmarksAyahsAyahAyahidQueryParamsIncludeEnumKey;
};

/**
 * @description Bookmark retrieved successfully
*/
export type GetQuranBookmarksAyahsAyahAyahid200 = QuranBookmarkAyahSuccessResponse;

/**
 * @description Bad request
*/
export type GetQuranBookmarksAyahsAyahAyahid400 = QuranQuranErrorResponse;

/**
 * @description Bookmark not found
*/
export type GetQuranBookmarksAyahsAyahAyahid404 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type GetQuranBookmarksAyahsAyahAyahid500 = QuranQuranErrorResponse;

export type GetQuranBookmarksAyahsAyahAyahidQueryResponse = GetQuranBookmarksAyahsAyahAyahid200;

export type GetQuranBookmarksAyahsAyahAyahidQuery = {
    Response: GetQuranBookmarksAyahsAyahAyahid200;
    PathParams: GetQuranBookmarksAyahsAyahAyahidPathParams;
    QueryParams: GetQuranBookmarksAyahsAyahAyahidQueryParams;
    Errors: GetQuranBookmarksAyahsAyahAyahid400 | GetQuranBookmarksAyahsAyahAyahid404 | GetQuranBookmarksAyahsAyahAyahid500;
};