/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranGetAllSurahsSuccessResponse } from "./quran/GetAllSurahsSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export const getQuranSurahsQueryParamsIncludeEnum = {
    "ayahs": "ayahs"
} as const;

export type GetQuranSurahsQueryParamsIncludeEnumKey = (typeof getQuranSurahsQueryParamsIncludeEnum)[keyof typeof getQuranSurahsQueryParamsIncludeEnum];

export type GetQuranSurahsQueryParams = {
    /**
     * @description Limit (0 for all)
     * @default 0
     * @type integer | undefined
    */
    limit?: number;
    /**
     * @description Offset
     * @default 0
     * @type integer | undefined
    */
    offset?: number;
    /**
     * @description Include related data
     * @type string | undefined
    */
    include?: GetQuranSurahsQueryParamsIncludeEnumKey;
};

/**
 * @description Surahs retrieved successfully
*/
export type GetQuranSurahs200 = QuranGetAllSurahsSuccessResponse;

/**
 * @description Bad request
*/
export type GetQuranSurahs400 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type GetQuranSurahs500 = QuranQuranErrorResponse;

export type GetQuranSurahsQueryResponse = GetQuranSurahs200;

export type GetQuranSurahsQuery = {
    Response: GetQuranSurahs200;
    QueryParams: GetQuranSurahsQueryParams;
    Errors: GetQuranSurahs400 | GetQuranSurahs500;
};