/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";
import type { QuranReciterSuccessResponse } from "./quran/ReciterSuccessResponse.ts";

export type GetQuranRecitersNamePathParams = {
    /**
     * @description Reciter name
     * @type string
    */
    name: string;
};

/**
 * @description Reciter retrieved successfully
*/
export type GetQuranRecitersName200 = QuranReciterSuccessResponse;

/**
 * @description Bad request
*/
export type GetQuranRecitersName400 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type GetQuranRecitersName500 = QuranQuranErrorResponse;

export type GetQuranRecitersNameQueryResponse = GetQuranRecitersName200;

export type GetQuranRecitersNameNameQuery = {
    Response: GetQuranRecitersName200;
    PathParams: GetQuranRecitersNamePathParams;
    Errors: GetQuranRecitersName400 | GetQuranRecitersName500;
};