/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranLastReadSuccessResponse } from "./quran/LastReadSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type GetQuranLastReadsIdPathParams = {
    /**
     * @description LastRead ID
     * @type string
    */
    id: string;
};

export const getQuranLastReadsIdQueryParamsIncludeEnum = {
    "relations": "relations"
} as const;

export type GetQuranLastReadsIdQueryParamsIncludeEnumKey = (typeof getQuranLastReadsIdQueryParamsIncludeEnum)[keyof typeof getQuranLastReadsIdQueryParamsIncludeEnum];

export type GetQuranLastReadsIdQueryParams = {
    /**
     * @description Include related data
     * @type string | undefined
    */
    include?: GetQuranLastReadsIdQueryParamsIncludeEnumKey;
};

/**
 * @description Last read retrieved successfully
*/
export type GetQuranLastReadsId200 = QuranLastReadSuccessResponse;

/**
 * @description Bad request
*/
export type GetQuranLastReadsId400 = QuranQuranErrorResponse;

/**
 * @description Last read not found
*/
export type GetQuranLastReadsId404 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type GetQuranLastReadsId500 = QuranQuranErrorResponse;

export type GetQuranLastReadsIdQueryResponse = GetQuranLastReadsId200;

export type GetQuranLastReadsIdQuery = {
    Response: GetQuranLastReadsId200;
    PathParams: GetQuranLastReadsIdPathParams;
    QueryParams: GetQuranLastReadsIdQueryParams;
    Errors: GetQuranLastReadsId400 | GetQuranLastReadsId404 | GetQuranLastReadsId500;
};