/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranProgressHatamSuccessResponse } from "./quran/ProgressHatamSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type GetQuranProgressHatamJuzJuzidPathParams = {
    /**
     * @description Juz ID
     * @type string
    */
    juzId: string;
};

export const getQuranProgressHatamJuzJuzidQueryParamsIncludeEnum = {
    "relations": "relations"
} as const;

export type GetQuranProgressHatamJuzJuzidQueryParamsIncludeEnumKey = (typeof getQuranProgressHatamJuzJuzidQueryParamsIncludeEnum)[keyof typeof getQuranProgressHatamJuzJuzidQueryParamsIncludeEnum];

export type GetQuranProgressHatamJuzJuzidQueryParams = {
    /**
     * @description Include related data
     * @type string | undefined
    */
    include?: GetQuranProgressHatamJuzJuzidQueryParamsIncludeEnumKey;
};

/**
 * @description Progress hatam retrieved successfully
*/
export type GetQuranProgressHatamJuzJuzid200 = QuranProgressHatamSuccessResponse;

/**
 * @description Bad request
*/
export type GetQuranProgressHatamJuzJuzid400 = QuranQuranErrorResponse;

/**
 * @description Progress hatam not found
*/
export type GetQuranProgressHatamJuzJuzid404 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type GetQuranProgressHatamJuzJuzid500 = QuranQuranErrorResponse;

export type GetQuranProgressHatamJuzJuzidQueryResponse = GetQuranProgressHatamJuzJuzid200;

export type GetQuranProgressHatamJuzJuzidQuery = {
    Response: GetQuranProgressHatamJuzJuzid200;
    PathParams: GetQuranProgressHatamJuzJuzidPathParams;
    QueryParams: GetQuranProgressHatamJuzJuzidQueryParams;
    Errors: GetQuranProgressHatamJuzJuzid400 | GetQuranProgressHatamJuzJuzid404 | GetQuranProgressHatamJuzJuzid500;
};