export type { CoreErrorDetail } from "./core/ErrorDetail.ts";
export type { DeleteQuranAudioAyahsIdPathParams, DeleteQuranAudioAyahsId200, DeleteQuranAudioAyahsId400, DeleteQuranAudioAyahsId500, DeleteQuranAudioAyahsIdMutationResponse, DeleteQuranAudioAyahsIdMutation } from "./DeleteQuranAudioAyahsId.ts";
export type { DeleteQuranAyahsIdPathParams, DeleteQuranAyahsId200, DeleteQuranAyahsId400, DeleteQuranAyahsId404, DeleteQuranAyahsId500, DeleteQuranAyahsIdMutationResponse, DeleteQuranAyahsIdMutation } from "./DeleteQuranAyahsId.ts";
export type { DeleteQuranBookmarksAyahsIdPathParams, DeleteQuranBookmarksAyahsId200, DeleteQuranBookmarksAyahsId400, DeleteQuranBookmarksAyahsId404, DeleteQuranBookmarksAyahsId500, DeleteQuranBookmarksAyahsIdMutationResponse, DeleteQuranBookmarksAyahsIdMutation } from "./DeleteQuranBookmarksAyahsId.ts";
export type { DeleteQuranJuzIdPathParams, DeleteQuranJuzId200, DeleteQuranJuzId400, DeleteQuranJuzId404, DeleteQuranJuzId500, DeleteQuranJuzIdMutationResponse, DeleteQuranJuzIdMutation } from "./DeleteQuranJuzId.ts";
export type { DeleteQuranLastReadsIdPathParams, DeleteQuranLastReadsId200, DeleteQuranLastReadsId400, DeleteQuranLastReadsId404, DeleteQuranLastReadsId500, DeleteQuranLastReadsIdMutationResponse, DeleteQuranLastReadsIdMutation } from "./DeleteQuranLastReadsId.ts";
export type { DeleteQuranProgressHatamIdPathParams, DeleteQuranProgressHatamId200, DeleteQuranProgressHatamId400, DeleteQuranProgressHatamId404, DeleteQuranProgressHatamId500, DeleteQuranProgressHatamIdMutationResponse, DeleteQuranProgressHatamIdMutation } from "./DeleteQuranProgressHatamId.ts";
export type { DeleteQuranRecitersIdPathParams, DeleteQuranRecitersId200, DeleteQuranRecitersId400, DeleteQuranRecitersId500, DeleteQuranRecitersIdMutationResponse, DeleteQuranRecitersIdMutation } from "./DeleteQuranRecitersId.ts";
export type { DeleteQuranSurahsIdPathParams, DeleteQuranSurahsId200, DeleteQuranSurahsId400, DeleteQuranSurahsId404, DeleteQuranSurahsId500, DeleteQuranSurahsIdMutationResponse, DeleteQuranSurahsIdMutation } from "./DeleteQuranSurahsId.ts";
export type { DtoAyahAudioFileListResponse } from "./dto/AyahAudioFileListResponse.ts";
export type { DtoAyahAudioFileResponse } from "./dto/AyahAudioFileResponse.ts";
export type { DtoAyahListResponse } from "./dto/AyahListResponse.ts";
export type { DtoAyahResponse } from "./dto/AyahResponse.ts";
export type { DtoAyahTranslationListResponse } from "./dto/AyahTranslationListResponse.ts";
export type { DtoAyahTranslationResponse } from "./dto/AyahTranslationResponse.ts";
export type { DtoAyahWithTranslationResponse } from "./dto/AyahWithTranslationResponse.ts";
export type { DtoBookmarkAyahListResponse } from "./dto/BookmarkAyahListResponse.ts";
export type { DtoBookmarkAyahResponse } from "./dto/BookmarkAyahResponse.ts";
export type { DtoCreateAyahAudioFileRequest } from "./dto/CreateAyahAudioFileRequest.ts";
export type { DtoCreateAyahRequest } from "./dto/CreateAyahRequest.ts";
export type { DtoCreateBookmarkAyahRequest } from "./dto/CreateBookmarkAyahRequest.ts";
export type { DtoCreateJuzRequest } from "./dto/CreateJuzRequest.ts";
export type { DtoCreateLastReadRequest } from "./dto/CreateLastReadRequest.ts";
export type { DtoCreateProgressHatamRequest } from "./dto/CreateProgressHatamRequest.ts";
export type { DtoCreateReciterRequest } from "./dto/CreateReciterRequest.ts";
export type { DtoCreateSurahRequest } from "./dto/CreateSurahRequest.ts";
export type { DtoJuzListResponse } from "./dto/JuzListResponse.ts";
export type { DtoJuzResponse } from "./dto/JuzResponse.ts";
export type { DtoJuzWithProgressBasicListResponse } from "./dto/JuzWithProgressBasicListResponse.ts";
export type { DtoJuzWithProgressBasicResponse } from "./dto/JuzWithProgressBasicResponse.ts";
export type { DtoLastReadListResponse } from "./dto/LastReadListResponse.ts";
export type { DtoLastReadResponse } from "./dto/LastReadResponse.ts";
export type { DtoPaginationResponse } from "./dto/PaginationResponse.ts";
export type { DtoPrayerTimesListResponse } from "./dto/PrayerTimesListResponse.ts";
export type { DtoPrayerTimesResponse } from "./dto/PrayerTimesResponse.ts";
export type { DtoProgressHatamListResponse } from "./dto/ProgressHatamListResponse.ts";
export type { DtoProgressHatamResponse } from "./dto/ProgressHatamResponse.ts";
export type { DtoReciterListResponse } from "./dto/ReciterListResponse.ts";
export type { DtoReciterResponse } from "./dto/ReciterResponse.ts";
export type { DtoSurahAyahsWithTranslationsResponse } from "./dto/SurahAyahsWithTranslationsResponse.ts";
export type { DtoSurahListResponse } from "./dto/SurahListResponse.ts";
export type { DtoSurahResponse } from "./dto/SurahResponse.ts";
export type { DtoTranslationEditionListResponse } from "./dto/TranslationEditionListResponse.ts";
export type { DtoTranslationEditionResponse } from "./dto/TranslationEditionResponse.ts";
export type { DtoUpdateAyahAudioFileRequest } from "./dto/UpdateAyahAudioFileRequest.ts";
export type { DtoUpdateAyahRequest } from "./dto/UpdateAyahRequest.ts";
export type { DtoUpdateJuzRequest } from "./dto/UpdateJuzRequest.ts";
export type { DtoUpdateLastReadRequest } from "./dto/UpdateLastReadRequest.ts";
export type { DtoUpdateProgressHatamRequest } from "./dto/UpdateProgressHatamRequest.ts";
export type { DtoUpdateReciterRequest } from "./dto/UpdateReciterRequest.ts";
export type { DtoUpdateSurahRequest } from "./dto/UpdateSurahRequest.ts";
export type { GetPrayertimesDailyQueryParams, GetPrayertimesDaily200, GetPrayertimesDaily400, GetPrayertimesDaily500, GetPrayertimesDailyQueryResponse, GetPrayertimesDailyQuery } from "./GetPrayertimesDaily.ts";
export type { GetPrayertimesMonthlyQueryParams, GetPrayertimesMonthly200, GetPrayertimesMonthly400, GetPrayertimesMonthly500, GetPrayertimesMonthlyQueryResponse, GetPrayertimesMonthlyQuery } from "./GetPrayertimesMonthly.ts";
export type { GetPrayertimesYearlyQueryParams, GetPrayertimesYearly200, GetPrayertimesYearly400, GetPrayertimesYearly500, GetPrayertimesYearlyQueryResponse, GetPrayertimesYearlyQuery } from "./GetPrayertimesYearly.ts";
export type { GetQuranAudioAyahsAyahAyahidReciterReciteridPathParams, GetQuranAudioAyahsAyahAyahidReciterReciterid200, GetQuranAudioAyahsAyahAyahidReciterReciterid400, GetQuranAudioAyahsAyahAyahidReciterReciterid500, GetQuranAudioAyahsAyahAyahidReciterReciteridQueryResponse, GetQuranAudioAyahsAyahAyahidReciterReciteridQuery } from "./GetQuranAudioAyahsAyahAyahidReciterReciterid.ts";
export type { GetQuranAudioAyahsIdPathParams, GetQuranAudioAyahsId200, GetQuranAudioAyahsId400, GetQuranAudioAyahsId500, GetQuranAudioAyahsIdQueryResponse, GetQuranAudioAyahsIdQuery } from "./GetQuranAudioAyahsId.ts";
export type { GetQuranAudioAyahsSurahSurahidReciterReciteridPathParams, GetQuranAudioAyahsSurahSurahidReciterReciteridQueryParams, GetQuranAudioAyahsSurahSurahidReciterReciterid200, GetQuranAudioAyahsSurahSurahidReciterReciterid400, GetQuranAudioAyahsSurahSurahidReciterReciterid500, GetQuranAudioAyahsSurahSurahidReciterReciteridQueryResponse, GetQuranAudioAyahsSurahSurahidReciterReciteridQuery } from "./GetQuranAudioAyahsSurahSurahidReciterReciterid.ts";
export type { GetQuranAyahsIdPathParams, GetQuranAyahsIdQueryParamsIncludeEnumKey, GetQuranAyahsIdQueryParams, GetQuranAyahsId200, GetQuranAyahsId400, GetQuranAyahsId404, GetQuranAyahsId500, GetQuranAyahsIdQueryResponse, GetQuranAyahsIdQuery } from "./GetQuranAyahsId.ts";
export type { GetQuranAyahsSurahSurahidPathParams, GetQuranAyahsSurahSurahidQueryParamsIncludeEnumKey, GetQuranAyahsSurahSurahidQueryParams, GetQuranAyahsSurahSurahid200, GetQuranAyahsSurahSurahid400, GetQuranAyahsSurahSurahid500, GetQuranAyahsSurahSurahidQueryResponse, GetQuranAyahsSurahSurahidQuery } from "./GetQuranAyahsSurahSurahid.ts";
export type { GetQuranBookmarksAyahsQueryParams, GetQuranBookmarksAyahs200, GetQuranBookmarksAyahs400, GetQuranBookmarksAyahs500, GetQuranBookmarksAyahsQueryResponse, GetQuranBookmarksAyahsQuery } from "./GetQuranBookmarksAyahs.ts";
export type { GetQuranBookmarksAyahsAyahAyahidPathParams, GetQuranBookmarksAyahsAyahAyahidQueryParamsIncludeEnumKey, GetQuranBookmarksAyahsAyahAyahidQueryParams, GetQuranBookmarksAyahsAyahAyahid200, GetQuranBookmarksAyahsAyahAyahid400, GetQuranBookmarksAyahsAyahAyahid404, GetQuranBookmarksAyahsAyahAyahid500, GetQuranBookmarksAyahsAyahAyahidQueryResponse, GetQuranBookmarksAyahsAyahAyahidQuery } from "./GetQuranBookmarksAyahsAyahAyahid.ts";
export type { GetQuranBookmarksAyahsIdPathParams, GetQuranBookmarksAyahsIdQueryParamsIncludeEnumKey, GetQuranBookmarksAyahsIdQueryParams, GetQuranBookmarksAyahsId200, GetQuranBookmarksAyahsId400, GetQuranBookmarksAyahsId404, GetQuranBookmarksAyahsId500, GetQuranBookmarksAyahsIdQueryResponse, GetQuranBookmarksAyahsIdQuery } from "./GetQuranBookmarksAyahsId.ts";
export type { GetQuranJuzQueryParamsIncludeEnumKey, GetQuranJuzQueryParams, GetQuranJuz200, GetQuranJuz400, GetQuranJuz500, GetQuranJuzQueryResponse, GetQuranJuzQuery } from "./GetQuranJuz.ts";
export type { GetQuranJuzIdPathParams, GetQuranJuzIdQueryParamsIncludeEnumKey, GetQuranJuzIdQueryParams, GetQuranJuzId200, GetQuranJuzId400, GetQuranJuzId404, GetQuranJuzId500, GetQuranJuzIdQueryResponse, GetQuranJuzIdQuery } from "./GetQuranJuzId.ts";
export type { GetQuranJuzJuznumberAyahsPathParams, GetQuranJuzJuznumberAyahsQueryParams, GetQuranJuzJuznumberAyahs200, GetQuranJuzJuznumberAyahs400, GetQuranJuzJuznumberAyahs500, GetQuranJuzJuznumberAyahsQueryResponse, GetQuranJuzJuznumberAyahsQuery } from "./GetQuranJuzJuznumberAyahs.ts";
export type { GetQuranJuzNumberPathParams, GetQuranJuzNumberQueryParamsIncludeEnumKey, GetQuranJuzNumberQueryParams, GetQuranJuzNumber200, GetQuranJuzNumber400, GetQuranJuzNumber404, GetQuranJuzNumber500, GetQuranJuzNumberQueryResponse, GetQuranJuzNumberNumberQuery } from "./GetQuranJuzNumberNumber.ts";
export type { GetQuranJuzWithProgressQueryParamsIncludeEnumKey, GetQuranJuzWithProgressQueryParams, GetQuranJuzWithProgress200, GetQuranJuzWithProgress400, GetQuranJuzWithProgress500, GetQuranJuzWithProgressQueryResponse, GetQuranJuzWithProgressQuery } from "./GetQuranJuzWithProgress.ts";
export type { GetQuranLastReadsQueryParamsIncludeEnumKey, GetQuranLastReadsQueryParams, GetQuranLastReads200, GetQuranLastReads400, GetQuranLastReads500, GetQuranLastReadsQueryResponse, GetQuranLastReadsQuery } from "./GetQuranLastReads.ts";
export type { GetQuranLastReadsIdPathParams, GetQuranLastReadsIdQueryParamsIncludeEnumKey, GetQuranLastReadsIdQueryParams, GetQuranLastReadsId200, GetQuranLastReadsId400, GetQuranLastReadsId404, GetQuranLastReadsId500, GetQuranLastReadsIdQueryResponse, GetQuranLastReadsIdQuery } from "./GetQuranLastReadsId.ts";
export type { GetQuranLastReadsSurahSurahidPathParams, GetQuranLastReadsSurahSurahidQueryParamsIncludeEnumKey, GetQuranLastReadsSurahSurahidQueryParams, GetQuranLastReadsSurahSurahid200, GetQuranLastReadsSurahSurahid400, GetQuranLastReadsSurahSurahid404, GetQuranLastReadsSurahSurahid500, GetQuranLastReadsSurahSurahidQueryResponse, GetQuranLastReadsSurahSurahidQuery } from "./GetQuranLastReadsSurahSurahid.ts";
export type { GetQuranProgressHatamQueryParamsIncludeEnumKey, GetQuranProgressHatamQueryParams, GetQuranProgressHatam200, GetQuranProgressHatam400, GetQuranProgressHatam500, GetQuranProgressHatamQueryResponse, GetQuranProgressHatamQuery } from "./GetQuranProgressHatam.ts";
export type { GetQuranProgressHatamIdPathParams, GetQuranProgressHatamIdQueryParamsIncludeEnumKey, GetQuranProgressHatamIdQueryParams, GetQuranProgressHatamId200, GetQuranProgressHatamId400, GetQuranProgressHatamId404, GetQuranProgressHatamId500, GetQuranProgressHatamIdQueryResponse, GetQuranProgressHatamIdQuery } from "./GetQuranProgressHatamId.ts";
export type { GetQuranProgressHatamJuzJuzidPathParams, GetQuranProgressHatamJuzJuzidQueryParamsIncludeEnumKey, GetQuranProgressHatamJuzJuzidQueryParams, GetQuranProgressHatamJuzJuzid200, GetQuranProgressHatamJuzJuzid400, GetQuranProgressHatamJuzJuzid404, GetQuranProgressHatamJuzJuzid500, GetQuranProgressHatamJuzJuzidQueryResponse, GetQuranProgressHatamJuzJuzidQuery } from "./GetQuranProgressHatamJuzJuzid.ts";
export type { GetQuranRecitersQueryParams, GetQuranReciters200, GetQuranReciters400, GetQuranReciters500, GetQuranRecitersQueryResponse, GetQuranRecitersQuery } from "./GetQuranReciters.ts";
export type { GetQuranRecitersIdPathParams, GetQuranRecitersId200, GetQuranRecitersId400, GetQuranRecitersId500, GetQuranRecitersIdQueryResponse, GetQuranRecitersIdQuery } from "./GetQuranRecitersId.ts";
export type { GetQuranRecitersNamePathParams, GetQuranRecitersName200, GetQuranRecitersName400, GetQuranRecitersName500, GetQuranRecitersNameQueryResponse, GetQuranRecitersNameNameQuery } from "./GetQuranRecitersNameName.ts";
export type { GetQuranSurahsQueryParamsIncludeEnumKey, GetQuranSurahsQueryParams, GetQuranSurahs200, GetQuranSurahs400, GetQuranSurahs500, GetQuranSurahsQueryResponse, GetQuranSurahsQuery } from "./GetQuranSurahs.ts";
export type { GetQuranSurahsIdPathParams, GetQuranSurahsIdQueryParamsIncludeEnumKey, GetQuranSurahsIdQueryParams, GetQuranSurahsId200, GetQuranSurahsId400, GetQuranSurahsId404, GetQuranSurahsId500, GetQuranSurahsIdQueryResponse, GetQuranSurahsIdQuery } from "./GetQuranSurahsId.ts";
export type { GetQuranSurahsNumberPathParams, GetQuranSurahsNumberQueryParamsIncludeEnumKey, GetQuranSurahsNumberQueryParams, GetQuranSurahsNumber200, GetQuranSurahsNumber400, GetQuranSurahsNumber404, GetQuranSurahsNumber500, GetQuranSurahsNumberQueryResponse, GetQuranSurahsNumberNumberQuery } from "./GetQuranSurahsNumberNumber.ts";
export type { GetQuranTranslationsAyahsAyahAyahidEditionEditionidPathParams, GetQuranTranslationsAyahsAyahAyahidEditionEditionid200, GetQuranTranslationsAyahsAyahAyahidEditionEditionid400, GetQuranTranslationsAyahsAyahAyahidEditionEditionid404, GetQuranTranslationsAyahsAyahAyahidEditionEditionid500, GetQuranTranslationsAyahsAyahAyahidEditionEditionidQueryResponse, GetQuranTranslationsAyahsAyahAyahidEditionEditionidQuery } from "./GetQuranTranslationsAyahsAyahAyahidEditionEditionid.ts";
export type { GetQuranTranslationsAyahsSurahSurahidEditionEditionidPathParams, GetQuranTranslationsAyahsSurahSurahidEditionEditionidQueryParams, GetQuranTranslationsAyahsSurahSurahidEditionEditionid200, GetQuranTranslationsAyahsSurahSurahidEditionEditionid400, GetQuranTranslationsAyahsSurahSurahidEditionEditionid500, GetQuranTranslationsAyahsSurahSurahidEditionEditionidQueryResponse, GetQuranTranslationsAyahsSurahSurahidEditionEditionidQuery } from "./GetQuranTranslationsAyahsSurahSurahidEditionEditionid.ts";
export type { GetQuranTranslationsEditionsQueryParams, GetQuranTranslationsEditions200, GetQuranTranslationsEditions400, GetQuranTranslationsEditions500, GetQuranTranslationsEditionsQueryResponse, GetQuranTranslationsEditionsQuery } from "./GetQuranTranslationsEditions.ts";
export type { PostQuranAudioAyahs201, PostQuranAudioAyahs400, PostQuranAudioAyahs500, PostQuranAudioAyahsMutationRequest, PostQuranAudioAyahsMutationResponse, PostQuranAudioAyahsMutation } from "./PostQuranAudioAyahs.ts";
export type { PostQuranAyahs201, PostQuranAyahs400, PostQuranAyahs500, PostQuranAyahsMutationRequest, PostQuranAyahsMutationResponse, PostQuranAyahsMutation } from "./PostQuranAyahs.ts";
export type { PostQuranBookmarksAyahs201, PostQuranBookmarksAyahs400, PostQuranBookmarksAyahs500, PostQuranBookmarksAyahsMutationRequest, PostQuranBookmarksAyahsMutationResponse, PostQuranBookmarksAyahsMutation } from "./PostQuranBookmarksAyahs.ts";
export type { PostQuranJuz201, PostQuranJuz400, PostQuranJuz500, PostQuranJuzMutationRequest, PostQuranJuzMutationResponse, PostQuranJuzMutation } from "./PostQuranJuz.ts";
export type { PostQuranLastReads201, PostQuranLastReads400, PostQuranLastReads500, PostQuranLastReadsMutationRequest, PostQuranLastReadsMutationResponse, PostQuranLastReadsMutation } from "./PostQuranLastReads.ts";
export type { PostQuranProgressHatam201, PostQuranProgressHatam400, PostQuranProgressHatam500, PostQuranProgressHatamMutationRequest, PostQuranProgressHatamMutationResponse, PostQuranProgressHatamMutation } from "./PostQuranProgressHatam.ts";
export type { PostQuranReciters201, PostQuranReciters400, PostQuranReciters500, PostQuranRecitersMutationRequest, PostQuranRecitersMutationResponse, PostQuranRecitersMutation } from "./PostQuranReciters.ts";
export type { PostQuranSurahs201, PostQuranSurahs400, PostQuranSurahs500, PostQuranSurahsMutationRequest, PostQuranSurahsMutationResponse, PostQuranSurahsMutation } from "./PostQuranSurahs.ts";
export type { PrayertimesPrayerTimesErrorResponse } from "./prayertimes/PrayerTimesErrorResponse.ts";
export type { PrayertimesPrayerTimesListSuccessResponse } from "./prayertimes/PrayerTimesListSuccessResponse.ts";
export type { PrayertimesPrayerTimesSuccessResponse } from "./prayertimes/PrayerTimesSuccessResponse.ts";
export type { PutQuranAudioAyahsIdPathParams, PutQuranAudioAyahsId200, PutQuranAudioAyahsId400, PutQuranAudioAyahsId500, PutQuranAudioAyahsIdMutationRequest, PutQuranAudioAyahsIdMutationResponse, PutQuranAudioAyahsIdMutation } from "./PutQuranAudioAyahsId.ts";
export type { PutQuranAyahsIdPathParams, PutQuranAyahsId200, PutQuranAyahsId400, PutQuranAyahsId404, PutQuranAyahsId500, PutQuranAyahsIdMutationRequest, PutQuranAyahsIdMutationResponse, PutQuranAyahsIdMutation } from "./PutQuranAyahsId.ts";
export type { PutQuranJuzIdPathParams, PutQuranJuzId200, PutQuranJuzId400, PutQuranJuzId404, PutQuranJuzId500, PutQuranJuzIdMutationRequest, PutQuranJuzIdMutationResponse, PutQuranJuzIdMutation } from "./PutQuranJuzId.ts";
export type { PutQuranLastReadsIdPathParams, PutQuranLastReadsId200, PutQuranLastReadsId400, PutQuranLastReadsId404, PutQuranLastReadsId500, PutQuranLastReadsIdMutationRequest, PutQuranLastReadsIdMutationResponse, PutQuranLastReadsIdMutation } from "./PutQuranLastReadsId.ts";
export type { PutQuranProgressHatamIdPathParams, PutQuranProgressHatamId200, PutQuranProgressHatamId400, PutQuranProgressHatamId404, PutQuranProgressHatamId500, PutQuranProgressHatamIdMutationRequest, PutQuranProgressHatamIdMutationResponse, PutQuranProgressHatamIdMutation } from "./PutQuranProgressHatamId.ts";
export type { PutQuranRecitersIdPathParams, PutQuranRecitersId200, PutQuranRecitersId400, PutQuranRecitersId500, PutQuranRecitersIdMutationRequest, PutQuranRecitersIdMutationResponse, PutQuranRecitersIdMutation } from "./PutQuranRecitersId.ts";
export type { PutQuranSurahsIdPathParams, PutQuranSurahsId200, PutQuranSurahsId400, PutQuranSurahsId404, PutQuranSurahsId500, PutQuranSurahsIdMutationRequest, PutQuranSurahsIdMutationResponse, PutQuranSurahsIdMutation } from "./PutQuranSurahsId.ts";
export type { QuranAyahAudioFileListSuccessResponse } from "./quran/AyahAudioFileListSuccessResponse.ts";
export type { QuranAyahAudioFileSuccessResponse } from "./quran/AyahAudioFileSuccessResponse.ts";
export type { QuranBookmarkAyahListSuccessResponse } from "./quran/BookmarkAyahListSuccessResponse.ts";
export type { QuranBookmarkAyahSuccessResponse } from "./quran/BookmarkAyahSuccessResponse.ts";
export type { QuranCreateAyahAudioFileSuccessResponse } from "./quran/CreateAyahAudioFileSuccessResponse.ts";
export type { QuranCreateAyahSuccessResponse } from "./quran/CreateAyahSuccessResponse.ts";
export type { QuranCreateReciterSuccessResponse } from "./quran/CreateReciterSuccessResponse.ts";
export type { QuranCreateSurahSuccessResponse } from "./quran/CreateSurahSuccessResponse.ts";
export type { QuranDeleteAyahAudioFileSuccessResponse } from "./quran/DeleteAyahAudioFileSuccessResponse.ts";
export type { QuranDeleteAyahSuccessResponse } from "./quran/DeleteAyahSuccessResponse.ts";
export type { QuranDeleteBookmarkAyahSuccessResponse } from "./quran/DeleteBookmarkAyahSuccessResponse.ts";
export type { QuranDeleteLastReadSuccessResponse } from "./quran/DeleteLastReadSuccessResponse.ts";
export type { QuranDeleteProgressHatamSuccessResponse } from "./quran/DeleteProgressHatamSuccessResponse.ts";
export type { QuranDeleteReciterSuccessResponse } from "./quran/DeleteReciterSuccessResponse.ts";
export type { QuranDeleteSurahSuccessResponse } from "./quran/DeleteSurahSuccessResponse.ts";
export type { QuranGetAllSurahsSuccessResponse } from "./quran/GetAllSurahsSuccessResponse.ts";
export type { QuranGetAyahByIdSuccessResponse } from "./quran/GetAyahByIdSuccessResponse.ts";
export type { QuranGetAyahsByJuzSuccessResponse } from "./quran/GetAyahsByJuzSuccessResponse.ts";
export type { QuranGetAyahsBySurahSuccessResponse } from "./quran/GetAyahsBySurahSuccessResponse.ts";
export type { QuranGetAyahsBySurahWithTranslationsSuccessResponse } from "./quran/GetAyahsBySurahWithTranslationsSuccessResponse.ts";
export type { QuranGetAyahTranslationListSuccessResponse } from "./quran/GetAyahTranslationListSuccessResponse.ts";
export type { QuranGetAyahTranslationSuccessResponse } from "./quran/GetAyahTranslationSuccessResponse.ts";
export type { QuranGetSurahByIdSuccessResponse } from "./quran/GetSurahByIdSuccessResponse.ts";
export type { QuranGetSurahByNumberSuccessResponse } from "./quran/GetSurahByNumberSuccessResponse.ts";
export type { QuranGetTranslationEditionListSuccessResponse } from "./quran/GetTranslationEditionListSuccessResponse.ts";
export type { QuranJuzListSuccessResponse } from "./quran/JuzListSuccessResponse.ts";
export type { QuranJuzSuccessResponse } from "./quran/JuzSuccessResponse.ts";
export type { QuranJuzWithProgressListSuccessResponse } from "./quran/JuzWithProgressListSuccessResponse.ts";
export type { QuranLastReadListSuccessResponse } from "./quran/LastReadListSuccessResponse.ts";
export type { QuranLastReadSuccessResponse } from "./quran/LastReadSuccessResponse.ts";
export type { QuranProgressHatamListSuccessResponse } from "./quran/ProgressHatamListSuccessResponse.ts";
export type { QuranProgressHatamSuccessResponse } from "./quran/ProgressHatamSuccessResponse.ts";
export type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";
export type { QuranReciterListSuccessResponse } from "./quran/ReciterListSuccessResponse.ts";
export type { QuranReciterSuccessResponse } from "./quran/ReciterSuccessResponse.ts";
export type { QuranUpdateAyahAudioFileSuccessResponse } from "./quran/UpdateAyahAudioFileSuccessResponse.ts";
export type { QuranUpdateAyahSuccessResponse } from "./quran/UpdateAyahSuccessResponse.ts";
export type { QuranUpdateReciterSuccessResponse } from "./quran/UpdateReciterSuccessResponse.ts";
export type { QuranUpdateSurahSuccessResponse } from "./quran/UpdateSurahSuccessResponse.ts";
export { getQuranAyahsIdQueryParamsIncludeEnum } from "./GetQuranAyahsId.ts";
export { getQuranAyahsSurahSurahidQueryParamsIncludeEnum } from "./GetQuranAyahsSurahSurahid.ts";
export { getQuranBookmarksAyahsAyahAyahidQueryParamsIncludeEnum } from "./GetQuranBookmarksAyahsAyahAyahid.ts";
export { getQuranBookmarksAyahsIdQueryParamsIncludeEnum } from "./GetQuranBookmarksAyahsId.ts";
export { getQuranJuzQueryParamsIncludeEnum } from "./GetQuranJuz.ts";
export { getQuranJuzIdQueryParamsIncludeEnum } from "./GetQuranJuzId.ts";
export { getQuranJuzNumberQueryParamsIncludeEnum } from "./GetQuranJuzNumberNumber.ts";
export { getQuranJuzWithProgressQueryParamsIncludeEnum } from "./GetQuranJuzWithProgress.ts";
export { getQuranLastReadsQueryParamsIncludeEnum } from "./GetQuranLastReads.ts";
export { getQuranLastReadsIdQueryParamsIncludeEnum } from "./GetQuranLastReadsId.ts";
export { getQuranLastReadsSurahSurahidQueryParamsIncludeEnum } from "./GetQuranLastReadsSurahSurahid.ts";
export { getQuranProgressHatamQueryParamsIncludeEnum } from "./GetQuranProgressHatam.ts";
export { getQuranProgressHatamIdQueryParamsIncludeEnum } from "./GetQuranProgressHatamId.ts";
export { getQuranProgressHatamJuzJuzidQueryParamsIncludeEnum } from "./GetQuranProgressHatamJuzJuzid.ts";
export { getQuranSurahsQueryParamsIncludeEnum } from "./GetQuranSurahs.ts";
export { getQuranSurahsIdQueryParamsIncludeEnum } from "./GetQuranSurahsId.ts";
export { getQuranSurahsNumberQueryParamsIncludeEnum } from "./GetQuranSurahsNumberNumber.ts";