/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoCreateSurahRequest } from "./dto/CreateSurahRequest.ts";
import type { QuranCreateSurahSuccessResponse } from "./quran/CreateSurahSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

/**
 * @description Surah created successfully
*/
export type PostQuranSurahs201 = QuranCreateSurahSuccessResponse;

/**
 * @description Bad request
*/
export type PostQuranSurahs400 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type PostQuranSurahs500 = QuranQuranErrorResponse;

/**
 * @description Create surah request
*/
export type PostQuranSurahsMutationRequest = DtoCreateSurahRequest;

export type PostQuranSurahsMutationResponse = PostQuranSurahs201;

export type PostQuranSurahsMutation = {
    Response: PostQuranSurahs201;
    Request: PostQuranSurahsMutationRequest;
    Errors: PostQuranSurahs400 | PostQuranSurahs500;
};