/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoCreateAyahRequest } from "./dto/CreateAyahRequest.ts";
import type { QuranCreateAyahSuccessResponse } from "./quran/CreateAyahSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

/**
 * @description Ayah created successfully
*/
export type PostQuranAyahs201 = QuranCreateAyahSuccessResponse;

/**
 * @description Bad request
*/
export type PostQuranAyahs400 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type PostQuranAyahs500 = QuranQuranErrorResponse;

/**
 * @description Create ayah request
*/
export type PostQuranAyahsMutationRequest = DtoCreateAyahRequest;

export type PostQuranAyahsMutationResponse = PostQuranAyahs201;

export type PostQuranAyahsMutation = {
    Response: PostQuranAyahs201;
    Request: PostQuranAyahsMutationRequest;
    Errors: PostQuranAyahs400 | PostQuranAyahs500;
};