/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoCreateLastReadRequest } from "./dto/CreateLastReadRequest.ts";
import type { QuranLastReadSuccessResponse } from "./quran/LastReadSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

/**
 * @description Last read created successfully
*/
export type PostQuranLastReads201 = QuranLastReadSuccessResponse;

/**
 * @description Bad request
*/
export type PostQuranLastReads400 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type PostQuranLastReads500 = QuranQuranErrorResponse;

/**
 * @description LastRead information
*/
export type PostQuranLastReadsMutationRequest = DtoCreateLastReadRequest;

export type PostQuranLastReadsMutationResponse = PostQuranLastReads201;

export type PostQuranLastReadsMutation = {
    Response: PostQuranLastReads201;
    Request: PostQuranLastReadsMutationRequest;
    Errors: PostQuranLastReads400 | PostQuranLastReads500;
};