/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoCreateProgressHatamRequest } from "./dto/CreateProgressHatamRequest.ts";
import type { QuranProgressHatamSuccessResponse } from "./quran/ProgressHatamSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

/**
 * @description Progress hatam created successfully
*/
export type PostQuranProgressHatam201 = QuranProgressHatamSuccessResponse;

/**
 * @description Bad request
*/
export type PostQuranProgressHatam400 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type PostQuranProgressHatam500 = QuranQuranErrorResponse;

/**
 * @description ProgressHatam information
*/
export type PostQuranProgressHatamMutationRequest = DtoCreateProgressHatamRequest;

export type PostQuranProgressHatamMutationResponse = PostQuranProgressHatam201;

export type PostQuranProgressHatamMutation = {
    Response: PostQuranProgressHatam201;
    Request: PostQuranProgressHatamMutationRequest;
    Errors: PostQuranProgressHatam400 | PostQuranProgressHatam500;
};