/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoCreateAyahAudioFileRequest } from "./dto/CreateAyahAudioFileRequest.ts";
import type { QuranCreateAyahAudioFileSuccessResponse } from "./quran/CreateAyahAudioFileSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

/**
 * @description Ayah audio file created successfully
*/
export type PostQuranAudioAyahs201 = QuranCreateAyahAudioFileSuccessResponse;

/**
 * @description Bad request
*/
export type PostQuranAudioAyahs400 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type PostQuranAudioAyahs500 = QuranQuranErrorResponse;

/**
 * @description Create ayah audio file request
*/
export type PostQuranAudioAyahsMutationRequest = DtoCreateAyahAudioFileRequest;

export type PostQuranAudioAyahsMutationResponse = PostQuranAudioAyahs201;

export type PostQuranAudioAyahsMutation = {
    Response: PostQuranAudioAyahs201;
    Request: PostQuranAudioAyahsMutationRequest;
    Errors: PostQuranAudioAyahs400 | PostQuranAudioAyahs500;
};