/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoCreateReciterRequest } from "./dto/CreateReciterRequest.ts";
import type { QuranCreateReciterSuccessResponse } from "./quran/CreateReciterSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

/**
 * @description Reciter created successfully
*/
export type PostQuranReciters201 = QuranCreateReciterSuccessResponse;

/**
 * @description Bad request
*/
export type PostQuranReciters400 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type PostQuranReciters500 = QuranQuranErrorResponse;

/**
 * @description Create reciter request
*/
export type PostQuranRecitersMutationRequest = DtoCreateReciterRequest;

export type PostQuranRecitersMutationResponse = PostQuranReciters201;

export type PostQuranRecitersMutation = {
    Response: PostQuranReciters201;
    Request: PostQuranRecitersMutationRequest;
    Errors: PostQuranReciters400 | PostQuranReciters500;
};