/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoCreateJuzRequest } from "./dto/CreateJuzRequest.ts";
import type { QuranJuzSuccessResponse } from "./quran/JuzSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

/**
 * @description Juz created successfully
*/
export type PostQuranJuz201 = QuranJuzSuccessResponse;

/**
 * @description Bad request
*/
export type PostQuranJuz400 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type PostQuranJuz500 = QuranQuranErrorResponse;

/**
 * @description Juz information
*/
export type PostQuranJuzMutationRequest = DtoCreateJuzRequest;

export type PostQuranJuzMutationResponse = PostQuranJuz201;

export type PostQuranJuzMutation = {
    Response: PostQuranJuz201;
    Request: PostQuranJuzMutationRequest;
    Errors: PostQuranJuz400 | PostQuranJuz500;
};