/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoCreateBookmarkAyahRequest } from "./dto/CreateBookmarkAyahRequest.ts";
import type { QuranBookmarkAyahSuccessResponse } from "./quran/BookmarkAyahSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

/**
 * @description Bookmark created successfully
*/
export type PostQuranBookmarksAyahs201 = QuranBookmarkAyahSuccessResponse;

/**
 * @description Bad request
*/
export type PostQuranBookmarksAyahs400 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type PostQuranBookmarksAyahs500 = QuranQuranErrorResponse;

/**
 * @description Create bookmark request
*/
export type PostQuranBookmarksAyahsMutationRequest = DtoCreateBookmarkAyahRequest;

export type PostQuranBookmarksAyahsMutationResponse = PostQuranBookmarksAyahs201;

export type PostQuranBookmarksAyahsMutation = {
    Response: PostQuranBookmarksAyahs201;
    Request: PostQuranBookmarksAyahsMutationRequest;
    Errors: PostQuranBookmarksAyahs400 | PostQuranBookmarksAyahs500;
};