/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoUpdateAyahAudioFileRequest } from "./dto/UpdateAyahAudioFileRequest.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";
import type { QuranUpdateAyahAudioFileSuccessResponse } from "./quran/UpdateAyahAudioFileSuccessResponse.ts";

export type PutQuranAudioAyahsIdPathParams = {
    /**
     * @description Ayah audio file ID
     * @type string
    */
    id: string;
};

/**
 * @description Ayah audio file updated successfully
*/
export type PutQuranAudioAyahsId200 = QuranUpdateAyahAudioFileSuccessResponse;

/**
 * @description Bad request
*/
export type PutQuranAudioAyahsId400 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type PutQuranAudioAyahsId500 = QuranQuranErrorResponse;

/**
 * @description Update ayah audio file request
*/
export type PutQuranAudioAyahsIdMutationRequest = DtoUpdateAyahAudioFileRequest;

export type PutQuranAudioAyahsIdMutationResponse = PutQuranAudioAyahsId200;

export type PutQuranAudioAyahsIdMutation = {
    Response: PutQuranAudioAyahsId200;
    Request: PutQuranAudioAyahsIdMutationRequest;
    PathParams: PutQuranAudioAyahsIdPathParams;
    Errors: PutQuranAudioAyahsId400 | PutQuranAudioAyahsId500;
};