/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoUpdateReciterRequest } from "./dto/UpdateReciterRequest.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";
import type { QuranUpdateReciterSuccessResponse } from "./quran/UpdateReciterSuccessResponse.ts";

export type PutQuranRecitersIdPathParams = {
    /**
     * @description Reciter ID
     * @type string
    */
    id: string;
};

/**
 * @description Reciter updated successfully
*/
export type PutQuranRecitersId200 = QuranUpdateReciterSuccessResponse;

/**
 * @description Bad request
*/
export type PutQuranRecitersId400 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type PutQuranRecitersId500 = QuranQuranErrorResponse;

/**
 * @description Update reciter request
*/
export type PutQuranRecitersIdMutationRequest = DtoUpdateReciterRequest;

export type PutQuranRecitersIdMutationResponse = PutQuranRecitersId200;

export type PutQuranRecitersIdMutation = {
    Response: PutQuranRecitersId200;
    Request: PutQuranRecitersIdMutationRequest;
    PathParams: PutQuranRecitersIdPathParams;
    Errors: PutQuranRecitersId400 | PutQuranRecitersId500;
};