/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoUpdateJuzRequest } from "./dto/UpdateJuzRequest.ts";
import type { QuranJuzSuccessResponse } from "./quran/JuzSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type PutQuranJuzIdPathParams = {
    /**
     * @description Juz ID
     * @type string
    */
    id: string;
};

/**
 * @description Juz updated successfully
*/
export type PutQuranJuzId200 = QuranJuzSuccessResponse;

/**
 * @description Bad request
*/
export type PutQuranJuzId400 = QuranQuranErrorResponse;

/**
 * @description Juz not found
*/
export type PutQuranJuzId404 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type PutQuranJuzId500 = QuranQuranErrorResponse;

/**
 * @description Juz information
*/
export type PutQuranJuzIdMutationRequest = DtoUpdateJuzRequest;

export type PutQuranJuzIdMutationResponse = PutQuranJuzId200;

export type PutQuranJuzIdMutation = {
    Response: PutQuranJuzId200;
    Request: PutQuranJuzIdMutationRequest;
    PathParams: PutQuranJuzIdPathParams;
    Errors: PutQuranJuzId400 | PutQuranJuzId404 | PutQuranJuzId500;
};