/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoUpdateSurahRequest } from "./dto/UpdateSurahRequest.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";
import type { QuranUpdateSurahSuccessResponse } from "./quran/UpdateSurahSuccessResponse.ts";

export type PutQuranSurahsIdPathParams = {
    /**
     * @description Surah ID
     * @type string
    */
    id: string;
};

/**
 * @description Surah updated successfully
*/
export type PutQuranSurahsId200 = QuranUpdateSurahSuccessResponse;

/**
 * @description Bad request
*/
export type PutQuranSurahsId400 = QuranQuranErrorResponse;

/**
 * @description Surah not found
*/
export type PutQuranSurahsId404 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type PutQuranSurahsId500 = QuranQuranErrorResponse;

/**
 * @description Update surah request
*/
export type PutQuranSurahsIdMutationRequest = DtoUpdateSurahRequest;

export type PutQuranSurahsIdMutationResponse = PutQuranSurahsId200;

export type PutQuranSurahsIdMutation = {
    Response: PutQuranSurahsId200;
    Request: PutQuranSurahsIdMutationRequest;
    PathParams: PutQuranSurahsIdPathParams;
    Errors: PutQuranSurahsId400 | PutQuranSurahsId404 | PutQuranSurahsId500;
};