/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoUpdateLastReadRequest } from "./dto/UpdateLastReadRequest.ts";
import type { QuranLastReadSuccessResponse } from "./quran/LastReadSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type PutQuranLastReadsIdPathParams = {
    /**
     * @description LastRead ID
     * @type string
    */
    id: string;
};

/**
 * @description Last read updated successfully
*/
export type PutQuranLastReadsId200 = QuranLastReadSuccessResponse;

/**
 * @description Bad request
*/
export type PutQuranLastReadsId400 = QuranQuranErrorResponse;

/**
 * @description Last read not found
*/
export type PutQuranLastReadsId404 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type PutQuranLastReadsId500 = QuranQuranErrorResponse;

/**
 * @description LastRead update information
*/
export type PutQuranLastReadsIdMutationRequest = DtoUpdateLastReadRequest;

export type PutQuranLastReadsIdMutationResponse = PutQuranLastReadsId200;

export type PutQuranLastReadsIdMutation = {
    Response: PutQuranLastReadsId200;
    Request: PutQuranLastReadsIdMutationRequest;
    PathParams: PutQuranLastReadsIdPathParams;
    Errors: PutQuranLastReadsId400 | PutQuranLastReadsId404 | PutQuranLastReadsId500;
};