/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoUpdateAyahRequest } from "./dto/UpdateAyahRequest.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";
import type { QuranUpdateAyahSuccessResponse } from "./quran/UpdateAyahSuccessResponse.ts";

export type PutQuranAyahsIdPathParams = {
    /**
     * @description Ayah ID
     * @type string
    */
    id: string;
};

/**
 * @description Ayah updated successfully
*/
export type PutQuranAyahsId200 = QuranUpdateAyahSuccessResponse;

/**
 * @description Bad request
*/
export type PutQuranAyahsId400 = QuranQuranErrorResponse;

/**
 * @description Ayah not found
*/
export type PutQuranAyahsId404 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type PutQuranAyahsId500 = QuranQuranErrorResponse;

/**
 * @description Update ayah request
*/
export type PutQuranAyahsIdMutationRequest = DtoUpdateAyahRequest;

export type PutQuranAyahsIdMutationResponse = PutQuranAyahsId200;

export type PutQuranAyahsIdMutation = {
    Response: PutQuranAyahsId200;
    Request: PutQuranAyahsIdMutationRequest;
    PathParams: PutQuranAyahsIdPathParams;
    Errors: PutQuranAyahsId400 | PutQuranAyahsId404 | PutQuranAyahsId500;
};