/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoUpdateProgressHatamRequest } from "./dto/UpdateProgressHatamRequest.ts";
import type { QuranProgressHatamSuccessResponse } from "./quran/ProgressHatamSuccessResponse.ts";
import type { QuranQuranErrorResponse } from "./quran/QuranErrorResponse.ts";

export type PutQuranProgressHatamIdPathParams = {
    /**
     * @description ProgressHatam ID
     * @type string
    */
    id: string;
};

/**
 * @description Progress hatam updated successfully
*/
export type PutQuranProgressHatamId200 = QuranProgressHatamSuccessResponse;

/**
 * @description Bad request
*/
export type PutQuranProgressHatamId400 = QuranQuranErrorResponse;

/**
 * @description Progress hatam not found
*/
export type PutQuranProgressHatamId404 = QuranQuranErrorResponse;

/**
 * @description Internal server error
*/
export type PutQuranProgressHatamId500 = QuranQuranErrorResponse;

/**
 * @description ProgressHatam update information
*/
export type PutQuranProgressHatamIdMutationRequest = DtoUpdateProgressHatamRequest;

export type PutQuranProgressHatamIdMutationResponse = PutQuranProgressHatamId200;

export type PutQuranProgressHatamIdMutation = {
    Response: PutQuranProgressHatamId200;
    Request: PutQuranProgressHatamIdMutationRequest;
    PathParams: PutQuranProgressHatamIdPathParams;
    Errors: PutQuranProgressHatamId400 | PutQuranProgressHatamId404 | PutQuranProgressHatamId500;
};