/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranAyahAudioFileListSuccessResponse } from "../../types/quran/AyahAudioFileListSuccessResponse.ts";
import { dtoAyahAudioFileListResponseSchema } from "../dto/ayahAudioFileListResponseSchema.ts";
import { z } from "zod";

export const quranAyahAudioFileListSuccessResponseSchema = z.object({
    get "data"(){
                return dtoAyahAudioFileListResponseSchema.optional()
              },
"message": z.optional(z.string()),
"responseTime": z.optional(z.string()),
"status_code": z.optional(z.int()),
"success": z.optional(z.boolean()),
"timestamp": z.optional(z.string())
    }) as unknown as z.ZodType<QuranAyahAudioFileListSuccessResponse>