/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranBookmarkAyahListSuccessResponse } from "../../types/quran/BookmarkAyahListSuccessResponse.ts";
import { dtoBookmarkAyahListResponseSchema } from "../dto/bookmarkAyahListResponseSchema.ts";
import { z } from "zod";

export const quranBookmarkAyahListSuccessResponseSchema = z.object({
    get "data"(){
                return dtoBookmarkAyahListResponseSchema.optional()
              },
"message": z.optional(z.string()),
"responseTime": z.optional(z.string()),
"status_code": z.optional(z.int()),
"success": z.optional(z.boolean()),
"timestamp": z.optional(z.string())
    }) as unknown as z.ZodType<QuranBookmarkAyahListSuccessResponse>