/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranBookmarkAyahSuccessResponse } from "../../types/quran/BookmarkAyahSuccessResponse.ts";
import { dtoBookmarkAyahResponseSchema } from "../dto/bookmarkAyahResponseSchema.ts";
import { z } from "zod";

export const quranBookmarkAyahSuccessResponseSchema = z.object({
    get "data"(){
                return dtoBookmarkAyahResponseSchema.optional()
              },
"message": z.optional(z.string()),
"responseTime": z.optional(z.string()),
"status_code": z.optional(z.int()),
"success": z.optional(z.boolean()),
"timestamp": z.optional(z.string())
    }) as unknown as z.ZodType<QuranBookmarkAyahSuccessResponse>