/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranCreateAyahAudioFileSuccessResponse } from "../../types/quran/CreateAyahAudioFileSuccessResponse.ts";
import { dtoAyahAudioFileResponseSchema } from "../dto/ayahAudioFileResponseSchema.ts";
import { z } from "zod";

export const quranCreateAyahAudioFileSuccessResponseSchema = z.object({
    get "data"(){
                return dtoAyahAudioFileResponseSchema.optional()
              },
"message": z.optional(z.string()),
"responseTime": z.optional(z.string()),
"status_code": z.optional(z.int()),
"success": z.optional(z.boolean()),
"timestamp": z.optional(z.string())
    }) as unknown as z.ZodType<QuranCreateAyahAudioFileSuccessResponse>