/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranCreateAyahSuccessResponse } from "../../types/quran/CreateAyahSuccessResponse.ts";
import { dtoAyahResponseSchema } from "../dto/ayahResponseSchema.ts";
import { z } from "zod";

export const quranCreateAyahSuccessResponseSchema = z.object({
    get "data"(){
                return dtoAyahResponseSchema.optional()
              },
"message": z.optional(z.string()),
"responseTime": z.optional(z.string()),
"status_code": z.optional(z.int()),
"success": z.optional(z.boolean()),
"timestamp": z.optional(z.string())
    }) as unknown as z.ZodType<QuranCreateAyahSuccessResponse>