/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranDeleteSurahSuccessResponse } from "../../types/quran/DeleteSurahSuccessResponse.ts";
import { z } from "zod";

export const quranDeleteSurahSuccessResponseSchema = z.object({
    "data": z.optional(z.string()),
"message": z.optional(z.string()),
"responseTime": z.optional(z.string()),
"status_code": z.optional(z.int()),
"success": z.optional(z.boolean()),
"timestamp": z.optional(z.string())
    }) as unknown as z.ZodType<QuranDeleteSurahSuccessResponse>