/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranGetAyahTranslationListSuccessResponse } from "../../types/quran/GetAyahTranslationListSuccessResponse.ts";
import { dtoAyahTranslationListResponseSchema } from "../dto/ayahTranslationListResponseSchema.ts";
import { z } from "zod";

export const quranGetAyahTranslationListSuccessResponseSchema = z.object({
    get "data"(){
                return dtoAyahTranslationListResponseSchema.optional()
              },
"message": z.optional(z.string()),
"responseTime": z.optional(z.string()),
"status_code": z.optional(z.int()),
"success": z.optional(z.boolean()),
"timestamp": z.optional(z.string())
    }) as unknown as z.ZodType<QuranGetAyahTranslationListSuccessResponse>