/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranGetAllSurahsSuccessResponse } from "../../types/quran/GetAllSurahsSuccessResponse.ts";
import { dtoSurahListResponseSchema } from "../dto/surahListResponseSchema.ts";
import { z } from "zod";

export const quranGetAllSurahsSuccessResponseSchema = z.object({
    get "data"(){
                return dtoSurahListResponseSchema.optional()
              },
"message": z.optional(z.string()),
"responseTime": z.optional(z.string()),
"status_code": z.optional(z.int()),
"success": z.optional(z.boolean()),
"timestamp": z.optional(z.string())
    }) as unknown as z.ZodType<QuranGetAllSurahsSuccessResponse>