/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranGetAyahsBySurahWithTranslationsSuccessResponse } from "../../types/quran/GetAyahsBySurahWithTranslationsSuccessResponse.ts";
import { dtoSurahAyahsWithTranslationsResponseSchema } from "../dto/surahAyahsWithTranslationsResponseSchema.ts";
import { z } from "zod";

export const quranGetAyahsBySurahWithTranslationsSuccessResponseSchema = z.object({
    get "data"(){
                return dtoSurahAyahsWithTranslationsResponseSchema.optional()
              },
"message": z.optional(z.string()),
"responseTime": z.optional(z.string()),
"status_code": z.optional(z.int()),
"success": z.optional(z.boolean()),
"timestamp": z.optional(z.string())
    }) as unknown as z.ZodType<QuranGetAyahsBySurahWithTranslationsSuccessResponse>