/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranGetAyahTranslationSuccessResponse } from "../../types/quran/GetAyahTranslationSuccessResponse.ts";
import { dtoAyahTranslationResponseSchema } from "../dto/ayahTranslationResponseSchema.ts";
import { z } from "zod";

export const quranGetAyahTranslationSuccessResponseSchema = z.object({
    get "data"(){
                return dtoAyahTranslationResponseSchema.optional()
              },
"message": z.optional(z.string()),
"responseTime": z.optional(z.string()),
"status_code": z.optional(z.int()),
"success": z.optional(z.boolean()),
"timestamp": z.optional(z.string())
    }) as unknown as z.ZodType<QuranGetAyahTranslationSuccessResponse>