/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranGetAyahsBySurahSuccessResponse } from "../../types/quran/GetAyahsBySurahSuccessResponse.ts";
import { dtoAyahListResponseSchema } from "../dto/ayahListResponseSchema.ts";
import { z } from "zod";

export const quranGetAyahsBySurahSuccessResponseSchema = z.object({
    get "data"(){
                return dtoAyahListResponseSchema.optional()
              },
"message": z.optional(z.string()),
"responseTime": z.optional(z.string()),
"status_code": z.optional(z.int()),
"success": z.optional(z.boolean()),
"timestamp": z.optional(z.string())
    }) as unknown as z.ZodType<QuranGetAyahsBySurahSuccessResponse>