/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranGetSurahByIdSuccessResponse } from "../../types/quran/GetSurahByIdSuccessResponse.ts";
import { dtoSurahResponseSchema } from "../dto/surahResponseSchema.ts";
import { z } from "zod";

export const quranGetSurahByIdSuccessResponseSchema = z.object({
    get "data"(){
                return dtoSurahResponseSchema.optional()
              },
"message": z.optional(z.string()),
"responseTime": z.optional(z.string()),
"status_code": z.optional(z.int()),
"success": z.optional(z.boolean()),
"timestamp": z.optional(z.string())
    }) as unknown as z.ZodType<QuranGetSurahByIdSuccessResponse>