/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranGetTranslationEditionListSuccessResponse } from "../../types/quran/GetTranslationEditionListSuccessResponse.ts";
import { dtoTranslationEditionListResponseSchema } from "../dto/translationEditionListResponseSchema.ts";
import { z } from "zod";

export const quranGetTranslationEditionListSuccessResponseSchema = z.object({
    get "data"(){
                return dtoTranslationEditionListResponseSchema.optional()
              },
"message": z.optional(z.string()),
"responseTime": z.optional(z.string()),
"status_code": z.optional(z.int()),
"success": z.optional(z.boolean()),
"timestamp": z.optional(z.string())
    }) as unknown as z.ZodType<QuranGetTranslationEditionListSuccessResponse>