/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranJuzListSuccessResponse } from "../../types/quran/JuzListSuccessResponse.ts";
import { dtoJuzListResponseSchema } from "../dto/juzListResponseSchema.ts";
import { z } from "zod";

export const quranJuzListSuccessResponseSchema = z.object({
    get "data"(){
                return dtoJuzListResponseSchema.optional()
              },
"message": z.optional(z.string()),
"responseTime": z.optional(z.string()),
"status_code": z.optional(z.int()),
"success": z.optional(z.boolean()),
"timestamp": z.optional(z.string())
    }) as unknown as z.ZodType<QuranJuzListSuccessResponse>