/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranJuzWithProgressListSuccessResponse } from "../../types/quran/JuzWithProgressListSuccessResponse.ts";
import { dtoJuzWithProgressBasicListResponseSchema } from "../dto/juzWithProgressBasicListResponseSchema.ts";
import { z } from "zod";

export const quranJuzWithProgressListSuccessResponseSchema = z.object({
    get "data"(){
                return dtoJuzWithProgressBasicListResponseSchema.optional()
              },
"message": z.optional(z.string()),
"responseTime": z.optional(z.string()),
"status_code": z.optional(z.int()),
"success": z.optional(z.boolean()),
"timestamp": z.optional(z.string())
    }) as unknown as z.ZodType<QuranJuzWithProgressListSuccessResponse>