/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranLastReadSuccessResponse } from "../../types/quran/LastReadSuccessResponse.ts";
import { dtoLastReadResponseSchema } from "../dto/lastReadResponseSchema.ts";
import { z } from "zod";

export const quranLastReadSuccessResponseSchema = z.object({
    get "data"(){
                return dtoLastReadResponseSchema.optional()
              },
"message": z.optional(z.string()),
"responseTime": z.optional(z.string()),
"status_code": z.optional(z.int()),
"success": z.optional(z.boolean()),
"timestamp": z.optional(z.string())
    }) as unknown as z.ZodType<QuranLastReadSuccessResponse>