/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranLastReadListSuccessResponse } from "../../types/quran/LastReadListSuccessResponse.ts";
import { dtoLastReadListResponseSchema } from "../dto/lastReadListResponseSchema.ts";
import { z } from "zod";

export const quranLastReadListSuccessResponseSchema = z.object({
    get "data"(){
                return dtoLastReadListResponseSchema.optional()
              },
"message": z.optional(z.string()),
"responseTime": z.optional(z.string()),
"status_code": z.optional(z.int()),
"success": z.optional(z.boolean()),
"timestamp": z.optional(z.string())
    }) as unknown as z.ZodType<QuranLastReadListSuccessResponse>