/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranProgressHatamSuccessResponse } from "../../types/quran/ProgressHatamSuccessResponse.ts";
import { dtoProgressHatamResponseSchema } from "../dto/progressHatamResponseSchema.ts";
import { z } from "zod";

export const quranProgressHatamSuccessResponseSchema = z.object({
    get "data"(){
                return dtoProgressHatamResponseSchema.optional()
              },
"message": z.optional(z.string()),
"responseTime": z.optional(z.string()),
"status_code": z.optional(z.int()),
"success": z.optional(z.boolean()),
"timestamp": z.optional(z.string())
    }) as unknown as z.ZodType<QuranProgressHatamSuccessResponse>