/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranProgressHatamListSuccessResponse } from "../../types/quran/ProgressHatamListSuccessResponse.ts";
import { dtoProgressHatamListResponseSchema } from "../dto/progressHatamListResponseSchema.ts";
import { z } from "zod";

export const quranProgressHatamListSuccessResponseSchema = z.object({
    get "data"(){
                return dtoProgressHatamListResponseSchema.optional()
              },
"message": z.optional(z.string()),
"responseTime": z.optional(z.string()),
"status_code": z.optional(z.int()),
"success": z.optional(z.boolean()),
"timestamp": z.optional(z.string())
    }) as unknown as z.ZodType<QuranProgressHatamListSuccessResponse>