/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranQuranErrorResponse } from "../../types/quran/QuranErrorResponse.ts";
import { coreErrorDetailSchema } from "../core/errorDetailSchema.ts";
import { z } from "zod";

export const quranQuranErrorResponseSchema = z.object({
    get "errors"(){
                return coreErrorDetailSchema.optional()
              },
"message": z.optional(z.string()),
"responseTime": z.optional(z.string()),
"status_code": z.optional(z.int()),
"success": z.optional(z.boolean()),
"timestamp": z.optional(z.string())
    }) as unknown as z.ZodType<QuranQuranErrorResponse>