/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranReciterListSuccessResponse } from "../../types/quran/ReciterListSuccessResponse.ts";
import { dtoReciterListResponseSchema } from "../dto/reciterListResponseSchema.ts";
import { z } from "zod";

export const quranReciterListSuccessResponseSchema = z.object({
    get "data"(){
                return dtoReciterListResponseSchema.optional()
              },
"message": z.optional(z.string()),
"responseTime": z.optional(z.string()),
"status_code": z.optional(z.int()),
"success": z.optional(z.boolean()),
"timestamp": z.optional(z.string())
    }) as unknown as z.ZodType<QuranReciterListSuccessResponse>