/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuranReciterSuccessResponse } from "../../types/quran/ReciterSuccessResponse.ts";
import { dtoReciterResponseSchema } from "../dto/reciterResponseSchema.ts";
import { z } from "zod";

export const quranReciterSuccessResponseSchema = z.object({
    get "data"(){
                return dtoReciterResponseSchema.optional()
              },
"message": z.optional(z.string()),
"responseTime": z.optional(z.string()),
"status_code": z.optional(z.int()),
"success": z.optional(z.boolean()),
"timestamp": z.optional(z.string())
    }) as unknown as z.ZodType<QuranReciterSuccessResponse>