/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeleteQuranJuzIdPathParams, DeleteQuranJuzId200, DeleteQuranJuzId400, DeleteQuranJuzId404, DeleteQuranJuzId500, DeleteQuranJuzIdMutationResponse } from "../../types/DeleteQuranJuzId.ts";
import { quranJuzSuccessResponseSchema } from "../quran/juzSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const deleteQuranJuzIdPathParamsSchema = z.object({
    "id": z.string().describe("Juz ID")
    }) as unknown as z.ZodType<DeleteQuranJuzIdPathParams>

/**
 * @description Juz deleted successfully
 */
export const deleteQuranJuzId200Schema = quranJuzSuccessResponseSchema as unknown as z.ZodType<DeleteQuranJuzId200>

/**
 * @description Bad request
 */
export const deleteQuranJuzId400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<DeleteQuranJuzId400>

/**
 * @description Juz not found
 */
export const deleteQuranJuzId404Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<DeleteQuranJuzId404>

/**
 * @description Internal server error
 */
export const deleteQuranJuzId500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<DeleteQuranJuzId500>

export const deleteQuranJuzIdMutationResponseSchema = deleteQuranJuzId200Schema as unknown as z.ZodType<DeleteQuranJuzIdMutationResponse>