/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetQuranJuzWithProgressQueryParams, GetQuranJuzWithProgress200, GetQuranJuzWithProgress400, GetQuranJuzWithProgress500, GetQuranJuzWithProgressQueryResponse } from "../../types/GetQuranJuzWithProgress.ts";
import { quranJuzWithProgressListSuccessResponseSchema } from "../quran/juzWithProgressListSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const getQuranJuzWithProgressQueryParamsSchema = z.object({
    "limit": z.optional(z.coerce.number().int().describe("Limit")),
"offset": z.optional(z.coerce.number().int().describe("Offset")),
"include": z.optional(z.enum(["relations"]).describe("Include related data"))
    }).optional() as unknown as z.ZodType<GetQuranJuzWithProgressQueryParams>

/**
 * @description OK
 */
export const getQuranJuzWithProgress200Schema = quranJuzWithProgressListSuccessResponseSchema as unknown as z.ZodType<GetQuranJuzWithProgress200>

/**
 * @description Bad request
 */
export const getQuranJuzWithProgress400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranJuzWithProgress400>

/**
 * @description Internal server error
 */
export const getQuranJuzWithProgress500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranJuzWithProgress500>

export const getQuranJuzWithProgressQueryResponseSchema = getQuranJuzWithProgress200Schema as unknown as z.ZodType<GetQuranJuzWithProgressQueryResponse>