/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetQuranJuzIdPathParams, GetQuranJuzIdQueryParams, GetQuranJuzId200, GetQuranJuzId400, GetQuranJuzId404, GetQuranJuzId500, GetQuranJuzIdQueryResponse } from "../../types/GetQuranJuzId.ts";
import { quranJuzSuccessResponseSchema } from "../quran/juzSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const getQuranJuzIdPathParamsSchema = z.object({
    "id": z.string().describe("Juz ID")
    }) as unknown as z.ZodType<GetQuranJuzIdPathParams>

export const getQuranJuzIdQueryParamsSchema = z.object({
    "include": z.optional(z.enum(["relations"]).describe("Include related data"))
    }).optional() as unknown as z.ZodType<GetQuranJuzIdQueryParams>

/**
 * @description Juz retrieved successfully
 */
export const getQuranJuzId200Schema = quranJuzSuccessResponseSchema as unknown as z.ZodType<GetQuranJuzId200>

/**
 * @description Bad request
 */
export const getQuranJuzId400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranJuzId400>

/**
 * @description Juz not found
 */
export const getQuranJuzId404Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranJuzId404>

/**
 * @description Internal server error
 */
export const getQuranJuzId500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranJuzId500>

export const getQuranJuzIdQueryResponseSchema = getQuranJuzId200Schema as unknown as z.ZodType<GetQuranJuzIdQueryResponse>