/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetQuranJuzQueryParams, GetQuranJuz200, GetQuranJuz400, GetQuranJuz500, GetQuranJuzQueryResponse } from "../../types/GetQuranJuz.ts";
import { quranJuzListSuccessResponseSchema } from "../quran/juzListSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const getQuranJuzQueryParamsSchema = z.object({
    "limit": z.coerce.number().int().default(0).describe("Limit (0 for all)"),
"offset": z.coerce.number().int().default(0).describe("Offset"),
"include": z.optional(z.enum(["relations"]).describe("Include related data"))
    }) as unknown as z.ZodType<GetQuranJuzQueryParams>

/**
 * @description Juz list retrieved successfully
 */
export const getQuranJuz200Schema = quranJuzListSuccessResponseSchema as unknown as z.ZodType<GetQuranJuz200>

/**
 * @description Bad request
 */
export const getQuranJuz400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranJuz400>

/**
 * @description Internal server error
 */
export const getQuranJuz500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranJuz500>

export const getQuranJuzQueryResponseSchema = getQuranJuz200Schema as unknown as z.ZodType<GetQuranJuzQueryResponse>