/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetQuranJuzNumberPathParams, GetQuranJuzNumberQueryParams, GetQuranJuzNumber200, GetQuranJuzNumber400, GetQuranJuzNumber404, GetQuranJuzNumber500, GetQuranJuzNumberQueryResponse } from "../../types/GetQuranJuzNumber.ts";
import { quranJuzSuccessResponseSchema } from "../quran/juzSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const getQuranJuzNumberPathParamsSchema = z.object({
    "number": z.coerce.number().int().describe("Juz Number")
    }) as unknown as z.ZodType<GetQuranJuzNumberPathParams>

export const getQuranJuzNumberQueryParamsSchema = z.object({
    "include": z.optional(z.enum(["relations"]).describe("Include related data"))
    }).optional() as unknown as z.ZodType<GetQuranJuzNumberQueryParams>

/**
 * @description Juz retrieved successfully
 */
export const getQuranJuzNumber200Schema = quranJuzSuccessResponseSchema as unknown as z.ZodType<GetQuranJuzNumber200>

/**
 * @description Bad request
 */
export const getQuranJuzNumber400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranJuzNumber400>

/**
 * @description Juz not found
 */
export const getQuranJuzNumber404Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranJuzNumber404>

/**
 * @description Internal server error
 */
export const getQuranJuzNumber500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranJuzNumber500>

export const getQuranJuzNumberQueryResponseSchema = getQuranJuzNumber200Schema as unknown as z.ZodType<GetQuranJuzNumberQueryResponse>