/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PostQuranJuz201, PostQuranJuz400, PostQuranJuz500, PostQuranJuzMutationRequest, PostQuranJuzMutationResponse } from "../../types/PostQuranJuz.ts";
import { dtoCreateJuzRequestSchema } from "../dto/createJuzRequestSchema.ts";
import { quranJuzSuccessResponseSchema } from "../quran/juzSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

/**
 * @description Juz created successfully
 */
export const postQuranJuz201Schema = quranJuzSuccessResponseSchema as unknown as z.ZodType<PostQuranJuz201>

/**
 * @description Bad request
 */
export const postQuranJuz400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PostQuranJuz400>

/**
 * @description Internal server error
 */
export const postQuranJuz500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PostQuranJuz500>

/**
 * @description Juz information
 */
export const postQuranJuzMutationRequestSchema = dtoCreateJuzRequestSchema as unknown as z.ZodType<PostQuranJuzMutationRequest>

export const postQuranJuzMutationResponseSchema = postQuranJuz201Schema as unknown as z.ZodType<PostQuranJuzMutationResponse>