/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PutQuranJuzIdPathParams, PutQuranJuzId200, PutQuranJuzId400, PutQuranJuzId404, PutQuranJuzId500, PutQuranJuzIdMutationRequest, PutQuranJuzIdMutationResponse } from "../../types/PutQuranJuzId.ts";
import { dtoUpdateJuzRequestSchema } from "../dto/updateJuzRequestSchema.ts";
import { quranJuzSuccessResponseSchema } from "../quran/juzSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const putQuranJuzIdPathParamsSchema = z.object({
    "id": z.string().describe("Juz ID")
    }) as unknown as z.ZodType<PutQuranJuzIdPathParams>

/**
 * @description Juz updated successfully
 */
export const putQuranJuzId200Schema = quranJuzSuccessResponseSchema as unknown as z.ZodType<PutQuranJuzId200>

/**
 * @description Bad request
 */
export const putQuranJuzId400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PutQuranJuzId400>

/**
 * @description Juz not found
 */
export const putQuranJuzId404Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PutQuranJuzId404>

/**
 * @description Internal server error
 */
export const putQuranJuzId500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PutQuranJuzId500>

/**
 * @description Juz information
 */
export const putQuranJuzIdMutationRequestSchema = dtoUpdateJuzRequestSchema as unknown as z.ZodType<PutQuranJuzIdMutationRequest>

export const putQuranJuzIdMutationResponseSchema = putQuranJuzId200Schema as unknown as z.ZodType<PutQuranJuzIdMutationResponse>