/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeleteQuranAudioAyahsIdPathParams, DeleteQuranAudioAyahsId200, DeleteQuranAudioAyahsId400, DeleteQuranAudioAyahsId500, DeleteQuranAudioAyahsIdMutationResponse } from "../../types/DeleteQuranAudioAyahsId.ts";
import { quranDeleteAyahAudioFileSuccessResponseSchema } from "../quran/deleteAyahAudioFileSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const deleteQuranAudioAyahsIdPathParamsSchema = z.object({
    "id": z.string().describe("Ayah audio file ID")
    }) as unknown as z.ZodType<DeleteQuranAudioAyahsIdPathParams>

/**
 * @description Ayah audio file deleted successfully
 */
export const deleteQuranAudioAyahsId200Schema = quranDeleteAyahAudioFileSuccessResponseSchema as unknown as z.ZodType<DeleteQuranAudioAyahsId200>

/**
 * @description Bad request
 */
export const deleteQuranAudioAyahsId400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<DeleteQuranAudioAyahsId400>

/**
 * @description Internal server error
 */
export const deleteQuranAudioAyahsId500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<DeleteQuranAudioAyahsId500>

export const deleteQuranAudioAyahsIdMutationResponseSchema = deleteQuranAudioAyahsId200Schema as unknown as z.ZodType<DeleteQuranAudioAyahsIdMutationResponse>