/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetQuranAudioAyahsIdPathParams, GetQuranAudioAyahsId200, GetQuranAudioAyahsId400, GetQuranAudioAyahsId500, GetQuranAudioAyahsIdQueryResponse } from "../../types/GetQuranAudioAyahsId.ts";
import { quranAyahAudioFileSuccessResponseSchema } from "../quran/ayahAudioFileSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const getQuranAudioAyahsIdPathParamsSchema = z.object({
    "id": z.string().describe("Ayah audio file ID")
    }) as unknown as z.ZodType<GetQuranAudioAyahsIdPathParams>

/**
 * @description Ayah audio file retrieved successfully
 */
export const getQuranAudioAyahsId200Schema = quranAyahAudioFileSuccessResponseSchema as unknown as z.ZodType<GetQuranAudioAyahsId200>

/**
 * @description Bad request
 */
export const getQuranAudioAyahsId400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranAudioAyahsId400>

/**
 * @description Internal server error
 */
export const getQuranAudioAyahsId500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranAudioAyahsId500>

export const getQuranAudioAyahsIdQueryResponseSchema = getQuranAudioAyahsId200Schema as unknown as z.ZodType<GetQuranAudioAyahsIdQueryResponse>