/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetQuranAudioAyahsAyahAyahidReciterReciteridPathParams, GetQuranAudioAyahsAyahAyahidReciterReciterid200, GetQuranAudioAyahsAyahAyahidReciterReciterid400, GetQuranAudioAyahsAyahAyahidReciterReciterid500, GetQuranAudioAyahsAyahAyahidReciterReciteridQueryResponse } from "../../types/GetQuranAudioAyahsAyahAyahidReciterReciterid.ts";
import { quranAyahAudioFileSuccessResponseSchema } from "../quran/ayahAudioFileSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const getQuranAudioAyahsAyahAyahidReciterReciteridPathParamsSchema = z.object({
    "ayahId": z.string().describe("Ayah ID"),
"reciterId": z.string().describe("Reciter ID")
    }) as unknown as z.ZodType<GetQuranAudioAyahsAyahAyahidReciterReciteridPathParams>

/**
 * @description Ayah audio file retrieved successfully
 */
export const getQuranAudioAyahsAyahAyahidReciterReciterid200Schema = quranAyahAudioFileSuccessResponseSchema as unknown as z.ZodType<GetQuranAudioAyahsAyahAyahidReciterReciterid200>

/**
 * @description Bad request
 */
export const getQuranAudioAyahsAyahAyahidReciterReciterid400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranAudioAyahsAyahAyahidReciterReciterid400>

/**
 * @description Internal server error
 */
export const getQuranAudioAyahsAyahAyahidReciterReciterid500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranAudioAyahsAyahAyahidReciterReciterid500>

export const getQuranAudioAyahsAyahAyahidReciterReciteridQueryResponseSchema = getQuranAudioAyahsAyahAyahidReciterReciterid200Schema as unknown as z.ZodType<GetQuranAudioAyahsAyahAyahidReciterReciteridQueryResponse>