/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetQuranAudioAyahsSurahSurahidReciterReciteridPathParams, GetQuranAudioAyahsSurahSurahidReciterReciteridQueryParams, GetQuranAudioAyahsSurahSurahidReciterReciterid200, GetQuranAudioAyahsSurahSurahidReciterReciterid400, GetQuranAudioAyahsSurahSurahidReciterReciterid500, GetQuranAudioAyahsSurahSurahidReciterReciteridQueryResponse } from "../../types/GetQuranAudioAyahsSurahSurahidReciterReciterid.ts";
import { quranAyahAudioFileListSuccessResponseSchema } from "../quran/ayahAudioFileListSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const getQuranAudioAyahsSurahSurahidReciterReciteridPathParamsSchema = z.object({
    "surahId": z.string().describe("Surah ID"),
"reciterId": z.string().describe("Reciter ID")
    }) as unknown as z.ZodType<GetQuranAudioAyahsSurahSurahidReciterReciteridPathParams>

export const getQuranAudioAyahsSurahSurahidReciterReciteridQueryParamsSchema = z.object({
    "limit": z.coerce.number().int().default(0).describe("Limit (0 for all)"),
"offset": z.coerce.number().int().default(0).describe("Offset")
    }) as unknown as z.ZodType<GetQuranAudioAyahsSurahSurahidReciterReciteridQueryParams>

/**
 * @description Ayah audio files retrieved successfully
 */
export const getQuranAudioAyahsSurahSurahidReciterReciterid200Schema = quranAyahAudioFileListSuccessResponseSchema as unknown as z.ZodType<GetQuranAudioAyahsSurahSurahidReciterReciterid200>

/**
 * @description Bad request
 */
export const getQuranAudioAyahsSurahSurahidReciterReciterid400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranAudioAyahsSurahSurahidReciterReciterid400>

/**
 * @description Internal server error
 */
export const getQuranAudioAyahsSurahSurahidReciterReciterid500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranAudioAyahsSurahSurahidReciterReciterid500>

export const getQuranAudioAyahsSurahSurahidReciterReciteridQueryResponseSchema = getQuranAudioAyahsSurahSurahidReciterReciterid200Schema as unknown as z.ZodType<GetQuranAudioAyahsSurahSurahidReciterReciteridQueryResponse>