/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PostQuranAudioAyahs201, PostQuranAudioAyahs400, PostQuranAudioAyahs500, PostQuranAudioAyahsMutationRequest, PostQuranAudioAyahsMutationResponse } from "../../types/PostQuranAudioAyahs.ts";
import { dtoCreateAyahAudioFileRequestSchema } from "../dto/createAyahAudioFileRequestSchema.ts";
import { quranCreateAyahAudioFileSuccessResponseSchema } from "../quran/createAyahAudioFileSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

/**
 * @description Ayah audio file created successfully
 */
export const postQuranAudioAyahs201Schema = quranCreateAyahAudioFileSuccessResponseSchema as unknown as z.ZodType<PostQuranAudioAyahs201>

/**
 * @description Bad request
 */
export const postQuranAudioAyahs400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PostQuranAudioAyahs400>

/**
 * @description Internal server error
 */
export const postQuranAudioAyahs500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PostQuranAudioAyahs500>

/**
 * @description Create ayah audio file request
 */
export const postQuranAudioAyahsMutationRequestSchema = dtoCreateAyahAudioFileRequestSchema as unknown as z.ZodType<PostQuranAudioAyahsMutationRequest>

export const postQuranAudioAyahsMutationResponseSchema = postQuranAudioAyahs201Schema as unknown as z.ZodType<PostQuranAudioAyahsMutationResponse>