/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PutQuranAudioAyahsIdPathParams, PutQuranAudioAyahsId200, PutQuranAudioAyahsId400, PutQuranAudioAyahsId500, PutQuranAudioAyahsIdMutationRequest, PutQuranAudioAyahsIdMutationResponse } from "../../types/PutQuranAudioAyahsId.ts";
import { dtoUpdateAyahAudioFileRequestSchema } from "../dto/updateAyahAudioFileRequestSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { quranUpdateAyahAudioFileSuccessResponseSchema } from "../quran/updateAyahAudioFileSuccessResponseSchema.ts";
import { z } from "zod";

export const putQuranAudioAyahsIdPathParamsSchema = z.object({
    "id": z.string().describe("Ayah audio file ID")
    }) as unknown as z.ZodType<PutQuranAudioAyahsIdPathParams>

/**
 * @description Ayah audio file updated successfully
 */
export const putQuranAudioAyahsId200Schema = quranUpdateAyahAudioFileSuccessResponseSchema as unknown as z.ZodType<PutQuranAudioAyahsId200>

/**
 * @description Bad request
 */
export const putQuranAudioAyahsId400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PutQuranAudioAyahsId400>

/**
 * @description Internal server error
 */
export const putQuranAudioAyahsId500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PutQuranAudioAyahsId500>

/**
 * @description Update ayah audio file request
 */
export const putQuranAudioAyahsIdMutationRequestSchema = dtoUpdateAyahAudioFileRequestSchema as unknown as z.ZodType<PutQuranAudioAyahsIdMutationRequest>

export const putQuranAudioAyahsIdMutationResponseSchema = putQuranAudioAyahsId200Schema as unknown as z.ZodType<PutQuranAudioAyahsIdMutationResponse>