/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetQuranTranslationsAyahsAyahAyahidEditionEditionidPathParams, GetQuranTranslationsAyahsAyahAyahidEditionEditionid200, GetQuranTranslationsAyahsAyahAyahidEditionEditionid400, GetQuranTranslationsAyahsAyahAyahidEditionEditionid404, GetQuranTranslationsAyahsAyahAyahidEditionEditionid500, GetQuranTranslationsAyahsAyahAyahidEditionEditionidQueryResponse } from "../../types/GetQuranTranslationsAyahsAyahAyahidEditionEditionid.ts";
import { quranGetAyahTranslationSuccessResponseSchema } from "../quran/getAyahTranslationSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const getQuranTranslationsAyahsAyahAyahidEditionEditionidPathParamsSchema = z.object({
    "ayahId": z.string().describe("Ayah ID"),
"editionId": z.string().describe("Translation Edition ID")
    }) as unknown as z.ZodType<GetQuranTranslationsAyahsAyahAyahidEditionEditionidPathParams>

/**
 * @description Ayah translation retrieved successfully
 */
export const getQuranTranslationsAyahsAyahAyahidEditionEditionid200Schema = quranGetAyahTranslationSuccessResponseSchema as unknown as z.ZodType<GetQuranTranslationsAyahsAyahAyahidEditionEditionid200>

/**
 * @description Bad request
 */
export const getQuranTranslationsAyahsAyahAyahidEditionEditionid400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranTranslationsAyahsAyahAyahidEditionEditionid400>

/**
 * @description Not found
 */
export const getQuranTranslationsAyahsAyahAyahidEditionEditionid404Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranTranslationsAyahsAyahAyahidEditionEditionid404>

/**
 * @description Internal server error
 */
export const getQuranTranslationsAyahsAyahAyahidEditionEditionid500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranTranslationsAyahsAyahAyahidEditionEditionid500>

export const getQuranTranslationsAyahsAyahAyahidEditionEditionidQueryResponseSchema = getQuranTranslationsAyahsAyahAyahidEditionEditionid200Schema as unknown as z.ZodType<GetQuranTranslationsAyahsAyahAyahidEditionEditionidQueryResponse>