/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetQuranTranslationsAyahsSurahSurahidEditionEditionidPathParams, GetQuranTranslationsAyahsSurahSurahidEditionEditionidQueryParams, GetQuranTranslationsAyahsSurahSurahidEditionEditionid200, GetQuranTranslationsAyahsSurahSurahidEditionEditionid400, GetQuranTranslationsAyahsSurahSurahidEditionEditionid500, GetQuranTranslationsAyahsSurahSurahidEditionEditionidQueryResponse } from "../../types/GetQuranTranslationsAyahsSurahSurahidEditionEditionid.ts";
import { quranGetAyahTranslationListSuccessResponseSchema } from "../quran/getAyahTranslationListSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const getQuranTranslationsAyahsSurahSurahidEditionEditionidPathParamsSchema = z.object({
    "surahId": z.string().describe("Surah ID"),
"editionId": z.string().describe("Translation Edition ID")
    }) as unknown as z.ZodType<GetQuranTranslationsAyahsSurahSurahidEditionEditionidPathParams>

export const getQuranTranslationsAyahsSurahSurahidEditionEditionidQueryParamsSchema = z.object({
    "limit": z.coerce.number().int().default(0).describe("Limit (0 for all)"),
"offset": z.coerce.number().int().default(0).describe("Offset")
    }) as unknown as z.ZodType<GetQuranTranslationsAyahsSurahSurahidEditionEditionidQueryParams>

/**
 * @description Ayah translations retrieved successfully
 */
export const getQuranTranslationsAyahsSurahSurahidEditionEditionid200Schema = quranGetAyahTranslationListSuccessResponseSchema as unknown as z.ZodType<GetQuranTranslationsAyahsSurahSurahidEditionEditionid200>

/**
 * @description Bad request
 */
export const getQuranTranslationsAyahsSurahSurahidEditionEditionid400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranTranslationsAyahsSurahSurahidEditionEditionid400>

/**
 * @description Internal server error
 */
export const getQuranTranslationsAyahsSurahSurahidEditionEditionid500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranTranslationsAyahsSurahSurahidEditionEditionid500>

export const getQuranTranslationsAyahsSurahSurahidEditionEditionidQueryResponseSchema = getQuranTranslationsAyahsSurahSurahidEditionEditionid200Schema as unknown as z.ZodType<GetQuranTranslationsAyahsSurahSurahidEditionEditionidQueryResponse>