/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetQuranTranslationsEditionsQueryParams, GetQuranTranslationsEditions200, GetQuranTranslationsEditions400, GetQuranTranslationsEditions500, GetQuranTranslationsEditionsQueryResponse } from "../../types/GetQuranTranslationsEditions.ts";
import { quranGetTranslationEditionListSuccessResponseSchema } from "../quran/getTranslationEditionListSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const getQuranTranslationsEditionsQueryParamsSchema = z.object({
    "language": z.optional(z.string().describe("Language code (e.g., en, id)")),
"limit": z.coerce.number().int().default(0).describe("Limit (0 for all)"),
"offset": z.coerce.number().int().default(0).describe("Offset")
    }) as unknown as z.ZodType<GetQuranTranslationsEditionsQueryParams>

/**
 * @description Translation editions retrieved successfully
 */
export const getQuranTranslationsEditions200Schema = quranGetTranslationEditionListSuccessResponseSchema as unknown as z.ZodType<GetQuranTranslationsEditions200>

/**
 * @description Bad request
 */
export const getQuranTranslationsEditions400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranTranslationsEditions400>

/**
 * @description Internal server error
 */
export const getQuranTranslationsEditions500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranTranslationsEditions500>

export const getQuranTranslationsEditionsQueryResponseSchema = getQuranTranslationsEditions200Schema as unknown as z.ZodType<GetQuranTranslationsEditionsQueryResponse>