/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeleteQuranBookmarksAyahsIdPathParams, DeleteQuranBookmarksAyahsId200, DeleteQuranBookmarksAyahsId400, DeleteQuranBookmarksAyahsId404, DeleteQuranBookmarksAyahsId500, DeleteQuranBookmarksAyahsIdMutationResponse } from "../../types/DeleteQuranBookmarksAyahsId.ts";
import { quranDeleteBookmarkAyahSuccessResponseSchema } from "../quran/deleteBookmarkAyahSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const deleteQuranBookmarksAyahsIdPathParamsSchema = z.object({
    "id": z.string().describe("Bookmark ID")
    }) as unknown as z.ZodType<DeleteQuranBookmarksAyahsIdPathParams>

/**
 * @description Bookmark deleted successfully
 */
export const deleteQuranBookmarksAyahsId200Schema = quranDeleteBookmarkAyahSuccessResponseSchema as unknown as z.ZodType<DeleteQuranBookmarksAyahsId200>

/**
 * @description Bad request
 */
export const deleteQuranBookmarksAyahsId400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<DeleteQuranBookmarksAyahsId400>

/**
 * @description Bookmark not found
 */
export const deleteQuranBookmarksAyahsId404Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<DeleteQuranBookmarksAyahsId404>

/**
 * @description Internal server error
 */
export const deleteQuranBookmarksAyahsId500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<DeleteQuranBookmarksAyahsId500>

export const deleteQuranBookmarksAyahsIdMutationResponseSchema = deleteQuranBookmarksAyahsId200Schema as unknown as z.ZodType<DeleteQuranBookmarksAyahsIdMutationResponse>