/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetQuranBookmarksAyahsAyahAyahidPathParams, GetQuranBookmarksAyahsAyahAyahidQueryParams, GetQuranBookmarksAyahsAyahAyahid200, GetQuranBookmarksAyahsAyahAyahid400, GetQuranBookmarksAyahsAyahAyahid404, GetQuranBookmarksAyahsAyahAyahid500, GetQuranBookmarksAyahsAyahAyahidQueryResponse } from "../../types/GetQuranBookmarksAyahsAyahAyahid.ts";
import { quranBookmarkAyahSuccessResponseSchema } from "../quran/bookmarkAyahSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const getQuranBookmarksAyahsAyahAyahidPathParamsSchema = z.object({
    "ayahId": z.string().describe("Ayah ID")
    }) as unknown as z.ZodType<GetQuranBookmarksAyahsAyahAyahidPathParams>

export const getQuranBookmarksAyahsAyahAyahidQueryParamsSchema = z.object({
    "include": z.optional(z.enum(["ayah"]).describe("Include related data"))
    }).optional() as unknown as z.ZodType<GetQuranBookmarksAyahsAyahAyahidQueryParams>

/**
 * @description Bookmark retrieved successfully
 */
export const getQuranBookmarksAyahsAyahAyahid200Schema = quranBookmarkAyahSuccessResponseSchema as unknown as z.ZodType<GetQuranBookmarksAyahsAyahAyahid200>

/**
 * @description Bad request
 */
export const getQuranBookmarksAyahsAyahAyahid400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranBookmarksAyahsAyahAyahid400>

/**
 * @description Bookmark not found
 */
export const getQuranBookmarksAyahsAyahAyahid404Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranBookmarksAyahsAyahAyahid404>

/**
 * @description Internal server error
 */
export const getQuranBookmarksAyahsAyahAyahid500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranBookmarksAyahsAyahAyahid500>

export const getQuranBookmarksAyahsAyahAyahidQueryResponseSchema = getQuranBookmarksAyahsAyahAyahid200Schema as unknown as z.ZodType<GetQuranBookmarksAyahsAyahAyahidQueryResponse>