/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetQuranBookmarksAyahsIdPathParams, GetQuranBookmarksAyahsIdQueryParams, GetQuranBookmarksAyahsId200, GetQuranBookmarksAyahsId400, GetQuranBookmarksAyahsId404, GetQuranBookmarksAyahsId500, GetQuranBookmarksAyahsIdQueryResponse } from "../../types/GetQuranBookmarksAyahsId.ts";
import { quranBookmarkAyahSuccessResponseSchema } from "../quran/bookmarkAyahSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const getQuranBookmarksAyahsIdPathParamsSchema = z.object({
    "id": z.string().describe("Bookmark ID")
    }) as unknown as z.ZodType<GetQuranBookmarksAyahsIdPathParams>

export const getQuranBookmarksAyahsIdQueryParamsSchema = z.object({
    "include": z.optional(z.enum(["ayah"]).describe("Include related data"))
    }).optional() as unknown as z.ZodType<GetQuranBookmarksAyahsIdQueryParams>

/**
 * @description Bookmark retrieved successfully
 */
export const getQuranBookmarksAyahsId200Schema = quranBookmarkAyahSuccessResponseSchema as unknown as z.ZodType<GetQuranBookmarksAyahsId200>

/**
 * @description Bad request
 */
export const getQuranBookmarksAyahsId400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranBookmarksAyahsId400>

/**
 * @description Bookmark not found
 */
export const getQuranBookmarksAyahsId404Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranBookmarksAyahsId404>

/**
 * @description Internal server error
 */
export const getQuranBookmarksAyahsId500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranBookmarksAyahsId500>

export const getQuranBookmarksAyahsIdQueryResponseSchema = getQuranBookmarksAyahsId200Schema as unknown as z.ZodType<GetQuranBookmarksAyahsIdQueryResponse>