/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetQuranBookmarksAyahsQueryParams, GetQuranBookmarksAyahs200, GetQuranBookmarksAyahs400, GetQuranBookmarksAyahs500, GetQuranBookmarksAyahsQueryResponse } from "../../types/GetQuranBookmarksAyahs.ts";
import { quranBookmarkAyahListSuccessResponseSchema } from "../quran/bookmarkAyahListSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const getQuranBookmarksAyahsQueryParamsSchema = z.object({
    "limit": z.optional(z.coerce.number().int().describe("Limit")),
"offset": z.optional(z.coerce.number().int().describe("Offset"))
    }).optional() as unknown as z.ZodType<GetQuranBookmarksAyahsQueryParams>

/**
 * @description Bookmarks retrieved successfully
 */
export const getQuranBookmarksAyahs200Schema = quranBookmarkAyahListSuccessResponseSchema as unknown as z.ZodType<GetQuranBookmarksAyahs200>

/**
 * @description Bad request
 */
export const getQuranBookmarksAyahs400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranBookmarksAyahs400>

/**
 * @description Internal server error
 */
export const getQuranBookmarksAyahs500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranBookmarksAyahs500>

export const getQuranBookmarksAyahsQueryResponseSchema = getQuranBookmarksAyahs200Schema as unknown as z.ZodType<GetQuranBookmarksAyahsQueryResponse>