/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PostQuranBookmarksAyahs201, PostQuranBookmarksAyahs400, PostQuranBookmarksAyahs500, PostQuranBookmarksAyahsMutationRequest, PostQuranBookmarksAyahsMutationResponse } from "../../types/PostQuranBookmarksAyahs.ts";
import { dtoCreateBookmarkAyahRequestSchema } from "../dto/createBookmarkAyahRequestSchema.ts";
import { quranBookmarkAyahSuccessResponseSchema } from "../quran/bookmarkAyahSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

/**
 * @description Bookmark created successfully
 */
export const postQuranBookmarksAyahs201Schema = quranBookmarkAyahSuccessResponseSchema as unknown as z.ZodType<PostQuranBookmarksAyahs201>

/**
 * @description Bad request
 */
export const postQuranBookmarksAyahs400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PostQuranBookmarksAyahs400>

/**
 * @description Internal server error
 */
export const postQuranBookmarksAyahs500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PostQuranBookmarksAyahs500>

/**
 * @description Create bookmark request
 */
export const postQuranBookmarksAyahsMutationRequestSchema = dtoCreateBookmarkAyahRequestSchema as unknown as z.ZodType<PostQuranBookmarksAyahsMutationRequest>

export const postQuranBookmarksAyahsMutationResponseSchema = postQuranBookmarksAyahs201Schema as unknown as z.ZodType<PostQuranBookmarksAyahsMutationResponse>