/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeleteQuranProgressHatamIdPathParams, DeleteQuranProgressHatamId200, DeleteQuranProgressHatamId400, DeleteQuranProgressHatamId404, DeleteQuranProgressHatamId500, DeleteQuranProgressHatamIdMutationResponse } from "../../types/DeleteQuranProgressHatamId.ts";
import { quranDeleteProgressHatamSuccessResponseSchema } from "../quran/deleteProgressHatamSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const deleteQuranProgressHatamIdPathParamsSchema = z.object({
    "id": z.string().describe("ProgressHatam ID")
    }) as unknown as z.ZodType<DeleteQuranProgressHatamIdPathParams>

/**
 * @description Progress hatam deleted successfully
 */
export const deleteQuranProgressHatamId200Schema = quranDeleteProgressHatamSuccessResponseSchema as unknown as z.ZodType<DeleteQuranProgressHatamId200>

/**
 * @description Bad request
 */
export const deleteQuranProgressHatamId400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<DeleteQuranProgressHatamId400>

/**
 * @description Progress hatam not found
 */
export const deleteQuranProgressHatamId404Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<DeleteQuranProgressHatamId404>

/**
 * @description Internal server error
 */
export const deleteQuranProgressHatamId500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<DeleteQuranProgressHatamId500>

export const deleteQuranProgressHatamIdMutationResponseSchema = deleteQuranProgressHatamId200Schema as unknown as z.ZodType<DeleteQuranProgressHatamIdMutationResponse>