/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetQuranProgressHatamQueryParams, GetQuranProgressHatam200, GetQuranProgressHatam400, GetQuranProgressHatam500, GetQuranProgressHatamQueryResponse } from "../../types/GetQuranProgressHatam.ts";
import { quranProgressHatamListSuccessResponseSchema } from "../quran/progressHatamListSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const getQuranProgressHatamQueryParamsSchema = z.object({
    "limit": z.optional(z.coerce.number().int().describe("Limit")),
"offset": z.optional(z.coerce.number().int().describe("Offset")),
"include": z.optional(z.enum(["relations"]).describe("Include related data"))
    }).optional() as unknown as z.ZodType<GetQuranProgressHatamQueryParams>

/**
 * @description Progress hatam list retrieved successfully
 */
export const getQuranProgressHatam200Schema = quranProgressHatamListSuccessResponseSchema as unknown as z.ZodType<GetQuranProgressHatam200>

/**
 * @description Bad request
 */
export const getQuranProgressHatam400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranProgressHatam400>

/**
 * @description Internal server error
 */
export const getQuranProgressHatam500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranProgressHatam500>

export const getQuranProgressHatamQueryResponseSchema = getQuranProgressHatam200Schema as unknown as z.ZodType<GetQuranProgressHatamQueryResponse>