/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetQuranProgressHatamJuzJuzidPathParams, GetQuranProgressHatamJuzJuzidQueryParams, GetQuranProgressHatamJuzJuzid200, GetQuranProgressHatamJuzJuzid400, GetQuranProgressHatamJuzJuzid404, GetQuranProgressHatamJuzJuzid500, GetQuranProgressHatamJuzJuzidQueryResponse } from "../../types/GetQuranProgressHatamJuzJuzid.ts";
import { quranProgressHatamSuccessResponseSchema } from "../quran/progressHatamSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const getQuranProgressHatamJuzJuzidPathParamsSchema = z.object({
    "juzId": z.string().describe("Juz ID")
    }) as unknown as z.ZodType<GetQuranProgressHatamJuzJuzidPathParams>

export const getQuranProgressHatamJuzJuzidQueryParamsSchema = z.object({
    "include": z.optional(z.enum(["relations"]).describe("Include related data"))
    }).optional() as unknown as z.ZodType<GetQuranProgressHatamJuzJuzidQueryParams>

/**
 * @description Progress hatam retrieved successfully
 */
export const getQuranProgressHatamJuzJuzid200Schema = quranProgressHatamSuccessResponseSchema as unknown as z.ZodType<GetQuranProgressHatamJuzJuzid200>

/**
 * @description Bad request
 */
export const getQuranProgressHatamJuzJuzid400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranProgressHatamJuzJuzid400>

/**
 * @description Progress hatam not found
 */
export const getQuranProgressHatamJuzJuzid404Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranProgressHatamJuzJuzid404>

/**
 * @description Internal server error
 */
export const getQuranProgressHatamJuzJuzid500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranProgressHatamJuzJuzid500>

export const getQuranProgressHatamJuzJuzidQueryResponseSchema = getQuranProgressHatamJuzJuzid200Schema as unknown as z.ZodType<GetQuranProgressHatamJuzJuzidQueryResponse>