/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetQuranProgressHatamIdPathParams, GetQuranProgressHatamIdQueryParams, GetQuranProgressHatamId200, GetQuranProgressHatamId400, GetQuranProgressHatamId404, GetQuranProgressHatamId500, GetQuranProgressHatamIdQueryResponse } from "../../types/GetQuranProgressHatamId.ts";
import { quranProgressHatamSuccessResponseSchema } from "../quran/progressHatamSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const getQuranProgressHatamIdPathParamsSchema = z.object({
    "id": z.string().describe("ProgressHatam ID")
    }) as unknown as z.ZodType<GetQuranProgressHatamIdPathParams>

export const getQuranProgressHatamIdQueryParamsSchema = z.object({
    "include": z.optional(z.enum(["relations"]).describe("Include related data"))
    }).optional() as unknown as z.ZodType<GetQuranProgressHatamIdQueryParams>

/**
 * @description Progress hatam retrieved successfully
 */
export const getQuranProgressHatamId200Schema = quranProgressHatamSuccessResponseSchema as unknown as z.ZodType<GetQuranProgressHatamId200>

/**
 * @description Bad request
 */
export const getQuranProgressHatamId400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranProgressHatamId400>

/**
 * @description Progress hatam not found
 */
export const getQuranProgressHatamId404Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranProgressHatamId404>

/**
 * @description Internal server error
 */
export const getQuranProgressHatamId500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranProgressHatamId500>

export const getQuranProgressHatamIdQueryResponseSchema = getQuranProgressHatamId200Schema as unknown as z.ZodType<GetQuranProgressHatamIdQueryResponse>