/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PostQuranProgressHatam201, PostQuranProgressHatam400, PostQuranProgressHatam500, PostQuranProgressHatamMutationRequest, PostQuranProgressHatamMutationResponse } from "../../types/PostQuranProgressHatam.ts";
import { dtoCreateProgressHatamRequestSchema } from "../dto/createProgressHatamRequestSchema.ts";
import { quranProgressHatamSuccessResponseSchema } from "../quran/progressHatamSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

/**
 * @description Progress hatam created successfully
 */
export const postQuranProgressHatam201Schema = quranProgressHatamSuccessResponseSchema as unknown as z.ZodType<PostQuranProgressHatam201>

/**
 * @description Bad request
 */
export const postQuranProgressHatam400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PostQuranProgressHatam400>

/**
 * @description Internal server error
 */
export const postQuranProgressHatam500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PostQuranProgressHatam500>

/**
 * @description ProgressHatam information
 */
export const postQuranProgressHatamMutationRequestSchema = dtoCreateProgressHatamRequestSchema as unknown as z.ZodType<PostQuranProgressHatamMutationRequest>

export const postQuranProgressHatamMutationResponseSchema = postQuranProgressHatam201Schema as unknown as z.ZodType<PostQuranProgressHatamMutationResponse>