/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PutQuranProgressHatamIdPathParams, PutQuranProgressHatamId200, PutQuranProgressHatamId400, PutQuranProgressHatamId404, PutQuranProgressHatamId500, PutQuranProgressHatamIdMutationRequest, PutQuranProgressHatamIdMutationResponse } from "../../types/PutQuranProgressHatamId.ts";
import { dtoUpdateProgressHatamRequestSchema } from "../dto/updateProgressHatamRequestSchema.ts";
import { quranProgressHatamSuccessResponseSchema } from "../quran/progressHatamSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const putQuranProgressHatamIdPathParamsSchema = z.object({
    "id": z.string().describe("ProgressHatam ID")
    }) as unknown as z.ZodType<PutQuranProgressHatamIdPathParams>

/**
 * @description Progress hatam updated successfully
 */
export const putQuranProgressHatamId200Schema = quranProgressHatamSuccessResponseSchema as unknown as z.ZodType<PutQuranProgressHatamId200>

/**
 * @description Bad request
 */
export const putQuranProgressHatamId400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PutQuranProgressHatamId400>

/**
 * @description Progress hatam not found
 */
export const putQuranProgressHatamId404Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PutQuranProgressHatamId404>

/**
 * @description Internal server error
 */
export const putQuranProgressHatamId500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PutQuranProgressHatamId500>

/**
 * @description ProgressHatam update information
 */
export const putQuranProgressHatamIdMutationRequestSchema = dtoUpdateProgressHatamRequestSchema as unknown as z.ZodType<PutQuranProgressHatamIdMutationRequest>

export const putQuranProgressHatamIdMutationResponseSchema = putQuranProgressHatamId200Schema as unknown as z.ZodType<PutQuranProgressHatamIdMutationResponse>