/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CoreErrorDetail = {
    /**
     * @type string | undefined
    */
    code?: string;
    /**
     * @type string | undefined
    */
    reason?: string;
};