/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { DeleteQuranSurahsIdMutationResponse, DeleteQuranSurahsIdPathParams, DeleteQuranSurahsId400, DeleteQuranSurahsId404, DeleteQuranSurahsId500 } from "../../types/DeleteQuranSurahsId.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteQuranSurahsIdMutationKey = () => [{ url: '/quran/surahs/:id' }] as const

export type DeleteQuranSurahsIdMutationKey = ReturnType<typeof deleteQuranSurahsIdMutationKey>

/**
 * @description Delete an existing surah from the Quran
 * @summary Delete a surah
 * {@link /quran/surahs/:id}
 */
export async function deleteQuranSurahsIdHook(id: DeleteQuranSurahsIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteQuranSurahsIdMutationResponse, ResponseErrorConfig<DeleteQuranSurahsId400 | DeleteQuranSurahsId404 | DeleteQuranSurahsId500>, unknown>({ method : "DELETE", url : `/quran/surahs/${id}`, ... requestConfig })  
  return res.data
}

export function deleteQuranSurahsIdMutationOptionsHook(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = deleteQuranSurahsIdMutationKey()
  return mutationOptions<DeleteQuranSurahsIdMutationResponse, ResponseErrorConfig<DeleteQuranSurahsId400 | DeleteQuranSurahsId404 | DeleteQuranSurahsId500>, {id: DeleteQuranSurahsIdPathParams["id"]}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id }) => {
      return deleteQuranSurahsIdHook(id, config)
    },
  })
}

/**
 * @description Delete an existing surah from the Quran
 * @summary Delete a surah
 * {@link /quran/surahs/:id}
 */
export function useDeleteQuranSurahsIdHook<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteQuranSurahsIdMutationResponse, ResponseErrorConfig<DeleteQuranSurahsId400 | DeleteQuranSurahsId404 | DeleteQuranSurahsId500>, {id: DeleteQuranSurahsIdPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteQuranSurahsIdMutationKey()

  const baseOptions = deleteQuranSurahsIdMutationOptionsHook(config) as UseMutationOptions<DeleteQuranSurahsIdMutationResponse, ResponseErrorConfig<DeleteQuranSurahsId400 | DeleteQuranSurahsId404 | DeleteQuranSurahsId500>, {id: DeleteQuranSurahsIdPathParams["id"]}, TContext>

  return useMutation<DeleteQuranSurahsIdMutationResponse, ResponseErrorConfig<DeleteQuranSurahsId400 | DeleteQuranSurahsId404 | DeleteQuranSurahsId500>, {id: DeleteQuranSurahsIdPathParams["id"]}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<DeleteQuranSurahsIdMutationResponse, ResponseErrorConfig<DeleteQuranSurahsId400 | DeleteQuranSurahsId404 | DeleteQuranSurahsId500>, {id: DeleteQuranSurahsIdPathParams["id"]}, TContext>
}