/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetQuranSurahsNumberQueryResponse, GetQuranSurahsNumberPathParams, GetQuranSurahsNumberQueryParams, GetQuranSurahsNumber400, GetQuranSurahsNumber404, GetQuranSurahsNumber500 } from "../../types/GetQuranSurahsNumberNumber.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getQuranSurahsNumberNumberQueryKey = (number: GetQuranSurahsNumberPathParams["number"], params?: GetQuranSurahsNumberQueryParams) => [{ url: '/quran/surahs/number/:number', params: {number:number} }, ...(params ? [params] : [])] as const

export type GetQuranSurahsNumberNumberQueryKey = ReturnType<typeof getQuranSurahsNumberNumberQueryKey>

/**
 * @description Get a surah by its number from the Quran
 * @summary Get surah by number
 * {@link /quran/surahs/number/:number}
 */
export async function getQuranSurahsNumberNumberHook(number: GetQuranSurahsNumberPathParams["number"], params?: GetQuranSurahsNumberQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetQuranSurahsNumberQueryResponse, ResponseErrorConfig<GetQuranSurahsNumber400 | GetQuranSurahsNumber404 | GetQuranSurahsNumber500>, unknown>({ method : "GET", url : `/quran/surahs/number/${number}`, params, ... requestConfig })  
  return res.data
}

export function getQuranSurahsNumberNumberQueryOptionsHook(number: GetQuranSurahsNumberPathParams["number"], params?: GetQuranSurahsNumberQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getQuranSurahsNumberNumberQueryKey(number, params)
  return queryOptions<GetQuranSurahsNumberQueryResponse, ResponseErrorConfig<GetQuranSurahsNumber400 | GetQuranSurahsNumber404 | GetQuranSurahsNumber500>, GetQuranSurahsNumberQueryResponse, typeof queryKey>({
   enabled: !!(number),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getQuranSurahsNumberNumberHook(number, params, config)
   },
  })
}

/**
 * @description Get a surah by its number from the Quran
 * @summary Get surah by number
 * {@link /quran/surahs/number/:number}
 */
export function useGetQuranSurahsNumberNumberHook<TData = GetQuranSurahsNumberQueryResponse, TQueryData = GetQuranSurahsNumberQueryResponse, TQueryKey extends QueryKey = GetQuranSurahsNumberNumberQueryKey>(number: GetQuranSurahsNumberPathParams["number"], params?: GetQuranSurahsNumberQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetQuranSurahsNumberQueryResponse, ResponseErrorConfig<GetQuranSurahsNumber400 | GetQuranSurahsNumber404 | GetQuranSurahsNumber500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getQuranSurahsNumberNumberQueryKey(number, params)

  const query = useQuery({
   ...getQuranSurahsNumberNumberQueryOptionsHook(number, params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetQuranSurahsNumber400 | GetQuranSurahsNumber404 | GetQuranSurahsNumber500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}