/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetQuranSurahsQueryResponse, GetQuranSurahsQueryParams, GetQuranSurahs400, GetQuranSurahs500 } from "../../types/GetQuranSurahs.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getQuranSurahsQueryKey = (params?: GetQuranSurahsQueryParams) => [{ url: '/quran/surahs' }, ...(params ? [params] : [])] as const

export type GetQuranSurahsQueryKey = ReturnType<typeof getQuranSurahsQueryKey>

/**
 * @description Get all surahs from the Quran with pagination
 * @summary Get all surahs
 * {@link /quran/surahs}
 */
export async function getQuranSurahsHook(params?: GetQuranSurahsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetQuranSurahsQueryResponse, ResponseErrorConfig<GetQuranSurahs400 | GetQuranSurahs500>, unknown>({ method : "GET", url : `/quran/surahs`, params, ... requestConfig })  
  return res.data
}

export function getQuranSurahsQueryOptionsHook(params?: GetQuranSurahsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getQuranSurahsQueryKey(params)
  return queryOptions<GetQuranSurahsQueryResponse, ResponseErrorConfig<GetQuranSurahs400 | GetQuranSurahs500>, GetQuranSurahsQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getQuranSurahsHook(params, config)
   },
  })
}

/**
 * @description Get all surahs from the Quran with pagination
 * @summary Get all surahs
 * {@link /quran/surahs}
 */
export function useGetQuranSurahsHook<TData = GetQuranSurahsQueryResponse, TQueryData = GetQuranSurahsQueryResponse, TQueryKey extends QueryKey = GetQuranSurahsQueryKey>(params?: GetQuranSurahsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetQuranSurahsQueryResponse, ResponseErrorConfig<GetQuranSurahs400 | GetQuranSurahs500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getQuranSurahsQueryKey(params)

  const query = useQuery({
   ...getQuranSurahsQueryOptionsHook(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetQuranSurahs400 | GetQuranSurahs500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}