/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetQuranSurahsIdQueryResponse, GetQuranSurahsIdPathParams, GetQuranSurahsIdQueryParams, GetQuranSurahsId400, GetQuranSurahsId404, GetQuranSurahsId500 } from "../../types/GetQuranSurahsId.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getQuranSurahsIdQueryKey = (id: GetQuranSurahsIdPathParams["id"], params?: GetQuranSurahsIdQueryParams) => [{ url: '/quran/surahs/:id', params: {id:id} }, ...(params ? [params] : [])] as const

export type GetQuranSurahsIdQueryKey = ReturnType<typeof getQuranSurahsIdQueryKey>

/**
 * @description Get a surah by its ID from the Quran
 * @summary Get surah by ID
 * {@link /quran/surahs/:id}
 */
export async function getQuranSurahsIdHook(id: GetQuranSurahsIdPathParams["id"], params?: GetQuranSurahsIdQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetQuranSurahsIdQueryResponse, ResponseErrorConfig<GetQuranSurahsId400 | GetQuranSurahsId404 | GetQuranSurahsId500>, unknown>({ method : "GET", url : `/quran/surahs/${id}`, params, ... requestConfig })  
  return res.data
}

export function getQuranSurahsIdQueryOptionsHook(id: GetQuranSurahsIdPathParams["id"], params?: GetQuranSurahsIdQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getQuranSurahsIdQueryKey(id, params)
  return queryOptions<GetQuranSurahsIdQueryResponse, ResponseErrorConfig<GetQuranSurahsId400 | GetQuranSurahsId404 | GetQuranSurahsId500>, GetQuranSurahsIdQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getQuranSurahsIdHook(id, params, config)
   },
  })
}

/**
 * @description Get a surah by its ID from the Quran
 * @summary Get surah by ID
 * {@link /quran/surahs/:id}
 */
export function useGetQuranSurahsIdHook<TData = GetQuranSurahsIdQueryResponse, TQueryData = GetQuranSurahsIdQueryResponse, TQueryKey extends QueryKey = GetQuranSurahsIdQueryKey>(id: GetQuranSurahsIdPathParams["id"], params?: GetQuranSurahsIdQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetQuranSurahsIdQueryResponse, ResponseErrorConfig<GetQuranSurahsId400 | GetQuranSurahsId404 | GetQuranSurahsId500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getQuranSurahsIdQueryKey(id, params)

  const query = useQuery({
   ...getQuranSurahsIdQueryOptionsHook(id, params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetQuranSurahsId400 | GetQuranSurahsId404 | GetQuranSurahsId500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}