/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { PostQuranSurahsMutationRequest, PostQuranSurahsMutationResponse, PostQuranSurahs400, PostQuranSurahs500 } from "../../types/PostQuranSurahs.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postQuranSurahsMutationKey = () => [{ url: '/quran/surahs' }] as const

export type PostQuranSurahsMutationKey = ReturnType<typeof postQuranSurahsMutationKey>

/**
 * @description Create a new surah in the Quran
 * @summary Create a new surah
 * {@link /quran/surahs}
 */
export async function postQuranSurahsHook(data: PostQuranSurahsMutationRequest, config: Partial<RequestConfig<PostQuranSurahsMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostQuranSurahsMutationResponse, ResponseErrorConfig<PostQuranSurahs400 | PostQuranSurahs500>, PostQuranSurahsMutationRequest>({ method : "POST", url : `/quran/surahs`, data : requestData, ... requestConfig })  
  return res.data
}

export function postQuranSurahsMutationOptionsHook(config: Partial<RequestConfig<PostQuranSurahsMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = postQuranSurahsMutationKey()
  return mutationOptions<PostQuranSurahsMutationResponse, ResponseErrorConfig<PostQuranSurahs400 | PostQuranSurahs500>, {data: PostQuranSurahsMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return postQuranSurahsHook(data, config)
    },
  })
}

/**
 * @description Create a new surah in the Quran
 * @summary Create a new surah
 * {@link /quran/surahs}
 */
export function usePostQuranSurahsHook<TContext>(options: 
{
  mutation?: UseMutationOptions<PostQuranSurahsMutationResponse, ResponseErrorConfig<PostQuranSurahs400 | PostQuranSurahs500>, {data: PostQuranSurahsMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostQuranSurahsMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postQuranSurahsMutationKey()

  const baseOptions = postQuranSurahsMutationOptionsHook(config) as UseMutationOptions<PostQuranSurahsMutationResponse, ResponseErrorConfig<PostQuranSurahs400 | PostQuranSurahs500>, {data: PostQuranSurahsMutationRequest}, TContext>

  return useMutation<PostQuranSurahsMutationResponse, ResponseErrorConfig<PostQuranSurahs400 | PostQuranSurahs500>, {data: PostQuranSurahsMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<PostQuranSurahsMutationResponse, ResponseErrorConfig<PostQuranSurahs400 | PostQuranSurahs500>, {data: PostQuranSurahsMutationRequest}, TContext>
}