/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { PutQuranSurahsIdMutationRequest, PutQuranSurahsIdMutationResponse, PutQuranSurahsIdPathParams, PutQuranSurahsId400, PutQuranSurahsId404, PutQuranSurahsId500 } from "../../types/PutQuranSurahsId.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const putQuranSurahsIdMutationKey = () => [{ url: '/quran/surahs/:id' }] as const

export type PutQuranSurahsIdMutationKey = ReturnType<typeof putQuranSurahsIdMutationKey>

/**
 * @description Update an existing surah in the Quran
 * @summary Update a surah
 * {@link /quran/surahs/:id}
 */
export async function putQuranSurahsIdHook(id: PutQuranSurahsIdPathParams["id"], data: PutQuranSurahsIdMutationRequest, config: Partial<RequestConfig<PutQuranSurahsIdMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PutQuranSurahsIdMutationResponse, ResponseErrorConfig<PutQuranSurahsId400 | PutQuranSurahsId404 | PutQuranSurahsId500>, PutQuranSurahsIdMutationRequest>({ method : "PUT", url : `/quran/surahs/${id}`, data : requestData, ... requestConfig })  
  return res.data
}

export function putQuranSurahsIdMutationOptionsHook(config: Partial<RequestConfig<PutQuranSurahsIdMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = putQuranSurahsIdMutationKey()
  return mutationOptions<PutQuranSurahsIdMutationResponse, ResponseErrorConfig<PutQuranSurahsId400 | PutQuranSurahsId404 | PutQuranSurahsId500>, {id: PutQuranSurahsIdPathParams["id"], data: PutQuranSurahsIdMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id, data }) => {
      return putQuranSurahsIdHook(id, data, config)
    },
  })
}

/**
 * @description Update an existing surah in the Quran
 * @summary Update a surah
 * {@link /quran/surahs/:id}
 */
export function usePutQuranSurahsIdHook<TContext>(options: 
{
  mutation?: UseMutationOptions<PutQuranSurahsIdMutationResponse, ResponseErrorConfig<PutQuranSurahsId400 | PutQuranSurahsId404 | PutQuranSurahsId500>, {id: PutQuranSurahsIdPathParams["id"], data: PutQuranSurahsIdMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PutQuranSurahsIdMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? putQuranSurahsIdMutationKey()

  const baseOptions = putQuranSurahsIdMutationOptionsHook(config) as UseMutationOptions<PutQuranSurahsIdMutationResponse, ResponseErrorConfig<PutQuranSurahsId400 | PutQuranSurahsId404 | PutQuranSurahsId500>, {id: PutQuranSurahsIdPathParams["id"], data: PutQuranSurahsIdMutationRequest}, TContext>

  return useMutation<PutQuranSurahsIdMutationResponse, ResponseErrorConfig<PutQuranSurahsId400 | PutQuranSurahsId404 | PutQuranSurahsId500>, {id: PutQuranSurahsIdPathParams["id"], data: PutQuranSurahsIdMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<PutQuranSurahsIdMutationResponse, ResponseErrorConfig<PutQuranSurahsId400 | PutQuranSurahsId404 | PutQuranSurahsId500>, {id: PutQuranSurahsIdPathParams["id"], data: PutQuranSurahsIdMutationRequest}, TContext>
}