/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { DeleteQuranJuzIdMutationResponse, DeleteQuranJuzIdPathParams, DeleteQuranJuzId400, DeleteQuranJuzId404, DeleteQuranJuzId500 } from "../../types/DeleteQuranJuzId.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteQuranJuzIdMutationKey = () => [{ url: '/quran/juz/:id' }] as const

export type DeleteQuranJuzIdMutationKey = ReturnType<typeof deleteQuranJuzIdMutationKey>

/**
 * @description Delete an existing juz by ID
 * @summary Delete a juz
 * {@link /quran/juz/:id}
 */
export async function deleteQuranJuzIdHook(id: DeleteQuranJuzIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteQuranJuzIdMutationResponse, ResponseErrorConfig<DeleteQuranJuzId400 | DeleteQuranJuzId404 | DeleteQuranJuzId500>, unknown>({ method : "DELETE", url : `/quran/juz/${id}`, ... requestConfig })  
  return res.data
}

export function deleteQuranJuzIdMutationOptionsHook(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = deleteQuranJuzIdMutationKey()
  return mutationOptions<DeleteQuranJuzIdMutationResponse, ResponseErrorConfig<DeleteQuranJuzId400 | DeleteQuranJuzId404 | DeleteQuranJuzId500>, {id: DeleteQuranJuzIdPathParams["id"]}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id }) => {
      return deleteQuranJuzIdHook(id, config)
    },
  })
}

/**
 * @description Delete an existing juz by ID
 * @summary Delete a juz
 * {@link /quran/juz/:id}
 */
export function useDeleteQuranJuzIdHook<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteQuranJuzIdMutationResponse, ResponseErrorConfig<DeleteQuranJuzId400 | DeleteQuranJuzId404 | DeleteQuranJuzId500>, {id: DeleteQuranJuzIdPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteQuranJuzIdMutationKey()

  const baseOptions = deleteQuranJuzIdMutationOptionsHook(config) as UseMutationOptions<DeleteQuranJuzIdMutationResponse, ResponseErrorConfig<DeleteQuranJuzId400 | DeleteQuranJuzId404 | DeleteQuranJuzId500>, {id: DeleteQuranJuzIdPathParams["id"]}, TContext>

  return useMutation<DeleteQuranJuzIdMutationResponse, ResponseErrorConfig<DeleteQuranJuzId400 | DeleteQuranJuzId404 | DeleteQuranJuzId500>, {id: DeleteQuranJuzIdPathParams["id"]}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<DeleteQuranJuzIdMutationResponse, ResponseErrorConfig<DeleteQuranJuzId400 | DeleteQuranJuzId404 | DeleteQuranJuzId500>, {id: DeleteQuranJuzIdPathParams["id"]}, TContext>
}