/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetQuranJuzIdQueryResponse, GetQuranJuzIdPathParams, GetQuranJuzIdQueryParams, GetQuranJuzId400, GetQuranJuzId404, GetQuranJuzId500 } from "../../types/GetQuranJuzId.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getQuranJuzIdQueryKey = (id: GetQuranJuzIdPathParams["id"], params?: GetQuranJuzIdQueryParams) => [{ url: '/quran/juz/:id', params: {id:id} }, ...(params ? [params] : [])] as const

export type GetQuranJuzIdQueryKey = ReturnType<typeof getQuranJuzIdQueryKey>

/**
 * @description Get a specific juz by its ID
 * @summary Get juz by ID
 * {@link /quran/juz/:id}
 */
export async function getQuranJuzIdHook(id: GetQuranJuzIdPathParams["id"], params?: GetQuranJuzIdQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetQuranJuzIdQueryResponse, ResponseErrorConfig<GetQuranJuzId400 | GetQuranJuzId404 | GetQuranJuzId500>, unknown>({ method : "GET", url : `/quran/juz/${id}`, params, ... requestConfig })  
  return res.data
}

export function getQuranJuzIdQueryOptionsHook(id: GetQuranJuzIdPathParams["id"], params?: GetQuranJuzIdQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getQuranJuzIdQueryKey(id, params)
  return queryOptions<GetQuranJuzIdQueryResponse, ResponseErrorConfig<GetQuranJuzId400 | GetQuranJuzId404 | GetQuranJuzId500>, GetQuranJuzIdQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getQuranJuzIdHook(id, params, config)
   },
  })
}

/**
 * @description Get a specific juz by its ID
 * @summary Get juz by ID
 * {@link /quran/juz/:id}
 */
export function useGetQuranJuzIdHook<TData = GetQuranJuzIdQueryResponse, TQueryData = GetQuranJuzIdQueryResponse, TQueryKey extends QueryKey = GetQuranJuzIdQueryKey>(id: GetQuranJuzIdPathParams["id"], params?: GetQuranJuzIdQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetQuranJuzIdQueryResponse, ResponseErrorConfig<GetQuranJuzId400 | GetQuranJuzId404 | GetQuranJuzId500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getQuranJuzIdQueryKey(id, params)

  const query = useQuery({
   ...getQuranJuzIdQueryOptionsHook(id, params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetQuranJuzId400 | GetQuranJuzId404 | GetQuranJuzId500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}