/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetQuranJuzQueryResponse, GetQuranJuzQueryParams, GetQuranJuz400, GetQuranJuz500 } from "../../types/GetQuranJuz.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getQuranJuzQueryKey = (params?: GetQuranJuzQueryParams) => [{ url: '/quran/juz' }, ...(params ? [params] : [])] as const

export type GetQuranJuzQueryKey = ReturnType<typeof getQuranJuzQueryKey>

/**
 * @description Get all juz with pagination
 * @summary Get all juz
 * {@link /quran/juz}
 */
export async function getQuranJuzHook(params?: GetQuranJuzQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetQuranJuzQueryResponse, ResponseErrorConfig<GetQuranJuz400 | GetQuranJuz500>, unknown>({ method : "GET", url : `/quran/juz`, params, ... requestConfig })  
  return res.data
}

export function getQuranJuzQueryOptionsHook(params?: GetQuranJuzQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getQuranJuzQueryKey(params)
  return queryOptions<GetQuranJuzQueryResponse, ResponseErrorConfig<GetQuranJuz400 | GetQuranJuz500>, GetQuranJuzQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getQuranJuzHook(params, config)
   },
  })
}

/**
 * @description Get all juz with pagination
 * @summary Get all juz
 * {@link /quran/juz}
 */
export function useGetQuranJuzHook<TData = GetQuranJuzQueryResponse, TQueryData = GetQuranJuzQueryResponse, TQueryKey extends QueryKey = GetQuranJuzQueryKey>(params?: GetQuranJuzQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetQuranJuzQueryResponse, ResponseErrorConfig<GetQuranJuz400 | GetQuranJuz500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getQuranJuzQueryKey(params)

  const query = useQuery({
   ...getQuranJuzQueryOptionsHook(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetQuranJuz400 | GetQuranJuz500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}