/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetQuranJuzWithProgressQueryResponse, GetQuranJuzWithProgressQueryParams, GetQuranJuzWithProgress400, GetQuranJuzWithProgress500 } from "../../types/GetQuranJuzWithProgress.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getQuranJuzWithProgressQueryKey = (params?: GetQuranJuzWithProgressQueryParams) => [{ url: '/quran/juz/with-progress' }, ...(params ? [params] : [])] as const

export type GetQuranJuzWithProgressQueryKey = ReturnType<typeof getQuranJuzWithProgressQueryKey>

/**
 * @description Returns all Juz combined with the authenticated user's hatam progress per Juz
 * @summary List all Juz with user ProgressHatam
 * {@link /quran/juz/with-progress}
 */
export async function getQuranJuzWithProgressHook(params?: GetQuranJuzWithProgressQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetQuranJuzWithProgressQueryResponse, ResponseErrorConfig<GetQuranJuzWithProgress400 | GetQuranJuzWithProgress500>, unknown>({ method : "GET", url : `/quran/juz/with-progress`, params, ... requestConfig })  
  return res.data
}

export function getQuranJuzWithProgressQueryOptionsHook(params?: GetQuranJuzWithProgressQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getQuranJuzWithProgressQueryKey(params)
  return queryOptions<GetQuranJuzWithProgressQueryResponse, ResponseErrorConfig<GetQuranJuzWithProgress400 | GetQuranJuzWithProgress500>, GetQuranJuzWithProgressQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getQuranJuzWithProgressHook(params, config)
   },
  })
}

/**
 * @description Returns all Juz combined with the authenticated user's hatam progress per Juz
 * @summary List all Juz with user ProgressHatam
 * {@link /quran/juz/with-progress}
 */
export function useGetQuranJuzWithProgressHook<TData = GetQuranJuzWithProgressQueryResponse, TQueryData = GetQuranJuzWithProgressQueryResponse, TQueryKey extends QueryKey = GetQuranJuzWithProgressQueryKey>(params?: GetQuranJuzWithProgressQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetQuranJuzWithProgressQueryResponse, ResponseErrorConfig<GetQuranJuzWithProgress400 | GetQuranJuzWithProgress500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getQuranJuzWithProgressQueryKey(params)

  const query = useQuery({
   ...getQuranJuzWithProgressQueryOptionsHook(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetQuranJuzWithProgress400 | GetQuranJuzWithProgress500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}