/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetQuranJuzNumberQueryResponse, GetQuranJuzNumberPathParams, GetQuranJuzNumberQueryParams, GetQuranJuzNumber400, GetQuranJuzNumber404, GetQuranJuzNumber500 } from "../../types/GetQuranJuzNumberNumber.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getQuranJuzNumberNumberQueryKey = (number: GetQuranJuzNumberPathParams["number"], params?: GetQuranJuzNumberQueryParams) => [{ url: '/quran/juz/number/:number', params: {number:number} }, ...(params ? [params] : [])] as const

export type GetQuranJuzNumberNumberQueryKey = ReturnType<typeof getQuranJuzNumberNumberQueryKey>

/**
 * @description Get a specific juz by its number
 * @summary Get juz by number
 * {@link /quran/juz/number/:number}
 */
export async function getQuranJuzNumberNumberHook(number: GetQuranJuzNumberPathParams["number"], params?: GetQuranJuzNumberQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetQuranJuzNumberQueryResponse, ResponseErrorConfig<GetQuranJuzNumber400 | GetQuranJuzNumber404 | GetQuranJuzNumber500>, unknown>({ method : "GET", url : `/quran/juz/number/${number}`, params, ... requestConfig })  
  return res.data
}

export function getQuranJuzNumberNumberQueryOptionsHook(number: GetQuranJuzNumberPathParams["number"], params?: GetQuranJuzNumberQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getQuranJuzNumberNumberQueryKey(number, params)
  return queryOptions<GetQuranJuzNumberQueryResponse, ResponseErrorConfig<GetQuranJuzNumber400 | GetQuranJuzNumber404 | GetQuranJuzNumber500>, GetQuranJuzNumberQueryResponse, typeof queryKey>({
   enabled: !!(number),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getQuranJuzNumberNumberHook(number, params, config)
   },
  })
}

/**
 * @description Get a specific juz by its number
 * @summary Get juz by number
 * {@link /quran/juz/number/:number}
 */
export function useGetQuranJuzNumberNumberHook<TData = GetQuranJuzNumberQueryResponse, TQueryData = GetQuranJuzNumberQueryResponse, TQueryKey extends QueryKey = GetQuranJuzNumberNumberQueryKey>(number: GetQuranJuzNumberPathParams["number"], params?: GetQuranJuzNumberQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetQuranJuzNumberQueryResponse, ResponseErrorConfig<GetQuranJuzNumber400 | GetQuranJuzNumber404 | GetQuranJuzNumber500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getQuranJuzNumberNumberQueryKey(number, params)

  const query = useQuery({
   ...getQuranJuzNumberNumberQueryOptionsHook(number, params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetQuranJuzNumber400 | GetQuranJuzNumber404 | GetQuranJuzNumber500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}