/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { PutQuranJuzIdMutationRequest, PutQuranJuzIdMutationResponse, PutQuranJuzIdPathParams, PutQuranJuzId400, PutQuranJuzId404, PutQuranJuzId500 } from "../../types/PutQuranJuzId.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const putQuranJuzIdMutationKey = () => [{ url: '/quran/juz/:id' }] as const

export type PutQuranJuzIdMutationKey = ReturnType<typeof putQuranJuzIdMutationKey>

/**
 * @description Update an existing juz with the provided information
 * @summary Update a juz
 * {@link /quran/juz/:id}
 */
export async function putQuranJuzIdHook(id: PutQuranJuzIdPathParams["id"], data: PutQuranJuzIdMutationRequest, config: Partial<RequestConfig<PutQuranJuzIdMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PutQuranJuzIdMutationResponse, ResponseErrorConfig<PutQuranJuzId400 | PutQuranJuzId404 | PutQuranJuzId500>, PutQuranJuzIdMutationRequest>({ method : "PUT", url : `/quran/juz/${id}`, data : requestData, ... requestConfig })  
  return res.data
}

export function putQuranJuzIdMutationOptionsHook(config: Partial<RequestConfig<PutQuranJuzIdMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = putQuranJuzIdMutationKey()
  return mutationOptions<PutQuranJuzIdMutationResponse, ResponseErrorConfig<PutQuranJuzId400 | PutQuranJuzId404 | PutQuranJuzId500>, {id: PutQuranJuzIdPathParams["id"], data: PutQuranJuzIdMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id, data }) => {
      return putQuranJuzIdHook(id, data, config)
    },
  })
}

/**
 * @description Update an existing juz with the provided information
 * @summary Update a juz
 * {@link /quran/juz/:id}
 */
export function usePutQuranJuzIdHook<TContext>(options: 
{
  mutation?: UseMutationOptions<PutQuranJuzIdMutationResponse, ResponseErrorConfig<PutQuranJuzId400 | PutQuranJuzId404 | PutQuranJuzId500>, {id: PutQuranJuzIdPathParams["id"], data: PutQuranJuzIdMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PutQuranJuzIdMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? putQuranJuzIdMutationKey()

  const baseOptions = putQuranJuzIdMutationOptionsHook(config) as UseMutationOptions<PutQuranJuzIdMutationResponse, ResponseErrorConfig<PutQuranJuzId400 | PutQuranJuzId404 | PutQuranJuzId500>, {id: PutQuranJuzIdPathParams["id"], data: PutQuranJuzIdMutationRequest}, TContext>

  return useMutation<PutQuranJuzIdMutationResponse, ResponseErrorConfig<PutQuranJuzId400 | PutQuranJuzId404 | PutQuranJuzId500>, {id: PutQuranJuzIdPathParams["id"], data: PutQuranJuzIdMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<PutQuranJuzIdMutationResponse, ResponseErrorConfig<PutQuranJuzId400 | PutQuranJuzId404 | PutQuranJuzId500>, {id: PutQuranJuzIdPathParams["id"], data: PutQuranJuzIdMutationRequest}, TContext>
}