/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { PostQuranJuzMutationRequest, PostQuranJuzMutationResponse, PostQuranJuz400, PostQuranJuz500 } from "../../types/PostQuranJuz.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postQuranJuzMutationKey = () => [{ url: '/quran/juz' }] as const

export type PostQuranJuzMutationKey = ReturnType<typeof postQuranJuzMutationKey>

/**
 * @description Create a new juz with the provided information
 * @summary Create a new juz
 * {@link /quran/juz}
 */
export async function postQuranJuzHook(data: PostQuranJuzMutationRequest, config: Partial<RequestConfig<PostQuranJuzMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostQuranJuzMutationResponse, ResponseErrorConfig<PostQuranJuz400 | PostQuranJuz500>, PostQuranJuzMutationRequest>({ method : "POST", url : `/quran/juz`, data : requestData, ... requestConfig })  
  return res.data
}

export function postQuranJuzMutationOptionsHook(config: Partial<RequestConfig<PostQuranJuzMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = postQuranJuzMutationKey()
  return mutationOptions<PostQuranJuzMutationResponse, ResponseErrorConfig<PostQuranJuz400 | PostQuranJuz500>, {data: PostQuranJuzMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return postQuranJuzHook(data, config)
    },
  })
}

/**
 * @description Create a new juz with the provided information
 * @summary Create a new juz
 * {@link /quran/juz}
 */
export function usePostQuranJuzHook<TContext>(options: 
{
  mutation?: UseMutationOptions<PostQuranJuzMutationResponse, ResponseErrorConfig<PostQuranJuz400 | PostQuranJuz500>, {data: PostQuranJuzMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostQuranJuzMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postQuranJuzMutationKey()

  const baseOptions = postQuranJuzMutationOptionsHook(config) as UseMutationOptions<PostQuranJuzMutationResponse, ResponseErrorConfig<PostQuranJuz400 | PostQuranJuz500>, {data: PostQuranJuzMutationRequest}, TContext>

  return useMutation<PostQuranJuzMutationResponse, ResponseErrorConfig<PostQuranJuz400 | PostQuranJuz500>, {data: PostQuranJuzMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<PostQuranJuzMutationResponse, ResponseErrorConfig<PostQuranJuz400 | PostQuranJuz500>, {data: PostQuranJuzMutationRequest}, TContext>
}