/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetPrayertimesYearlyQueryParams, GetPrayertimesYearly200, GetPrayertimesYearly400, GetPrayertimesYearly500, GetPrayertimesYearlyQueryResponse } from "../../types/GetPrayertimesYearly.ts";
import { prayertimesPrayerTimesErrorResponseSchema } from "../prayertimes/prayerTimesErrorResponseSchema.ts";
import { prayertimesPrayerTimesListSuccessResponseSchema } from "../prayertimes/prayerTimesListSuccessResponseSchema.ts";
import { z } from "zod";

export const getPrayertimesYearlyQueryParamsSchema = z.object({
    "latitude": z.coerce.number().describe("Latitude"),
"longitude": z.coerce.number().describe("Longitude"),
"timezone": z.string().describe("Timezone (IANA)"),
"year": z.coerce.number().int().describe("Year"),
"method": z.optional(z.coerce.number().int().describe("Calculation method (provider-specific)"))
    }) as unknown as z.ZodType<GetPrayertimesYearlyQueryParams>

/**
 * @description Prayer times list retrieved successfully
 */
export const getPrayertimesYearly200Schema = prayertimesPrayerTimesListSuccessResponseSchema as unknown as z.ZodType<GetPrayertimesYearly200>

/**
 * @description Bad request
 */
export const getPrayertimesYearly400Schema = prayertimesPrayerTimesErrorResponseSchema as unknown as z.ZodType<GetPrayertimesYearly400>

/**
 * @description Internal server error
 */
export const getPrayertimesYearly500Schema = prayertimesPrayerTimesErrorResponseSchema as unknown as z.ZodType<GetPrayertimesYearly500>

export const getPrayertimesYearlyQueryResponseSchema = getPrayertimesYearly200Schema as unknown as z.ZodType<GetPrayertimesYearlyQueryResponse>