/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetPrayertimesMonthlyQueryParams, GetPrayertimesMonthly200, GetPrayertimesMonthly400, GetPrayertimesMonthly500, GetPrayertimesMonthlyQueryResponse } from "../../types/GetPrayertimesMonthly.ts";
import { prayertimesPrayerTimesErrorResponseSchema } from "../prayertimes/prayerTimesErrorResponseSchema.ts";
import { prayertimesPrayerTimesListSuccessResponseSchema } from "../prayertimes/prayerTimesListSuccessResponseSchema.ts";
import { z } from "zod";

export const getPrayertimesMonthlyQueryParamsSchema = z.object({
    "latitude": z.coerce.number().describe("Latitude"),
"longitude": z.coerce.number().describe("Longitude"),
"timezone": z.string().describe("Timezone (IANA)"),
"month": z.coerce.number().int().describe("Month (1-12)"),
"year": z.coerce.number().int().describe("Year"),
"method": z.optional(z.coerce.number().int().describe("Calculation method (provider-specific)"))
    }) as unknown as z.ZodType<GetPrayertimesMonthlyQueryParams>

/**
 * @description Prayer times list retrieved successfully
 */
export const getPrayertimesMonthly200Schema = prayertimesPrayerTimesListSuccessResponseSchema as unknown as z.ZodType<GetPrayertimesMonthly200>

/**
 * @description Bad request
 */
export const getPrayertimesMonthly400Schema = prayertimesPrayerTimesErrorResponseSchema as unknown as z.ZodType<GetPrayertimesMonthly400>

/**
 * @description Internal server error
 */
export const getPrayertimesMonthly500Schema = prayertimesPrayerTimesErrorResponseSchema as unknown as z.ZodType<GetPrayertimesMonthly500>

export const getPrayertimesMonthlyQueryResponseSchema = getPrayertimesMonthly200Schema as unknown as z.ZodType<GetPrayertimesMonthlyQueryResponse>