/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetPrayertimesDailyQueryParams, GetPrayertimesDaily200, GetPrayertimesDaily400, GetPrayertimesDaily500, GetPrayertimesDailyQueryResponse } from "../../types/GetPrayertimesDaily.ts";
import { prayertimesPrayerTimesErrorResponseSchema } from "../prayertimes/prayerTimesErrorResponseSchema.ts";
import { prayertimesPrayerTimesSuccessResponseSchema } from "../prayertimes/prayerTimesSuccessResponseSchema.ts";
import { z } from "zod";

export const getPrayertimesDailyQueryParamsSchema = z.object({
    "latitude": z.coerce.number().describe("Latitude"),
"longitude": z.coerce.number().describe("Longitude"),
"timezone": z.string().describe("Timezone (IANA)"),
"date": z.optional(z.string().describe("Date (YYYY-MM-DD)")),
"method": z.optional(z.coerce.number().int().describe("Calculation method (provider-specific)"))
    }) as unknown as z.ZodType<GetPrayertimesDailyQueryParams>

/**
 * @description Prayer times retrieved successfully
 */
export const getPrayertimesDaily200Schema = prayertimesPrayerTimesSuccessResponseSchema as unknown as z.ZodType<GetPrayertimesDaily200>

/**
 * @description Bad request
 */
export const getPrayertimesDaily400Schema = prayertimesPrayerTimesErrorResponseSchema as unknown as z.ZodType<GetPrayertimesDaily400>

/**
 * @description Internal server error
 */
export const getPrayertimesDaily500Schema = prayertimesPrayerTimesErrorResponseSchema as unknown as z.ZodType<GetPrayertimesDaily500>

export const getPrayertimesDailyQueryResponseSchema = getPrayertimesDaily200Schema as unknown as z.ZodType<GetPrayertimesDailyQueryResponse>