/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetQuranTranslationsAyahsSurahSurahidEditionEditionidQueryResponse, GetQuranTranslationsAyahsSurahSurahidEditionEditionidPathParams, GetQuranTranslationsAyahsSurahSurahidEditionEditionidQueryParams, GetQuranTranslationsAyahsSurahSurahidEditionEditionid400, GetQuranTranslationsAyahsSurahSurahidEditionEditionid500 } from "../../types/GetQuranTranslationsAyahsSurahSurahidEditionEditionid.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getQuranTranslationsAyahsSurahSurahidEditionEditionidQueryKey = (surahId: GetQuranTranslationsAyahsSurahSurahidEditionEditionidPathParams["surahId"], editionId: GetQuranTranslationsAyahsSurahSurahidEditionEditionidPathParams["editionId"], params?: GetQuranTranslationsAyahsSurahSurahidEditionEditionidQueryParams) => [{ url: '/quran/translations/ayahs/surah/:surahId/edition/:editionId', params: {surahId:surahId,editionId:editionId} }, ...(params ? [params] : [])] as const

export type GetQuranTranslationsAyahsSurahSurahidEditionEditionidQueryKey = ReturnType<typeof getQuranTranslationsAyahsSurahSurahidEditionEditionidQueryKey>

/**
 * @description Get translated ayahs for a surah by translation edition with pagination
 * @summary Get ayah translations by surah and edition
 * {@link /quran/translations/ayahs/surah/:surahId/edition/:editionId}
 */
export async function getQuranTranslationsAyahsSurahSurahidEditionEditionidHook(surahId: GetQuranTranslationsAyahsSurahSurahidEditionEditionidPathParams["surahId"], editionId: GetQuranTranslationsAyahsSurahSurahidEditionEditionidPathParams["editionId"], params?: GetQuranTranslationsAyahsSurahSurahidEditionEditionidQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetQuranTranslationsAyahsSurahSurahidEditionEditionidQueryResponse, ResponseErrorConfig<GetQuranTranslationsAyahsSurahSurahidEditionEditionid400 | GetQuranTranslationsAyahsSurahSurahidEditionEditionid500>, unknown>({ method : "GET", url : `/quran/translations/ayahs/surah/${surahId}/edition/${editionId}`, params, ... requestConfig })  
  return res.data
}

export function getQuranTranslationsAyahsSurahSurahidEditionEditionidQueryOptionsHook(surahId: GetQuranTranslationsAyahsSurahSurahidEditionEditionidPathParams["surahId"], editionId: GetQuranTranslationsAyahsSurahSurahidEditionEditionidPathParams["editionId"], params?: GetQuranTranslationsAyahsSurahSurahidEditionEditionidQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getQuranTranslationsAyahsSurahSurahidEditionEditionidQueryKey(surahId, editionId, params)
  return queryOptions<GetQuranTranslationsAyahsSurahSurahidEditionEditionidQueryResponse, ResponseErrorConfig<GetQuranTranslationsAyahsSurahSurahidEditionEditionid400 | GetQuranTranslationsAyahsSurahSurahidEditionEditionid500>, GetQuranTranslationsAyahsSurahSurahidEditionEditionidQueryResponse, typeof queryKey>({
   enabled: !!(surahId&& editionId),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getQuranTranslationsAyahsSurahSurahidEditionEditionidHook(surahId, editionId, params, config)
   },
  })
}

/**
 * @description Get translated ayahs for a surah by translation edition with pagination
 * @summary Get ayah translations by surah and edition
 * {@link /quran/translations/ayahs/surah/:surahId/edition/:editionId}
 */
export function useGetQuranTranslationsAyahsSurahSurahidEditionEditionidHook<TData = GetQuranTranslationsAyahsSurahSurahidEditionEditionidQueryResponse, TQueryData = GetQuranTranslationsAyahsSurahSurahidEditionEditionidQueryResponse, TQueryKey extends QueryKey = GetQuranTranslationsAyahsSurahSurahidEditionEditionidQueryKey>(surahId: GetQuranTranslationsAyahsSurahSurahidEditionEditionidPathParams["surahId"], editionId: GetQuranTranslationsAyahsSurahSurahidEditionEditionidPathParams["editionId"], params?: GetQuranTranslationsAyahsSurahSurahidEditionEditionidQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetQuranTranslationsAyahsSurahSurahidEditionEditionidQueryResponse, ResponseErrorConfig<GetQuranTranslationsAyahsSurahSurahidEditionEditionid400 | GetQuranTranslationsAyahsSurahSurahidEditionEditionid500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getQuranTranslationsAyahsSurahSurahidEditionEditionidQueryKey(surahId, editionId, params)

  const query = useQuery({
   ...getQuranTranslationsAyahsSurahSurahidEditionEditionidQueryOptionsHook(surahId, editionId, params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetQuranTranslationsAyahsSurahSurahidEditionEditionid400 | GetQuranTranslationsAyahsSurahSurahidEditionEditionid500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}