/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetQuranTranslationsEditionsQueryResponse, GetQuranTranslationsEditionsQueryParams, GetQuranTranslationsEditions400, GetQuranTranslationsEditions500 } from "../../types/GetQuranTranslationsEditions.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getQuranTranslationsEditionsQueryKey = (params?: GetQuranTranslationsEditionsQueryParams) => [{ url: '/quran/translations/editions' }, ...(params ? [params] : [])] as const

export type GetQuranTranslationsEditionsQueryKey = ReturnType<typeof getQuranTranslationsEditionsQueryKey>

/**
 * @description Get translation editions with optional language filter and pagination
 * @summary Get translation editions
 * {@link /quran/translations/editions}
 */
export async function getQuranTranslationsEditionsHook(params?: GetQuranTranslationsEditionsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetQuranTranslationsEditionsQueryResponse, ResponseErrorConfig<GetQuranTranslationsEditions400 | GetQuranTranslationsEditions500>, unknown>({ method : "GET", url : `/quran/translations/editions`, params, ... requestConfig })  
  return res.data
}

export function getQuranTranslationsEditionsQueryOptionsHook(params?: GetQuranTranslationsEditionsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getQuranTranslationsEditionsQueryKey(params)
  return queryOptions<GetQuranTranslationsEditionsQueryResponse, ResponseErrorConfig<GetQuranTranslationsEditions400 | GetQuranTranslationsEditions500>, GetQuranTranslationsEditionsQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getQuranTranslationsEditionsHook(params, config)
   },
  })
}

/**
 * @description Get translation editions with optional language filter and pagination
 * @summary Get translation editions
 * {@link /quran/translations/editions}
 */
export function useGetQuranTranslationsEditionsHook<TData = GetQuranTranslationsEditionsQueryResponse, TQueryData = GetQuranTranslationsEditionsQueryResponse, TQueryKey extends QueryKey = GetQuranTranslationsEditionsQueryKey>(params?: GetQuranTranslationsEditionsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetQuranTranslationsEditionsQueryResponse, ResponseErrorConfig<GetQuranTranslationsEditions400 | GetQuranTranslationsEditions500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getQuranTranslationsEditionsQueryKey(params)

  const query = useQuery({
   ...getQuranTranslationsEditionsQueryOptionsHook(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetQuranTranslationsEditions400 | GetQuranTranslationsEditions500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}