/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetQuranTranslationsAyahsAyahAyahidEditionEditionidQueryResponse, GetQuranTranslationsAyahsAyahAyahidEditionEditionidPathParams, GetQuranTranslationsAyahsAyahAyahidEditionEditionid400, GetQuranTranslationsAyahsAyahAyahidEditionEditionid404, GetQuranTranslationsAyahsAyahAyahidEditionEditionid500 } from "../../types/GetQuranTranslationsAyahsAyahAyahidEditionEditionid.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getQuranTranslationsAyahsAyahAyahidEditionEditionidQueryKey = (ayahId: GetQuranTranslationsAyahsAyahAyahidEditionEditionidPathParams["ayahId"], editionId: GetQuranTranslationsAyahsAyahAyahidEditionEditionidPathParams["editionId"]) => [{ url: '/quran/translations/ayahs/ayah/:ayahId/edition/:editionId', params: {ayahId:ayahId,editionId:editionId} }] as const

export type GetQuranTranslationsAyahsAyahAyahidEditionEditionidQueryKey = ReturnType<typeof getQuranTranslationsAyahsAyahAyahidEditionEditionidQueryKey>

/**
 * @description Get a translated ayah text by ayah ID and translation edition ID
 * @summary Get ayah translation by ayah and edition
 * {@link /quran/translations/ayahs/ayah/:ayahId/edition/:editionId}
 */
export async function getQuranTranslationsAyahsAyahAyahidEditionEditionidHook(ayahId: GetQuranTranslationsAyahsAyahAyahidEditionEditionidPathParams["ayahId"], editionId: GetQuranTranslationsAyahsAyahAyahidEditionEditionidPathParams["editionId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetQuranTranslationsAyahsAyahAyahidEditionEditionidQueryResponse, ResponseErrorConfig<GetQuranTranslationsAyahsAyahAyahidEditionEditionid400 | GetQuranTranslationsAyahsAyahAyahidEditionEditionid404 | GetQuranTranslationsAyahsAyahAyahidEditionEditionid500>, unknown>({ method : "GET", url : `/quran/translations/ayahs/ayah/${ayahId}/edition/${editionId}`, ... requestConfig })  
  return res.data
}

export function getQuranTranslationsAyahsAyahAyahidEditionEditionidQueryOptionsHook(ayahId: GetQuranTranslationsAyahsAyahAyahidEditionEditionidPathParams["ayahId"], editionId: GetQuranTranslationsAyahsAyahAyahidEditionEditionidPathParams["editionId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getQuranTranslationsAyahsAyahAyahidEditionEditionidQueryKey(ayahId, editionId)
  return queryOptions<GetQuranTranslationsAyahsAyahAyahidEditionEditionidQueryResponse, ResponseErrorConfig<GetQuranTranslationsAyahsAyahAyahidEditionEditionid400 | GetQuranTranslationsAyahsAyahAyahidEditionEditionid404 | GetQuranTranslationsAyahsAyahAyahidEditionEditionid500>, GetQuranTranslationsAyahsAyahAyahidEditionEditionidQueryResponse, typeof queryKey>({
   enabled: !!(ayahId&& editionId),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getQuranTranslationsAyahsAyahAyahidEditionEditionidHook(ayahId, editionId, config)
   },
  })
}

/**
 * @description Get a translated ayah text by ayah ID and translation edition ID
 * @summary Get ayah translation by ayah and edition
 * {@link /quran/translations/ayahs/ayah/:ayahId/edition/:editionId}
 */
export function useGetQuranTranslationsAyahsAyahAyahidEditionEditionidHook<TData = GetQuranTranslationsAyahsAyahAyahidEditionEditionidQueryResponse, TQueryData = GetQuranTranslationsAyahsAyahAyahidEditionEditionidQueryResponse, TQueryKey extends QueryKey = GetQuranTranslationsAyahsAyahAyahidEditionEditionidQueryKey>(ayahId: GetQuranTranslationsAyahsAyahAyahidEditionEditionidPathParams["ayahId"], editionId: GetQuranTranslationsAyahsAyahAyahidEditionEditionidPathParams["editionId"], options: 
{
  query?: Partial<QueryObserverOptions<GetQuranTranslationsAyahsAyahAyahidEditionEditionidQueryResponse, ResponseErrorConfig<GetQuranTranslationsAyahsAyahAyahidEditionEditionid400 | GetQuranTranslationsAyahsAyahAyahidEditionEditionid404 | GetQuranTranslationsAyahsAyahAyahidEditionEditionid500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getQuranTranslationsAyahsAyahAyahidEditionEditionidQueryKey(ayahId, editionId)

  const query = useQuery({
   ...getQuranTranslationsAyahsAyahAyahidEditionEditionidQueryOptionsHook(ayahId, editionId, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetQuranTranslationsAyahsAyahAyahidEditionEditionid400 | GetQuranTranslationsAyahsAyahAyahidEditionEditionid404 | GetQuranTranslationsAyahsAyahAyahidEditionEditionid500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}