/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { DeleteQuranLastReadsIdMutationResponse, DeleteQuranLastReadsIdPathParams, DeleteQuranLastReadsId400, DeleteQuranLastReadsId404, DeleteQuranLastReadsId500 } from "../../types/DeleteQuranLastReadsId.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteQuranLastReadsIdMutationKey = () => [{ url: '/quran/last-reads/:id' }] as const

export type DeleteQuranLastReadsIdMutationKey = ReturnType<typeof deleteQuranLastReadsIdMutationKey>

/**
 * @description Delete a last read entry by its ID
 * @summary Delete last read
 * {@link /quran/last-reads/:id}
 */
export async function deleteQuranLastReadsIdHook(id: DeleteQuranLastReadsIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteQuranLastReadsIdMutationResponse, ResponseErrorConfig<DeleteQuranLastReadsId400 | DeleteQuranLastReadsId404 | DeleteQuranLastReadsId500>, unknown>({ method : "DELETE", url : `/quran/last-reads/${id}`, ... requestConfig })  
  return res.data
}

export function deleteQuranLastReadsIdMutationOptionsHook(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = deleteQuranLastReadsIdMutationKey()
  return mutationOptions<DeleteQuranLastReadsIdMutationResponse, ResponseErrorConfig<DeleteQuranLastReadsId400 | DeleteQuranLastReadsId404 | DeleteQuranLastReadsId500>, {id: DeleteQuranLastReadsIdPathParams["id"]}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id }) => {
      return deleteQuranLastReadsIdHook(id, config)
    },
  })
}

/**
 * @description Delete a last read entry by its ID
 * @summary Delete last read
 * {@link /quran/last-reads/:id}
 */
export function useDeleteQuranLastReadsIdHook<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteQuranLastReadsIdMutationResponse, ResponseErrorConfig<DeleteQuranLastReadsId400 | DeleteQuranLastReadsId404 | DeleteQuranLastReadsId500>, {id: DeleteQuranLastReadsIdPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteQuranLastReadsIdMutationKey()

  const baseOptions = deleteQuranLastReadsIdMutationOptionsHook(config) as UseMutationOptions<DeleteQuranLastReadsIdMutationResponse, ResponseErrorConfig<DeleteQuranLastReadsId400 | DeleteQuranLastReadsId404 | DeleteQuranLastReadsId500>, {id: DeleteQuranLastReadsIdPathParams["id"]}, TContext>

  return useMutation<DeleteQuranLastReadsIdMutationResponse, ResponseErrorConfig<DeleteQuranLastReadsId400 | DeleteQuranLastReadsId404 | DeleteQuranLastReadsId500>, {id: DeleteQuranLastReadsIdPathParams["id"]}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<DeleteQuranLastReadsIdMutationResponse, ResponseErrorConfig<DeleteQuranLastReadsId400 | DeleteQuranLastReadsId404 | DeleteQuranLastReadsId500>, {id: DeleteQuranLastReadsIdPathParams["id"]}, TContext>
}