/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetQuranLastReadsQueryResponse, GetQuranLastReadsQueryParams, GetQuranLastReads400, GetQuranLastReads500 } from "../../types/GetQuranLastReads.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getQuranLastReadsQueryKey = (params?: GetQuranLastReadsQueryParams) => [{ url: '/quran/last-reads' }, ...(params ? [params] : [])] as const

export type GetQuranLastReadsQueryKey = ReturnType<typeof getQuranLastReadsQueryKey>

/**
 * @description Get a paginated list of last read entries for the authenticated user
 * @summary List last reads by current user
 * {@link /quran/last-reads}
 */
export async function getQuranLastReadsHook(params?: GetQuranLastReadsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetQuranLastReadsQueryResponse, ResponseErrorConfig<GetQuranLastReads400 | GetQuranLastReads500>, unknown>({ method : "GET", url : `/quran/last-reads`, params, ... requestConfig })  
  return res.data
}

export function getQuranLastReadsQueryOptionsHook(params?: GetQuranLastReadsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getQuranLastReadsQueryKey(params)
  return queryOptions<GetQuranLastReadsQueryResponse, ResponseErrorConfig<GetQuranLastReads400 | GetQuranLastReads500>, GetQuranLastReadsQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getQuranLastReadsHook(params, config)
   },
  })
}

/**
 * @description Get a paginated list of last read entries for the authenticated user
 * @summary List last reads by current user
 * {@link /quran/last-reads}
 */
export function useGetQuranLastReadsHook<TData = GetQuranLastReadsQueryResponse, TQueryData = GetQuranLastReadsQueryResponse, TQueryKey extends QueryKey = GetQuranLastReadsQueryKey>(params?: GetQuranLastReadsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetQuranLastReadsQueryResponse, ResponseErrorConfig<GetQuranLastReads400 | GetQuranLastReads500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getQuranLastReadsQueryKey(params)

  const query = useQuery({
   ...getQuranLastReadsQueryOptionsHook(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetQuranLastReads400 | GetQuranLastReads500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}