/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetQuranLastReadsSurahSurahidQueryResponse, GetQuranLastReadsSurahSurahidPathParams, GetQuranLastReadsSurahSurahidQueryParams, GetQuranLastReadsSurahSurahid400, GetQuranLastReadsSurahSurahid404, GetQuranLastReadsSurahSurahid500 } from "../../types/GetQuranLastReadsSurahSurahid.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getQuranLastReadsSurahSurahidQueryKey = (surahId: GetQuranLastReadsSurahSurahidPathParams["surahId"], params?: GetQuranLastReadsSurahSurahidQueryParams) => [{ url: '/quran/last-reads/surah/:surahId', params: {surahId:surahId} }, ...(params ? [params] : [])] as const

export type GetQuranLastReadsSurahSurahidQueryKey = ReturnType<typeof getQuranLastReadsSurahSurahidQueryKey>

/**
 * @description Get the last read entry for the authenticated user and surah
 * @summary Get last read by current user and surah
 * {@link /quran/last-reads/surah/:surahId}
 */
export async function getQuranLastReadsSurahSurahidHook(surahId: GetQuranLastReadsSurahSurahidPathParams["surahId"], params?: GetQuranLastReadsSurahSurahidQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetQuranLastReadsSurahSurahidQueryResponse, ResponseErrorConfig<GetQuranLastReadsSurahSurahid400 | GetQuranLastReadsSurahSurahid404 | GetQuranLastReadsSurahSurahid500>, unknown>({ method : "GET", url : `/quran/last-reads/surah/${surahId}`, params, ... requestConfig })  
  return res.data
}

export function getQuranLastReadsSurahSurahidQueryOptionsHook(surahId: GetQuranLastReadsSurahSurahidPathParams["surahId"], params?: GetQuranLastReadsSurahSurahidQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getQuranLastReadsSurahSurahidQueryKey(surahId, params)
  return queryOptions<GetQuranLastReadsSurahSurahidQueryResponse, ResponseErrorConfig<GetQuranLastReadsSurahSurahid400 | GetQuranLastReadsSurahSurahid404 | GetQuranLastReadsSurahSurahid500>, GetQuranLastReadsSurahSurahidQueryResponse, typeof queryKey>({
   enabled: !!(surahId),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getQuranLastReadsSurahSurahidHook(surahId, params, config)
   },
  })
}

/**
 * @description Get the last read entry for the authenticated user and surah
 * @summary Get last read by current user and surah
 * {@link /quran/last-reads/surah/:surahId}
 */
export function useGetQuranLastReadsSurahSurahidHook<TData = GetQuranLastReadsSurahSurahidQueryResponse, TQueryData = GetQuranLastReadsSurahSurahidQueryResponse, TQueryKey extends QueryKey = GetQuranLastReadsSurahSurahidQueryKey>(surahId: GetQuranLastReadsSurahSurahidPathParams["surahId"], params?: GetQuranLastReadsSurahSurahidQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetQuranLastReadsSurahSurahidQueryResponse, ResponseErrorConfig<GetQuranLastReadsSurahSurahid400 | GetQuranLastReadsSurahSurahid404 | GetQuranLastReadsSurahSurahid500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getQuranLastReadsSurahSurahidQueryKey(surahId, params)

  const query = useQuery({
   ...getQuranLastReadsSurahSurahidQueryOptionsHook(surahId, params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetQuranLastReadsSurahSurahid400 | GetQuranLastReadsSurahSurahid404 | GetQuranLastReadsSurahSurahid500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}