/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetQuranLastReadsIdQueryResponse, GetQuranLastReadsIdPathParams, GetQuranLastReadsIdQueryParams, GetQuranLastReadsId400, GetQuranLastReadsId404, GetQuranLastReadsId500 } from "../../types/GetQuranLastReadsId.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getQuranLastReadsIdQueryKey = (id: GetQuranLastReadsIdPathParams["id"], params?: GetQuranLastReadsIdQueryParams) => [{ url: '/quran/last-reads/:id', params: {id:id} }, ...(params ? [params] : [])] as const

export type GetQuranLastReadsIdQueryKey = ReturnType<typeof getQuranLastReadsIdQueryKey>

/**
 * @description Get a specific last read entry by its ID
 * @summary Get last read by ID
 * {@link /quran/last-reads/:id}
 */
export async function getQuranLastReadsIdHook(id: GetQuranLastReadsIdPathParams["id"], params?: GetQuranLastReadsIdQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetQuranLastReadsIdQueryResponse, ResponseErrorConfig<GetQuranLastReadsId400 | GetQuranLastReadsId404 | GetQuranLastReadsId500>, unknown>({ method : "GET", url : `/quran/last-reads/${id}`, params, ... requestConfig })  
  return res.data
}

export function getQuranLastReadsIdQueryOptionsHook(id: GetQuranLastReadsIdPathParams["id"], params?: GetQuranLastReadsIdQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getQuranLastReadsIdQueryKey(id, params)
  return queryOptions<GetQuranLastReadsIdQueryResponse, ResponseErrorConfig<GetQuranLastReadsId400 | GetQuranLastReadsId404 | GetQuranLastReadsId500>, GetQuranLastReadsIdQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getQuranLastReadsIdHook(id, params, config)
   },
  })
}

/**
 * @description Get a specific last read entry by its ID
 * @summary Get last read by ID
 * {@link /quran/last-reads/:id}
 */
export function useGetQuranLastReadsIdHook<TData = GetQuranLastReadsIdQueryResponse, TQueryData = GetQuranLastReadsIdQueryResponse, TQueryKey extends QueryKey = GetQuranLastReadsIdQueryKey>(id: GetQuranLastReadsIdPathParams["id"], params?: GetQuranLastReadsIdQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetQuranLastReadsIdQueryResponse, ResponseErrorConfig<GetQuranLastReadsId400 | GetQuranLastReadsId404 | GetQuranLastReadsId500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getQuranLastReadsIdQueryKey(id, params)

  const query = useQuery({
   ...getQuranLastReadsIdQueryOptionsHook(id, params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetQuranLastReadsId400 | GetQuranLastReadsId404 | GetQuranLastReadsId500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}