/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { PutQuranLastReadsIdMutationRequest, PutQuranLastReadsIdMutationResponse, PutQuranLastReadsIdPathParams, PutQuranLastReadsId400, PutQuranLastReadsId404, PutQuranLastReadsId500 } from "../../types/PutQuranLastReadsId.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const putQuranLastReadsIdMutationKey = () => [{ url: '/quran/last-reads/:id' }] as const

export type PutQuranLastReadsIdMutationKey = ReturnType<typeof putQuranLastReadsIdMutationKey>

/**
 * @description Update fields of an existing last read entry
 * @summary Update last read
 * {@link /quran/last-reads/:id}
 */
export async function putQuranLastReadsIdHook(id: PutQuranLastReadsIdPathParams["id"], data: PutQuranLastReadsIdMutationRequest, config: Partial<RequestConfig<PutQuranLastReadsIdMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PutQuranLastReadsIdMutationResponse, ResponseErrorConfig<PutQuranLastReadsId400 | PutQuranLastReadsId404 | PutQuranLastReadsId500>, PutQuranLastReadsIdMutationRequest>({ method : "PUT", url : `/quran/last-reads/${id}`, data : requestData, ... requestConfig })  
  return res.data
}

export function putQuranLastReadsIdMutationOptionsHook(config: Partial<RequestConfig<PutQuranLastReadsIdMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = putQuranLastReadsIdMutationKey()
  return mutationOptions<PutQuranLastReadsIdMutationResponse, ResponseErrorConfig<PutQuranLastReadsId400 | PutQuranLastReadsId404 | PutQuranLastReadsId500>, {id: PutQuranLastReadsIdPathParams["id"], data: PutQuranLastReadsIdMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id, data }) => {
      return putQuranLastReadsIdHook(id, data, config)
    },
  })
}

/**
 * @description Update fields of an existing last read entry
 * @summary Update last read
 * {@link /quran/last-reads/:id}
 */
export function usePutQuranLastReadsIdHook<TContext>(options: 
{
  mutation?: UseMutationOptions<PutQuranLastReadsIdMutationResponse, ResponseErrorConfig<PutQuranLastReadsId400 | PutQuranLastReadsId404 | PutQuranLastReadsId500>, {id: PutQuranLastReadsIdPathParams["id"], data: PutQuranLastReadsIdMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PutQuranLastReadsIdMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? putQuranLastReadsIdMutationKey()

  const baseOptions = putQuranLastReadsIdMutationOptionsHook(config) as UseMutationOptions<PutQuranLastReadsIdMutationResponse, ResponseErrorConfig<PutQuranLastReadsId400 | PutQuranLastReadsId404 | PutQuranLastReadsId500>, {id: PutQuranLastReadsIdPathParams["id"], data: PutQuranLastReadsIdMutationRequest}, TContext>

  return useMutation<PutQuranLastReadsIdMutationResponse, ResponseErrorConfig<PutQuranLastReadsId400 | PutQuranLastReadsId404 | PutQuranLastReadsId500>, {id: PutQuranLastReadsIdPathParams["id"], data: PutQuranLastReadsIdMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<PutQuranLastReadsIdMutationResponse, ResponseErrorConfig<PutQuranLastReadsId400 | PutQuranLastReadsId404 | PutQuranLastReadsId500>, {id: PutQuranLastReadsIdPathParams["id"], data: PutQuranLastReadsIdMutationRequest}, TContext>
}