/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { PostQuranLastReadsMutationRequest, PostQuranLastReadsMutationResponse, PostQuranLastReads400, PostQuranLastReads500 } from "../../types/PostQuranLastReads.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postQuranLastReadsMutationKey = () => [{ url: '/quran/last-reads' }] as const

export type PostQuranLastReadsMutationKey = ReturnType<typeof postQuranLastReadsMutationKey>

/**
 * @description Create a new last read entry for a user
 * @summary Create last read
 * {@link /quran/last-reads}
 */
export async function postQuranLastReadsHook(data: PostQuranLastReadsMutationRequest, config: Partial<RequestConfig<PostQuranLastReadsMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostQuranLastReadsMutationResponse, ResponseErrorConfig<PostQuranLastReads400 | PostQuranLastReads500>, PostQuranLastReadsMutationRequest>({ method : "POST", url : `/quran/last-reads`, data : requestData, ... requestConfig })  
  return res.data
}

export function postQuranLastReadsMutationOptionsHook(config: Partial<RequestConfig<PostQuranLastReadsMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = postQuranLastReadsMutationKey()
  return mutationOptions<PostQuranLastReadsMutationResponse, ResponseErrorConfig<PostQuranLastReads400 | PostQuranLastReads500>, {data: PostQuranLastReadsMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return postQuranLastReadsHook(data, config)
    },
  })
}

/**
 * @description Create a new last read entry for a user
 * @summary Create last read
 * {@link /quran/last-reads}
 */
export function usePostQuranLastReadsHook<TContext>(options: 
{
  mutation?: UseMutationOptions<PostQuranLastReadsMutationResponse, ResponseErrorConfig<PostQuranLastReads400 | PostQuranLastReads500>, {data: PostQuranLastReadsMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostQuranLastReadsMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postQuranLastReadsMutationKey()

  const baseOptions = postQuranLastReadsMutationOptionsHook(config) as UseMutationOptions<PostQuranLastReadsMutationResponse, ResponseErrorConfig<PostQuranLastReads400 | PostQuranLastReads500>, {data: PostQuranLastReadsMutationRequest}, TContext>

  return useMutation<PostQuranLastReadsMutationResponse, ResponseErrorConfig<PostQuranLastReads400 | PostQuranLastReads500>, {data: PostQuranLastReadsMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<PostQuranLastReadsMutationResponse, ResponseErrorConfig<PostQuranLastReads400 | PostQuranLastReads500>, {data: PostQuranLastReadsMutationRequest}, TContext>
}