/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CoreErrorDetail } from "../../types/core/ErrorDetail.ts";
import { z } from "zod";

export const coreErrorDetailSchema = z.object({
    "code": z.optional(z.string()),
"reason": z.optional(z.string())
    }) as unknown as z.ZodType<CoreErrorDetail>