/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoPrayerTimesResponse } from "../dto/PrayerTimesResponse.ts";

export type PrayertimesPrayerTimesSuccessResponse = {
    /**
     * @type object | undefined
    */
    data?: DtoPrayerTimesResponse;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type string | undefined
    */
    responseTime?: string;
    /**
     * @type integer | undefined
    */
    status_code?: number;
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type string | undefined
    */
    timestamp?: string;
};