/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoPrayerTimesListResponse } from "../dto/PrayerTimesListResponse.ts";

export type PrayertimesPrayerTimesListSuccessResponse = {
    /**
     * @type object | undefined
    */
    data?: DtoPrayerTimesListResponse;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type string | undefined
    */
    responseTime?: string;
    /**
     * @type integer | undefined
    */
    status_code?: number;
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type string | undefined
    */
    timestamp?: string;
};