/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoAyahListResponse } from "../../types/dto/AyahListResponse.ts";
import { dtoAyahResponseSchema } from "./ayahResponseSchema.ts";
import { dtoPaginationResponseSchema } from "./paginationResponseSchema.ts";
import { z } from "zod";

export const dtoAyahListResponseSchema = z.object({
    get "data"(){
                return z.array(dtoAyahResponseSchema).optional()
              },
get "pagination"(){
                return dtoPaginationResponseSchema.optional()
              }
    }) as unknown as z.ZodType<DtoAyahListResponse>