/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoAyahTranslationListResponse } from "../../types/dto/AyahTranslationListResponse.ts";
import { dtoAyahTranslationResponseSchema } from "./ayahTranslationResponseSchema.ts";
import { dtoPaginationResponseSchema } from "./paginationResponseSchema.ts";
import { z } from "zod";

export const dtoAyahTranslationListResponseSchema = z.object({
    get "data"(){
                return z.array(dtoAyahTranslationResponseSchema).optional()
              },
get "pagination"(){
                return dtoPaginationResponseSchema.optional()
              }
    }) as unknown as z.ZodType<DtoAyahTranslationListResponse>