/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoAyahAudioFileResponse } from "../../types/dto/AyahAudioFileResponse.ts";
import { z } from "zod";

export const dtoAyahAudioFileResponseSchema = z.object({
    "ayahId": z.optional(z.string()),
"byteSize": z.optional(z.number()),
"createdAt": z.optional(z.string()),
"createdBy": z.optional(z.string()),
"duration": z.optional(z.number()),
"filePath": z.optional(z.string()),
"id": z.optional(z.string()),
"reciterId": z.optional(z.string()),
"surahId": z.optional(z.string()),
"updatedAt": z.optional(z.string()),
"updatedBy": z.optional(z.string())
    }) as unknown as z.ZodType<DtoAyahAudioFileResponse>