/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoAyahWithTranslationResponse } from "../../types/dto/AyahWithTranslationResponse.ts";
import { dtoAyahAudioFileResponseSchema } from "./ayahAudioFileResponseSchema.ts";
import { dtoAyahTranslationResponseSchema } from "./ayahTranslationResponseSchema.ts";
import { z } from "zod";

export const dtoAyahWithTranslationResponseSchema = z.object({
    get "audio"(){
                return dtoAyahAudioFileResponseSchema.optional()
              },
"createdAt": z.optional(z.string()),
"createdBy": z.optional(z.string()),
"hizbNumber": z.optional(z.int()),
"id": z.optional(z.string()),
"juzNumber": z.optional(z.int()),
"manzilNumber": z.optional(z.int()),
"pageNumber": z.optional(z.int()),
"surahId": z.optional(z.string()),
"text": z.optional(z.string()),
get "translation"(){
                return dtoAyahTranslationResponseSchema.optional()
              },
"updatedAt": z.optional(z.string()),
"updatedBy": z.optional(z.string())
    }) as unknown as z.ZodType<DtoAyahWithTranslationResponse>