/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoAyahAudioFileListResponse } from "../../types/dto/AyahAudioFileListResponse.ts";
import { dtoAyahAudioFileResponseSchema } from "./ayahAudioFileResponseSchema.ts";
import { dtoPaginationResponseSchema } from "./paginationResponseSchema.ts";
import { z } from "zod";

export const dtoAyahAudioFileListResponseSchema = z.object({
    get "data"(){
                return z.array(dtoAyahAudioFileResponseSchema).optional()
              },
get "pagination"(){
                return dtoPaginationResponseSchema.optional()
              }
    }) as unknown as z.ZodType<DtoAyahAudioFileListResponse>