/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoAyahResponse } from "../../types/dto/AyahResponse.ts";
import { z } from "zod";

export const dtoAyahResponseSchema = z.object({
    "createdAt": z.optional(z.string()),
"createdBy": z.optional(z.string()),
"hizbNumber": z.optional(z.int()),
"id": z.optional(z.string()),
"juzNumber": z.optional(z.int()),
"manzilNumber": z.optional(z.int()),
"pageNumber": z.optional(z.int()),
"surahId": z.optional(z.string()),
"text": z.optional(z.string()),
"updatedAt": z.optional(z.string()),
"updatedBy": z.optional(z.string())
    }) as unknown as z.ZodType<DtoAyahResponse>