/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoAyahTranslationResponse } from "../../types/dto/AyahTranslationResponse.ts";
import { z } from "zod";

export const dtoAyahTranslationResponseSchema = z.object({
    "ayahId": z.optional(z.string()),
"createdAt": z.optional(z.string()),
"createdBy": z.optional(z.string()),
"id": z.optional(z.string()),
"surahId": z.optional(z.string()),
"text": z.optional(z.string()),
"translationEditionId": z.optional(z.string()),
"updatedAt": z.optional(z.string()),
"updatedBy": z.optional(z.string())
    }) as unknown as z.ZodType<DtoAyahTranslationResponse>