/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoBookmarkAyahListResponse } from "../../types/dto/BookmarkAyahListResponse.ts";
import { dtoBookmarkAyahResponseSchema } from "./bookmarkAyahResponseSchema.ts";
import { dtoPaginationResponseSchema } from "./paginationResponseSchema.ts";
import { z } from "zod";

export const dtoBookmarkAyahListResponseSchema = z.object({
    get "data"(){
                return z.array(dtoBookmarkAyahResponseSchema).optional()
              },
get "pagination"(){
                return dtoPaginationResponseSchema.optional()
              }
    }) as unknown as z.ZodType<DtoBookmarkAyahListResponse>