/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoBookmarkAyahResponse } from "../../types/dto/BookmarkAyahResponse.ts";
import { z } from "zod";

export const dtoBookmarkAyahResponseSchema = z.object({
    "ayahId": z.optional(z.string()),
"createdAt": z.optional(z.string()),
"createdBy": z.optional(z.string()),
"id": z.optional(z.string()),
"updatedAt": z.optional(z.string()),
"updatedBy": z.optional(z.string()),
"userId": z.optional(z.string())
    }) as unknown as z.ZodType<DtoBookmarkAyahResponse>