/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoCreateBookmarkAyahRequest } from "../../types/dto/CreateBookmarkAyahRequest.ts";
import { z } from "zod";

export const dtoCreateBookmarkAyahRequestSchema = z.object({
    "ayahId": z.string()
    }) as unknown as z.ZodType<DtoCreateBookmarkAyahRequest>