/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoCreateAyahAudioFileRequest } from "../../types/dto/CreateAyahAudioFileRequest.ts";
import { z } from "zod";

export const dtoCreateAyahAudioFileRequestSchema = z.object({
    "ayahId": z.string(),
"byteSize": z.number().min(0),
"createdBy": z.string().min(1).max(255),
"duration": z.number().min(0),
"filePath": z.string().min(1),
"reciterId": z.string(),
"surahId": z.string()
    }) as unknown as z.ZodType<DtoCreateAyahAudioFileRequest>