/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoCreateLastReadRequest } from "../../types/dto/CreateLastReadRequest.ts";
import { z } from "zod";

export const dtoCreateLastReadRequestSchema = z.object({
    "ayahId": z.string(),
"ayahNumber": z.int().min(1),
"progressPct": z.number().min(0).max(100),
"surahId": z.string()
    }) as unknown as z.ZodType<DtoCreateLastReadRequest>