/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoCreateJuzRequest } from "../../types/dto/CreateJuzRequest.ts";
import { z } from "zod";

export const dtoCreateJuzRequestSchema = z.object({
    "createdBy": z.string().min(1).max(255),
"endAyahId": z.string(),
"endSurahId": z.string(),
"startAyahId": z.string(),
"startSurahId": z.string()
    }) as unknown as z.ZodType<DtoCreateJuzRequest>