/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoCreateSurahRequest } from "../../types/dto/CreateSurahRequest.ts";
import { z } from "zod";

export const dtoCreateSurahRequestSchema = z.object({
    "ayahCount": z.int().min(1),
"createdBy": z.string().min(1).max(255),
"nameArabic": z.string().min(1).max(255),
"nameEnglish": z.string().min(1).max(255),
"revelationOrder": z.int().min(1).max(114),
"revelationPlace": z.string().min(1).max(100)
    }) as unknown as z.ZodType<DtoCreateSurahRequest>