/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoCreateProgressHatamRequest } from "../../types/dto/CreateProgressHatamRequest.ts";
import { z } from "zod";

export const dtoCreateProgressHatamRequestSchema = z.object({
    "juzId": z.string(),
"progressPct": z.number().min(0).max(100),
"startAyahId": z.string()
    }) as unknown as z.ZodType<DtoCreateProgressHatamRequest>