/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoCreateReciterRequest } from "../../types/dto/CreateReciterRequest.ts";
import { z } from "zod";

export const dtoCreateReciterRequestSchema = z.object({
    "createdBy": z.string().min(1).max(255),
"name": z.string().min(1).max(255),
"picture": z.optional(z.string().max(255)),
"place": z.optional(z.string().max(20)),
"style": z.string().min(1).max(255)
    }) as unknown as z.ZodType<DtoCreateReciterRequest>