/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoCreateAyahRequest } from "../../types/dto/CreateAyahRequest.ts";
import { z } from "zod";

export const dtoCreateAyahRequestSchema = z.object({
    "createdBy": z.string().min(1).max(255),
"hizbNumber": z.int().min(1).max(60),
"juzNumber": z.int().min(1).max(30),
"manzilNumber": z.int().min(1).max(7),
"pageNumber": z.int().min(1).max(604),
"surahId": z.string(),
"text": z.string().min(1)
    }) as unknown as z.ZodType<DtoCreateAyahRequest>