/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoJuzListResponse } from "../../types/dto/JuzListResponse.ts";
import { dtoJuzResponseSchema } from "./juzResponseSchema.ts";
import { dtoPaginationResponseSchema } from "./paginationResponseSchema.ts";
import { z } from "zod";

export const dtoJuzListResponseSchema = z.object({
    get "data"(){
                return z.array(dtoJuzResponseSchema).optional()
              },
get "pagination"(){
                return dtoPaginationResponseSchema.optional()
              }
    }) as unknown as z.ZodType<DtoJuzListResponse>