/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoJuzResponse } from "../../types/dto/JuzResponse.ts";
import { z } from "zod";

export const dtoJuzResponseSchema = z.object({
    "createdAt": z.optional(z.string()),
"createdBy": z.optional(z.string()),
"endAyahId": z.optional(z.string()),
"endSurahId": z.optional(z.string()),
"id": z.optional(z.string()),
"startAyahId": z.optional(z.string()),
"startSurahId": z.optional(z.string()),
"updatedAt": z.optional(z.string()),
"updatedBy": z.optional(z.string())
    }) as unknown as z.ZodType<DtoJuzResponse>