/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoJuzWithProgressBasicResponse } from "../../types/dto/JuzWithProgressBasicResponse.ts";
import { dtoJuzResponseSchema } from "./juzResponseSchema.ts";
import { dtoProgressHatamResponseSchema } from "./progressHatamResponseSchema.ts";
import { z } from "zod";

export const dtoJuzWithProgressBasicResponseSchema = z.object({
    get "juz"(){
                return dtoJuzResponseSchema.optional()
              },
get "progressHatam"(){
                return dtoProgressHatamResponseSchema.optional()
              }
    }) as unknown as z.ZodType<DtoJuzWithProgressBasicResponse>