/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoJuzWithProgressBasicListResponse } from "../../types/dto/JuzWithProgressBasicListResponse.ts";
import { dtoJuzWithProgressBasicResponseSchema } from "./juzWithProgressBasicResponseSchema.ts";
import { dtoPaginationResponseSchema } from "./paginationResponseSchema.ts";
import { z } from "zod";

export const dtoJuzWithProgressBasicListResponseSchema = z.object({
    get "data"(){
                return z.array(dtoJuzWithProgressBasicResponseSchema).optional()
              },
get "pagination"(){
                return dtoPaginationResponseSchema.optional()
              }
    }) as unknown as z.ZodType<DtoJuzWithProgressBasicListResponse>