/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoLastReadListResponse } from "../../types/dto/LastReadListResponse.ts";
import { dtoLastReadResponseSchema } from "./lastReadResponseSchema.ts";
import { dtoPaginationResponseSchema } from "./paginationResponseSchema.ts";
import { z } from "zod";

export const dtoLastReadListResponseSchema = z.object({
    get "data"(){
                return z.array(dtoLastReadResponseSchema).optional()
              },
get "pagination"(){
                return dtoPaginationResponseSchema.optional()
              }
    }) as unknown as z.ZodType<DtoLastReadListResponse>