/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoLastReadResponse } from "../../types/dto/LastReadResponse.ts";
import { z } from "zod";

export const dtoLastReadResponseSchema = z.object({
    "ayahId": z.optional(z.string()),
"ayahNumber": z.optional(z.int()),
"createdAt": z.optional(z.string()),
"createdBy": z.optional(z.string()),
"id": z.optional(z.string()),
"lastReadAt": z.optional(z.string()),
"progressPct": z.optional(z.number()),
"surahId": z.optional(z.string()),
"updatedAt": z.optional(z.string()),
"updatedBy": z.optional(z.string()),
"userId": z.optional(z.string())
    }) as unknown as z.ZodType<DtoLastReadResponse>