/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoPaginationResponse } from "../../types/dto/PaginationResponse.ts";
import { z } from "zod";

export const dtoPaginationResponseSchema = z.object({
    "limit": z.optional(z.int()),
"offset": z.optional(z.int()),
"total": z.optional(z.int())
    }) as unknown as z.ZodType<DtoPaginationResponse>