/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoPrayerTimesResponse } from "../../types/dto/PrayerTimesResponse.ts";
import { z } from "zod";

export const dtoPrayerTimesResponseSchema = z.object({
    "asr": z.optional(z.string()),
"date": z.optional(z.string()),
"dhuhr": z.optional(z.string()),
"fajr": z.optional(z.string()),
"isha": z.optional(z.string()),
"maghrib": z.optional(z.string()),
"source": z.optional(z.string()),
"sunrise": z.optional(z.string()),
"timezone": z.optional(z.string())
    }) as unknown as z.ZodType<DtoPrayerTimesResponse>