/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoPrayerTimesListResponse } from "../../types/dto/PrayerTimesListResponse.ts";
import { dtoPrayerTimesResponseSchema } from "./prayerTimesResponseSchema.ts";
import { z } from "zod";

export const dtoPrayerTimesListResponseSchema = z.object({
    get "items"(){
                return z.array(dtoPrayerTimesResponseSchema).optional()
              }
    }) as unknown as z.ZodType<DtoPrayerTimesListResponse>