/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoProgressHatamListResponse } from "../../types/dto/ProgressHatamListResponse.ts";
import { dtoPaginationResponseSchema } from "./paginationResponseSchema.ts";
import { dtoProgressHatamResponseSchema } from "./progressHatamResponseSchema.ts";
import { z } from "zod";

export const dtoProgressHatamListResponseSchema = z.object({
    get "data"(){
                return z.array(dtoProgressHatamResponseSchema).optional()
              },
get "pagination"(){
                return dtoPaginationResponseSchema.optional()
              }
    }) as unknown as z.ZodType<DtoProgressHatamListResponse>