/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoProgressHatamResponse } from "../../types/dto/ProgressHatamResponse.ts";
import { z } from "zod";

export const dtoProgressHatamResponseSchema = z.object({
    "completedAt": z.optional(z.string()),
"createdAt": z.optional(z.string()),
"createdBy": z.optional(z.string()),
"id": z.optional(z.string()),
"isCompleted": z.optional(z.boolean()),
"juzId": z.optional(z.string()),
"lastAyahId": z.optional(z.string()),
"progressPct": z.optional(z.number()),
"startAyahId": z.optional(z.string()),
"startedAt": z.optional(z.string()),
"updatedAt": z.optional(z.string()),
"updatedBy": z.optional(z.string()),
"userId": z.optional(z.string())
    }) as unknown as z.ZodType<DtoProgressHatamResponse>