/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoReciterResponse } from "../../types/dto/ReciterResponse.ts";
import { z } from "zod";

export const dtoReciterResponseSchema = z.object({
    "createdAt": z.optional(z.string()),
"createdBy": z.optional(z.string()),
"id": z.optional(z.string()),
"name": z.optional(z.string()),
"picture": z.optional(z.string()),
"place": z.optional(z.string()),
"style": z.optional(z.string()),
"updatedAt": z.optional(z.string()),
"updatedBy": z.optional(z.string())
    }) as unknown as z.ZodType<DtoReciterResponse>