/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoReciterListResponse } from "../../types/dto/ReciterListResponse.ts";
import { dtoPaginationResponseSchema } from "./paginationResponseSchema.ts";
import { dtoReciterResponseSchema } from "./reciterResponseSchema.ts";
import { z } from "zod";

export const dtoReciterListResponseSchema = z.object({
    get "data"(){
                return z.array(dtoReciterResponseSchema).optional()
              },
get "pagination"(){
                return dtoPaginationResponseSchema.optional()
              }
    }) as unknown as z.ZodType<DtoReciterListResponse>