/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoSurahResponse } from "../../types/dto/SurahResponse.ts";
import { z } from "zod";

export const dtoSurahResponseSchema = z.object({
    "ayahCount": z.optional(z.int()),
"createdAt": z.optional(z.string()),
"createdBy": z.optional(z.string()),
"id": z.optional(z.string()),
"nameArabic": z.optional(z.string()),
"nameEnglish": z.optional(z.string()),
"revelationOrder": z.optional(z.int()),
"revelationPlace": z.optional(z.string()),
"updatedAt": z.optional(z.string()),
"updatedBy": z.optional(z.string())
    }) as unknown as z.ZodType<DtoSurahResponse>