/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoSurahAyahsWithTranslationsResponse } from "../../types/dto/SurahAyahsWithTranslationsResponse.ts";
import { dtoAyahWithTranslationResponseSchema } from "./ayahWithTranslationResponseSchema.ts";
import { dtoPaginationResponseSchema } from "./paginationResponseSchema.ts";
import { dtoReciterResponseSchema } from "./reciterResponseSchema.ts";
import { dtoSurahResponseSchema } from "./surahResponseSchema.ts";
import { z } from "zod";

export const dtoSurahAyahsWithTranslationsResponseSchema = z.object({
    get "ayahs"(){
                return z.array(dtoAyahWithTranslationResponseSchema).optional()
              },
get "pagination"(){
                return dtoPaginationResponseSchema.optional()
              },
get "reciter"(){
                return dtoReciterResponseSchema.optional()
              },
get "surah"(){
                return dtoSurahResponseSchema.optional()
              }
    }) as unknown as z.ZodType<DtoSurahAyahsWithTranslationsResponse>