/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoSurahListResponse } from "../../types/dto/SurahListResponse.ts";
import { dtoPaginationResponseSchema } from "./paginationResponseSchema.ts";
import { dtoSurahResponseSchema } from "./surahResponseSchema.ts";
import { z } from "zod";

export const dtoSurahListResponseSchema = z.object({
    get "data"(){
                return z.array(dtoSurahResponseSchema).optional()
              },
get "pagination"(){
                return dtoPaginationResponseSchema.optional()
              }
    }) as unknown as z.ZodType<DtoSurahListResponse>