/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoTranslationEditionListResponse } from "../../types/dto/TranslationEditionListResponse.ts";
import { dtoPaginationResponseSchema } from "./paginationResponseSchema.ts";
import { dtoTranslationEditionResponseSchema } from "./translationEditionResponseSchema.ts";
import { z } from "zod";

export const dtoTranslationEditionListResponseSchema = z.object({
    get "data"(){
                return z.array(dtoTranslationEditionResponseSchema).optional()
              },
get "pagination"(){
                return dtoPaginationResponseSchema.optional()
              }
    }) as unknown as z.ZodType<DtoTranslationEditionListResponse>