/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoTranslationEditionResponse } from "../../types/dto/TranslationEditionResponse.ts";
import { z } from "zod";

export const dtoTranslationEditionResponseSchema = z.object({
    "author": z.optional(z.string()),
"createdAt": z.optional(z.string()),
"createdBy": z.optional(z.string()),
"id": z.optional(z.string()),
"language": z.optional(z.string()),
"name": z.optional(z.string()),
"updatedAt": z.optional(z.string()),
"updatedBy": z.optional(z.string())
    }) as unknown as z.ZodType<DtoTranslationEditionResponse>