/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoUpdateLastReadRequest } from "../../types/dto/UpdateLastReadRequest.ts";
import { z } from "zod";

export const dtoUpdateLastReadRequestSchema = z.object({
    "ayahId": z.string(),
"ayahNumber": z.int().min(1),
"id": z.string(),
"progressPct": z.number().min(0).max(100),
"updatedBy": z.string().min(1).max(255)
    }) as unknown as z.ZodType<DtoUpdateLastReadRequest>