/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoUpdateAyahRequest } from "../../types/dto/UpdateAyahRequest.ts";
import { z } from "zod";

export const dtoUpdateAyahRequestSchema = z.object({
    "hizbNumber": z.int().min(1).max(60),
"id": z.string(),
"juzNumber": z.int().min(1).max(30),
"manzilNumber": z.int().min(1).max(7),
"pageNumber": z.int().min(1).max(604),
"text": z.string().min(1),
"updatedBy": z.string().min(1).max(255)
    }) as unknown as z.ZodType<DtoUpdateAyahRequest>