/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoUpdateJuzRequest } from "../../types/dto/UpdateJuzRequest.ts";
import { z } from "zod";

export const dtoUpdateJuzRequestSchema = z.object({
    "endAyahId": z.string(),
"endSurahId": z.string(),
"id": z.string(),
"startAyahId": z.string(),
"startSurahId": z.string(),
"updatedBy": z.string().min(1).max(255)
    }) as unknown as z.ZodType<DtoUpdateJuzRequest>