/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoUpdateSurahRequest } from "../../types/dto/UpdateSurahRequest.ts";
import { z } from "zod";

export const dtoUpdateSurahRequestSchema = z.object({
    "ayahCount": z.int().min(1),
"id": z.string(),
"nameArabic": z.string().min(1).max(255),
"nameEnglish": z.string().min(1).max(255),
"revelationOrder": z.int().min(1).max(114),
"revelationPlace": z.string().min(1).max(100),
"updatedBy": z.string().min(1).max(255)
    }) as unknown as z.ZodType<DtoUpdateSurahRequest>