/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoUpdateReciterRequest } from "../../types/dto/UpdateReciterRequest.ts";
import { z } from "zod";

export const dtoUpdateReciterRequestSchema = z.object({
    "id": z.string(),
"name": z.string().min(1).max(255),
"picture": z.optional(z.string().max(255)),
"place": z.optional(z.string().max(20)),
"style": z.string().min(1).max(255),
"updatedBy": z.string().min(1).max(255)
    }) as unknown as z.ZodType<DtoUpdateReciterRequest>