/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoUpdateProgressHatamRequest } from "../../types/dto/UpdateProgressHatamRequest.ts";
import { z } from "zod";

export const dtoUpdateProgressHatamRequestSchema = z.object({
    "completedAt": z.optional(z.string()),
"id": z.string(),
"isCompleted": z.boolean(),
"lastAyahId": z.string(),
"progressPct": z.number().min(0).max(100),
"updatedBy": z.string().min(1).max(255)
    }) as unknown as z.ZodType<DtoUpdateProgressHatamRequest>