/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoUpdateAyahAudioFileRequest } from "../../types/dto/UpdateAyahAudioFileRequest.ts";
import { z } from "zod";

export const dtoUpdateAyahAudioFileRequestSchema = z.object({
    "byteSize": z.number().min(0),
"duration": z.number().min(0),
"filePath": z.string().min(1),
"id": z.string(),
"updatedBy": z.string().min(1).max(255)
    }) as unknown as z.ZodType<DtoUpdateAyahAudioFileRequest>