/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { DeleteQuranBookmarksAyahsIdMutationResponse, DeleteQuranBookmarksAyahsIdPathParams, DeleteQuranBookmarksAyahsId400, DeleteQuranBookmarksAyahsId404, DeleteQuranBookmarksAyahsId500 } from "../../types/DeleteQuranBookmarksAyahsId.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteQuranBookmarksAyahsIdMutationKey = () => [{ url: '/quran/bookmarks/ayahs/:id' }] as const

export type DeleteQuranBookmarksAyahsIdMutationKey = ReturnType<typeof deleteQuranBookmarksAyahsIdMutationKey>

/**
 * @description Delete a bookmark by its ID
 * @summary Delete bookmark ayah
 * {@link /quran/bookmarks/ayahs/:id}
 */
export async function deleteQuranBookmarksAyahsIdHook(id: DeleteQuranBookmarksAyahsIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteQuranBookmarksAyahsIdMutationResponse, ResponseErrorConfig<DeleteQuranBookmarksAyahsId400 | DeleteQuranBookmarksAyahsId404 | DeleteQuranBookmarksAyahsId500>, unknown>({ method : "DELETE", url : `/quran/bookmarks/ayahs/${id}`, ... requestConfig })  
  return res.data
}

export function deleteQuranBookmarksAyahsIdMutationOptionsHook(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = deleteQuranBookmarksAyahsIdMutationKey()
  return mutationOptions<DeleteQuranBookmarksAyahsIdMutationResponse, ResponseErrorConfig<DeleteQuranBookmarksAyahsId400 | DeleteQuranBookmarksAyahsId404 | DeleteQuranBookmarksAyahsId500>, {id: DeleteQuranBookmarksAyahsIdPathParams["id"]}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id }) => {
      return deleteQuranBookmarksAyahsIdHook(id, config)
    },
  })
}

/**
 * @description Delete a bookmark by its ID
 * @summary Delete bookmark ayah
 * {@link /quran/bookmarks/ayahs/:id}
 */
export function useDeleteQuranBookmarksAyahsIdHook<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteQuranBookmarksAyahsIdMutationResponse, ResponseErrorConfig<DeleteQuranBookmarksAyahsId400 | DeleteQuranBookmarksAyahsId404 | DeleteQuranBookmarksAyahsId500>, {id: DeleteQuranBookmarksAyahsIdPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteQuranBookmarksAyahsIdMutationKey()

  const baseOptions = deleteQuranBookmarksAyahsIdMutationOptionsHook(config) as UseMutationOptions<DeleteQuranBookmarksAyahsIdMutationResponse, ResponseErrorConfig<DeleteQuranBookmarksAyahsId400 | DeleteQuranBookmarksAyahsId404 | DeleteQuranBookmarksAyahsId500>, {id: DeleteQuranBookmarksAyahsIdPathParams["id"]}, TContext>

  return useMutation<DeleteQuranBookmarksAyahsIdMutationResponse, ResponseErrorConfig<DeleteQuranBookmarksAyahsId400 | DeleteQuranBookmarksAyahsId404 | DeleteQuranBookmarksAyahsId500>, {id: DeleteQuranBookmarksAyahsIdPathParams["id"]}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<DeleteQuranBookmarksAyahsIdMutationResponse, ResponseErrorConfig<DeleteQuranBookmarksAyahsId400 | DeleteQuranBookmarksAyahsId404 | DeleteQuranBookmarksAyahsId500>, {id: DeleteQuranBookmarksAyahsIdPathParams["id"]}, TContext>
}