/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetQuranBookmarksAyahsQueryResponse, GetQuranBookmarksAyahsQueryParams, GetQuranBookmarksAyahs400, GetQuranBookmarksAyahs500 } from "../../types/GetQuranBookmarksAyahs.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getQuranBookmarksAyahsQueryKey = (params?: GetQuranBookmarksAyahsQueryParams) => [{ url: '/quran/bookmarks/ayahs' }, ...(params ? [params] : [])] as const

export type GetQuranBookmarksAyahsQueryKey = ReturnType<typeof getQuranBookmarksAyahsQueryKey>

/**
 * @description Get a paginated list of ayah bookmarks for the authenticated user
 * @summary List bookmark ayahs by current user
 * {@link /quran/bookmarks/ayahs}
 */
export async function getQuranBookmarksAyahsHook(params?: GetQuranBookmarksAyahsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetQuranBookmarksAyahsQueryResponse, ResponseErrorConfig<GetQuranBookmarksAyahs400 | GetQuranBookmarksAyahs500>, unknown>({ method : "GET", url : `/quran/bookmarks/ayahs`, params, ... requestConfig })  
  return res.data
}

export function getQuranBookmarksAyahsQueryOptionsHook(params?: GetQuranBookmarksAyahsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getQuranBookmarksAyahsQueryKey(params)
  return queryOptions<GetQuranBookmarksAyahsQueryResponse, ResponseErrorConfig<GetQuranBookmarksAyahs400 | GetQuranBookmarksAyahs500>, GetQuranBookmarksAyahsQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getQuranBookmarksAyahsHook(params, config)
   },
  })
}

/**
 * @description Get a paginated list of ayah bookmarks for the authenticated user
 * @summary List bookmark ayahs by current user
 * {@link /quran/bookmarks/ayahs}
 */
export function useGetQuranBookmarksAyahsHook<TData = GetQuranBookmarksAyahsQueryResponse, TQueryData = GetQuranBookmarksAyahsQueryResponse, TQueryKey extends QueryKey = GetQuranBookmarksAyahsQueryKey>(params?: GetQuranBookmarksAyahsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetQuranBookmarksAyahsQueryResponse, ResponseErrorConfig<GetQuranBookmarksAyahs400 | GetQuranBookmarksAyahs500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getQuranBookmarksAyahsQueryKey(params)

  const query = useQuery({
   ...getQuranBookmarksAyahsQueryOptionsHook(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetQuranBookmarksAyahs400 | GetQuranBookmarksAyahs500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}