/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetQuranBookmarksAyahsAyahAyahidQueryResponse, GetQuranBookmarksAyahsAyahAyahidPathParams, GetQuranBookmarksAyahsAyahAyahidQueryParams, GetQuranBookmarksAyahsAyahAyahid400, GetQuranBookmarksAyahsAyahAyahid404, GetQuranBookmarksAyahsAyahAyahid500 } from "../../types/GetQuranBookmarksAyahsAyahAyahid.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getQuranBookmarksAyahsAyahAyahidQueryKey = (ayahId: GetQuranBookmarksAyahsAyahAyahidPathParams["ayahId"], params?: GetQuranBookmarksAyahsAyahAyahidQueryParams) => [{ url: '/quran/bookmarks/ayahs/ayah/:ayahId', params: {ayahId:ayahId} }, ...(params ? [params] : [])] as const

export type GetQuranBookmarksAyahsAyahAyahidQueryKey = ReturnType<typeof getQuranBookmarksAyahsAyahAyahidQueryKey>

/**
 * @description Get a bookmark for the authenticated user and specified ayah
 * @summary Get bookmark ayah by current user and ayah
 * {@link /quran/bookmarks/ayahs/ayah/:ayahId}
 */
export async function getQuranBookmarksAyahsAyahAyahidHook(ayahId: GetQuranBookmarksAyahsAyahAyahidPathParams["ayahId"], params?: GetQuranBookmarksAyahsAyahAyahidQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetQuranBookmarksAyahsAyahAyahidQueryResponse, ResponseErrorConfig<GetQuranBookmarksAyahsAyahAyahid400 | GetQuranBookmarksAyahsAyahAyahid404 | GetQuranBookmarksAyahsAyahAyahid500>, unknown>({ method : "GET", url : `/quran/bookmarks/ayahs/ayah/${ayahId}`, params, ... requestConfig })  
  return res.data
}

export function getQuranBookmarksAyahsAyahAyahidQueryOptionsHook(ayahId: GetQuranBookmarksAyahsAyahAyahidPathParams["ayahId"], params?: GetQuranBookmarksAyahsAyahAyahidQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getQuranBookmarksAyahsAyahAyahidQueryKey(ayahId, params)
  return queryOptions<GetQuranBookmarksAyahsAyahAyahidQueryResponse, ResponseErrorConfig<GetQuranBookmarksAyahsAyahAyahid400 | GetQuranBookmarksAyahsAyahAyahid404 | GetQuranBookmarksAyahsAyahAyahid500>, GetQuranBookmarksAyahsAyahAyahidQueryResponse, typeof queryKey>({
   enabled: !!(ayahId),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getQuranBookmarksAyahsAyahAyahidHook(ayahId, params, config)
   },
  })
}

/**
 * @description Get a bookmark for the authenticated user and specified ayah
 * @summary Get bookmark ayah by current user and ayah
 * {@link /quran/bookmarks/ayahs/ayah/:ayahId}
 */
export function useGetQuranBookmarksAyahsAyahAyahidHook<TData = GetQuranBookmarksAyahsAyahAyahidQueryResponse, TQueryData = GetQuranBookmarksAyahsAyahAyahidQueryResponse, TQueryKey extends QueryKey = GetQuranBookmarksAyahsAyahAyahidQueryKey>(ayahId: GetQuranBookmarksAyahsAyahAyahidPathParams["ayahId"], params?: GetQuranBookmarksAyahsAyahAyahidQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetQuranBookmarksAyahsAyahAyahidQueryResponse, ResponseErrorConfig<GetQuranBookmarksAyahsAyahAyahid400 | GetQuranBookmarksAyahsAyahAyahid404 | GetQuranBookmarksAyahsAyahAyahid500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getQuranBookmarksAyahsAyahAyahidQueryKey(ayahId, params)

  const query = useQuery({
   ...getQuranBookmarksAyahsAyahAyahidQueryOptionsHook(ayahId, params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetQuranBookmarksAyahsAyahAyahid400 | GetQuranBookmarksAyahsAyahAyahid404 | GetQuranBookmarksAyahsAyahAyahid500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}