/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetQuranBookmarksAyahsIdQueryResponse, GetQuranBookmarksAyahsIdPathParams, GetQuranBookmarksAyahsIdQueryParams, GetQuranBookmarksAyahsId400, GetQuranBookmarksAyahsId404, GetQuranBookmarksAyahsId500 } from "../../types/GetQuranBookmarksAyahsId.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getQuranBookmarksAyahsIdQueryKey = (id: GetQuranBookmarksAyahsIdPathParams["id"], params?: GetQuranBookmarksAyahsIdQueryParams) => [{ url: '/quran/bookmarks/ayahs/:id', params: {id:id} }, ...(params ? [params] : [])] as const

export type GetQuranBookmarksAyahsIdQueryKey = ReturnType<typeof getQuranBookmarksAyahsIdQueryKey>

/**
 * @description Get a specific bookmark by its ID
 * @summary Get bookmark ayah by ID
 * {@link /quran/bookmarks/ayahs/:id}
 */
export async function getQuranBookmarksAyahsIdHook(id: GetQuranBookmarksAyahsIdPathParams["id"], params?: GetQuranBookmarksAyahsIdQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetQuranBookmarksAyahsIdQueryResponse, ResponseErrorConfig<GetQuranBookmarksAyahsId400 | GetQuranBookmarksAyahsId404 | GetQuranBookmarksAyahsId500>, unknown>({ method : "GET", url : `/quran/bookmarks/ayahs/${id}`, params, ... requestConfig })  
  return res.data
}

export function getQuranBookmarksAyahsIdQueryOptionsHook(id: GetQuranBookmarksAyahsIdPathParams["id"], params?: GetQuranBookmarksAyahsIdQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getQuranBookmarksAyahsIdQueryKey(id, params)
  return queryOptions<GetQuranBookmarksAyahsIdQueryResponse, ResponseErrorConfig<GetQuranBookmarksAyahsId400 | GetQuranBookmarksAyahsId404 | GetQuranBookmarksAyahsId500>, GetQuranBookmarksAyahsIdQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getQuranBookmarksAyahsIdHook(id, params, config)
   },
  })
}

/**
 * @description Get a specific bookmark by its ID
 * @summary Get bookmark ayah by ID
 * {@link /quran/bookmarks/ayahs/:id}
 */
export function useGetQuranBookmarksAyahsIdHook<TData = GetQuranBookmarksAyahsIdQueryResponse, TQueryData = GetQuranBookmarksAyahsIdQueryResponse, TQueryKey extends QueryKey = GetQuranBookmarksAyahsIdQueryKey>(id: GetQuranBookmarksAyahsIdPathParams["id"], params?: GetQuranBookmarksAyahsIdQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetQuranBookmarksAyahsIdQueryResponse, ResponseErrorConfig<GetQuranBookmarksAyahsId400 | GetQuranBookmarksAyahsId404 | GetQuranBookmarksAyahsId500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getQuranBookmarksAyahsIdQueryKey(id, params)

  const query = useQuery({
   ...getQuranBookmarksAyahsIdQueryOptionsHook(id, params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetQuranBookmarksAyahsId400 | GetQuranBookmarksAyahsId404 | GetQuranBookmarksAyahsId500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}