/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { PostQuranBookmarksAyahsMutationRequest, PostQuranBookmarksAyahsMutationResponse, PostQuranBookmarksAyahs400, PostQuranBookmarksAyahs500 } from "../../types/PostQuranBookmarksAyahs.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postQuranBookmarksAyahsMutationKey = () => [{ url: '/quran/bookmarks/ayahs' }] as const

export type PostQuranBookmarksAyahsMutationKey = ReturnType<typeof postQuranBookmarksAyahsMutationKey>

/**
 * @description Bookmark an ayah for the current user
 * @summary Create ayah bookmark
 * {@link /quran/bookmarks/ayahs}
 */
export async function postQuranBookmarksAyahsHook(data: PostQuranBookmarksAyahsMutationRequest, config: Partial<RequestConfig<PostQuranBookmarksAyahsMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostQuranBookmarksAyahsMutationResponse, ResponseErrorConfig<PostQuranBookmarksAyahs400 | PostQuranBookmarksAyahs500>, PostQuranBookmarksAyahsMutationRequest>({ method : "POST", url : `/quran/bookmarks/ayahs`, data : requestData, ... requestConfig })  
  return res.data
}

export function postQuranBookmarksAyahsMutationOptionsHook(config: Partial<RequestConfig<PostQuranBookmarksAyahsMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = postQuranBookmarksAyahsMutationKey()
  return mutationOptions<PostQuranBookmarksAyahsMutationResponse, ResponseErrorConfig<PostQuranBookmarksAyahs400 | PostQuranBookmarksAyahs500>, {data: PostQuranBookmarksAyahsMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return postQuranBookmarksAyahsHook(data, config)
    },
  })
}

/**
 * @description Bookmark an ayah for the current user
 * @summary Create ayah bookmark
 * {@link /quran/bookmarks/ayahs}
 */
export function usePostQuranBookmarksAyahsHook<TContext>(options: 
{
  mutation?: UseMutationOptions<PostQuranBookmarksAyahsMutationResponse, ResponseErrorConfig<PostQuranBookmarksAyahs400 | PostQuranBookmarksAyahs500>, {data: PostQuranBookmarksAyahsMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostQuranBookmarksAyahsMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postQuranBookmarksAyahsMutationKey()

  const baseOptions = postQuranBookmarksAyahsMutationOptionsHook(config) as UseMutationOptions<PostQuranBookmarksAyahsMutationResponse, ResponseErrorConfig<PostQuranBookmarksAyahs400 | PostQuranBookmarksAyahs500>, {data: PostQuranBookmarksAyahsMutationRequest}, TContext>

  return useMutation<PostQuranBookmarksAyahsMutationResponse, ResponseErrorConfig<PostQuranBookmarksAyahs400 | PostQuranBookmarksAyahs500>, {data: PostQuranBookmarksAyahsMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<PostQuranBookmarksAyahsMutationResponse, ResponseErrorConfig<PostQuranBookmarksAyahs400 | PostQuranBookmarksAyahs500>, {data: PostQuranBookmarksAyahsMutationRequest}, TContext>
}