/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetQuranProgressHatamQueryResponse, GetQuranProgressHatamQueryParams, GetQuranProgressHatam400, GetQuranProgressHatam500 } from "../../types/GetQuranProgressHatam.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getQuranProgressHatamQueryKey = (params?: GetQuranProgressHatamQueryParams) => [{ url: '/quran/progress-hatam' }, ...(params ? [params] : [])] as const

export type GetQuranProgressHatamQueryKey = ReturnType<typeof getQuranProgressHatamQueryKey>

/**
 * @description Get a paginated list of progress hatam entries for the authenticated user
 * @summary List progress hatam by current user
 * {@link /quran/progress-hatam}
 */
export async function getQuranProgressHatamHook(params?: GetQuranProgressHatamQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetQuranProgressHatamQueryResponse, ResponseErrorConfig<GetQuranProgressHatam400 | GetQuranProgressHatam500>, unknown>({ method : "GET", url : `/quran/progress-hatam`, params, ... requestConfig })  
  return res.data
}

export function getQuranProgressHatamQueryOptionsHook(params?: GetQuranProgressHatamQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getQuranProgressHatamQueryKey(params)
  return queryOptions<GetQuranProgressHatamQueryResponse, ResponseErrorConfig<GetQuranProgressHatam400 | GetQuranProgressHatam500>, GetQuranProgressHatamQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getQuranProgressHatamHook(params, config)
   },
  })
}

/**
 * @description Get a paginated list of progress hatam entries for the authenticated user
 * @summary List progress hatam by current user
 * {@link /quran/progress-hatam}
 */
export function useGetQuranProgressHatamHook<TData = GetQuranProgressHatamQueryResponse, TQueryData = GetQuranProgressHatamQueryResponse, TQueryKey extends QueryKey = GetQuranProgressHatamQueryKey>(params?: GetQuranProgressHatamQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetQuranProgressHatamQueryResponse, ResponseErrorConfig<GetQuranProgressHatam400 | GetQuranProgressHatam500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getQuranProgressHatamQueryKey(params)

  const query = useQuery({
   ...getQuranProgressHatamQueryOptionsHook(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetQuranProgressHatam400 | GetQuranProgressHatam500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}