/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetQuranProgressHatamIdQueryResponse, GetQuranProgressHatamIdPathParams, GetQuranProgressHatamIdQueryParams, GetQuranProgressHatamId400, GetQuranProgressHatamId404, GetQuranProgressHatamId500 } from "../../types/GetQuranProgressHatamId.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getQuranProgressHatamIdQueryKey = (id: GetQuranProgressHatamIdPathParams["id"], params?: GetQuranProgressHatamIdQueryParams) => [{ url: '/quran/progress-hatam/:id', params: {id:id} }, ...(params ? [params] : [])] as const

export type GetQuranProgressHatamIdQueryKey = ReturnType<typeof getQuranProgressHatamIdQueryKey>

/**
 * @description Get a specific progress hatam entry by its ID
 * @summary Get progress hatam by ID
 * {@link /quran/progress-hatam/:id}
 */
export async function getQuranProgressHatamIdHook(id: GetQuranProgressHatamIdPathParams["id"], params?: GetQuranProgressHatamIdQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetQuranProgressHatamIdQueryResponse, ResponseErrorConfig<GetQuranProgressHatamId400 | GetQuranProgressHatamId404 | GetQuranProgressHatamId500>, unknown>({ method : "GET", url : `/quran/progress-hatam/${id}`, params, ... requestConfig })  
  return res.data
}

export function getQuranProgressHatamIdQueryOptionsHook(id: GetQuranProgressHatamIdPathParams["id"], params?: GetQuranProgressHatamIdQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getQuranProgressHatamIdQueryKey(id, params)
  return queryOptions<GetQuranProgressHatamIdQueryResponse, ResponseErrorConfig<GetQuranProgressHatamId400 | GetQuranProgressHatamId404 | GetQuranProgressHatamId500>, GetQuranProgressHatamIdQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getQuranProgressHatamIdHook(id, params, config)
   },
  })
}

/**
 * @description Get a specific progress hatam entry by its ID
 * @summary Get progress hatam by ID
 * {@link /quran/progress-hatam/:id}
 */
export function useGetQuranProgressHatamIdHook<TData = GetQuranProgressHatamIdQueryResponse, TQueryData = GetQuranProgressHatamIdQueryResponse, TQueryKey extends QueryKey = GetQuranProgressHatamIdQueryKey>(id: GetQuranProgressHatamIdPathParams["id"], params?: GetQuranProgressHatamIdQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetQuranProgressHatamIdQueryResponse, ResponseErrorConfig<GetQuranProgressHatamId400 | GetQuranProgressHatamId404 | GetQuranProgressHatamId500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getQuranProgressHatamIdQueryKey(id, params)

  const query = useQuery({
   ...getQuranProgressHatamIdQueryOptionsHook(id, params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetQuranProgressHatamId400 | GetQuranProgressHatamId404 | GetQuranProgressHatamId500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}