/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { GetQuranProgressHatamJuzJuzidQueryResponse, GetQuranProgressHatamJuzJuzidPathParams, GetQuranProgressHatamJuzJuzidQueryParams, GetQuranProgressHatamJuzJuzid400, GetQuranProgressHatamJuzJuzid404, GetQuranProgressHatamJuzJuzid500 } from "../../types/GetQuranProgressHatamJuzJuzid.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getQuranProgressHatamJuzJuzidQueryKey = (juzId: GetQuranProgressHatamJuzJuzidPathParams["juzId"], params?: GetQuranProgressHatamJuzJuzidQueryParams) => [{ url: '/quran/progress-hatam/juz/:juzId', params: {juzId:juzId} }, ...(params ? [params] : [])] as const

export type GetQuranProgressHatamJuzJuzidQueryKey = ReturnType<typeof getQuranProgressHatamJuzJuzidQueryKey>

/**
 * @description Get a progress hatam entry for the authenticated user and juz
 * @summary Get progress hatam by current user and juz
 * {@link /quran/progress-hatam/juz/:juzId}
 */
export async function getQuranProgressHatamJuzJuzidHook(juzId: GetQuranProgressHatamJuzJuzidPathParams["juzId"], params?: GetQuranProgressHatamJuzJuzidQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetQuranProgressHatamJuzJuzidQueryResponse, ResponseErrorConfig<GetQuranProgressHatamJuzJuzid400 | GetQuranProgressHatamJuzJuzid404 | GetQuranProgressHatamJuzJuzid500>, unknown>({ method : "GET", url : `/quran/progress-hatam/juz/${juzId}`, params, ... requestConfig })  
  return res.data
}

export function getQuranProgressHatamJuzJuzidQueryOptionsHook(juzId: GetQuranProgressHatamJuzJuzidPathParams["juzId"], params?: GetQuranProgressHatamJuzJuzidQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getQuranProgressHatamJuzJuzidQueryKey(juzId, params)
  return queryOptions<GetQuranProgressHatamJuzJuzidQueryResponse, ResponseErrorConfig<GetQuranProgressHatamJuzJuzid400 | GetQuranProgressHatamJuzJuzid404 | GetQuranProgressHatamJuzJuzid500>, GetQuranProgressHatamJuzJuzidQueryResponse, typeof queryKey>({
   enabled: !!(juzId),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getQuranProgressHatamJuzJuzidHook(juzId, params, config)
   },
  })
}

/**
 * @description Get a progress hatam entry for the authenticated user and juz
 * @summary Get progress hatam by current user and juz
 * {@link /quran/progress-hatam/juz/:juzId}
 */
export function useGetQuranProgressHatamJuzJuzidHook<TData = GetQuranProgressHatamJuzJuzidQueryResponse, TQueryData = GetQuranProgressHatamJuzJuzidQueryResponse, TQueryKey extends QueryKey = GetQuranProgressHatamJuzJuzidQueryKey>(juzId: GetQuranProgressHatamJuzJuzidPathParams["juzId"], params?: GetQuranProgressHatamJuzJuzidQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetQuranProgressHatamJuzJuzidQueryResponse, ResponseErrorConfig<GetQuranProgressHatamJuzJuzid400 | GetQuranProgressHatamJuzJuzid404 | GetQuranProgressHatamJuzJuzid500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getQuranProgressHatamJuzJuzidQueryKey(juzId, params)

  const query = useQuery({
   ...getQuranProgressHatamJuzJuzidQueryOptionsHook(juzId, params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetQuranProgressHatamJuzJuzid400 | GetQuranProgressHatamJuzJuzid404 | GetQuranProgressHatamJuzJuzid500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}