/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { PostQuranProgressHatamMutationRequest, PostQuranProgressHatamMutationResponse, PostQuranProgressHatam400, PostQuranProgressHatam500 } from "../../types/PostQuranProgressHatam.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postQuranProgressHatamMutationKey = () => [{ url: '/quran/progress-hatam' }] as const

export type PostQuranProgressHatamMutationKey = ReturnType<typeof postQuranProgressHatamMutationKey>

/**
 * @description Create a new progress hatam entry for a user
 * @summary Create progress hatam
 * {@link /quran/progress-hatam}
 */
export async function postQuranProgressHatamHook(data: PostQuranProgressHatamMutationRequest, config: Partial<RequestConfig<PostQuranProgressHatamMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostQuranProgressHatamMutationResponse, ResponseErrorConfig<PostQuranProgressHatam400 | PostQuranProgressHatam500>, PostQuranProgressHatamMutationRequest>({ method : "POST", url : `/quran/progress-hatam`, data : requestData, ... requestConfig })  
  return res.data
}

export function postQuranProgressHatamMutationOptionsHook(config: Partial<RequestConfig<PostQuranProgressHatamMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = postQuranProgressHatamMutationKey()
  return mutationOptions<PostQuranProgressHatamMutationResponse, ResponseErrorConfig<PostQuranProgressHatam400 | PostQuranProgressHatam500>, {data: PostQuranProgressHatamMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return postQuranProgressHatamHook(data, config)
    },
  })
}

/**
 * @description Create a new progress hatam entry for a user
 * @summary Create progress hatam
 * {@link /quran/progress-hatam}
 */
export function usePostQuranProgressHatamHook<TContext>(options: 
{
  mutation?: UseMutationOptions<PostQuranProgressHatamMutationResponse, ResponseErrorConfig<PostQuranProgressHatam400 | PostQuranProgressHatam500>, {data: PostQuranProgressHatamMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostQuranProgressHatamMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? postQuranProgressHatamMutationKey()

  const baseOptions = postQuranProgressHatamMutationOptionsHook(config) as UseMutationOptions<PostQuranProgressHatamMutationResponse, ResponseErrorConfig<PostQuranProgressHatam400 | PostQuranProgressHatam500>, {data: PostQuranProgressHatamMutationRequest}, TContext>

  return useMutation<PostQuranProgressHatamMutationResponse, ResponseErrorConfig<PostQuranProgressHatam400 | PostQuranProgressHatam500>, {data: PostQuranProgressHatamMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<PostQuranProgressHatamMutationResponse, ResponseErrorConfig<PostQuranProgressHatam400 | PostQuranProgressHatam500>, {data: PostQuranProgressHatamMutationRequest}, TContext>
}