/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/configs/core-service-instance";
import type { PutQuranProgressHatamIdMutationRequest, PutQuranProgressHatamIdMutationResponse, PutQuranProgressHatamIdPathParams, PutQuranProgressHatamId400, PutQuranProgressHatamId404, PutQuranProgressHatamId500 } from "../../types/PutQuranProgressHatamId.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/configs/core-service-instance";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const putQuranProgressHatamIdMutationKey = () => [{ url: '/quran/progress-hatam/:id' }] as const

export type PutQuranProgressHatamIdMutationKey = ReturnType<typeof putQuranProgressHatamIdMutationKey>

/**
 * @description Update fields of an existing progress hatam entry
 * @summary Update progress hatam
 * {@link /quran/progress-hatam/:id}
 */
export async function putQuranProgressHatamIdHook(id: PutQuranProgressHatamIdPathParams["id"], data: PutQuranProgressHatamIdMutationRequest, config: Partial<RequestConfig<PutQuranProgressHatamIdMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PutQuranProgressHatamIdMutationResponse, ResponseErrorConfig<PutQuranProgressHatamId400 | PutQuranProgressHatamId404 | PutQuranProgressHatamId500>, PutQuranProgressHatamIdMutationRequest>({ method : "PUT", url : `/quran/progress-hatam/${id}`, data : requestData, ... requestConfig })  
  return res.data
}

export function putQuranProgressHatamIdMutationOptionsHook(config: Partial<RequestConfig<PutQuranProgressHatamIdMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = putQuranProgressHatamIdMutationKey()
  return mutationOptions<PutQuranProgressHatamIdMutationResponse, ResponseErrorConfig<PutQuranProgressHatamId400 | PutQuranProgressHatamId404 | PutQuranProgressHatamId500>, {id: PutQuranProgressHatamIdPathParams["id"], data: PutQuranProgressHatamIdMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id, data }) => {
      return putQuranProgressHatamIdHook(id, data, config)
    },
  })
}

/**
 * @description Update fields of an existing progress hatam entry
 * @summary Update progress hatam
 * {@link /quran/progress-hatam/:id}
 */
export function usePutQuranProgressHatamIdHook<TContext>(options: 
{
  mutation?: UseMutationOptions<PutQuranProgressHatamIdMutationResponse, ResponseErrorConfig<PutQuranProgressHatamId400 | PutQuranProgressHatamId404 | PutQuranProgressHatamId500>, {id: PutQuranProgressHatamIdPathParams["id"], data: PutQuranProgressHatamIdMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PutQuranProgressHatamIdMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? putQuranProgressHatamIdMutationKey()

  const baseOptions = putQuranProgressHatamIdMutationOptionsHook(config) as UseMutationOptions<PutQuranProgressHatamIdMutationResponse, ResponseErrorConfig<PutQuranProgressHatamId400 | PutQuranProgressHatamId404 | PutQuranProgressHatamId500>, {id: PutQuranProgressHatamIdPathParams["id"], data: PutQuranProgressHatamIdMutationRequest}, TContext>

  return useMutation<PutQuranProgressHatamIdMutationResponse, ResponseErrorConfig<PutQuranProgressHatamId400 | PutQuranProgressHatamId404 | PutQuranProgressHatamId500>, {id: PutQuranProgressHatamIdPathParams["id"], data: PutQuranProgressHatamIdMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<PutQuranProgressHatamIdMutationResponse, ResponseErrorConfig<PutQuranProgressHatamId400 | PutQuranProgressHatamId404 | PutQuranProgressHatamId500>, {id: PutQuranProgressHatamIdPathParams["id"], data: PutQuranProgressHatamIdMutationRequest}, TContext>
}