export type { DeleteQuranAudioAyahsIdMutationKey } from "./audioController/useDeleteQuranAudioAyahsIdHook.ts";
export type { GetQuranAudioAyahsAyahAyahidReciterReciteridQueryKey } from "./audioController/useGetQuranAudioAyahsAyahAyahidReciterReciteridHook.ts";
export type { GetQuranAudioAyahsIdQueryKey } from "./audioController/useGetQuranAudioAyahsIdHook.ts";
export type { GetQuranAudioAyahsSurahSurahidReciterReciteridQueryKey } from "./audioController/useGetQuranAudioAyahsSurahSurahidReciterReciteridHook.ts";
export type { PostQuranAudioAyahsMutationKey } from "./audioController/usePostQuranAudioAyahsHook.ts";
export type { PutQuranAudioAyahsIdMutationKey } from "./audioController/usePutQuranAudioAyahsIdHook.ts";
export type { DeleteQuranAyahsIdMutationKey } from "./ayahsController/useDeleteQuranAyahsIdHook.ts";
export type { GetQuranAyahsIdQueryKey } from "./ayahsController/useGetQuranAyahsIdHook.ts";
export type { GetQuranAyahsSurahSurahidQueryKey } from "./ayahsController/useGetQuranAyahsSurahSurahidHook.ts";
export type { GetQuranJuzJuznumberAyahsQueryKey } from "./ayahsController/useGetQuranJuzJuznumberAyahsHook.ts";
export type { PostQuranAyahsMutationKey } from "./ayahsController/usePostQuranAyahsHook.ts";
export type { PutQuranAyahsIdMutationKey } from "./ayahsController/usePutQuranAyahsIdHook.ts";
export type { DeleteQuranBookmarksAyahsIdMutationKey } from "./bookmarksController/useDeleteQuranBookmarksAyahsIdHook.ts";
export type { GetQuranBookmarksAyahsAyahAyahidQueryKey } from "./bookmarksController/useGetQuranBookmarksAyahsAyahAyahidHook.ts";
export type { GetQuranBookmarksAyahsQueryKey } from "./bookmarksController/useGetQuranBookmarksAyahsHook.ts";
export type { GetQuranBookmarksAyahsIdQueryKey } from "./bookmarksController/useGetQuranBookmarksAyahsIdHook.ts";
export type { PostQuranBookmarksAyahsMutationKey } from "./bookmarksController/usePostQuranBookmarksAyahsHook.ts";
export type { DeleteQuranJuzIdMutationKey } from "./juzController/useDeleteQuranJuzIdHook.ts";
export type { GetQuranJuzQueryKey } from "./juzController/useGetQuranJuzHook.ts";
export type { GetQuranJuzIdQueryKey } from "./juzController/useGetQuranJuzIdHook.ts";
export type { GetQuranJuzNumberNumberQueryKey } from "./juzController/useGetQuranJuzNumberNumberHook.ts";
export type { GetQuranJuzWithProgressQueryKey } from "./juzController/useGetQuranJuzWithProgressHook.ts";
export type { PostQuranJuzMutationKey } from "./juzController/usePostQuranJuzHook.ts";
export type { PutQuranJuzIdMutationKey } from "./juzController/usePutQuranJuzIdHook.ts";
export type { DeleteQuranLastReadsIdMutationKey } from "./lastReadController/useDeleteQuranLastReadsIdHook.ts";
export type { GetQuranLastReadsQueryKey } from "./lastReadController/useGetQuranLastReadsHook.ts";
export type { GetQuranLastReadsIdQueryKey } from "./lastReadController/useGetQuranLastReadsIdHook.ts";
export type { GetQuranLastReadsSurahSurahidQueryKey } from "./lastReadController/useGetQuranLastReadsSurahSurahidHook.ts";
export type { PostQuranLastReadsMutationKey } from "./lastReadController/usePostQuranLastReadsHook.ts";
export type { PutQuranLastReadsIdMutationKey } from "./lastReadController/usePutQuranLastReadsIdHook.ts";
export type { GetPrayertimesDailyQueryKey } from "./prayerTimesController/useGetPrayertimesDailyHook.ts";
export type { GetPrayertimesMonthlyQueryKey } from "./prayerTimesController/useGetPrayertimesMonthlyHook.ts";
export type { GetPrayertimesYearlyQueryKey } from "./prayerTimesController/useGetPrayertimesYearlyHook.ts";
export type { DeleteQuranProgressHatamIdMutationKey } from "./progressHatamController/useDeleteQuranProgressHatamIdHook.ts";
export type { GetQuranProgressHatamQueryKey } from "./progressHatamController/useGetQuranProgressHatamHook.ts";
export type { GetQuranProgressHatamIdQueryKey } from "./progressHatamController/useGetQuranProgressHatamIdHook.ts";
export type { GetQuranProgressHatamJuzJuzidQueryKey } from "./progressHatamController/useGetQuranProgressHatamJuzJuzidHook.ts";
export type { PostQuranProgressHatamMutationKey } from "./progressHatamController/usePostQuranProgressHatamHook.ts";
export type { PutQuranProgressHatamIdMutationKey } from "./progressHatamController/usePutQuranProgressHatamIdHook.ts";
export type { DeleteQuranRecitersIdMutationKey } from "./recitersController/useDeleteQuranRecitersIdHook.ts";
export type { GetQuranRecitersQueryKey } from "./recitersController/useGetQuranRecitersHook.ts";
export type { GetQuranRecitersIdQueryKey } from "./recitersController/useGetQuranRecitersIdHook.ts";
export type { GetQuranRecitersNameNameQueryKey } from "./recitersController/useGetQuranRecitersNameNameHook.ts";
export type { PostQuranRecitersMutationKey } from "./recitersController/usePostQuranRecitersHook.ts";
export type { PutQuranRecitersIdMutationKey } from "./recitersController/usePutQuranRecitersIdHook.ts";
export type { DeleteQuranSurahsIdMutationKey } from "./surahsController/useDeleteQuranSurahsIdHook.ts";
export type { GetQuranSurahsQueryKey } from "./surahsController/useGetQuranSurahsHook.ts";
export type { GetQuranSurahsIdQueryKey } from "./surahsController/useGetQuranSurahsIdHook.ts";
export type { GetQuranSurahsNumberNumberQueryKey } from "./surahsController/useGetQuranSurahsNumberNumberHook.ts";
export type { PostQuranSurahsMutationKey } from "./surahsController/usePostQuranSurahsHook.ts";
export type { PutQuranSurahsIdMutationKey } from "./surahsController/usePutQuranSurahsIdHook.ts";
export type { GetQuranTranslationsAyahsAyahAyahidEditionEditionidQueryKey } from "./translationsController/useGetQuranTranslationsAyahsAyahAyahidEditionEditionidHook.ts";
export type { GetQuranTranslationsAyahsSurahSurahidEditionEditionidQueryKey } from "./translationsController/useGetQuranTranslationsAyahsSurahSurahidEditionEditionidHook.ts";
export type { GetQuranTranslationsEditionsQueryKey } from "./translationsController/useGetQuranTranslationsEditionsHook.ts";
export { deleteQuranAudioAyahsIdMutationKey, deleteQuranAudioAyahsIdHook, deleteQuranAudioAyahsIdMutationOptionsHook, useDeleteQuranAudioAyahsIdHook } from "./audioController/useDeleteQuranAudioAyahsIdHook.ts";
export { getQuranAudioAyahsAyahAyahidReciterReciteridQueryKey, getQuranAudioAyahsAyahAyahidReciterReciteridHook, getQuranAudioAyahsAyahAyahidReciterReciteridQueryOptionsHook, useGetQuranAudioAyahsAyahAyahidReciterReciteridHook } from "./audioController/useGetQuranAudioAyahsAyahAyahidReciterReciteridHook.ts";
export { getQuranAudioAyahsIdQueryKey, getQuranAudioAyahsIdHook, getQuranAudioAyahsIdQueryOptionsHook, useGetQuranAudioAyahsIdHook } from "./audioController/useGetQuranAudioAyahsIdHook.ts";
export { getQuranAudioAyahsSurahSurahidReciterReciteridQueryKey, getQuranAudioAyahsSurahSurahidReciterReciteridHook, getQuranAudioAyahsSurahSurahidReciterReciteridQueryOptionsHook, useGetQuranAudioAyahsSurahSurahidReciterReciteridHook } from "./audioController/useGetQuranAudioAyahsSurahSurahidReciterReciteridHook.ts";
export { postQuranAudioAyahsMutationKey, postQuranAudioAyahsHook, postQuranAudioAyahsMutationOptionsHook, usePostQuranAudioAyahsHook } from "./audioController/usePostQuranAudioAyahsHook.ts";
export { putQuranAudioAyahsIdMutationKey, putQuranAudioAyahsIdHook, putQuranAudioAyahsIdMutationOptionsHook, usePutQuranAudioAyahsIdHook } from "./audioController/usePutQuranAudioAyahsIdHook.ts";
export { deleteQuranAyahsIdMutationKey, deleteQuranAyahsIdHook, deleteQuranAyahsIdMutationOptionsHook, useDeleteQuranAyahsIdHook } from "./ayahsController/useDeleteQuranAyahsIdHook.ts";
export { getQuranAyahsIdQueryKey, getQuranAyahsIdHook, getQuranAyahsIdQueryOptionsHook, useGetQuranAyahsIdHook } from "./ayahsController/useGetQuranAyahsIdHook.ts";
export { getQuranAyahsSurahSurahidQueryKey, getQuranAyahsSurahSurahidHook, getQuranAyahsSurahSurahidQueryOptionsHook, useGetQuranAyahsSurahSurahidHook } from "./ayahsController/useGetQuranAyahsSurahSurahidHook.ts";
export { getQuranJuzJuznumberAyahsQueryKey, getQuranJuzJuznumberAyahsHook, getQuranJuzJuznumberAyahsQueryOptionsHook, useGetQuranJuzJuznumberAyahsHook } from "./ayahsController/useGetQuranJuzJuznumberAyahsHook.ts";
export { postQuranAyahsMutationKey, postQuranAyahsHook, postQuranAyahsMutationOptionsHook, usePostQuranAyahsHook } from "./ayahsController/usePostQuranAyahsHook.ts";
export { putQuranAyahsIdMutationKey, putQuranAyahsIdHook, putQuranAyahsIdMutationOptionsHook, usePutQuranAyahsIdHook } from "./ayahsController/usePutQuranAyahsIdHook.ts";
export { deleteQuranBookmarksAyahsIdMutationKey, deleteQuranBookmarksAyahsIdHook, deleteQuranBookmarksAyahsIdMutationOptionsHook, useDeleteQuranBookmarksAyahsIdHook } from "./bookmarksController/useDeleteQuranBookmarksAyahsIdHook.ts";
export { getQuranBookmarksAyahsAyahAyahidQueryKey, getQuranBookmarksAyahsAyahAyahidHook, getQuranBookmarksAyahsAyahAyahidQueryOptionsHook, useGetQuranBookmarksAyahsAyahAyahidHook } from "./bookmarksController/useGetQuranBookmarksAyahsAyahAyahidHook.ts";
export { getQuranBookmarksAyahsQueryKey, getQuranBookmarksAyahsHook, getQuranBookmarksAyahsQueryOptionsHook, useGetQuranBookmarksAyahsHook } from "./bookmarksController/useGetQuranBookmarksAyahsHook.ts";
export { getQuranBookmarksAyahsIdQueryKey, getQuranBookmarksAyahsIdHook, getQuranBookmarksAyahsIdQueryOptionsHook, useGetQuranBookmarksAyahsIdHook } from "./bookmarksController/useGetQuranBookmarksAyahsIdHook.ts";
export { postQuranBookmarksAyahsMutationKey, postQuranBookmarksAyahsHook, postQuranBookmarksAyahsMutationOptionsHook, usePostQuranBookmarksAyahsHook } from "./bookmarksController/usePostQuranBookmarksAyahsHook.ts";
export { deleteQuranJuzIdMutationKey, deleteQuranJuzIdHook, deleteQuranJuzIdMutationOptionsHook, useDeleteQuranJuzIdHook } from "./juzController/useDeleteQuranJuzIdHook.ts";
export { getQuranJuzQueryKey, getQuranJuzHook, getQuranJuzQueryOptionsHook, useGetQuranJuzHook } from "./juzController/useGetQuranJuzHook.ts";
export { getQuranJuzIdQueryKey, getQuranJuzIdHook, getQuranJuzIdQueryOptionsHook, useGetQuranJuzIdHook } from "./juzController/useGetQuranJuzIdHook.ts";
export { getQuranJuzNumberNumberQueryKey, getQuranJuzNumberNumberHook, getQuranJuzNumberNumberQueryOptionsHook, useGetQuranJuzNumberNumberHook } from "./juzController/useGetQuranJuzNumberNumberHook.ts";
export { getQuranJuzWithProgressQueryKey, getQuranJuzWithProgressHook, getQuranJuzWithProgressQueryOptionsHook, useGetQuranJuzWithProgressHook } from "./juzController/useGetQuranJuzWithProgressHook.ts";
export { postQuranJuzMutationKey, postQuranJuzHook, postQuranJuzMutationOptionsHook, usePostQuranJuzHook } from "./juzController/usePostQuranJuzHook.ts";
export { putQuranJuzIdMutationKey, putQuranJuzIdHook, putQuranJuzIdMutationOptionsHook, usePutQuranJuzIdHook } from "./juzController/usePutQuranJuzIdHook.ts";
export { deleteQuranLastReadsIdMutationKey, deleteQuranLastReadsIdHook, deleteQuranLastReadsIdMutationOptionsHook, useDeleteQuranLastReadsIdHook } from "./lastReadController/useDeleteQuranLastReadsIdHook.ts";
export { getQuranLastReadsQueryKey, getQuranLastReadsHook, getQuranLastReadsQueryOptionsHook, useGetQuranLastReadsHook } from "./lastReadController/useGetQuranLastReadsHook.ts";
export { getQuranLastReadsIdQueryKey, getQuranLastReadsIdHook, getQuranLastReadsIdQueryOptionsHook, useGetQuranLastReadsIdHook } from "./lastReadController/useGetQuranLastReadsIdHook.ts";
export { getQuranLastReadsSurahSurahidQueryKey, getQuranLastReadsSurahSurahidHook, getQuranLastReadsSurahSurahidQueryOptionsHook, useGetQuranLastReadsSurahSurahidHook } from "./lastReadController/useGetQuranLastReadsSurahSurahidHook.ts";
export { postQuranLastReadsMutationKey, postQuranLastReadsHook, postQuranLastReadsMutationOptionsHook, usePostQuranLastReadsHook } from "./lastReadController/usePostQuranLastReadsHook.ts";
export { putQuranLastReadsIdMutationKey, putQuranLastReadsIdHook, putQuranLastReadsIdMutationOptionsHook, usePutQuranLastReadsIdHook } from "./lastReadController/usePutQuranLastReadsIdHook.ts";
export { getPrayertimesDailyQueryKey, getPrayertimesDailyHook, getPrayertimesDailyQueryOptionsHook, useGetPrayertimesDailyHook } from "./prayerTimesController/useGetPrayertimesDailyHook.ts";
export { getPrayertimesMonthlyQueryKey, getPrayertimesMonthlyHook, getPrayertimesMonthlyQueryOptionsHook, useGetPrayertimesMonthlyHook } from "./prayerTimesController/useGetPrayertimesMonthlyHook.ts";
export { getPrayertimesYearlyQueryKey, getPrayertimesYearlyHook, getPrayertimesYearlyQueryOptionsHook, useGetPrayertimesYearlyHook } from "./prayerTimesController/useGetPrayertimesYearlyHook.ts";
export { deleteQuranProgressHatamIdMutationKey, deleteQuranProgressHatamIdHook, deleteQuranProgressHatamIdMutationOptionsHook, useDeleteQuranProgressHatamIdHook } from "./progressHatamController/useDeleteQuranProgressHatamIdHook.ts";
export { getQuranProgressHatamQueryKey, getQuranProgressHatamHook, getQuranProgressHatamQueryOptionsHook, useGetQuranProgressHatamHook } from "./progressHatamController/useGetQuranProgressHatamHook.ts";
export { getQuranProgressHatamIdQueryKey, getQuranProgressHatamIdHook, getQuranProgressHatamIdQueryOptionsHook, useGetQuranProgressHatamIdHook } from "./progressHatamController/useGetQuranProgressHatamIdHook.ts";
export { getQuranProgressHatamJuzJuzidQueryKey, getQuranProgressHatamJuzJuzidHook, getQuranProgressHatamJuzJuzidQueryOptionsHook, useGetQuranProgressHatamJuzJuzidHook } from "./progressHatamController/useGetQuranProgressHatamJuzJuzidHook.ts";
export { postQuranProgressHatamMutationKey, postQuranProgressHatamHook, postQuranProgressHatamMutationOptionsHook, usePostQuranProgressHatamHook } from "./progressHatamController/usePostQuranProgressHatamHook.ts";
export { putQuranProgressHatamIdMutationKey, putQuranProgressHatamIdHook, putQuranProgressHatamIdMutationOptionsHook, usePutQuranProgressHatamIdHook } from "./progressHatamController/usePutQuranProgressHatamIdHook.ts";
export { deleteQuranRecitersIdMutationKey, deleteQuranRecitersIdHook, deleteQuranRecitersIdMutationOptionsHook, useDeleteQuranRecitersIdHook } from "./recitersController/useDeleteQuranRecitersIdHook.ts";
export { getQuranRecitersQueryKey, getQuranRecitersHook, getQuranRecitersQueryOptionsHook, useGetQuranRecitersHook } from "./recitersController/useGetQuranRecitersHook.ts";
export { getQuranRecitersIdQueryKey, getQuranRecitersIdHook, getQuranRecitersIdQueryOptionsHook, useGetQuranRecitersIdHook } from "./recitersController/useGetQuranRecitersIdHook.ts";
export { getQuranRecitersNameNameQueryKey, getQuranRecitersNameNameHook, getQuranRecitersNameNameQueryOptionsHook, useGetQuranRecitersNameNameHook } from "./recitersController/useGetQuranRecitersNameNameHook.ts";
export { postQuranRecitersMutationKey, postQuranRecitersHook, postQuranRecitersMutationOptionsHook, usePostQuranRecitersHook } from "./recitersController/usePostQuranRecitersHook.ts";
export { putQuranRecitersIdMutationKey, putQuranRecitersIdHook, putQuranRecitersIdMutationOptionsHook, usePutQuranRecitersIdHook } from "./recitersController/usePutQuranRecitersIdHook.ts";
export { deleteQuranSurahsIdMutationKey, deleteQuranSurahsIdHook, deleteQuranSurahsIdMutationOptionsHook, useDeleteQuranSurahsIdHook } from "./surahsController/useDeleteQuranSurahsIdHook.ts";
export { getQuranSurahsQueryKey, getQuranSurahsHook, getQuranSurahsQueryOptionsHook, useGetQuranSurahsHook } from "./surahsController/useGetQuranSurahsHook.ts";
export { getQuranSurahsIdQueryKey, getQuranSurahsIdHook, getQuranSurahsIdQueryOptionsHook, useGetQuranSurahsIdHook } from "./surahsController/useGetQuranSurahsIdHook.ts";
export { getQuranSurahsNumberNumberQueryKey, getQuranSurahsNumberNumberHook, getQuranSurahsNumberNumberQueryOptionsHook, useGetQuranSurahsNumberNumberHook } from "./surahsController/useGetQuranSurahsNumberNumberHook.ts";
export { postQuranSurahsMutationKey, postQuranSurahsHook, postQuranSurahsMutationOptionsHook, usePostQuranSurahsHook } from "./surahsController/usePostQuranSurahsHook.ts";
export { putQuranSurahsIdMutationKey, putQuranSurahsIdHook, putQuranSurahsIdMutationOptionsHook, usePutQuranSurahsIdHook } from "./surahsController/usePutQuranSurahsIdHook.ts";
export { getQuranTranslationsAyahsAyahAyahidEditionEditionidQueryKey, getQuranTranslationsAyahsAyahAyahidEditionEditionidHook, getQuranTranslationsAyahsAyahAyahidEditionEditionidQueryOptionsHook, useGetQuranTranslationsAyahsAyahAyahidEditionEditionidHook } from "./translationsController/useGetQuranTranslationsAyahsAyahAyahidEditionEditionidHook.ts";
export { getQuranTranslationsAyahsSurahSurahidEditionEditionidQueryKey, getQuranTranslationsAyahsSurahSurahidEditionEditionidHook, getQuranTranslationsAyahsSurahSurahidEditionEditionidQueryOptionsHook, useGetQuranTranslationsAyahsSurahSurahidEditionEditionidHook } from "./translationsController/useGetQuranTranslationsAyahsSurahSurahidEditionEditionidHook.ts";
export { getQuranTranslationsEditionsQueryKey, getQuranTranslationsEditionsHook, getQuranTranslationsEditionsQueryOptionsHook, useGetQuranTranslationsEditionsHook } from "./translationsController/useGetQuranTranslationsEditionsHook.ts";