/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeleteQuranAyahsIdPathParams, DeleteQuranAyahsId200, DeleteQuranAyahsId400, DeleteQuranAyahsId404, DeleteQuranAyahsId500, DeleteQuranAyahsIdMutationResponse } from "../../types/DeleteQuranAyahsId.ts";
import { quranDeleteAyahSuccessResponseSchema } from "../quran/deleteAyahSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const deleteQuranAyahsIdPathParamsSchema = z.object({
    "id": z.string().describe("Ayah ID")
    }) as unknown as z.ZodType<DeleteQuranAyahsIdPathParams>

/**
 * @description Ayah deleted successfully
 */
export const deleteQuranAyahsId200Schema = quranDeleteAyahSuccessResponseSchema as unknown as z.ZodType<DeleteQuranAyahsId200>

/**
 * @description Bad request
 */
export const deleteQuranAyahsId400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<DeleteQuranAyahsId400>

/**
 * @description Ayah not found
 */
export const deleteQuranAyahsId404Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<DeleteQuranAyahsId404>

/**
 * @description Internal server error
 */
export const deleteQuranAyahsId500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<DeleteQuranAyahsId500>

export const deleteQuranAyahsIdMutationResponseSchema = deleteQuranAyahsId200Schema as unknown as z.ZodType<DeleteQuranAyahsIdMutationResponse>