/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetQuranJuzJuznumberAyahsPathParams, GetQuranJuzJuznumberAyahsQueryParams, GetQuranJuzJuznumberAyahs200, GetQuranJuzJuznumberAyahs400, GetQuranJuzJuznumberAyahs500, GetQuranJuzJuznumberAyahsQueryResponse } from "../../types/GetQuranJuzJuznumberAyahs.ts";
import { quranGetAyahsByJuzSuccessResponseSchema } from "../quran/getAyahsByJuzSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const getQuranJuzJuznumberAyahsPathParamsSchema = z.object({
    "juzNumber": z.coerce.number().int().describe("Juz Number")
    }) as unknown as z.ZodType<GetQuranJuzJuznumberAyahsPathParams>

export const getQuranJuzJuznumberAyahsQueryParamsSchema = z.object({
    "limit": z.coerce.number().int().default(0).describe("Limit (0 for all)"),
"offset": z.coerce.number().int().default(0).describe("Offset")
    }) as unknown as z.ZodType<GetQuranJuzJuznumberAyahsQueryParams>

/**
 * @description Ayahs retrieved successfully
 */
export const getQuranJuzJuznumberAyahs200Schema = quranGetAyahsByJuzSuccessResponseSchema as unknown as z.ZodType<GetQuranJuzJuznumberAyahs200>

/**
 * @description Bad request
 */
export const getQuranJuzJuznumberAyahs400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranJuzJuznumberAyahs400>

/**
 * @description Internal server error
 */
export const getQuranJuzJuznumberAyahs500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranJuzJuznumberAyahs500>

export const getQuranJuzJuznumberAyahsQueryResponseSchema = getQuranJuzJuznumberAyahs200Schema as unknown as z.ZodType<GetQuranJuzJuznumberAyahsQueryResponse>