/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetQuranAyahsIdPathParams, GetQuranAyahsIdQueryParams, GetQuranAyahsId200, GetQuranAyahsId400, GetQuranAyahsId404, GetQuranAyahsId500, GetQuranAyahsIdQueryResponse } from "../../types/GetQuranAyahsId.ts";
import { quranGetAyahByIdSuccessResponseSchema } from "../quran/getAyahByIdSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const getQuranAyahsIdPathParamsSchema = z.object({
    "id": z.string().describe("Ayah ID")
    }) as unknown as z.ZodType<GetQuranAyahsIdPathParams>

export const getQuranAyahsIdQueryParamsSchema = z.object({
    "include": z.optional(z.enum(["surah"]).describe("Include related data"))
    }).optional() as unknown as z.ZodType<GetQuranAyahsIdQueryParams>

/**
 * @description Ayah retrieved successfully
 */
export const getQuranAyahsId200Schema = quranGetAyahByIdSuccessResponseSchema as unknown as z.ZodType<GetQuranAyahsId200>

/**
 * @description Bad request
 */
export const getQuranAyahsId400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranAyahsId400>

/**
 * @description Ayah not found
 */
export const getQuranAyahsId404Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranAyahsId404>

/**
 * @description Internal server error
 */
export const getQuranAyahsId500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranAyahsId500>

export const getQuranAyahsIdQueryResponseSchema = getQuranAyahsId200Schema as unknown as z.ZodType<GetQuranAyahsIdQueryResponse>