/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetQuranAyahsSurahSurahidPathParams, GetQuranAyahsSurahSurahidQueryParams, GetQuranAyahsSurahSurahid200, GetQuranAyahsSurahSurahid400, GetQuranAyahsSurahSurahid500, GetQuranAyahsSurahSurahidQueryResponse } from "../../types/GetQuranAyahsSurahSurahid.ts";
import { quranGetAyahsBySurahWithTranslationsSuccessResponseSchema } from "../quran/getAyahsBySurahWithTranslationsSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

export const getQuranAyahsSurahSurahidPathParamsSchema = z.object({
    "surahId": z.string().describe("Surah ID")
    }) as unknown as z.ZodType<GetQuranAyahsSurahSurahidPathParams>

export const getQuranAyahsSurahSurahidQueryParamsSchema = z.object({
    "limit": z.coerce.number().int().default(0).describe("Limit (0 for all)"),
"offset": z.coerce.number().int().default(0).describe("Offset"),
"include": z.optional(z.enum(["surah"]).describe("Include related data")),
"editionId": z.optional(z.string().describe("Translation edition ID to include per-ayah translation")),
"reciterId": z.optional(z.string().describe("Reciter ID to include per-ayah audio"))
    }) as unknown as z.ZodType<GetQuranAyahsSurahSurahidQueryParams>

/**
 * @description Ayahs with translations retrieved successfully
 */
export const getQuranAyahsSurahSurahid200Schema = quranGetAyahsBySurahWithTranslationsSuccessResponseSchema as unknown as z.ZodType<GetQuranAyahsSurahSurahid200>

/**
 * @description Bad request
 */
export const getQuranAyahsSurahSurahid400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranAyahsSurahSurahid400>

/**
 * @description Internal server error
 */
export const getQuranAyahsSurahSurahid500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<GetQuranAyahsSurahSurahid500>

export const getQuranAyahsSurahSurahidQueryResponseSchema = getQuranAyahsSurahSurahid200Schema as unknown as z.ZodType<GetQuranAyahsSurahSurahidQueryResponse>