/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PostQuranAyahs201, PostQuranAyahs400, PostQuranAyahs500, PostQuranAyahsMutationRequest, PostQuranAyahsMutationResponse } from "../../types/PostQuranAyahs.ts";
import { dtoCreateAyahRequestSchema } from "../dto/createAyahRequestSchema.ts";
import { quranCreateAyahSuccessResponseSchema } from "../quran/createAyahSuccessResponseSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { z } from "zod";

/**
 * @description Ayah created successfully
 */
export const postQuranAyahs201Schema = quranCreateAyahSuccessResponseSchema as unknown as z.ZodType<PostQuranAyahs201>

/**
 * @description Bad request
 */
export const postQuranAyahs400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PostQuranAyahs400>

/**
 * @description Internal server error
 */
export const postQuranAyahs500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PostQuranAyahs500>

/**
 * @description Create ayah request
 */
export const postQuranAyahsMutationRequestSchema = dtoCreateAyahRequestSchema as unknown as z.ZodType<PostQuranAyahsMutationRequest>

export const postQuranAyahsMutationResponseSchema = postQuranAyahs201Schema as unknown as z.ZodType<PostQuranAyahsMutationResponse>