/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PutQuranAyahsIdPathParams, PutQuranAyahsId200, PutQuranAyahsId400, PutQuranAyahsId404, PutQuranAyahsId500, PutQuranAyahsIdMutationRequest, PutQuranAyahsIdMutationResponse } from "../../types/PutQuranAyahsId.ts";
import { dtoUpdateAyahRequestSchema } from "../dto/updateAyahRequestSchema.ts";
import { quranQuranErrorResponseSchema } from "../quran/quranErrorResponseSchema.ts";
import { quranUpdateAyahSuccessResponseSchema } from "../quran/updateAyahSuccessResponseSchema.ts";
import { z } from "zod";

export const putQuranAyahsIdPathParamsSchema = z.object({
    "id": z.string().describe("Ayah ID")
    }) as unknown as z.ZodType<PutQuranAyahsIdPathParams>

/**
 * @description Ayah updated successfully
 */
export const putQuranAyahsId200Schema = quranUpdateAyahSuccessResponseSchema as unknown as z.ZodType<PutQuranAyahsId200>

/**
 * @description Bad request
 */
export const putQuranAyahsId400Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PutQuranAyahsId400>

/**
 * @description Ayah not found
 */
export const putQuranAyahsId404Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PutQuranAyahsId404>

/**
 * @description Internal server error
 */
export const putQuranAyahsId500Schema = quranQuranErrorResponseSchema as unknown as z.ZodType<PutQuranAyahsId500>

/**
 * @description Update ayah request
 */
export const putQuranAyahsIdMutationRequestSchema = dtoUpdateAyahRequestSchema as unknown as z.ZodType<PutQuranAyahsIdMutationRequest>

export const putQuranAyahsIdMutationResponseSchema = putQuranAyahsId200Schema as unknown as z.ZodType<PutQuranAyahsIdMutationResponse>