/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoAyahAudioFileListResponse } from "../dto/AyahAudioFileListResponse.ts";

export type QuranAyahAudioFileListSuccessResponse = {
    /**
     * @type object | undefined
    */
    data?: DtoAyahAudioFileListResponse;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type string | undefined
    */
    responseTime?: string;
    /**
     * @type integer | undefined
    */
    status_code?: number;
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type string | undefined
    */
    timestamp?: string;
};