/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoBookmarkAyahResponse } from "../dto/BookmarkAyahResponse.ts";

export type QuranBookmarkAyahSuccessResponse = {
    /**
     * @type object | undefined
    */
    data?: DtoBookmarkAyahResponse;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type string | undefined
    */
    responseTime?: string;
    /**
     * @type integer | undefined
    */
    status_code?: number;
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type string | undefined
    */
    timestamp?: string;
};