/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoBookmarkAyahListResponse } from "../dto/BookmarkAyahListResponse.ts";

export type QuranBookmarkAyahListSuccessResponse = {
    /**
     * @type object | undefined
    */
    data?: DtoBookmarkAyahListResponse;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type string | undefined
    */
    responseTime?: string;
    /**
     * @type integer | undefined
    */
    status_code?: number;
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type string | undefined
    */
    timestamp?: string;
};