/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoAyahAudioFileResponse } from "../dto/AyahAudioFileResponse.ts";

export type QuranCreateAyahAudioFileSuccessResponse = {
    /**
     * @type object | undefined
    */
    data?: DtoAyahAudioFileResponse;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type string | undefined
    */
    responseTime?: string;
    /**
     * @type integer | undefined
    */
    status_code?: number;
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type string | undefined
    */
    timestamp?: string;
};