/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type QuranDeleteReciterSuccessResponse = {
    /**
     * @type string | undefined
    */
    data?: string;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type string | undefined
    */
    responseTime?: string;
    /**
     * @type integer | undefined
    */
    status_code?: number;
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type string | undefined
    */
    timestamp?: string;
};