/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoSurahAyahsWithTranslationsResponse } from "../dto/SurahAyahsWithTranslationsResponse.ts";

export type QuranGetAyahsBySurahWithTranslationsSuccessResponse = {
    /**
     * @type object | undefined
    */
    data?: DtoSurahAyahsWithTranslationsResponse;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type string | undefined
    */
    responseTime?: string;
    /**
     * @type integer | undefined
    */
    status_code?: number;
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type string | undefined
    */
    timestamp?: string;
};