/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoAyahListResponse } from "../dto/AyahListResponse.ts";

export type QuranGetAyahsByJuzSuccessResponse = {
    /**
     * @type object | undefined
    */
    data?: DtoAyahListResponse;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type string | undefined
    */
    responseTime?: string;
    /**
     * @type integer | undefined
    */
    status_code?: number;
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type string | undefined
    */
    timestamp?: string;
};