/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoAyahTranslationListResponse } from "../dto/AyahTranslationListResponse.ts";

export type QuranGetAyahTranslationListSuccessResponse = {
    /**
     * @type object | undefined
    */
    data?: DtoAyahTranslationListResponse;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type string | undefined
    */
    responseTime?: string;
    /**
     * @type integer | undefined
    */
    status_code?: number;
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type string | undefined
    */
    timestamp?: string;
};