/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoAyahTranslationResponse } from "../dto/AyahTranslationResponse.ts";

export type QuranGetAyahTranslationSuccessResponse = {
    /**
     * @type object | undefined
    */
    data?: DtoAyahTranslationResponse;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type string | undefined
    */
    responseTime?: string;
    /**
     * @type integer | undefined
    */
    status_code?: number;
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type string | undefined
    */
    timestamp?: string;
};