/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoTranslationEditionListResponse } from "../dto/TranslationEditionListResponse.ts";

export type QuranGetTranslationEditionListSuccessResponse = {
    /**
     * @type object | undefined
    */
    data?: DtoTranslationEditionListResponse;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type string | undefined
    */
    responseTime?: string;
    /**
     * @type integer | undefined
    */
    status_code?: number;
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type string | undefined
    */
    timestamp?: string;
};