/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoJuzListResponse } from "../dto/JuzListResponse.ts";

export type QuranJuzListSuccessResponse = {
    /**
     * @type object | undefined
    */
    data?: DtoJuzListResponse;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type string | undefined
    */
    responseTime?: string;
    /**
     * @type integer | undefined
    */
    status_code?: number;
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type string | undefined
    */
    timestamp?: string;
};