/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoJuzWithProgressBasicListResponse } from "../dto/JuzWithProgressBasicListResponse.ts";

export type QuranJuzWithProgressListSuccessResponse = {
    /**
     * @type object | undefined
    */
    data?: DtoJuzWithProgressBasicListResponse;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type string | undefined
    */
    responseTime?: string;
    /**
     * @type integer | undefined
    */
    status_code?: number;
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type string | undefined
    */
    timestamp?: string;
};