/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoLastReadResponse } from "../dto/LastReadResponse.ts";

export type QuranLastReadSuccessResponse = {
    /**
     * @type object | undefined
    */
    data?: DtoLastReadResponse;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type string | undefined
    */
    responseTime?: string;
    /**
     * @type integer | undefined
    */
    status_code?: number;
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type string | undefined
    */
    timestamp?: string;
};