/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoProgressHatamListResponse } from "../dto/ProgressHatamListResponse.ts";

export type QuranProgressHatamListSuccessResponse = {
    /**
     * @type object | undefined
    */
    data?: DtoProgressHatamListResponse;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type string | undefined
    */
    responseTime?: string;
    /**
     * @type integer | undefined
    */
    status_code?: number;
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type string | undefined
    */
    timestamp?: string;
};