/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoProgressHatamResponse } from "../dto/ProgressHatamResponse.ts";

export type QuranProgressHatamSuccessResponse = {
    /**
     * @type object | undefined
    */
    data?: DtoProgressHatamResponse;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type string | undefined
    */
    responseTime?: string;
    /**
     * @type integer | undefined
    */
    status_code?: number;
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type string | undefined
    */
    timestamp?: string;
};