/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CoreErrorDetail } from "../core/ErrorDetail.ts";

export type QuranQuranErrorResponse = {
    /**
     * @type object | undefined
    */
    errors?: CoreErrorDetail;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type string | undefined
    */
    responseTime?: string;
    /**
     * @type integer | undefined
    */
    status_code?: number;
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type string | undefined
    */
    timestamp?: string;
};