/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoReciterResponse } from "../dto/ReciterResponse.ts";

export type QuranReciterSuccessResponse = {
    /**
     * @type object | undefined
    */
    data?: DtoReciterResponse;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type string | undefined
    */
    responseTime?: string;
    /**
     * @type integer | undefined
    */
    status_code?: number;
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type string | undefined
    */
    timestamp?: string;
};