/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoReciterListResponse } from "../dto/ReciterListResponse.ts";

export type QuranReciterListSuccessResponse = {
    /**
     * @type object | undefined
    */
    data?: DtoReciterListResponse;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type string | undefined
    */
    responseTime?: string;
    /**
     * @type integer | undefined
    */
    status_code?: number;
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type string | undefined
    */
    timestamp?: string;
};