/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DtoSurahResponse } from "../dto/SurahResponse.ts";

export type QuranUpdateSurahSuccessResponse = {
    /**
     * @type object | undefined
    */
    data?: DtoSurahResponse;
    /**
     * @type string | undefined
    */
    message?: string;
    /**
     * @type string | undefined
    */
    responseTime?: string;
    /**
     * @type integer | undefined
    */
    status_code?: number;
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type string | undefined
    */
    timestamp?: string;
};